#include "stdafx.h"

#ifdef _EDITOR

#include "EffectLegacyCases.h"

#include "Core/Globals/_define.h"
#include "Core/Globals/_enum.h"
#include "Core/Globals/_TextureIndex.h"

#include <algorithm>
#include <iterator>

// When a phase moves a stage of a type into the registry (data or a handler)
// and deletes its case, its flag goes here too; a type without flags leaves the
// list. See docs/effect-data.md.
namespace MuEditor::Effects
{
namespace
{
// clang-format off
constexpr EffectLegacyCases LegacyCases[] = {
    {MODEL_KALIMA_FALLING_STONE, CreateCase | MoveCase | RenderCase},
    {BATTLE_CASTLE_WALL1, RenderCase},
    {BATTLE_CASTLE_WALL2, RenderCase},
    {BATTLE_CASTLE_WALL3, RenderCase},
    {BATTLE_CASTLE_WALL4, RenderCase},
    {MODEL_BUTTERFLY01, CreateCase | RenderCase},
    {MODEL_GHOST, CreateCase | RenderCase},
    {MODEL_DRAGON, RenderCase},
    {MODEL_CLOUD, RenderCase},
    {MODEL_SHINE, CreateCase | RenderCase},
    {MODEL_XMAS_EVENT_ICEHEART, CreateCase | RenderCase},
    {MODEL_XMAS_EVENT_BOX, CreateCase | RenderCase},
    {MODEL_XMAS_EVENT_CANDY, CreateCase | RenderCase},
    {MODEL_XMAS_EVENT_TREE, CreateCase | RenderCase},
    {MODEL_XMAS_EVENT_SOCKS, CreateCase | RenderCase},
    {MODEL_NEWYEARSDAY_EVENT_BEKSULKI, CreateCase | RenderCase},
    {MODEL_NEWYEARSDAY_EVENT_CANDY, CreateCase | RenderCase},
    {MODEL_NEWYEARSDAY_EVENT_HOTPEPPER_GREEN, CreateCase | RenderCase},
    {MODEL_NEWYEARSDAY_EVENT_HOTPEPPER_RED, CreateCase | RenderCase},
    {MODEL_NEWYEARSDAY_EVENT_PIG, CreateCase | RenderCase},
    {MODEL_NEWYEARSDAY_EVENT_YUT, CreateCase | RenderCase},
    {MODEL_NEWYEARSDAY_EVENT_MONEY, CreateCase | RenderCase},
    {MODEL_MOONHARVEST_GAM, CreateCase | RenderCase},
    {MODEL_MOONHARVEST_SONGPUEN1, CreateCase | RenderCase},
    {MODEL_MOONHARVEST_SONGPUEN2, CreateCase | RenderCase},
    {MODEL_MOONHARVEST_MOON, RenderCase},
    {MODEL_LIGHTNING_ORB, MoveCase},
    {MODEL_ALICE_BUFFSKILL_EFFECT, RenderCase},
    {MODEL_ALICE_BUFFSKILL_EFFECT2, RenderCase},
    {MODEL_RAKLION_BOSS_CRACKEFFECT, CreateCase | RenderCase},
    {MODEL_RAKLION_BOSS_MAGIC, RenderCase | GroundCase},
    {MODEL_LIGHTNING_SHOCK, CreateCase},
    {MODEL_MOVE_TARGETPOSITION_EFFECT, CreateCase | RenderCase},
    {MODEL_ICE, CreateCase | MoveCase},
    {MODEL_FIRE, CreateCase | MoveCase},
    {MODEL_WARCRAFT, CreateCase},
    {MODEL_STONE1, CreateCase | MoveCase},
    {MODEL_STONE2, CreateCase | MoveCase},
    {MODEL_ICE_SMALL, CreateCase},
    {MODEL_CIRCLE, CreateCase},
    {MODEL_MAGIC2, CreateCase},
    {MODEL_STORM, CreateCase | RenderCase},
    {MODEL_LASER, CreateCase},
    {MODEL_HALLOWEEN, RenderCase},
    {MODEL_HALLOWEEN_EX, CreateCase | RenderCase},
    {MODEL_HALLOWEEN_CANDY_BLUE, CreateCase | RenderCase},
    {MODEL_HALLOWEEN_CANDY_ORANGE, CreateCase | RenderCase},
    {MODEL_HALLOWEEN_CANDY_RED, CreateCase | RenderCase},
    {MODEL_HALLOWEEN_CANDY_YELLOW, CreateCase | RenderCase},
    {MODEL_HALLOWEEN_CANDY_HOBAK, CreateCase | RenderCase},
    {MODEL_HALLOWEEN_CANDY_STAR, CreateCase | RenderCase},
    {MODEL_WOOSISTONE, CreateCase | MoveCase},
    {MODEL_SAW, CreateCase},
    {MODEL_BONE1, CreateCase | MoveCase},
    {MODEL_BONE2, CreateCase | MoveCase},
    {MODEL_SNOW1, CreateCase | MoveCase},
    {MODEL_SNOW2, CreateCase | MoveCase},
    {MODEL_SNOW3, CreateCase | MoveCase},
    {MODEL_DUNGEON_STONE01, CreateCase},
    {MODEL_ARROW, CreateCase},
    {MODEL_ARROW_STEEL, CreateCase},
    {MODEL_ARROW_THUNDER, CreateCase},
    {MODEL_ARROW_LASER, CreateCase},
    {MODEL_ARROW_V, CreateCase},
    {MODEL_ARROW_SAW, CreateCase},
    {MODEL_ARROW_NATURE, CreateCase},
    {MODEL_ARROW_BOMB, CreateCase},
    {MODEL_ARROW_WING, CreateCase},
    {MODEL_BIG_STONE1, CreateCase | MoveCase},
    {MODEL_BIG_STONE2, CreateCase | MoveCase},
    {MODEL_BIG_METEO1, CreateCase | MoveCase},
    {MODEL_BIG_METEO2, CreateCase | MoveCase},
    {MODEL_BIG_METEO3, CreateCase | MoveCase},
    {MODEL_METEO1, CreateCase},
    {MODEL_METEO2, CreateCase},
    {MODEL_ARROW_TANKER, CreateCase},
    {MODEL_SKILL_WHEEL1, CreateCase | RenderCase},
    {MODEL_SKILL_WHEEL2, CreateCase | RenderCase},
    {MODEL_SKILL_BLAST, CreateCase},
    {MODEL_SKILL_INFERNO, CreateCase},
    {MODEL_ARROW_DOUBLE, CreateCase},
    {MODEL_ARROW_HOLY, CreateCase | RenderCase},
    {MODEL_ARROW_SPARK, CreateCase},
    {MODEL_ARROW_RING, CreateCase},
    {MODEL_ARROW_DARKSTINGER, CreateCase},
    {MODEL_FEATHER, CreateCase | MoveCase},
    {MODEL_FEATHER_FOREIGN, CreateCase | MoveCase},
    {MODEL_SKILL_FURY_STRIKE, CreateCase | RenderCase},
    {MODEL_SKILL_FURY_STRIKE + 1, CreateCase | MoveCase},
    {MODEL_SKILL_FURY_STRIKE + 2, CreateCase | MoveCase},
    {MODEL_SKILL_FURY_STRIKE + 3, CreateCase | MoveCase},
    {MODEL_SKILL_FURY_STRIKE + 4, CreateCase | MoveCase},
    {MODEL_SKILL_FURY_STRIKE + 5, CreateCase | MoveCase},
    {MODEL_SKILL_FURY_STRIKE + 6, CreateCase | MoveCase},
    {MODEL_SKILL_FURY_STRIKE + 7, CreateCase | MoveCase},
    {MODEL_SKILL_FURY_STRIKE + 8, CreateCase | MoveCase},
    {MODEL_PIERCING, CreateCase | RenderCase},
    {MODEL_PIERCING + 1, CreateCase | MoveCase},
    {MODEL_WAVE_FORCE, CreateCase | RenderCase},
    {MODEL_BLIZZARD, CreateCase},
    {MODEL_MAGIC_CAPSULE2, RenderCase},
    {MODEL_STONE_COFFIN, CreateCase | MoveCase | RenderCase},
    {MODEL_STONE_COFFIN + 1, CreateCase | MoveCase | RenderCase},
    {MODEL_GATE, CreateCase | MoveCase | RenderCase},
    {MODEL_GATE + 1, CreateCase | MoveCase | RenderCase},
    {MODEL_ARROW_BEST_CROSSBOW, CreateCase | RenderCase},
    {MODEL_SPEARSKILL, CreateCase | RenderCase},
    {MODEL_ARROW_DRILL, CreateCase},
    {MODEL_COMBO, CreateCase},
    {MODEL_AIR_FORCE, RenderCase},
    {MODEL_WAVES, CreateCase},
    {MODEL_PIERCING2, RenderCase},
    {MODEL_PIER_PART, CreateCase | RenderCase},
    {MODEL_DARKLORD_SKILL, CreateCase},
    {MODEL_GROUND_STONE, CreateCase},
    {MODEL_GROUND_STONE2, CreateCase},
    {MODEL_SKULL, CreateCase},
    {MODEL_LACEARROW, CreateCase},
    {MODEL_CUNDUN_PART1, CreateCase | RenderCase},
    {MODEL_CUNDUN_PART2, CreateCase | RenderCase},
    {MODEL_CUNDUN_PART3, CreateCase | RenderCase},
    {MODEL_CUNDUN_PART4, CreateCase | RenderCase},
    {MODEL_CUNDUN_PART5, CreateCase | RenderCase},
    {MODEL_CUNDUN_PART6, CreateCase | RenderCase},
    {MODEL_CUNDUN_PART7, CreateCase | RenderCase},
    {MODEL_CUNDUN_PART8, CreateCase | RenderCase},
    {MODEL_CUNDUN_DRAGON_HEAD, CreateCase | RenderCase},
    {MODEL_CUNDUN_PHOENIX, CreateCase | RenderCase},
    {MODEL_CUNDUN_GHOST, RenderCase},
    {MODEL_CUNDUN_SKILL, CreateCase},
    {MODEL_FLY_BIG_STONE1, CreateCase},
    {MODEL_FLY_BIG_STONE2, CreateCase},
    {MODEL_BIG_STONE_PART1, CreateCase},
    {MODEL_BIG_STONE_PART2, CreateCase},
    {MODEL_WALL_PART1, CreateCase},
    {MODEL_WALL_PART2, CreateCase},
    {MODEL_GATE_PART1, CreateCase},
    {MODEL_GATE_PART2, CreateCase},
    {MODEL_GATE_PART3, CreateCase},
    {MODEL_AURORA, CreateCase},
    {MODEL_TOWER_GATE_PLANE, RenderCase},
    {MODEL_STUN_STONE, CreateCase},
    {MODEL_SKIN_SHELL, CreateCase},
    {MODEL_SKILL_JAVELIN, CreateCase},
    {MODEL_ARROW_IMPACT, CreateCase},
    {MODEL_GOLEM_STONE, CreateCase},
    {MODEL_PROTECTGUILD, CreateCase | RenderCase},
    {MODEL_TREE_ATTACK, RenderCase},
    {MODEL_WARP, CreateCase | RenderCase},
    {MODEL_WARP2, CreateCase | RenderCase},
    {MODEL_WARP3, RenderCase},
    {MODEL_WARP4, CreateCase | RenderCase},
    {MODEL_WARP5, CreateCase | RenderCase},
    {MODEL_WARP6, RenderCase},
    {MODEL_DEATH_SPI_SKILL, CreateCase},
    {MODEL_FENRIR_THUNDER, CreateCase | RenderCase},
    {MODEL_FENRIR_FOOT_THUNDER, CreateCase | RenderCase},
    {MODEL_FENRIR_SKILL_DAMAGE, CreateCase},
    {MODEL_ARROW_AUTOLOAD, RenderCase},
    {MODEL_SHIELD_CRASH, CreateCase},
    {MODEL_INFINITY_ARROW, CreateCase | RenderCase},
    {MODEL_INFINITY_ARROW1, RenderCase},
    {MODEL_INFINITY_ARROW2, RenderCase},
    {MODEL_INFINITY_ARROW3, RenderCase},
    {MODEL_INFINITY_ARROW4, RenderCase},
    {MODEL_IRON_RIDER_ARROW, CreateCase},
    {MODEL_TWINTAIL_EFFECT, CreateCase | RenderCase},
    {MODEL_STORM2, CreateCase | RenderCase},
    {MODEL_SUMMON, CreateCase | RenderCase},
    {MODEL_STORM3, CreateCase | RenderCase | AfterCharactersCase},
    {MODEL_MAYASTAR, RenderCase | AfterCharactersCase},
    {MODEL_MAYASTONE1, CreateCase | RenderCase},
    {MODEL_MAYASTONE2, CreateCase | RenderCase},
    {MODEL_MAYASTONE3, CreateCase | RenderCase},
    {MODEL_MAYASTONE4, RenderCase},
    {MODEL_MAYASTONE5, RenderCase},
    {MODEL_MAYASTONEFIRE, CreateCase | RenderCase},
    {MODEL_MAYAHANDSKILL, RenderCase | AfterCharactersCase},
    {MODEL_DARK_SCREAM, CreateCase},
    {MODEL_DARK_SCREAM_FIRE, CreateCase},
    {MODEL_CURSEDTEMPLE_HOLYITEM, RenderCase},
    {MODEL_CURSEDTEMPLE_PRODECTION_SKILL, RenderCase},
    {MODEL_CURSEDTEMPLE_RESTRAINT_SKILL, RenderCase},
    {MODEL_FALL_STONE_EFFECT, CreateCase | RenderCase},
    {MODEL_CURSEDTEMPLE_STATUE_PART1, CreateCase | RenderCase},
    {MODEL_CURSEDTEMPLE_STATUE_PART2, CreateCase | RenderCase},
    {MODEL_CHANGE_UP_EFF, RenderCase},
    {MODEL_TOTEMGOLEM_PART1, CreateCase | MoveCase | RenderCase},
    {MODEL_TOTEMGOLEM_PART2, CreateCase | MoveCase | RenderCase},
    {MODEL_TOTEMGOLEM_PART3, CreateCase | MoveCase | RenderCase},
    {MODEL_TOTEMGOLEM_PART4, CreateCase | MoveCase | RenderCase},
    {MODEL_TOTEMGOLEM_PART5, CreateCase | MoveCase | RenderCase},
    {MODEL_TOTEMGOLEM_PART6, CreateCase | MoveCase | RenderCase},
    {MODEL_SUMMONER_WRISTRING_EFFECT, RenderCase},
    {MODEL_SUMMONER_EQUIP_HEAD_SAHAMUTT, CreateCase | RenderCase},
    {MODEL_SUMMONER_EQUIP_HEAD_NEIL, CreateCase | RenderCase},
    {MODEL_SUMMONER_EQUIP_HEAD_LAGUL, CreateCase | MoveCase},
    {MODEL_SUMMONER_CASTING_EFFECT1, RenderCase},
    {MODEL_SUMMONER_CASTING_EFFECT11, RenderCase},
    {MODEL_SUMMONER_CASTING_EFFECT111, RenderCase},
    {MODEL_SUMMONER_CASTING_EFFECT2, RenderCase},
    {MODEL_SUMMONER_CASTING_EFFECT22, RenderCase},
    {MODEL_SUMMONER_CASTING_EFFECT222, RenderCase},
    {MODEL_SUMMONER_CASTING_EFFECT4, RenderCase},
    {MODEL_SUMMONER_SUMMON_SAHAMUTT, RenderCase},
    {MODEL_SUMMONER_SUMMON_NEIL, RenderCase},
    {MODEL_SUMMONER_SUMMON_LAGUL, CreateCase | RenderCase},
    {MODEL_SUMMONER_SUMMON_NEIL_NIFE1, RenderCase},
    {MODEL_SUMMONER_SUMMON_NEIL_NIFE2, RenderCase},
    {MODEL_SUMMONER_SUMMON_NEIL_NIFE3, RenderCase},
    {MODEL_SUMMONER_SUMMON_NEIL_GROUND1, RenderCase},
    {MODEL_SUMMONER_SUMMON_NEIL_GROUND2, RenderCase},
    {MODEL_SUMMONER_SUMMON_NEIL_GROUND3, RenderCase},
    {MODEL_SHADOW_PAWN_ANKLE_LEFT, CreateCase | MoveCase | RenderCase},
    {MODEL_SHADOW_PAWN_ANKLE_RIGHT, CreateCase | MoveCase | RenderCase},
    {MODEL_SHADOW_PAWN_BELT, CreateCase | MoveCase | RenderCase},
    {MODEL_SHADOW_PAWN_CHEST, CreateCase | MoveCase | RenderCase},
    {MODEL_SHADOW_PAWN_HELMET, CreateCase | MoveCase | RenderCase},
    {MODEL_SHADOW_PAWN_KNEE_LEFT, CreateCase | MoveCase | RenderCase},
    {MODEL_SHADOW_PAWN_KNEE_RIGHT, CreateCase | MoveCase | RenderCase},
    {MODEL_SHADOW_PAWN_WRIST_LEFT, CreateCase | MoveCase | RenderCase},
    {MODEL_SHADOW_PAWN_WRIST_RIGHT, CreateCase | MoveCase | RenderCase},
    {MODEL_SHADOW_KNIGHT_ANKLE_LEFT, CreateCase | MoveCase | RenderCase},
    {MODEL_SHADOW_KNIGHT_ANKLE_RIGHT, CreateCase | MoveCase | RenderCase},
    {MODEL_SHADOW_KNIGHT_BELT, CreateCase | MoveCase | RenderCase},
    {MODEL_SHADOW_KNIGHT_CHEST, CreateCase | MoveCase | RenderCase},
    {MODEL_SHADOW_KNIGHT_HELMET, CreateCase | MoveCase | RenderCase},
    {MODEL_SHADOW_KNIGHT_KNEE_LEFT, CreateCase | MoveCase | RenderCase},
    {MODEL_SHADOW_KNIGHT_KNEE_RIGHT, CreateCase | MoveCase | RenderCase},
    {MODEL_SHADOW_KNIGHT_WRIST_LEFT, CreateCase | MoveCase | RenderCase},
    {MODEL_SHADOW_KNIGHT_WRIST_RIGHT, CreateCase | MoveCase | RenderCase},
    {MODEL_SHADOW_ROOK_ANKLE_LEFT, CreateCase | MoveCase | RenderCase},
    {MODEL_SHADOW_ROOK_ANKLE_RIGHT, CreateCase | MoveCase | RenderCase},
    {MODEL_SHADOW_ROOK_BELT, CreateCase | MoveCase | RenderCase},
    {MODEL_SHADOW_ROOK_CHEST, CreateCase | MoveCase | RenderCase},
    {MODEL_SHADOW_ROOK_HELMET, CreateCase | MoveCase | RenderCase},
    {MODEL_SHADOW_ROOK_KNEE_LEFT, CreateCase | MoveCase | RenderCase},
    {MODEL_SHADOW_ROOK_KNEE_RIGHT, CreateCase | MoveCase | RenderCase},
    {MODEL_SHADOW_ROOK_WRIST_LEFT, CreateCase | MoveCase | RenderCase},
    {MODEL_SHADOW_ROOK_WRIST_RIGHT, CreateCase | MoveCase | RenderCase},
    {MODEL_ICE_GIANT_PART1, CreateCase | MoveCase | RenderCase},
    {MODEL_ICE_GIANT_PART2, CreateCase | MoveCase | RenderCase},
    {MODEL_ICE_GIANT_PART3, CreateCase | MoveCase | RenderCase},
    {MODEL_ICE_GIANT_PART4, CreateCase | MoveCase | RenderCase},
    {MODEL_ICE_GIANT_PART5, MoveCase | RenderCase},
    {MODEL_ICE_GIANT_PART6, MoveCase | RenderCase},
    {MODEL_EFFECT_SAPITRES_ATTACK, CreateCase},
    {MODEL_EFFECT_SAPITRES_ATTACK_1, CreateCase | MoveCase | RenderCase},
    {MODEL_EFFECT_SAPITRES_ATTACK_2, CreateCase | RenderCase},
    {MODEL_EFFECT_BROKEN_ICE0, CreateCase | MoveCase | RenderCase | GroundCase},
    {MODEL_EFFECT_BROKEN_ICE1, CreateCase | MoveCase | RenderCase | GroundCase},
    {MODEL_EFFECT_BROKEN_ICE2, CreateCase | MoveCase | RenderCase | GroundCase},
    {MODEL_EFFECT_BROKEN_ICE3, CreateCase | MoveCase | RenderCase | GroundCase},
    {MODEL_EFFECT_TRACE, CreateCase},
    {MODEL_STAR_SHINE, CreateCase | MoveCase},
    {MODEL_BLOW_OF_DESTRUCTION, CreateCase | RenderCase | GroundCase},
    {MODEL_NIGHTWATER_01, CreateCase | RenderCase},
    {MODEL_KNIGHT_PLANCRACK_A, CreateCase | RenderCase},
    {MODEL_KNIGHT_PLANCRACK_B, RenderCase},
    {MODEL_SWELL_OF_MAGICPOWER, MoveCase},
    {MODEL_ARROWSRE06, MoveCase},
    {MODEL_SWELL_OF_MAGICPOWER_BUFF_EFF, CreateCase | MoveCase | RenderCase},
    {MODEL_EFFECT_FLAME_STRIKE, CreateCase | RenderCase},
    {MODEL_STREAMOFICEBREATH, CreateCase | MoveCase},
    {MODEL_ARROW_GAMBLE, CreateCase | MoveCase},
    {MODEL_PKFIELD_ASSASSIN_EFFECT_GREEN_HEAD, CreateCase},
    {MODEL_PKFIELD_ASSASSIN_EFFECT_RED_HEAD, CreateCase},
    {MODEL_PKFIELD_ASSASSIN_EFFECT_GREEN_BODY, CreateCase},
    {MODEL_PKFIELD_ASSASSIN_EFFECT_RED_BODY, CreateCase},
    {MODEL_LAVAGIANT_FOOTPRINT_R, CreateCase | RenderCase},
    {MODEL_LAVAGIANT_FOOTPRINT_V, CreateCase | RenderCase},
    {MODEL_EFFECT_FIRE_HIK3_MONO, CreateCase},
    {MODEL_PROJECTILE, RenderCase},
    {MODEL_DOOR_CRUSH_EFFECT, CreateCase},
    {MODEL_DOOR_CRUSH_EFFECT_PIECE01, CreateCase | RenderCase},
    {MODEL_DOOR_CRUSH_EFFECT_PIECE02, CreateCase | RenderCase},
    {MODEL_DOOR_CRUSH_EFFECT_PIECE03, CreateCase | RenderCase},
    {MODEL_DOOR_CRUSH_EFFECT_PIECE04, CreateCase | RenderCase},
    {MODEL_DOOR_CRUSH_EFFECT_PIECE05, CreateCase | RenderCase},
    {MODEL_DOOR_CRUSH_EFFECT_PIECE06, CreateCase | RenderCase},
    {MODEL_DOOR_CRUSH_EFFECT_PIECE07, CreateCase | RenderCase},
    {MODEL_DOOR_CRUSH_EFFECT_PIECE08, CreateCase | RenderCase},
    {MODEL_DOOR_CRUSH_EFFECT_PIECE09, CreateCase | RenderCase},
    {MODEL_DOOR_CRUSH_EFFECT_PIECE10, RenderCase},
    {MODEL_DOOR_CRUSH_EFFECT_PIECE11, CreateCase | RenderCase},
    {MODEL_DOOR_CRUSH_EFFECT_PIECE12, CreateCase | RenderCase},
    {MODEL_DOOR_CRUSH_EFFECT_PIECE13, CreateCase | RenderCase},
    {MODEL_STATUE_CRUSH_EFFECT, CreateCase},
    {MODEL_STATUE_CRUSH_EFFECT_PIECE01, CreateCase | RenderCase},
    {MODEL_STATUE_CRUSH_EFFECT_PIECE02, CreateCase | RenderCase},
    {MODEL_STATUE_CRUSH_EFFECT_PIECE03, CreateCase | RenderCase},
    {MODEL_STATUE_CRUSH_EFFECT_PIECE04, RenderCase},
    {MODEL_PANDA, RenderCase},
    {MODEL_SWORDLEFT01_EMPIREGUARDIAN_BOSS_GAION_, CreateCase | RenderCase},
    {MODEL_SWORDLEFT02_EMPIREGUARDIAN_BOSS_GAION_, CreateCase | RenderCase},
    {MODEL_SWORDRIGHT01_EMPIREGUARDIAN_BOSS_GAION_, CreateCase | RenderCase},
    {MODEL_SWORDRIGHT02_EMPIREGUARDIAN_BOSS_GAION_, CreateCase | RenderCase},
    {MODEL_SWORDMAIN01_EMPIREGUARDIAN_BOSS_GAION_, CreateCase | RenderCase},
    {MODEL_EMPIREGUARDIAN_BLOW_OF_DESTRUCTION, CreateCase | RenderCase},
    {MODEL_EFFECT_UMBRELLA_DIE, MoveCase},
    {MODEL_EFFECT_UMBRELLA_GOLD, CreateCase | MoveCase},
    {MODEL_DOPPELGANGER_SLIME_CHIP, CreateCase},
    {MODEL_EMPIREGUARDIANBOSS_FRAMESTRIKE, CreateCase | RenderCase},
    {MODEL_DEASULER, CreateCase},
    {MODEL_EFFECT_EG_GUARDIANDEFENDER_ATTACK2, MoveCase},
    {MODEL_CONDRA_ARM_L, CreateCase | MoveCase},
    {MODEL_CONDRA_ARM_L2, CreateCase | MoveCase},
    {MODEL_CONDRA_SHOULDER, CreateCase | MoveCase},
    {MODEL_CONDRA_ARM_R, CreateCase | MoveCase},
    {MODEL_CONDRA_ARM_R2, CreateCase | MoveCase},
    {MODEL_CONDRA_CONE_L, CreateCase | MoveCase},
    {MODEL_CONDRA_CONE_R, CreateCase | MoveCase},
    {MODEL_CONDRA_PELVIS, CreateCase | MoveCase},
    {MODEL_CONDRA_STOMACH, CreateCase | MoveCase},
    {MODEL_CONDRA_NECK, CreateCase | MoveCase},
    {MODEL_CONDRA_STONE, CreateCase | MoveCase},
    {MODEL_CONDRA_STONE1, CreateCase | MoveCase},
    {MODEL_CONDRA_STONE2, CreateCase | MoveCase},
    {MODEL_CONDRA_STONE3, CreateCase | MoveCase},
    {MODEL_CONDRA_STONE4, CreateCase | MoveCase},
    {MODEL_CONDRA_STONE5, CreateCase | MoveCase},
    {MODEL_NARCONDRA_ARM_L, CreateCase | MoveCase},
    {MODEL_NARCONDRA_ARM_L2, CreateCase | MoveCase},
    {MODEL_NARCONDRA_SHOULDER_L, CreateCase | MoveCase},
    {MODEL_NARCONDRA_SHOULDER_R, CreateCase | MoveCase},
    {MODEL_NARCONDRA_ARM_R, CreateCase | MoveCase},
    {MODEL_NARCONDRA_ARM_R2, CreateCase | MoveCase},
    {MODEL_NARCONDRA_ARM_R3, CreateCase | MoveCase},
    {MODEL_NARCONDRA_CONE_1, CreateCase | MoveCase},
    {MODEL_NARCONDRA_CONE_2, CreateCase | MoveCase},
    {MODEL_NARCONDRA_CONE_3, CreateCase | MoveCase},
    {MODEL_NARCONDRA_CONE_4, CreateCase | MoveCase},
    {MODEL_NARCONDRA_CONE_5, CreateCase | MoveCase},
    {MODEL_NARCONDRA_CONE_6, CreateCase | MoveCase},
    {MODEL_NARCONDRA_PELVIS, CreateCase | MoveCase},
    {MODEL_NARCONDRA_STOMACH, CreateCase | MoveCase},
    {MODEL_NARCONDRA_NECK, CreateCase | MoveCase},
    {MODEL_NARCONDRA_STONE, CreateCase | MoveCase},
    {MODEL_NARCONDRA_STONE1, CreateCase | MoveCase},
    {MODEL_NARCONDRA_STONE2, CreateCase | MoveCase},
    {MODEL_NARCONDRA_STONE3, CreateCase | MoveCase},
    {MODEL_WOLF_HEAD_EFFECT, CreateCase},
    {MODEL_DOWN_ATTACK_DUMMY_L, CreateCase},
    {MODEL_DOWN_ATTACK_DUMMY_R, CreateCase},
    {MODEL_SHOCKWAVE01, CreateCase},
    {MODEL_SHOCKWAVE02, CreateCase | RenderCase},
    {MODEL_SHOCKWAVE_SPIN01, CreateCase},
    {MODEL_WOLF_HEAD_EFFECT2, CreateCase},
    {MODEL_DRAGON_KICK_DUMMY, CreateCase},
    {MODEL_DRAGON_LOWER_DUMMY, CreateCase | RenderCase},
    {MODEL_VOLCANO_OF_MONK, CreateCase},
    {MODEL_VOLCANO_STONE, CreateCase},
    {MODEL_ILLUSION_OF_KUNDUN, CreateCase | RenderCase},
    {MODEL_BATTLE_GUARD2, CreateCase},
    {MODEL_XMAS2008_SNOWMAN_HEAD, CreateCase | RenderCase},
    {MODEL_XMAS2008_SNOWMAN_BODY, CreateCase | RenderCase},
    {MODEL_STAFF_OF_DESTRUCTION, RenderCase},
    {MODEL_MULTI_SHOT1, CreateCase | RenderCase},
    {MODEL_MULTI_SHOT2, CreateCase | RenderCase},
    {MODEL_MULTI_SHOT3, CreateCase | RenderCase},
    {BITMAP_EVENT_CLOUD, RenderCase},
    {BITMAP_LIGHT, CreateCase | MoveCase},
    {BITMAP_SWORD_FORCE, CreateCase},
    {BITMAP_SPARK + 1, MoveCase},
    {BITMAP_SPARK + 2, MoveCase},
    {BITMAP_ENERGY, MoveCase},
    {BITMAP_LIGHTNING + 1, MoveCase | GroundCase},
    {BITMAP_FIRE + 1, CreateCase | MoveCase},
    {BITMAP_FLAME, CreateCase | GroundCase},
    {BITMAP_BOSS_LASER, CreateCase | RenderCase},
    {BITMAP_BOSS_LASER + 1, CreateCase | RenderCase},
    {BITMAP_BOSS_LASER + 2, CreateCase | RenderCase},
    {BITMAP_SHINY + 4, MoveCase},
    {BITMAP_SHINY + 6, MoveCase},
    {BITMAP_JOINT_THUNDER + 1, CreateCase | MoveCase},
    {BITMAP_MAGIC, CreateCase | GroundCase},
    {BITMAP_MAGIC + 1, CreateCase | MoveCase | GroundCase},
    {BITMAP_MAGIC + 2, CreateCase | MoveCase | GroundCase},
    {BITMAP_OUR_INFLUENCE_GROUND, GroundCase},
    {BITMAP_ENEMY_INFLUENCE_GROUND, GroundCase},
    {BITMAP_CLOUD, CreateCase | GroundCase},
    {BITMAP_BLIZZARD, CreateCase},
    {BITMAP_FIRECRACKER, CreateCase},
    {BITMAP_JOINT_FORCE, CreateCase},
    {BITMAP_GATHERING, CreateCase},
    {BITMAP_FLARE_FORCE, CreateCase},
    {BITMAP_LAVA, CreateCase},
    {BITMAP_CRATER, GroundCase},
    {BITMAP_SHOTGUN, CreateCase},
    {BITMAP_CHROME_ENERGY2, GroundCase},
    {BITMAP_SHOCK_WAVE, CreateCase | GroundCase},
    {BITMAP_DAMAGE_01_MONO, GroundCase},
    {BITMAP_WATERFALL_4, CreateCase | RenderCase},
    {BITMAP_FIRE_CURSEDLICH, RenderCase},
    {BITMAP_PIN_LIGHT, CreateCase},
    {BITMAP_MAGIC_ZIN, GroundCase},
    {BITMAP_ORORA, CreateCase},
    {BITMAP_LIGHT_MARKS, RenderCase},
    {BITMAP_TARGET_POSITION_EFFECT1, GroundCase},
    {BITMAP_TARGET_POSITION_EFFECT2, GroundCase},
    {BITMAP_FIRE_HIK2_MONO, GroundCase},
    {BITMAP_TWLIGHT, GroundCase},
    {BITMAP_FIRECRACKER0002, CreateCase},
    {BITMAP_FIRECRACKER0003, CreateCase},
    {BITMAP_LIGHT_RED, CreateCase | RenderCase},
    {BITMAP_RING_OF_GRADATION, MoveCase | GroundCase},
    {BITMAP_SBUMB, CreateCase},
    {BITMAP_DAMAGE1, CreateCase},
};
// clang-format on
} // namespace

std::span<const EffectLegacyCases> GetEffectLegacyCases()
{
    return LegacyCases;
}

std::uint8_t FindEffectLegacyCases(int type)
{
    const auto found = std::lower_bound(std::begin(LegacyCases), std::end(LegacyCases), type,
                                        [](const EffectLegacyCases& entry, int value) { return entry.type < value; });
    return found != std::end(LegacyCases) && found->type == type ? found->cases : 0;
}
} // namespace MuEditor::Effects

#endif // _EDITOR
