// <copyright file="PacketBindings.h" company="MUnique">
// Licensed under the MIT License. See LICENSE file in the project root for full license information.
// </copyright>

//------------------------------------------------------------------------------
// <auto-generated>
//     This source code was auto-generated by an XSL transformation.
//     Do not change this file. Instead, change the XML data which contains
//     the packet definitions and re-run the transformation (publish/rebuild the
//     managed library project).
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once

#include "stdafx.h"
#include "Connection.h"
#include <coreclr_delegates.h>



typedef void(CORECLR_DELEGATE_CALLTYPE* SendConnectionInfoRequest075)(int32_t, BYTE );
inline SendConnectionInfoRequest075 dotnet_SendConnectionInfoRequest075 = reinterpret_cast<SendConnectionInfoRequest075>(symLoad(munique_client_library_handle, "SendConnectionInfoRequest075"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendConnectionInfoRequest)(int32_t, uint16_t );
inline SendConnectionInfoRequest dotnet_SendConnectionInfoRequest = reinterpret_cast<SendConnectionInfoRequest>(symLoad(munique_client_library_handle, "SendConnectionInfoRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendConnectionInfo)(int32_t, const wchar_t* , uint16_t );
inline SendConnectionInfo dotnet_SendConnectionInfo = reinterpret_cast<SendConnectionInfo>(symLoad(munique_client_library_handle, "SendConnectionInfo"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendServerListRequest)(int32_t);
inline SendServerListRequest dotnet_SendServerListRequest = reinterpret_cast<SendServerListRequest>(symLoad(munique_client_library_handle, "SendServerListRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendServerListRequestOld)(int32_t);
inline SendServerListRequestOld dotnet_SendServerListRequestOld = reinterpret_cast<SendServerListRequestOld>(symLoad(munique_client_library_handle, "SendServerListRequestOld"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendHello)(int32_t);
inline SendHello dotnet_SendHello = reinterpret_cast<SendHello>(symLoad(munique_client_library_handle, "SendHello"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendPatchCheckRequest)(int32_t, BYTE , BYTE , BYTE );
inline SendPatchCheckRequest dotnet_SendPatchCheckRequest = reinterpret_cast<SendPatchCheckRequest>(symLoad(munique_client_library_handle, "SendPatchCheckRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendPatchVersionOkay)(int32_t);
inline SendPatchVersionOkay dotnet_SendPatchVersionOkay = reinterpret_cast<SendPatchVersionOkay>(symLoad(munique_client_library_handle, "SendPatchVersionOkay"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendClientNeedsPatch)(int32_t, BYTE , const wchar_t* );
inline SendClientNeedsPatch dotnet_SendClientNeedsPatch = reinterpret_cast<SendClientNeedsPatch>(symLoad(munique_client_library_handle, "SendClientNeedsPatch"));
