// <copyright file="PacketFunctions.cpp" company="MUnique">
// Licensed under the MIT License. See LICENSE file in the project root for full license information.
// </copyright>

//------------------------------------------------------------------------------
// <auto-generated>
//     This source code was auto-generated by an XSL transformation.
//     Do not change this file. Instead, change the XML data which contains
//     the packet definitions and re-run the transformation (publish/rebuild the
//     managed library project).
// </auto-generated>
//------------------------------------------------------------------------------

#include "stdafx.h"
#include "Connection.h"
#include "PacketFunctions_ClientToServer.h"

typedef void(CORECLR_DELEGATE_CALLTYPE* SendLoginFn)(int32_t, const char16_t*, const char16_t*, uint32_t, const BYTE*,
                                                     const BYTE*);

void PacketFunctions_ClientToServer_Custom::SendLogin(const wchar_t* username, const wchar_t* password,
                                                      const BYTE* clientVersion, const BYTE* clientSerial)
{
    static SendLoginFn dotnet_SendLogin = nullptr;
    if (!dotnet_SendLogin)
    {
        dotnet_SendLogin = LoadManagedSymbol<SendLoginFn>("ConnectionManager_SendLogin");
        if (!dotnet_SendLogin)
        {
            return;
        }
    }

    // .NET expects UTF-16 (char16_t). On macOS, wchar_t is 4 bytes (UTF-32) — MU_C16 converts.
    dotnet_SendLogin(this->GetHandle(), MU_C16(username), MU_C16(password), GetTickCount(), clientVersion,
                     clientSerial);
}

typedef void(CORECLR_DELEGATE_CALLTYPE* SendAuthenticateExtFn)(int32_t, uint16_t, uint32_t);

void PacketFunctions_ChatServer_Custom::SendAuthenticateExt(uint16_t roomId, uint32_t token)
{
    static SendAuthenticateExtFn dotnet_SendAuthenticateExt = nullptr;
    if (!dotnet_SendAuthenticateExt)
    {
        dotnet_SendAuthenticateExt = LoadManagedSymbol<SendAuthenticateExtFn>("ConnectionManager_SendAuthenticateExt");
        if (!dotnet_SendAuthenticateExt)
        {
            return;
        }
    }

    dotnet_SendAuthenticateExt(this->GetHandle(), roomId, token);
}

typedef void(CORECLR_DELEGATE_CALLTYPE* SendChatMessageExtFn)(int32_t, BYTE, const char16_t*);

void PacketFunctions_ChatServer_Custom::SendChatMessageExt(BYTE senderIndex, const wchar_t* message)
{
    static SendChatMessageExtFn dotnet_SendChatMessageExt = nullptr;
    if (!dotnet_SendChatMessageExt)
    {
        dotnet_SendChatMessageExt = LoadManagedSymbol<SendChatMessageExtFn>("ConnectionManager_SendChatMessageExt");
        if (!dotnet_SendChatMessageExt)
        {
            return;
        }
    }

    dotnet_SendChatMessageExt(this->GetHandle(), senderIndex, MU_C16(message));
}
