// <copyright file="PacketBindings.h" company="MUnique">
// Licensed under the MIT License. See LICENSE file in the project root for full license information.
// </copyright>

//------------------------------------------------------------------------------
// <auto-generated>
//     This source code was auto-generated by an XSL transformation.
//     Do not change this file. Instead, change the XML data which contains
//     the packet definitions and re-run the transformation (publish/rebuild the
//     managed library project).
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once

enum class TradeButtonState : uint32_t
{
Unchecked = 0, ///< Trade button is not pressed. It means that the trade is not yet accepted by the trader.
Checked = 1, ///< Trade Button is pressed. It means that the trade is accepted by the trader.
Red = 2, ///< This state is only sent to the client. After some seconds the client is changing back to normal Unchecked.
};

enum class StorageType : uint32_t
{
Inventory = 0, ///< The inventory of the player.
Vault = 1, ///< The vault of the player.
TradeOwn = 2, ///< The own trading storage.
TradeOther = 3, ///< The trading storage of the other player.
Crafting = 4, ///< The crafting storage of the player.
PersonalShop = 5, ///< The shop storage of another player.
NpcShop = 6, ///< The shop storage of an NPC (merchant).
InventoryPetSlot = 254, ///< The inventory slot of the pet. That's used when a pet leveled up.
};

enum class PetType : uint32_t
{
DarkRaven = 0, ///< The dark raven pet.
DarkHorse = 1, ///< The dark horse pet.
};

enum class PetCommandMode : uint32_t
{
Normal = 0, ///< The pet is in a normal mode, where it doesn't attack.
AttackRandom = 1, ///< The pet attacks random targets.
AttackWithOwner = 2, ///< The pet attacks the same targets as the owner.
AttackTarget = 3, ///< The pet attacks a specific target until it's dead.
};

enum class GensType : uint32_t
{
Undefined = 0, ///< The undefined gens type.
Duprian = 1, ///< The Duprian gens.
Vanert = 2, ///< The Vanert gens.
};

enum class GuildRelationshipType : uint32_t
{
Undefined = 0, ///< The undefined relationship type.
Alliance = 1, ///< The alliance relationship type.
Hostility = 2, ///< The hostility relationship type.
};

enum class GuildRequestType : uint32_t
{
Undefined = 0, ///< The undefined request type.
Join = 1, ///< The join type.
Leave = 2, ///< The leave type.
};

enum class FruitUsage : uint32_t
{
AddPoints = 0, ///< Adds 1~3 stat points to the character.
RemovePoints = 1, ///< Removes 1~9 stat points from the character.
};

enum class VaultMoneyMoveDirection : uint32_t
{
InventoryToVault = 0, ///< The money is moved from the inventory to the vault.
VaultToInventory = 1, ///< The money is moved from the vault to the inventory.
};

enum class MixType : uint32_t
{
Mix = 0, ///< The player wants to mix single jewels into a bundle.
Unmix = 1, ///< The player wants to disband a bundle into single jewels.
};

enum class StackSize : uint32_t
{
Ten = 0, ///< A stack of 10 items.
Twenty = 1, ///< A stack of 20 items.
Thirty = 2, ///< A stack of 30 items.
};

enum class ItemType : uint32_t
{
JewelOfBless = 0, ///< Jewel of Bless.
JewelOfSoul = 1, ///< Jewel of Soul.
JewelOfLife = 2, ///< Jewel of Life.
JewelOfCreation = 3, ///< Jewel of Creation.
JewelOfGuardian = 4, ///< Jewel of Guardian.
Gemstone = 5, ///< The gemstone.
JewelOfHarmony = 6, ///< Jewel of Harmony.
JewelOfChaos = 7, ///< Jewel of Chaos.
LowerRefineStone = 8, ///< Lower refine stone.
HigherRefineStone = 9, ///< Higher refine stone.
};

enum class ChaosMachineMixType : uint32_t
{
ChaosWeapon = 1, ///< Mixes the items to a chaos weapon.
UpgradeItemLevelTo10 = 3, ///< Upgrades an item to level 10.
UpgradeItemLevelTo11 = 4, ///< Upgrades an item to level 11.
UpgradeItemLevelTo12 = 22, ///< Upgrades an item to level 12.
UpgradeItemLevelTo13 = 23, ///< Upgrades an item to level 13.
UpgradeItemLevelTo14 = 49, ///< Upgrades an item to level 14.
UpgradeItemLevelTo15 = 50, ///< Upgrades an item to level 15.
FruitCreation = 6, ///< Mixes the items to a fruit.
GemstoneRefinery = 41, ///< Refines a gemstone to a jewel of harmony.
PotionOfBless = 15, ///< Refines a Jewel Of Bless to a stack of potions of bless.
PotionOfSoul = 16, ///< Refines a Jewel Of Soul to a stack of potions of bless.
};

enum class QuestProceedAction : uint32_t
{
Undefined = 0, ///< Undefined action.
AcceptQuest = 1, ///< The quest is accepted and started.
RefuseQuest = 2, ///< The quest is refused and not started.
};

