// <copyright file="PacketBindings.h" company="MUnique">
// Licensed under the MIT License. See LICENSE file in the project root for full license information.
// </copyright>

//------------------------------------------------------------------------------
// <auto-generated>
//     This source code was auto-generated by an XSL transformation.
//     Do not change this file. Instead, change the XML data which contains
//     the packet definitions and re-run the transformation (publish/rebuild the
//     managed library project).
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once

#include "stdafx.h"
#include "Connection.h"
#include <coreclr_delegates.h>

#include "PacketFunctions_CommonEnums.h"
#include "PacketFunctions_ClientToServer_Enums.h"

typedef void(CORECLR_DELEGATE_CALLTYPE* SendPing)(int32_t, uint32_t , uint16_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendChecksumResponse)(int32_t, uint32_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendPublicChatMessage)(int32_t, const char16_t* , const char16_t* );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendWhisperMessage)(int32_t, const char16_t* , const char16_t* );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendLoginLongPassword)(int32_t, const BYTE* , uint32_t, const BYTE* , uint32_t, uint32_t , const BYTE* , uint32_t, const BYTE* , uint32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendLoginShortPassword)(int32_t, const BYTE* , uint32_t, const BYTE* , uint32_t, uint32_t , const BYTE* , uint32_t, const BYTE* , uint32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendLogin075)(int32_t, const BYTE* , uint32_t, const BYTE* , uint32_t, uint32_t , const BYTE* , uint32_t, const BYTE* , uint32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendLogOut)(int32_t, LogOutType );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendLogOutByCheatDetection)(int32_t, BYTE , BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendResetCharacterPointRequest)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendPlayerShopSetItemPrice)(int32_t, BYTE , uint32_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendPlayerShopOpen)(int32_t, const char16_t* );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendPlayerShopClose)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendPlayerShopItemListRequest)(int32_t, uint16_t , const char16_t* );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendPlayerShopItemBuyRequest)(int32_t, uint16_t , const char16_t* , BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendPlayerShopCloseOther)(int32_t, uint16_t , const char16_t* );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendPickupItemRequest)(int32_t, uint16_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendPickupItemRequest075)(int32_t, uint16_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendDropItemRequest)(int32_t, BYTE , BYTE , BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendItemMoveRequest)(int32_t, ItemStorageKind , BYTE , const BYTE* , uint32_t, ItemStorageKind , BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendItemMoveRequestExtended)(int32_t, ItemStorageKind , BYTE , ItemStorageKind , BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendConsumeItemRequest)(int32_t, BYTE , BYTE , FruitUsage );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendConsumeItemRequest075)(int32_t, BYTE , BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendTalkToNpcRequest)(int32_t, uint16_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCloseNpcRequest)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendBuyItemFromNpcRequest)(int32_t, BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendSellItemToNpcRequest)(int32_t, BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendRepairItemRequest)(int32_t, BYTE , BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendWarpCommandRequest)(int32_t, uint32_t , uint16_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendEnterGateRequest)(int32_t, uint16_t , BYTE , BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendEnterGateRequest075)(int32_t, BYTE , BYTE , BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendTeleportTarget)(int32_t, uint16_t , BYTE , BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendServerChangeAuthentication)(int32_t, const BYTE* , uint32_t, const BYTE* , uint32_t, uint32_t , uint32_t , uint32_t , uint32_t , uint32_t , const BYTE* , uint32_t, const BYTE* , uint32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCastleSiegeStatusRequest)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCastleSiegeRegistrationRequest)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCastleSiegeUnregisterRequest)(int32_t, BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCastleSiegeRegistrationStateRequest)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCastleSiegeMarkRegistration)(int32_t, BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCastleSiegeDefenseBuyRequest)(int32_t, uint32_t , uint32_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCastleSiegeDefenseRepairRequest)(int32_t, uint32_t , uint32_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCastleSiegeDefenseUpgradeRequest)(int32_t, uint32_t , uint32_t , uint32_t , uint32_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCastleSiegeTaxInfoRequest)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCastleSiegeTaxChangeRequest)(int32_t, BYTE , uint32_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCastleSiegeTaxMoneyWithdraw)(int32_t, uint32_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendToggleCastleGateRequest)(int32_t, BYTE , uint16_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCastleGuildCommand)(int32_t, BYTE , BYTE , BYTE , BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCastleSiegeHuntingZoneEntranceSetting)(int32_t, BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCastleSiegeGateListRequest)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCastleSiegeStatueListRequest)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCastleSiegeRegisteredGuildsListRequest)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCastleOwnerListRequest)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendFireCatapultRequest)(int32_t, uint16_t , BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendWeaponExplosionRequest)(int32_t, uint16_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendGuildLogoOfCastleOwnerRequest)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCastleSiegeHuntingZoneEnterRequest)(int32_t, uint32_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCrywolfInfoRequest)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCrywolfContractRequest)(int32_t, uint16_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCrywolfChaosRateBenefitRequest)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendWhiteAngelItemRequest)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendEnterOnWerewolfRequest)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendEnterOnGatekeeperRequest)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendLeoHelperItemRequest)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendMoveToDeviasBySnowmanRequest)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendSantaClausItemRequest)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendKanturuInfoRequest)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendKanturuEnterRequest)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendRaklionStateInfoRequest)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCashShopPointInfoRequest)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCashShopOpenState)(int32_t, BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCashShopItemBuyRequest)(int32_t, uint32_t , uint32_t , uint32_t , uint16_t , uint32_t , BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCashShopItemGiftRequest)(int32_t, uint32_t , uint32_t , uint32_t , uint16_t , uint32_t , BYTE , const char16_t* , const char16_t* );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCashShopStorageListRequest)(int32_t, uint32_t , BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCashShopDeleteStorageItemRequest)(int32_t, uint32_t , uint32_t , BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCashShopStorageItemConsumeRequest)(int32_t, uint32_t , uint32_t , uint16_t , BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCashShopEventItemListRequest)(int32_t, uint32_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendUnlockVault)(int32_t, uint16_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendSetVaultPin)(int32_t, uint16_t , const char16_t* );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendRemoveVaultPin)(int32_t, const char16_t* );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendVaultClosed)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendVaultMoveMoneyRequest)(int32_t, VaultMoneyMoveDirection , uint32_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendLahapJewelMixRequest)(int32_t, MixType , ItemType , StackSize , BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendPartyListRequest)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendPartyPlayerKickRequest)(int32_t, BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendPartyInviteRequest)(int32_t, uint16_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendPartyInviteResponse)(int32_t, BYTE , uint16_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendWalkRequest)(int32_t, BYTE , BYTE , BYTE , BYTE , const BYTE* , uint32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendWalkRequest075)(int32_t, BYTE , BYTE , BYTE , BYTE , const BYTE* , uint32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendInstantMoveRequest)(int32_t, BYTE , BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendAnimationRequest)(int32_t, BYTE , BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendRequestCharacterList)(int32_t, BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCreateCharacter)(int32_t, const char16_t* , CharacterClassNumber );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendDeleteCharacter)(int32_t, const char16_t* , const char16_t* );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendSelectCharacter)(int32_t, const char16_t* );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendFocusCharacter)(int32_t, const char16_t* );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendIncreaseCharacterStatPoint)(int32_t, CharacterStatAttribute );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendInventoryRequest)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendClientReadyAfterMapChange)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendSaveKeyConfiguration)(int32_t, const BYTE* , uint32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendAddMasterSkillPoint)(int32_t, uint16_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendHitRequest)(int32_t, uint16_t , BYTE , BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendTargetedSkill)(int32_t, uint16_t , uint16_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendTargetedSkill075)(int32_t, BYTE , uint16_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendTargetedSkill095)(int32_t, BYTE , uint16_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendMagicEffectCancelRequest)(int32_t, uint16_t , uint16_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendAreaSkill)(int32_t, uint16_t , BYTE , BYTE , BYTE , uint16_t , BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendAreaSkill075)(int32_t, BYTE , BYTE , BYTE , BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendAreaSkill095)(int32_t, BYTE , BYTE , BYTE , BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendRageAttackRequest)(int32_t, uint16_t , uint16_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendRageAttackRangeRequest)(int32_t, uint16_t , uint16_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendTradeCancel)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendTradeButtonStateChange)(int32_t, TradeButtonState );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendTradeRequest)(int32_t, uint16_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendTradeRequestResponse)(int32_t, BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendSetTradeMoney)(int32_t, uint32_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendLetterDeleteRequest)(int32_t, uint16_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendLetterListRequest)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendLetterSendRequest)(int32_t, uint32_t , const char16_t* , const char16_t* , BYTE , BYTE , uint16_t , const char16_t* );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendLetterReadRequest)(int32_t, uint16_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendGuildKickPlayerRequest)(int32_t, const char16_t* , const char16_t* );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendGuildJoinRequest)(int32_t, uint16_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendGuildJoinResponse)(int32_t, BYTE , uint16_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendGuildListRequest)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendGuildCreateRequest)(int32_t, const char16_t* , const BYTE* , uint32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendGuildCreateRequest075)(int32_t, const char16_t* , const BYTE* , uint32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendGuildMasterAnswer)(int32_t, BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCancelGuildCreation)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendGuildWarResponse)(int32_t, BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendGuildInfoRequest)(int32_t, uint32_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendGuildRoleAssignRequest)(int32_t, uint32_t , const char16_t* , BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendGuildTypeChangeRequest)(int32_t, BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendGuildRelationshipChangeRequest)(int32_t, GuildRelationshipType , GuildRequestType , uint16_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendGuildRelationshipChangeResponse)(int32_t, GuildRelationshipType , GuildRequestType , BYTE , uint16_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendRequestAllianceList)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendRemoveAllianceGuildRequest)(int32_t, const char16_t* );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendPingResponse)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendItemRepair)(int32_t, BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendChaosMachineMixRequest)(int32_t, ChaosMachineMixType , BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCraftingDialogCloseRequest)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendFriendListRequest)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendFriendAddRequest)(int32_t, const char16_t* );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendFriendDelete)(int32_t, const char16_t* );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendChatRoomCreateRequest)(int32_t, const char16_t* );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendFriendAddResponse)(int32_t, BYTE , const char16_t* );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendSetFriendOnlineState)(int32_t, BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendChatRoomInvitationRequest)(int32_t, const char16_t* , uint16_t , uint32_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendLegacyQuestStateRequest)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendLegacyQuestStateSetRequest)(int32_t, BYTE , LegacyQuestState );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendPetCommandRequest)(int32_t, PetType , PetCommandMode , uint16_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendPetInfoRequest)(int32_t, PetType , StorageType , BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendIllusionTempleEnterRequest)(int32_t, BYTE , BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendIllusionTempleSkillRequest)(int32_t, uint16_t , BYTE , BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendIllusionTempleRewardRequest)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendLuckyCoinCountRequest)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendLuckyCoinRegistrationRequest)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendLuckyCoinExchangeRequest)(int32_t, uint32_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendDoppelgangerEnterRequest)(int32_t, BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendEnterMarketPlaceRequest)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendMuHelperStatusChangeRequest)(int32_t, BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendMuHelperSaveDataRequest)(int32_t, const BYTE* , uint32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendQuestSelectRequest)(int32_t, uint16_t , uint16_t , BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendQuestProceedRequest)(int32_t, uint16_t , uint16_t , QuestProceedAction );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendQuestCompletionRequest)(int32_t, uint16_t , uint16_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendQuestCancelRequest)(int32_t, uint16_t , uint16_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendQuestClientActionRequest)(int32_t, uint16_t , uint16_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendActiveQuestListRequest)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendQuestStateRequest)(int32_t, uint16_t , uint16_t );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendEventQuestStateListRequest)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendAvailableQuestsRequest)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendNpcBuffRequest)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendEnterEmpireGuardianEvent)(int32_t, BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendGensJoinRequest)(int32_t, GensType );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendGensLeaveRequest)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendGensRewardRequest)(int32_t, GensType );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendGensRankingRequest)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendDevilSquareEnterRequest)(int32_t, BYTE , BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendMiniGameOpeningStateRequest)(int32_t, MiniGameType , BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendEventChipRegistrationRequest)(int32_t, BYTE , BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendMutoNumberRequest)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendEventChipExitDialog)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendEventChipExchangeRequest)(int32_t, BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendServerImmigrationRequest)(int32_t, const char16_t* );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendLuckyNumberRequest)(int32_t, const char16_t* , const char16_t* , const char16_t* );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendBloodCastleEnterRequest)(int32_t, BYTE , BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendMiniGameEventCountRequest)(int32_t, MiniGameType );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendChaosCastleEnterRequest)(int32_t, BYTE , BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendChaosCastlePositionSet)(int32_t, BYTE , BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendDuelStartRequest)(int32_t, uint16_t , const char16_t* );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendDuelStartResponse)(int32_t, BYTE , uint16_t , const char16_t* );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendDuelStopRequest)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendDuelChannelJoinRequest)(int32_t, BYTE );

typedef void(CORECLR_DELEGATE_CALLTYPE* SendDuelChannelQuitRequest)(int32_t);

typedef void(CORECLR_DELEGATE_CALLTYPE* SendChatCommandListRequest)(int32_t);
