using System.Globalization;
using System.Text;

namespace MuMain.Tools.DialogImporter;

/// Emits the language-agnostic dialog branching table as a C++ header/source
/// pair. The text lives in I18N::Dialog (generated by ResxGen); this table
/// covers what the text cannot:
///   - how many reply buttons each dialog index has
///   - which dialog index each reply jumps to (m_iLinkForAnswer)
///   - which return code each reply sends back to the server (m_iReturnForAnswer)
///
/// Output namespace: GameLogic::Quests::Dialog
///   const Entry& GetEntry(int dialogIndex) noexcept;
///   struct Branch { int link; int returnCode; };
///   struct Entry  { int numAnswer; Branch answers[10]; };
internal static class StructureWriter
{
    private const string Banner = """
        // =============================================================
        // Auto-generated by Tools/DialogImporter. Do not edit by hand.
        // Source: Data/Local/Eng/Dialog_eng.bmd (structural fields only)
        // =============================================================
        """;

    public static void Write(string headerPath, string sourcePath, IReadOnlyList<DialogRecord> entries)
    {
        File.WriteAllText(headerPath, BuildHeader());
        File.WriteAllText(sourcePath, BuildSource(entries));
    }

    private static string BuildHeader()
    {
        var sb = new StringBuilder();
        sb.AppendLine(Banner);
        sb.AppendLine();
        sb.AppendLine("#pragma once");
        sb.AppendLine();
        sb.Append("""
            namespace GameLogic::Quests::Dialog {

            inline constexpr int MaxAnswer = 10;
            inline constexpr int MaxDialog = 200;

            // I18N::Dialog legacy-id encoding (must mirror Tools/DialogImporter):
            //   text:           legacy_id = dialogIndex                   (0..199)
            //   answer (i, n):  legacy_id = 1000 + dialogIndex*10 + slot  (1000..2999)
            inline constexpr int AnswerLegacyIdBase = 1000;
            inline constexpr int AnswerLegacyIdStride = 10;
            inline constexpr int DialogAnswerLegacyId(int dialogIndex, int answerSlot) noexcept
            {
                return AnswerLegacyIdBase + dialogIndex * AnswerLegacyIdStride + answerSlot;
            }

            // One reply branch in a dialog entry. `link` is the dialog index
            // the client jumps to when the player picks this reply; `returnCode`
            // is the answer code the client sends back to the server.
            struct Branch {
                int link;
                int returnCode;
            };

            // The non-localized half of a dialog entry. The localized NPC line
            // and reply labels live in I18N::Dialog (resolved by index via
            // I18N::Dialog::Lookup / LookupSlot).
            struct Entry {
                int numAnswer;
                Branch answers[MaxAnswer];
            };

            // Returns the entry for `dialogIndex` (0-based). Out-of-range
            // indices return a zero-answer sentinel entry so callers can
            // render an empty dialog rather than dereferencing past the table.
            const Entry& GetEntry(int dialogIndex) noexcept;

            }  // namespace GameLogic::Quests::Dialog
            """);
        sb.AppendLine();
        return sb.ToString();
    }

    private static string BuildSource(IReadOnlyList<DialogRecord> entries)
    {
        var sb = new StringBuilder();
        sb.AppendLine(Banner);
        sb.AppendLine();
        sb.Append("""
            #include "GameLogic/Quests/DialogStructure.h"

            namespace GameLogic::Quests::Dialog {
            namespace {

            constexpr Entry kEntries[MaxDialog] = {

            """);

        for (var idx = 0; idx < entries.Count; idx++)
        {
            var entry = entries[idx];
            sb.Append("    {");
            sb.Append(entry.NumAnswer.ToString(CultureInfo.InvariantCulture));
            sb.Append(", {");
            for (var i = 0; i < BmdReader.MaxAnswer; i++)
            {
                if (i > 0) sb.Append(", ");
                sb.Append('{');
                sb.Append(entry.Links[i].ToString(CultureInfo.InvariantCulture));
                sb.Append(", ");
                sb.Append(entry.Returns[i].ToString(CultureInfo.InvariantCulture));
                sb.Append('}');
            }
            sb.Append("}},  // idx ");
            sb.Append(idx.ToString(CultureInfo.InvariantCulture));
            sb.AppendLine();
        }

        sb.Append("""
            };

            constexpr Entry kEmptyEntry = {0, {}};

            }  // namespace

            const Entry& GetEntry(int dialogIndex) noexcept
            {
                if (dialogIndex < 0 || dialogIndex >= MaxDialog) return kEmptyEntry;
                return kEntries[dialogIndex];
            }

            }  // namespace GameLogic::Quests::Dialog
            """);
        sb.AppendLine();
        return sb.ToString();
    }
}
