// Profiler_Define.h: interface for the CProfiler_Define class.
//
//////////////////////////////////////////////////////////////////////

#ifdef LDS_ADD_DEBUGINGMODULES_FOR_PROFILING

#pragma once

#define	OUTPUT_OPTION_RATES 0xf000
#define OUTPUT_OPTION_MEGATICKS 0x0f00
#define OUTPUT_OPTION_MS 0x00f0
#define OUTPUT_OPTION_CALLCOUNT 0x000f
#define OUTPUT_OPTION_ALL 0xffff

#define OUTPUT_OPTION_DEFAULT OUTPUT_OPTION_RATES|OUTPUT_OPTION_MS|OUTPUT_OPTION_CALLCOUNT

enum ESAVEFILE_TYPE {	ESAVEFILE_START = -1,
						ESAVEFILE_NEW_NEXT,
						ESAVEFILE_NEW,
						ESAVEFILE_ACCORD,
						ESAVEFILE_END, };

enum EPROFILESORTING_DIRECTION {
						EPROFILESORTING_DIRECTION_START = -1,
						EPROFILESORTING_DIRECTION_ASCENDING,
						EPROFILESORTING_DIRECTION_DESCENDING,
						EPROFILESORTING_DIRECTION_END,
};

#define EPROFILINGSORTING_DIRECTION_DEFAULT EPROFILESORTING_DIRECTION_ASCENDING

enum EPROFILESORTING_TYPE {	
						EPROFILESORTING_START = -1,
						EPROFILESORTING_WEIGHT,
						EPROFILESORTING_INDEX,
						EPROFILESORTING_END,
};

#define EPROFILESORTING_DEFAULT EPROFILESORTING_INDEX

typedef WORD OUTPUT_OPTION;

#define PROFILING_PROCESS_TOTAL  TEXT( "PROCESS_TOTAL" )
#define PROFILING_SCENE_TOTAL	TEXT( "SCENE_TOTAL" )
#define PROFILING_MAINSCENE_TOTAL  TEXT( "MAINSCENE_TOTAL" )
#define PROFILING_CHARACTERSCENE_TOTAL  TEXT( "CHARACTERSCENE_TOTAL" )
#define PROFILING_LOGOSCENE_TOTAL TEXT("LOGOSCENE_TOTAL")

#define PROFILING_LOADING_TOTAL	TEXT("LOADING_TOTAL")				// Loading Start

#define PROFILING_LOADING_LOADBITMAP TEXT("LOADING_LOADBITMAP")
#define PROFILING_LOADING_GLOBALBITMAP_LOADIMAGE TEXT("LOADING_GLOBALBITMAP_LOADIMAGE")
#define PROFILING_LOADING_GLOBALBITMAP_FINDTEXTURE_BYSTRING TEXT("LOADING_GLOBALBITMAP_FINDTEXTURE_BYSTRING")
#define PROFILING_LOADING_GLOBALBITMAP_FINDTEXTUREBYNAME TEXT("LOADING_GLOBALBITMAP_FINDTEXTUREBYNAME")
#define PROFILING_LOADING_OPENTGA TEXT("LOADING_OPENTGA")
#define PROFILING_LOADING_OPENJPEG TEXT("LOADING_OPENJPEG")
#define PROFILING_LOADING_ACCESSMODEL TEXT("LOADING_ACCESSMODEL")

#define PROFILING_LOADING_ACCESSMODEL_OPEN2 				TEXT("LOADING_ACCESSMODEL_OPEN2")
#define PROFILING_LOADING_ACCESSMODEL_OPEN2_PREOPEN2        TEXT("LOADING_ACCESSMODEL_OPEN2_PREOPEN2")
#define PROFILING_LOADING_ACCESSMODEL_OPEN2_MESHPARSING     TEXT("LOADING_ACCESSMODEL_OPEN2_MESH PARSING")
#define PROFILING_LOADING_ACCESSMODEL_OPEN2_SETNEARTRIANGLE TEXT("LOADING_ACCESSMODEL_OPEN2_SETNEARTRIANGLE")
#define PROFILING_LOADING_ACCESSMODEL_OPEN2_ACTIONPARSING   TEXT("LOADING_ACCESSMODEL_OPEN2_ACTION PARSING")
#define PROFILING_LOADING_ACCESSMODEL_OPEN2_BONEANIPARSING  TEXT("LOADING_ACCESSMODEL_OPEN2_BONEANIPARSING")
#define PROFILING_LOADING_ACCESSMODEL_OPEN2_POSTOPEN2       TEXT("LOADING_ACCESSMODEL_OPEN2_POSTOPEN2")

#define PROFILING_LOADING_OPENTEXTURE TEXT("LOADING_OPENTEXTURE")

#define PROFILING_LOADING_OPENBASICDATA  TEXT("LOADING_OPENBASICDATA")
#define PROFILING_LOADING_PRELOADS  TEXT("LOADING_PRELOADS")
#define PROFILING_LOADING_OPENPLAYERS TEXT("LOADING_OPENPLAYERS")
#define PROFILING_LOADING_OPENPLAYERTEXTURES TEXT("LOADING_OPENPLAYERTEXTURES")
#define PROFILING_LOADING_OPENITEMS TEXT("LOADING_OPENITEMS")
#define PROFILING_LOADING_OPENITEMTEXTURES TEXT("LOADING_OPENITEMTEXTURES")
#define PROFILING_LOADING_OPENSKILLS TEXT("LOADING_OPENSKILLS")
#define PROFILING_LOADING_OPENIMAGES TEXT("LOADING_OPENIMAGES")
#define PROFILING_LOADING_OPENSOUNDS TEXT("LOADING_OPENSOUNDS")
#define PROFILING_LOADING_POSTLOADS TEXT("LOADING_POSTLOADS")		// Loading End

#define PROFILING_MOVE_MAINSCENE_TOTAL  TEXT( "MOVE_MAINSCENE_TOTAL" )
#define PROFILING_MOVE_CHARACTERSCENE_TOTAL  TEXT( "MOVE_CHARACTERSCENE_TOTAL" )
#define PROFILING_MOVE_CHARACTERSCENE_INPUTEVENTS  TEXT( "MOVE_CHARACTERSCENE_INPUTEVENTS" )
#define PROFILING_MOVE_INVENTORY  TEXT( "MOVE_INVENTORY" )
#define PROFILING_UPDATE_NEWUIINVENTORY  TEXT( "UPDATE_NEWUIINVENTORY" )
#define PROFILING_MOVE_BUGS  TEXT( "MOVE_BUGS" )
#define PROFILING_MOVE_BLURS  TEXT( "MOVE_BLURS" )
#define PROFILING_MOVE_INTERFACE  TEXT( "MOVE_INTERFACE" )
#define PROFILING_MOVE_TOURNAMENTINTERFACE  TEXT( "MOVE_TOURNAMENTINTERFACE" )
#define PROFILING_MOVE_OBJECTS  TEXT( "MOVE_OBJECTS" )
#define PROFILING_MOVE_ITEMS  TEXT( "MOVE_ITEMS" )
#define PROFILING_MOVE_LEAVES  TEXT( "MOVE_LEAVES" )
#define PROFILING_MOVE_HERO  TEXT( "MOVE_HERO" )
#define PROFILING_MOVE_CHARACTERSCLIENT  TEXT( "MOVE_CHARACTERSCLIENT" )
#define PROFILING_MOVE_CHARACTERCLIENT  TEXT( "MOVE_CHARACTERCLIENT" )
#define PROFILING_MOVE_EFFECTS_TOTAL  TEXT( "MOVE_EFFECTS_TOTAL" )
#define PROFILING_MOVE_PLANES  TEXT( "MOVE_PLANES" )
#define PROFILING_MOVE_EFFECTS  TEXT( "MOVE_EFFECTS" )
#define PROFILING_MOVE_JOINTS  TEXT( "MOVE_JOINTS" )
#define PROFILING_MOVE_POINTS  TEXT( "MOVE_POINTS" )
#define PROFILING_MOVE_PARTICLES  TEXT( "MOVE_PARTICLES" )
#define PROFILING_MOVE_CAMERA  TEXT( "MOVE_CAMERA" )
#define PROFILING_MOVE_POINTERS  TEXT( "MOVE_POINTERS" )
#define PROFILING_RENDER_SCENE_TOTAL  TEXT( "RENDER_SCENE_TOTAL" )
#define PROFILING_RENDER_MAINSCENE_TOTAL  TEXT( "RENDER_MAINSCENE_TOTAL" )
#define PROFILING_RENDER_CHARACTERSCENE_TOTAL  TEXT( "RENDER_CHARACTERSCENE_TOTAL" )
#define PROFILING_RENDER_MOVEMAINCAMERA  TEXT( "RENDER_MOVEMAINCAMERA" )
#define PROFILING_RENDER_INVENTORY ("RENDER_INVENTORY")
#define PROFILING_RENDER_NEWUIINVENTORY ("RENDER_NEWUIINVENTORY")
#define PROFILING_RENDER_NEWUIINVENTORY_RENDERFRAME ("RENDER_NEWUIINVENTORY_RENDERFRAME")
#define PROFILING_RENDER_NEWUIINVENTORY_RENDERINVENTORYDETAILS ("RENDER_NEWUIINVENTORY_RENDERINVENTORYDETAILS")
#define PROFILING_RENDER_NEWUIINVENTORY_RENDERSETOPTION ("RENDER_NEWUIINVENTORY_RENDERSETOPTION")
#define PROFILING_RENDER_NEWUIINVENTORY_RENDERSOCKETOPTION ("RENDER_NEWUIINVENTORY_RENDERSOCKETOPTION")
#define PROFILING_RENDER_NEWUIINVENTORY_RENDERBUTTONS ("RENDER_NEWUIINVENTORY_RENDERBUTTONS")
#define PROFILING_RENDER_NEWUIINVENTORY_INVENTORYCTRLRENDER ("RENDER_NEWUIINVENTORY_INVENTORYCTRLRENDER")
#define PROFILING_RENDER_NEWUIINVENTORY_RENDEREQUIPEDITEM ("RENDER_NEWUIINVENTORY_RENDEREQUIPEDITEM")
#define PROFILING_RENDER_TERRAIN ("RENDER_TERRAIN")                                
#define PROFILING_RENDER_BUGS ("RENDER_BUGS")
#define PROFILING_RENDER_BLURS ("RENDER_BLURS")
#define PROFILING_RENDER_INTERFACE ("RENDER_INTERFACE")
#define PROFILING_RENDER_TOURNAMENTINTERFACE ("RENDER_TOURNAMENTINTERFACE")
#define PROFILING_RENDER_OBJECTS ("RENDER_OBJECTS") 
#define PROFILING_RENDER_ITEMS ("RENDER_ITEMS") 
#define PROFILING_RENDER_LEAVES ("RENDER_LEAVES")                               
#define PROFILING_RENDER_CHARACTERSCLIENT ("RENDER_CHARACTERSCLIENT")
#define PROFILING_RENDER_EFFECT_TOTAL ("RENDER_EFFECT_TOTAL")
#define PROFILING_RENDER_JOINTS ("RENDER_JOINTS")                                
#define PROFILING_RENDER_EFFECTS ("RENDER_EFFECTS")                                
#define PROFILING_RENDER_BOIDS ("RENDER_BOIDS")                                
#define PROFILING_RENDER_OBJECTS_AFTERCHARACTER ("RENDER_OBJECTS_AFTERCHARACTER")
#define PROFILING_RENDER_SPRITES ("RENDER_SPRITES")                                
#define PROFILING_RENDER_PARTICLES ("RENDER_PARTICLES")                                
#define PROFILING_RENDER_POINTS ("RENDER_POINTS")                                
#define PROFILING_RENDER_INFORMATION ("RENDER_INFORMATION")              
#define PROFILING_SOUNDPROCESS_TOTAL  TEXT( "SOUNDPROCESS_TOTAL" )

enum EPROFILING_PROCESSTYPE { 
	EPROFILING_START = -1,
		EPROFILING_PROCESS_TOTAL,
		EPROFILING_SCENE_TOTAL,
		EPROFILING_MAINSCENE_TOTAL,
		EPROFILING_CHARACTERSCENE_TOTAL,
		EPROFILING_LOGOSCENE_TOTAL,
		EPROFILING_LOADING_TOTAL,				// Loading Start
		
		EPROFILING_LOADING_LOADBITMAP,
		EPROFILING_LOADING_GLOBALBITMAP_LOADIMAGE,
		EPROFILING_LOADING_GLOBALBITMAP_FINDTEXTURE_BYSTRING,
		EPROFILING_LOADING_GLOBALBITMAP_FINDTEXTUREBYNAME,
		EPROFILING_LOADING_OPENTGA, 
		EPROFILING_LOADING_OPENJPEG,
		EPROFILING_LOADING_ACCESSMODEL,

		EPROFILING_LOADING_ACCESSMODEL_OPEN2, 				
		EPROFILING_LOADING_ACCESSMODEL_OPEN2_PREOPEN2,
		EPROFILING_LOADING_ACCESSMODEL_OPEN2_MESHPARSING,     
		EPROFILING_LOADING_ACCESSMODEL_OPEN2_SETNEARTRIANGLE,
		EPROFILING_LOADING_ACCESSMODEL_OPEN2_ACTIONPARSING, 
		EPROFILING_LOADING_ACCESSMODEL_OPEN2_BONEANIPARSING,  
		EPROFILING_LOADING_ACCESSMODEL_OPEN2_POSTOPEN2,

		EPROFILING_LOADING_OPENTEXTURE,

		EPROFILING_LOADING_OPENBASICDATA,
		EPROFILING_LOADING_PRELOADS,
		EPROFILING_LOADING_OPENPLAYERS,
		EPROFILING_LOADING_OPENPLAYERTEXTURES,
		EPROFILING_LOADING_OPENITEMS,
		EPROFILING_LOADING_OPENITEMTEXTURES,
		EPROFILING_LOADING_OPENSKILLS,
		EPROFILING_LOADING_OPENIMAGES,
		EPROFILING_LOADING_OPENSOUNDS,
		EPROFILING_LOADING_POSTLOADS,			// Loading End
		EPROFILING_MOVE_MAINSCENE_TOTAL,
		EPROFILING_MOVE_CHARACTERSCENE_TOTAL,
		EPROFILING_MOVE_CHARACTERSCENE_INPUTEVENTS,
		EPROFILING_MOVE_INVENTORY,
		EPROFILING_UPDATE_NEWUIINVENTORY,
		EPROFILING_MOVE_BUGS,
		EPROFILING_MOVE_BLURS,
		EPROFILING_MOVE_INTERFACE,
		EPROFILING_MOVE_TOURNAMENTINTERFACE,
		EPROFILING_MOVE_OBJECTS,
		EPROFILING_MOVE_ITEMS,
		EPROFILING_MOVE_LEAVES,
		EPROFILING_MOVE_HERO,
		EPROFILING_MOVE_CHARACTERSCLIENT,
		EPROFILING_MOVE_CHARACTERCLIENT,
		EPROFILING_MOVE_EFFECTS_TOTAL,
		EPROFILING_MOVE_PLANES,
		EPROFILING_MOVE_EFFECTS,
		EPROFILING_MOVE_JOINTS,
		EPROFILING_MOVE_POINTS,
		EPROFILING_MOVE_PARTICLES,
		EPROFILING_MOVE_CAMERA,
		EPROFILING_MOVE_POINTERS,
		EPROFILING_RENDER_SCENE_TOTAL,
		EPROFILING_RENDER_MAINSCENE_TOTAL,
		EPROFILING_RENDER_CHARACTERSCENE_TOTAL,
		EPROFILING_RENDER_MOVEMAINCAMERA,
		EPROFILING_RENDER_INVENTORY,
		EPROFILING_RENDER_NEWUIINVENTORY,
		EPROFILING_RENDER_NEWUIINVENTORY_RENDERFRAME,
		EPROFILING_RENDER_NEWUIINVENTORY_RENDERINVENTORYDETAILS,
		EPROFILING_RENDER_NEWUIINVENTORY_RENDERSETOPTION,
		EPROFILING_RENDER_NEWUIINVENTORY_RENDERSOCKETOPTION,
		EPROFILING_RENDER_NEWUIINVENTORY_RENDERBUTTONS,
		EPROFILING_RENDER_NEWUIINVENTORY_INVENTORYCTRLRENDER,
		EPROFILING_RENDER_NEWUIINVENTORY_RENDEREQUIPEDITEM,
		EPROFILING_RENDER_TERRAIN,
		EPROFILING_RENDER_BUGS,
		EPROFILING_RENDER_BLURS,
		EPROFILING_RENDER_INTERFACE,
		EPROFILING_RENDER_TOURNAMENTINTERFACE,
		EPROFILING_RENDER_OBJECTS,
		EPROFILING_RENDER_ITEMS,
		EPROFILING_RENDER_LEAVES,
		EPROFILING_RENDER_CHARACTERSCLIENT,
		EPROFILING_RENDER_EFFECT_TOTAL,
		EPROFILING_RENDER_JOINTS,
		EPROFILING_RENDER_EFFECTS,
		EPROFILING_RENDER_BOIDS,
		EPROFILING_RENDER_OBJECTS_AFTERCHARACTER,
		EPROFILING_RENDER_SPRITES,
		EPROFILING_RENDER_PARTICLES,
		EPROFILING_RENDER_POINTS,
		EPROFILING_RENDER_INFORMATION,
		EPROFILING_SOUNDPROCESS_TOTAL,
		EPROFILING_END,};


#endif // LDS_ADD_DEBUGINGMODULES_FOR_PROFILING