using System.Text;

namespace MuMain.Tools.ResxGen;

/// Emits C++ headers and sources from loaded resource groups.
///
/// Output shape (per group "Editor"):
///
///   I18N/Editor.h
///     namespace I18N::Editor {
///         extern const char* SaveSkills;
///         void ApplyLocale(const char* locale) noexcept;
///     }
///
///   I18N/Editor.cpp
///     Per-locale string tables, mutable pointer variables, ApplyLocale().
///
/// Plus a master pair:
///
///   I18N/All.h       — fans out SetLocale() to each group's ApplyLocale().
///   I18N/All.cpp
internal static class CppEmitter
{
    /// Root C++ namespace for everything we emit.
    private const string RootNamespace = "I18N";

    /// Master header/source filename (without extension).
    private const string MasterFileName = "All";

    /// Display name for each known locale, in that locale's own language.
    /// Locales emitted by the generator but missing here fall through to
    /// returning the locale code itself at runtime.
    private static readonly IReadOnlyDictionary<string, string> KnownLanguageDisplayNames =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["de"]    = "Deutsch",
            ["en"]    = "English",
            ["es"]    = "Español",
            ["id"]    = "Bahasa Indonesia",
            ["ja"]    = "日本語",
            ["pl"]    = "Polski",
            ["pt"]    = "Português",
            ["ru"]    = "Русский",
            ["tl"]    = "Tagalog",
            ["uk"]    = "Українська",
            ["zh-TW"] = "繁體中文",
        };

    /// Banner placed at the top of every generated file.
    private const string GeneratedBanner = """
        // =============================================================
        // Auto-generated by Tools/ResxGen. Do not edit by hand.
        // Source: src/Localization/*.resx
        // =============================================================
        """;

    /// Locale ordering used by both the master kLocales table and every
    /// group's data-driven kSlots table. Default locale first, the rest in
    /// ordinal order. Every group's per-identifier value array indexes into
    /// this list, so the order MUST stay in sync.
    public static IReadOnlyList<string> ComputeMasterLocales(IReadOnlyList<ResourceGroup> groups)
    {
        return groups.SelectMany(g => g.Locales)
                     .Distinct(StringComparer.Ordinal)
                     .OrderBy(l => l == ResxLoader.DefaultLocale ? "" : l, StringComparer.Ordinal)
                     .ToList();
    }

    public static void WriteGroupHeader(string outputDir, ResourceGroup group)
    {
        var sb = new StringBuilder();
        AppendBanner(sb);

        sb.Append($$"""
            #pragma once

            namespace {{RootNamespace}}::{{group.Name}} {


            """);

        var charType = group.IsWide ? "wchar_t" : "char";
        foreach (var entry in group.Entries)
        {
            sb.AppendLine($"extern const {charType}* {entry.Identifier};   // {EscapeComment(entry.Key)}");
        }

        sb.Append($$"""

            // Switches every string in this group to the locale identified by
            // `localeIndex` (the index into I18N::GetAvailableLocales, also the
            // value returned by I18N::LocaleIndex). The master SetLocale
            // resolves the locale string once and dispatches the int here.
            void ApplyLocale(int localeIndex) noexcept;

            """);

        if (HasLegacyIds(group))
        {
            sb.Append($$"""

                // Resolves a legacy integer ID (from the pre-migration GlobalText[N]
                // contract) to the corresponding string in the active locale. Returns
                // a non-null empty literal for unknown IDs.
                const {{charType}}* Lookup(int legacyId) noexcept;

                // Slot variant of Lookup: returns a pointer to the runtime
                // I18N slot rather than its current value. Useful for widgets
                // that take a const T* const* and refresh themselves on
                // locale change. Returns nullptr for unknown IDs.
                const {{charType}}* const* LookupSlot(int legacyId) noexcept;

                """);
        }

        sb.Append($$"""

            }  // namespace {{RootNamespace}}::{{group.Name}}

            """);

        File.WriteAllText(Path.Combine(outputDir, $"{group.Name}.h"), sb.ToString());
    }

    public static void WriteGroupSource(string outputDir, ResourceGroup group, IReadOnlyList<string> masterLocales)
    {
        var sb = new StringBuilder();
        AppendBanner(sb);

        sb.Append($$"""
            #include "{{group.Name}}.h"

            #include <algorithm>
            #include <cstring>
            #include <iterator>

            namespace {{RootNamespace}}::{{group.Name}} {

            namespace {

            """);

        WriteLocaleTables(sb, group);

        sb.AppendLine();
        sb.AppendLine("}  // namespace");
        sb.AppendLine();

        WriteRuntimePointers(sb, group);
        sb.AppendLine();
        WriteSlotTable(sb, group, masterLocales);
        sb.AppendLine();
        WriteApplyLocale(sb);

        if (HasLegacyIds(group))
        {
            sb.AppendLine();
            WriteLegacyLookup(sb, group);
        }

        sb.Append($$"""

            }  // namespace {{RootNamespace}}::{{group.Name}}

            """);

        File.WriteAllText(Path.Combine(outputDir, $"{group.Name}.cpp"), sb.ToString());
    }

    public static void WriteMasterHeader(string outputDir, IReadOnlyList<ResourceGroup> groups)
    {
        var sb = new StringBuilder();
        AppendBanner(sb);

        sb.AppendLine("#pragma once");
        sb.AppendLine();
        sb.AppendLine("#include <initializer_list>");
        sb.AppendLine("#include <span>");
        sb.AppendLine("#include <string>");
        sb.AppendLine("#include <string_view>");
        sb.AppendLine();
        foreach (var g in groups)
        {
            sb.AppendLine($"#include \"{g.Name}.h\"");
        }
        sb.Append($$"""

            namespace {{RootNamespace}} {

            // Switches every group to the given locale. Unknown locales fall
            // back to the default locale (en). After updating the group pointers,
            // invokes every registered LocaleObserver so cached UI state (button
            // tooltips, list labels, etc.) can refresh from the new locale.
            void SetLocale(const char* locale) noexcept;

            // Returns the locale code passed to the last successful SetLocale
            // (or the default locale before any explicit call). Never null.
            const char* GetCurrentLocale() noexcept;

            // Substitutes {0}, {1}, ... in `format` with the given arguments and
            // returns the result. Used for translated strings that contain
            // placeholders, e.g. Format(Editor::ErrorIndexAlreadyInUse, {idxStr}).
            std::string Format(const char* format, std::initializer_list<std::string_view> args);

            // Returns the locale codes this build was generated with, default
            // locale ("en") first. The span backs static storage and is valid
            // for the program's lifetime.
            std::span<const char* const> GetAvailableLocales() noexcept;

            // Returns the position of `locale` in GetAvailableLocales (0-based,
            // default locale at 0). Returns -1 for unknown or null. Used by
            // each group's data-driven ApplyLocale(int) dispatch.
            int LocaleIndex(const char* locale) noexcept;

            // Returns the display name for `locale` in that locale's own
            // language (e.g. "Deutsch" for "de"). Returns `locale` itself for
            // codes the generator does not have a display name for.
            const char* GetLanguageDisplayName(const char* locale) noexcept;

            // Callback invoked from SetLocale after group pointers have been
            // updated. Implementations should re-read any cached I18N strings.
            using LocaleObserver = void (*)(void* context) noexcept;

            // Registers `cb` to be invoked on every subsequent SetLocale. The
            // (cb, ctx) pair identifies the registration: the same callback
            // function may be registered with different contexts. Duplicate
            // (cb, ctx) registrations are ignored. Null callbacks are ignored.
            void RegisterLocaleObserver(LocaleObserver cb, void* ctx) noexcept;

            // Removes a previously registered (cb, ctx) pair. No-op if the pair
            // is not currently registered.
            void UnregisterLocaleObserver(LocaleObserver cb, void* ctx) noexcept;

            }  // namespace {{RootNamespace}}

            """);

        File.WriteAllText(Path.Combine(outputDir, $"{MasterFileName}.h"), sb.ToString());
    }

    public static void WriteMasterSource(string outputDir, IReadOnlyList<ResourceGroup> groups)
    {
        var sb = new StringBuilder();
        AppendBanner(sb);

        sb.Append($$"""
            #include "{{MasterFileName}}.h"

            #include <cstddef>
            #include <cstring>
            #include <vector>

            namespace {{RootNamespace}} {
            namespace {

            """);

        WriteLocaleRegistry(sb, groups);

        sb.Append($$"""

            constexpr int kDefaultLocaleIndex = 0;
            const char* g_currentLocale = kLocales[kDefaultLocaleIndex];

            struct ObserverEntry { LocaleObserver cb; void* ctx; };

            // Function-local static keeps construction order well-defined for
            // observers registered during global init (e.g. statically allocated
            // UI). Heap usage is bounded by live observer count; locale switches
            // are user-driven and not on any hot path.
            std::vector<ObserverEntry>& Observers() noexcept
            {
                static std::vector<ObserverEntry> v;
                return v;
            }

            }  // namespace

            int LocaleIndex(const char* locale) noexcept
            {
                if (locale == nullptr) return -1;
                for (int i = 0; i < static_cast<int>(std::size(kLocales)); ++i)
                {
                    if (std::strcmp(kLocales[i], locale) == 0) return i;
                }
                return -1;
            }

            void SetLocale(const char* locale) noexcept
            {
                int idx = LocaleIndex(locale);
                if (idx < 0) idx = kDefaultLocaleIndex;
                g_currentLocale = kLocales[idx];

            """);

        foreach (var g in groups)
        {
            sb.AppendLine($"    {g.Name}::ApplyLocale(idx);");
        }

        sb.Append($$"""

                // Snapshot the registry so observers that unregister themselves
                // (e.g. via a destructor triggered as a side effect of the
                // callback) don't shift indices mid-iteration.
                const std::vector<ObserverEntry> snapshot = Observers();
                for (const auto& entry : snapshot)
                {
                    if (entry.cb != nullptr) entry.cb(entry.ctx);
                }
            }

            void RegisterLocaleObserver(LocaleObserver cb, void* ctx) noexcept
            {
                if (cb == nullptr) return;
                auto& list = Observers();
                for (const auto& entry : list)
                {
                    if (entry.cb == cb && entry.ctx == ctx) return;
                }
                list.push_back({cb, ctx});
            }

            void UnregisterLocaleObserver(LocaleObserver cb, void* ctx) noexcept
            {
                auto& list = Observers();
                for (auto it = list.begin(); it != list.end(); ++it)
                {
                    if (it->cb == cb && it->ctx == ctx)
                    {
                        *it = list.back();
                        list.pop_back();
                        return;
                    }
                }
            }

            const char* GetCurrentLocale() noexcept
            {
                return g_currentLocale;
            }

            std::span<const char* const> GetAvailableLocales() noexcept
            {
                return {kLocales, sizeof(kLocales) / sizeof(kLocales[0])};
            }

            const char* GetLanguageDisplayName(const char* locale) noexcept
            {
                if (locale == nullptr) return "";
                for (const auto& entry : kLanguageDisplayNames)
                {
                    if (std::strcmp(entry.code, locale) == 0) return entry.name;
                }
                return locale;
            }

            std::string Format(const char* format, std::initializer_list<std::string_view> args)
            {
                if (format == nullptr) return {};

                // Reserve format length plus the total size of all arguments.
                // This is an over-estimate when args appear fewer times than
                // they are provided, but it eliminates string growth for the
                // common case where every arg expands at least once.
                std::size_t reserveSize = std::char_traits<char>::length(format);
                for (const auto& arg : args) reserveSize += arg.size();
                std::string result;
                result.reserve(reserveSize);

                for (const char* p = format; *p != '\0'; )
                {
                    if (*p == '{')
                    {
                        // Two adjacent open braces collapse to one literal,
                        // so translations can carry brace characters next to
                        // placeholders.
                        if (p[1] == '{')
                        {
                            result.push_back('{');
                            p += 2;
                            continue;
                        }

                        // Parse {N} where N is a non-negative integer index.
                        const char* digits = p + 1;
                        std::size_t index = 0;
                        bool hasDigit = false;
                        while (*digits >= '0' && *digits <= '9')
                        {
                            index = index * 10 + static_cast<std::size_t>(*digits - '0');
                            ++digits;
                            hasDigit = true;
                        }
                        if (hasDigit && *digits == '}')
                        {
                            if (index < args.size())
                            {
                                const auto& arg = *(args.begin() + index);
                                result.append(arg.data(), arg.size());
                            }
                            else
                            {
                                // Unknown index: keep the original {N} text so
                                // missing or mis-numbered arguments are visible
                                // in-game and during translation review.
                                result.append(p, static_cast<std::size_t>(digits + 1 - p));
                            }
                            p = digits + 1;
                            continue;
                        }
                    }
                    else if (*p == '}' && p[1] == '}')
                    {
                        // Two adjacent close braces collapse to one literal,
                        // symmetric with the open-brace escape above.
                        result.push_back('}');
                        p += 2;
                        continue;
                    }
                    result.push_back(*p++);
                }

                return result;
            }

            }  // namespace {{RootNamespace}}

            """);

        File.WriteAllText(Path.Combine(outputDir, $"{MasterFileName}.cpp"), sb.ToString());
    }

    private static void WriteLocaleRegistry(StringBuilder sb, IReadOnlyList<ResourceGroup> groups)
    {
        var locales = ComputeMasterLocales(groups);

        sb.AppendLine("constexpr const char* kLocales[] = {");
        foreach (var locale in locales)
        {
            sb.AppendLine($"    {Naming.EscapeCppString(locale)},");
        }
        sb.AppendLine("};");
        sb.AppendLine();

        sb.AppendLine("struct LanguageDisplayEntry { const char* code; const char* name; };");
        sb.AppendLine("constexpr LanguageDisplayEntry kLanguageDisplayNames[] = {");
        foreach (var locale in locales)
        {
            if (KnownLanguageDisplayNames.TryGetValue(locale, out var displayName))
            {
                sb.AppendLine($"    {{ {Naming.EscapeCppString(locale)}, {Naming.EscapeCppString(displayName)} }},");
            }
        }
        sb.AppendLine("};");
    }

    private static void WriteLocaleTables(StringBuilder sb, ResourceGroup group)
    {
        var charType = group.IsWide ? "wchar_t" : "char";
        foreach (var locale in group.Locales)
        {
            var sanitized = Naming.SanitizeLocale(locale);
            foreach (var entry in group.Entries)
            {
                var value = ResolveValueWithFallback(entry, locale);
                if (group.IsWide)
                {
                    // Rewrite %s/%S -> %ls so swprintf reads the wchar_t* arg
                    // correctly on Windows; mirrors the legacy bmd loader.
                    value = Naming.NormalizePrintfSpecifiersForWide(value);
                }
                sb.AppendLine($"constexpr const {charType}* k_{sanitized}_{entry.Identifier} = {Naming.EscapeCppString(value, group.IsWide)};");
            }
            sb.AppendLine();
        }
    }

    private static void WriteRuntimePointers(StringBuilder sb, ResourceGroup group)
    {
        var charType = group.IsWide ? "wchar_t" : "char";
        var defaultSanitized = Naming.SanitizeLocale(ResxLoader.DefaultLocale);
        foreach (var entry in group.Entries)
        {
            sb.AppendLine($"const {charType}* {entry.Identifier} = k_{defaultSanitized}_{entry.Identifier};");
        }
    }

    /// Emits the per-identifier {dest, values[]} table that ApplyLocale
    /// walks. Each row carries the address of the identifier's runtime
    /// pointer plus one value per master locale (in master-locale order).
    /// When this group has no translation for a master locale, the value
    /// for that column falls back to the default-locale literal, so the
    /// runtime never needs to branch on a missing-translation case.
    private static void WriteSlotTable(StringBuilder sb, ResourceGroup group, IReadOnlyList<string> masterLocales)
    {
        var charType = group.IsWide ? "wchar_t" : "char";
        var defaultSanitized = Naming.SanitizeLocale(ResxLoader.DefaultLocale);
        var groupLocaleSet = new HashSet<string>(group.Locales, StringComparer.Ordinal);

        sb.AppendLine("namespace {");
        sb.AppendLine($"struct LocaleSlot {{ const {charType}** dest; const {charType}* values[{masterLocales.Count}]; }};");
        sb.AppendLine("constexpr LocaleSlot kSlots[] = {");
        foreach (var entry in group.Entries)
        {
            sb.Append($"    {{ &{entry.Identifier}, {{ ");
            for (var i = 0; i < masterLocales.Count; i++)
            {
                if (i > 0) sb.Append(", ");
                var locale = masterLocales[i];
                var key = groupLocaleSet.Contains(locale)
                    ? Naming.SanitizeLocale(locale)
                    : defaultSanitized;
                sb.Append($"k_{key}_{entry.Identifier}");
            }
            sb.AppendLine(" } },");
        }
        sb.AppendLine("};");
        sb.AppendLine("}  // namespace");
    }

    private static void WriteApplyLocale(StringBuilder sb)
    {
        sb.AppendLine("void ApplyLocale(int localeIndex) noexcept");
        sb.AppendLine("{");
        sb.AppendLine("    for (const auto& slot : kSlots)");
        sb.AppendLine("    {");
        sb.AppendLine("        *slot.dest = slot.values[localeIndex];");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static string ResolveValueWithFallback(ResourceEntry entry, string locale)
    {
        if (entry.Translations.TryGetValue(locale, out var value))
        {
            return value;
        }
        // Fall back to the English key, since the key IS the English text.
        return entry.Translations.TryGetValue(ResxLoader.DefaultLocale, out var defaultValue)
            ? defaultValue
            : entry.Key;
    }

    private static bool HasLegacyIds(ResourceGroup group)
    {
        return group.Entries.Any(e => e.LegacyIds.Count > 0);
    }

    private static void WriteLegacyLookup(StringBuilder sb, ResourceGroup group)
    {
        var charType = group.IsWide ? "wchar_t" : "char";

        // Flatten (legacyId, identifier) pairs and sort by id for binary search.
        var rows = group.Entries
                        .SelectMany(e => e.LegacyIds.Select(id => (id, ident: e.Identifier)))
                        .OrderBy(r => r.id)
                        .ToList();

        sb.AppendLine("namespace {");
        sb.AppendLine($"struct LegacyEntry {{ int id; const {charType}* const* slot; }};");
        sb.AppendLine("constexpr LegacyEntry kLegacyTable[] = {");
        foreach (var (id, ident) in rows)
        {
            sb.AppendLine($"    {{ {id}, &{ident} }},");
        }
        sb.AppendLine("};");
        sb.AppendLine($"constexpr {(group.IsWide ? "wchar_t" : "char")} kLegacyFallback[] = {(group.IsWide ? "L\"\"" : "\"\"")};");
        sb.AppendLine();
        sb.AppendLine("// Compile-time guard: the lookup uses std::lower_bound and assumes");
        sb.AppendLine("// strictly-increasing IDs. ResxGen already rejects duplicate");
        sb.AppendLine("// legacy_id entries at generation time; this assert protects against");
        sb.AppendLine("// the generated file being hand-edited out of sync.");
        sb.AppendLine("constexpr bool LegacyTableStrictlySorted() noexcept");
        sb.AppendLine("{");
        sb.AppendLine("    for (std::size_t i = 1; i < std::size(kLegacyTable); ++i)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (kLegacyTable[i - 1].id >= kLegacyTable[i].id) return false;");
        sb.AppendLine("    }");
        sb.AppendLine("    return true;");
        sb.AppendLine("}");
        sb.AppendLine($"static_assert(LegacyTableStrictlySorted(),");
        sb.AppendLine($"    \"Duplicate or unsorted legacy_id in I18N::{group.Name}::kLegacyTable; \"");
        sb.AppendLine($"    \"Lookup(int) requires unique IDs. Check Tools/ResxGen output.\");");
        sb.AppendLine();
        sb.AppendLine("const LegacyEntry* FindLegacyEntry(int legacyId) noexcept");
        sb.AppendLine("{");
        sb.AppendLine("    const auto* const end = std::end(kLegacyTable);");
        sb.AppendLine("    const auto* it = std::lower_bound(std::begin(kLegacyTable), end, legacyId,");
        sb.AppendLine("        [](const LegacyEntry& e, int id) { return e.id < id; });");
        sb.AppendLine("    if (it != end && it->id == legacyId) return it;");
        sb.AppendLine("    return nullptr;");
        sb.AppendLine("}");
        sb.AppendLine("}  // namespace");
        sb.AppendLine();
        sb.AppendLine($"const {charType}* Lookup(int legacyId) noexcept");
        sb.AppendLine("{");
        sb.AppendLine("    const LegacyEntry* entry = FindLegacyEntry(legacyId);");
        sb.AppendLine("    return entry != nullptr ? *entry->slot : kLegacyFallback;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine($"const {charType}* const* LookupSlot(int legacyId) noexcept");
        sb.AppendLine("{");
        sb.AppendLine("    const LegacyEntry* entry = FindLegacyEntry(legacyId);");
        sb.AppendLine("    return entry != nullptr ? entry->slot : nullptr;");
        sb.AppendLine("}");
    }

    private static void AppendBanner(StringBuilder sb)
    {
        sb.AppendLine(GeneratedBanner);
        sb.AppendLine();
    }

    /// Sanitize a key for use in a // comment — strip newlines so the
    /// comment stays on one line.
    private static string EscapeComment(string key)
    {
        return key.Replace('\n', ' ').Replace('\r', ' ');
    }
}
