using System.Text;

namespace MuMain.Tools.ResxGen;

/// Emits C++ headers and sources from loaded resource groups.
///
/// Output shape (per group "Editor"):
///
///   I18N/Editor.h
///     namespace I18N::Editor {
///         extern const char* SaveSkills;
///         void ApplyLocale(const char* locale) noexcept;
///     }
///
///   I18N/Editor.cpp
///     Per-locale string tables, mutable pointer variables, ApplyLocale().
///
/// Plus a master pair:
///
///   I18N/All.h       — fans out SetLocale() to each group's ApplyLocale().
///   I18N/All.cpp
internal static class CppEmitter
{
    /// Root C++ namespace for everything we emit.
    private const string RootNamespace = "I18N";

    /// Master header/source filename (without extension).
    private const string MasterFileName = "All";

    /// Banner placed at the top of every generated file.
    private const string GeneratedBanner = """
        // =============================================================
        // Auto-generated by Tools/ResxGen. Do not edit by hand.
        // Source: src/Localization/*.resx
        // =============================================================
        """;

    public static void WriteGroupHeader(string outputDir, ResourceGroup group)
    {
        var sb = new StringBuilder();
        AppendBanner(sb);

        sb.Append($$"""
            #pragma once

            namespace {{RootNamespace}}::{{group.Name}} {


            """);

        foreach (var entry in group.Entries)
        {
            sb.AppendLine($"extern const char* {entry.Identifier};   // {EscapeComment(entry.Key)}");
        }

        sb.Append($$"""

            void ApplyLocale(const char* locale) noexcept;

            }  // namespace {{RootNamespace}}::{{group.Name}}

            """);

        File.WriteAllText(Path.Combine(outputDir, $"{group.Name}.h"), sb.ToString());
    }

    public static void WriteGroupSource(string outputDir, ResourceGroup group)
    {
        var sb = new StringBuilder();
        AppendBanner(sb);

        sb.Append($$"""
            #include "{{group.Name}}.h"

            #include <cstring>

            namespace {{RootNamespace}}::{{group.Name}} {

            namespace {

            """);

        WriteLocaleTables(sb, group);

        sb.AppendLine();
        sb.AppendLine("}  // namespace");
        sb.AppendLine();

        WriteRuntimePointers(sb, group);
        sb.AppendLine();
        WriteApplyLocale(sb, group);

        sb.Append($$"""

            }  // namespace {{RootNamespace}}::{{group.Name}}

            """);

        File.WriteAllText(Path.Combine(outputDir, $"{group.Name}.cpp"), sb.ToString());
    }

    public static void WriteMasterHeader(string outputDir, IReadOnlyList<ResourceGroup> groups)
    {
        var sb = new StringBuilder();
        AppendBanner(sb);

        sb.AppendLine("#pragma once");
        sb.AppendLine();
        foreach (var g in groups)
        {
            sb.AppendLine($"#include \"{g.Name}.h\"");
        }
        sb.Append($$"""

            namespace {{RootNamespace}} {

            // Switches every group to the given locale. Unknown locales fall
            // back to the default locale (en).
            void SetLocale(const char* locale) noexcept;

            }  // namespace {{RootNamespace}}

            """);

        File.WriteAllText(Path.Combine(outputDir, $"{MasterFileName}.h"), sb.ToString());
    }

    public static void WriteMasterSource(string outputDir, IReadOnlyList<ResourceGroup> groups)
    {
        var sb = new StringBuilder();
        AppendBanner(sb);

        sb.Append($$"""
            #include "{{MasterFileName}}.h"

            namespace {{RootNamespace}} {

            void SetLocale(const char* locale) noexcept
            {

            """);

        foreach (var g in groups)
        {
            sb.AppendLine($"    {g.Name}::ApplyLocale(locale);");
        }

        sb.Append($$"""
            }

            }  // namespace {{RootNamespace}}

            """);

        File.WriteAllText(Path.Combine(outputDir, $"{MasterFileName}.cpp"), sb.ToString());
    }

    private static void WriteLocaleTables(StringBuilder sb, ResourceGroup group)
    {
        foreach (var locale in group.Locales)
        {
            var sanitized = Naming.SanitizeLocale(locale);
            foreach (var entry in group.Entries)
            {
                var value = ResolveValueWithFallback(entry, locale);
                sb.AppendLine($"constexpr const char* k_{sanitized}_{entry.Identifier} = {Naming.EscapeCppString(value)};");
            }
            sb.AppendLine();
        }
    }

    private static void WriteRuntimePointers(StringBuilder sb, ResourceGroup group)
    {
        var defaultSanitized = Naming.SanitizeLocale(ResxLoader.DefaultLocale);
        foreach (var entry in group.Entries)
        {
            sb.AppendLine($"const char* {entry.Identifier} = k_{defaultSanitized}_{entry.Identifier};");
        }
    }

    private static void WriteApplyLocale(StringBuilder sb, ResourceGroup group)
    {
        var defaultSanitized = Naming.SanitizeLocale(ResxLoader.DefaultLocale);

        sb.AppendLine("void ApplyLocale(const char* locale) noexcept");
        sb.AppendLine("{");

        // Non-default locales first: pattern is one branch per locale, each
        // assigns all pointers and returns. Fallback at the bottom handles
        // both nullptr and unknown locales.
        foreach (var locale in group.Locales.Where(l => l != ResxLoader.DefaultLocale))
        {
            var sanitized = Naming.SanitizeLocale(locale);
            sb.AppendLine($"    if (locale != nullptr && std::strcmp(locale, \"{locale}\") == 0)");
            sb.AppendLine("    {");
            foreach (var entry in group.Entries)
            {
                sb.AppendLine($"        {entry.Identifier} = k_{sanitized}_{entry.Identifier};");
            }
            sb.AppendLine("        return;");
            sb.AppendLine("    }");
        }

        foreach (var entry in group.Entries)
        {
            sb.AppendLine($"    {entry.Identifier} = k_{defaultSanitized}_{entry.Identifier};");
        }

        sb.AppendLine("}");
    }

    private static string ResolveValueWithFallback(ResourceEntry entry, string locale)
    {
        if (entry.Translations.TryGetValue(locale, out var value))
        {
            return value;
        }
        // Fall back to the English key, since the key IS the English text.
        return entry.Translations.TryGetValue(ResxLoader.DefaultLocale, out var defaultValue)
            ? defaultValue
            : entry.Key;
    }

    private static void AppendBanner(StringBuilder sb)
    {
        sb.AppendLine(GeneratedBanner);
        sb.AppendLine();
    }

    /// Sanitize a key for use in a // comment — strip newlines so the
    /// comment stays on one line.
    private static string EscapeComment(string key)
    {
        return key.Replace('\n', ' ').Replace('\r', ' ');
    }
}
