using System.Text;

namespace MuMain.Tools.ResxGen;

/// Emits C++ headers and sources from loaded resource groups.
///
/// Output shape (per group "Editor"):
///
///   I18N/Editor.h
///     namespace I18N::Editor {
///         extern const char* SaveSkills;
///         void ApplyLocale(const char* locale) noexcept;
///     }
///
///   I18N/Editor.cpp
///     Per-locale string tables, mutable pointer variables, ApplyLocale().
///
/// Plus a master pair:
///
///   I18N/All.h       — fans out SetLocale() to each group's ApplyLocale().
///   I18N/All.cpp
internal static class CppEmitter
{
    /// Root C++ namespace for everything we emit.
    private const string RootNamespace = "I18N";

    /// Master header/source filename (without extension).
    private const string MasterFileName = "All";

    /// Display name for each known locale, in that locale's own language.
    /// Locales emitted by the generator but missing here fall through to
    /// returning the locale code itself at runtime.
    private static readonly IReadOnlyDictionary<string, string> KnownLanguageDisplayNames =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["de"]    = "Deutsch",
            ["en"]    = "English",
            ["es"]    = "Español",
            ["id"]    = "Bahasa Indonesia",
            ["pl"]    = "Polski",
            ["pt"]    = "Português",
            ["ru"]    = "Русский",
            ["tl"]    = "Tagalog",
            ["uk"]    = "Українська",
            ["zh-TW"] = "繁體中文",
        };

    /// Banner placed at the top of every generated file.
    private const string GeneratedBanner = """
        // =============================================================
        // Auto-generated by Tools/ResxGen. Do not edit by hand.
        // Source: src/Localization/*.resx
        // =============================================================
        """;

    public static void WriteGroupHeader(string outputDir, ResourceGroup group)
    {
        var sb = new StringBuilder();
        AppendBanner(sb);

        sb.Append($$"""
            #pragma once

            namespace {{RootNamespace}}::{{group.Name}} {


            """);

        var charType = group.IsWide ? "wchar_t" : "char";
        foreach (var entry in group.Entries)
        {
            sb.AppendLine($"extern const {charType}* {entry.Identifier};   // {EscapeComment(entry.Key)}");
        }

        sb.Append($$"""

            void ApplyLocale(const char* locale) noexcept;

            """);

        if (HasLegacyIds(group))
        {
            sb.Append($$"""

                // Resolves a legacy integer ID (from the pre-migration GlobalText[N]
                // contract) to the corresponding string in the active locale. Returns
                // a non-null empty literal for unknown IDs.
                const {{charType}}* Lookup(int legacyId) noexcept;

                """);
        }

        sb.Append($$"""

            }  // namespace {{RootNamespace}}::{{group.Name}}

            """);

        File.WriteAllText(Path.Combine(outputDir, $"{group.Name}.h"), sb.ToString());
    }

    public static void WriteGroupSource(string outputDir, ResourceGroup group)
    {
        var sb = new StringBuilder();
        AppendBanner(sb);

        sb.Append($$"""
            #include "{{group.Name}}.h"

            #include <cstring>

            namespace {{RootNamespace}}::{{group.Name}} {

            namespace {

            """);

        WriteLocaleTables(sb, group);

        sb.AppendLine();
        sb.AppendLine("}  // namespace");
        sb.AppendLine();

        WriteRuntimePointers(sb, group);
        sb.AppendLine();
        WriteApplyLocale(sb, group);

        if (HasLegacyIds(group))
        {
            sb.AppendLine();
            WriteLegacyLookup(sb, group);
        }

        sb.Append($$"""

            }  // namespace {{RootNamespace}}::{{group.Name}}

            """);

        File.WriteAllText(Path.Combine(outputDir, $"{group.Name}.cpp"), sb.ToString());
    }

    public static void WriteMasterHeader(string outputDir, IReadOnlyList<ResourceGroup> groups)
    {
        var sb = new StringBuilder();
        AppendBanner(sb);

        sb.AppendLine("#pragma once");
        sb.AppendLine();
        sb.AppendLine("#include <initializer_list>");
        sb.AppendLine("#include <span>");
        sb.AppendLine("#include <string>");
        sb.AppendLine("#include <string_view>");
        sb.AppendLine();
        foreach (var g in groups)
        {
            sb.AppendLine($"#include \"{g.Name}.h\"");
        }
        sb.Append($$"""

            namespace {{RootNamespace}} {

            // Switches every group to the given locale. Unknown locales fall
            // back to the default locale (en). After updating the group pointers,
            // invokes every registered LocaleObserver so cached UI state (button
            // tooltips, list labels, etc.) can refresh from the new locale.
            void SetLocale(const char* locale) noexcept;

            // Returns the locale code passed to the last successful SetLocale
            // (or the default locale before any explicit call). Never null.
            const char* GetCurrentLocale() noexcept;

            // Substitutes {0}, {1}, ... in `format` with the given arguments and
            // returns the result. Used for translated strings that contain
            // placeholders, e.g. Format(Editor::ErrorIndexAlreadyInUse, {idxStr}).
            std::string Format(const char* format, std::initializer_list<std::string_view> args);

            // Returns the locale codes this build was generated with, default
            // locale ("en") first. The span backs static storage and is valid
            // for the program's lifetime.
            std::span<const char* const> GetAvailableLocales() noexcept;

            // Returns the display name for `locale` in that locale's own
            // language (e.g. "Deutsch" for "de"). Returns `locale` itself for
            // codes the generator does not have a display name for.
            const char* GetLanguageDisplayName(const char* locale) noexcept;

            // Callback invoked from SetLocale after group pointers have been
            // updated. Implementations should re-read any cached I18N strings.
            using LocaleObserver = void (*)(void* context) noexcept;

            // Registers `cb` to be invoked on every subsequent SetLocale. The
            // (cb, ctx) pair identifies the registration: the same callback
            // function may be registered with different contexts. Duplicate
            // (cb, ctx) registrations are ignored. Null callbacks are ignored.
            void RegisterLocaleObserver(LocaleObserver cb, void* ctx) noexcept;

            // Removes a previously registered (cb, ctx) pair. No-op if the pair
            // is not currently registered.
            void UnregisterLocaleObserver(LocaleObserver cb, void* ctx) noexcept;

            }  // namespace {{RootNamespace}}

            """);

        File.WriteAllText(Path.Combine(outputDir, $"{MasterFileName}.h"), sb.ToString());
    }

    public static void WriteMasterSource(string outputDir, IReadOnlyList<ResourceGroup> groups)
    {
        var sb = new StringBuilder();
        AppendBanner(sb);

        sb.Append($$"""
            #include "{{MasterFileName}}.h"

            #include <cstddef>
            #include <cstring>
            #include <vector>

            namespace {{RootNamespace}} {
            namespace {

            """);

        WriteLocaleRegistry(sb, groups);

        sb.Append($$"""

            const char* g_currentLocale = "{{ResxLoader.DefaultLocale}}";

            const char* ResolveLocale(const char* locale) noexcept
            {
                if (locale == nullptr) return "{{ResxLoader.DefaultLocale}}";
                for (const char* known : kLocales)
                {
                    if (std::strcmp(known, locale) == 0) return known;
                }
                return "{{ResxLoader.DefaultLocale}}";
            }

            struct ObserverEntry { LocaleObserver cb; void* ctx; };

            // Function-local static keeps construction order well-defined for
            // observers registered during global init (e.g. statically allocated
            // UI). Heap usage is bounded by live observer count; locale switches
            // are user-driven and not on any hot path.
            std::vector<ObserverEntry>& Observers() noexcept
            {
                static std::vector<ObserverEntry> v;
                return v;
            }

            }  // namespace

            void SetLocale(const char* locale) noexcept
            {
                g_currentLocale = ResolveLocale(locale);

            """);

        foreach (var g in groups)
        {
            sb.AppendLine($"    {g.Name}::ApplyLocale(g_currentLocale);");
        }

        sb.Append($$"""

                // Snapshot the registry so observers that unregister themselves
                // (e.g. via a destructor triggered as a side effect of the
                // callback) don't shift indices mid-iteration.
                const std::vector<ObserverEntry> snapshot = Observers();
                for (const auto& entry : snapshot)
                {
                    if (entry.cb != nullptr) entry.cb(entry.ctx);
                }
            }

            void RegisterLocaleObserver(LocaleObserver cb, void* ctx) noexcept
            {
                if (cb == nullptr) return;
                auto& list = Observers();
                for (const auto& entry : list)
                {
                    if (entry.cb == cb && entry.ctx == ctx) return;
                }
                list.push_back({cb, ctx});
            }

            void UnregisterLocaleObserver(LocaleObserver cb, void* ctx) noexcept
            {
                auto& list = Observers();
                for (auto it = list.begin(); it != list.end(); ++it)
                {
                    if (it->cb == cb && it->ctx == ctx)
                    {
                        *it = list.back();
                        list.pop_back();
                        return;
                    }
                }
            }

            const char* GetCurrentLocale() noexcept
            {
                return g_currentLocale;
            }

            std::span<const char* const> GetAvailableLocales() noexcept
            {
                return {kLocales, sizeof(kLocales) / sizeof(kLocales[0])};
            }

            const char* GetLanguageDisplayName(const char* locale) noexcept
            {
                if (locale == nullptr) return "";
                for (const auto& entry : kLanguageDisplayNames)
                {
                    if (std::strcmp(entry.code, locale) == 0) return entry.name;
                }
                return locale;
            }

            std::string Format(const char* format, std::initializer_list<std::string_view> args)
            {
                if (format == nullptr) return {};

                // Pre-compute the final size to do exactly one allocation for the
                // common case where every placeholder is found at most once. We
                // walk the format string twice; the placeholder scan is cheap
                // compared to the heap traffic of std::string growth.
                std::string result;
                result.reserve(std::char_traits<char>::length(format));

                for (const char* p = format; *p != '\0'; )
                {
                    if (*p == '{')
                    {
                        // Parse {N} where N is a non-negative integer index.
                        const char* digits = p + 1;
                        std::size_t index = 0;
                        bool hasDigit = false;
                        while (*digits >= '0' && *digits <= '9')
                        {
                            index = index * 10 + static_cast<std::size_t>(*digits - '0');
                            ++digits;
                            hasDigit = true;
                        }
                        if (hasDigit && *digits == '}')
                        {
                            if (index < args.size())
                            {
                                const auto& arg = *(args.begin() + index);
                                result.append(arg.data(), arg.size());
                            }
                            // Unknown index: silently drop the placeholder.
                            p = digits + 1;
                            continue;
                        }
                    }
                    result.push_back(*p++);
                }

                return result;
            }

            }  // namespace {{RootNamespace}}

            """);

        File.WriteAllText(Path.Combine(outputDir, $"{MasterFileName}.cpp"), sb.ToString());
    }

    private static void WriteLocaleRegistry(StringBuilder sb, IReadOnlyList<ResourceGroup> groups)
    {
        // Union of locales across all groups, default locale first, rest sorted.
        var locales = groups.SelectMany(g => g.Locales)
                            .Distinct(StringComparer.Ordinal)
                            .OrderBy(l => l == ResxLoader.DefaultLocale ? "" : l, StringComparer.Ordinal)
                            .ToList();

        sb.AppendLine("constexpr const char* kLocales[] = {");
        foreach (var locale in locales)
        {
            sb.AppendLine($"    {Naming.EscapeCppString(locale)},");
        }
        sb.AppendLine("};");
        sb.AppendLine();

        sb.AppendLine("struct LanguageDisplayEntry { const char* code; const char* name; };");
        sb.AppendLine("constexpr LanguageDisplayEntry kLanguageDisplayNames[] = {");
        foreach (var locale in locales)
        {
            if (KnownLanguageDisplayNames.TryGetValue(locale, out var displayName))
            {
                sb.AppendLine($"    {{ {Naming.EscapeCppString(locale)}, {Naming.EscapeCppString(displayName)} }},");
            }
        }
        sb.AppendLine("};");
    }

    private static void WriteLocaleTables(StringBuilder sb, ResourceGroup group)
    {
        var charType = group.IsWide ? "wchar_t" : "char";
        foreach (var locale in group.Locales)
        {
            var sanitized = Naming.SanitizeLocale(locale);
            foreach (var entry in group.Entries)
            {
                var value = ResolveValueWithFallback(entry, locale);
                if (group.IsWide)
                {
                    // Rewrite %s/%S -> %ls so swprintf reads the wchar_t* arg
                    // correctly on Windows; mirrors the legacy bmd loader.
                    value = Naming.NormalizePrintfSpecifiersForWide(value);
                }
                sb.AppendLine($"constexpr const {charType}* k_{sanitized}_{entry.Identifier} = {Naming.EscapeCppString(value, group.IsWide)};");
            }
            sb.AppendLine();
        }
    }

    private static void WriteRuntimePointers(StringBuilder sb, ResourceGroup group)
    {
        var charType = group.IsWide ? "wchar_t" : "char";
        var defaultSanitized = Naming.SanitizeLocale(ResxLoader.DefaultLocale);
        foreach (var entry in group.Entries)
        {
            sb.AppendLine($"const {charType}* {entry.Identifier} = k_{defaultSanitized}_{entry.Identifier};");
        }
    }

    private static void WriteApplyLocale(StringBuilder sb, ResourceGroup group)
    {
        var defaultSanitized = Naming.SanitizeLocale(ResxLoader.DefaultLocale);

        sb.AppendLine("void ApplyLocale(const char* locale) noexcept");
        sb.AppendLine("{");

        // Non-default locales first: pattern is one branch per locale, each
        // assigns all pointers and returns. Fallback at the bottom handles
        // both nullptr and unknown locales.
        foreach (var locale in group.Locales.Where(l => l != ResxLoader.DefaultLocale))
        {
            var sanitized = Naming.SanitizeLocale(locale);
            sb.AppendLine($"    if (locale != nullptr && std::strcmp(locale, \"{locale}\") == 0)");
            sb.AppendLine("    {");
            foreach (var entry in group.Entries)
            {
                sb.AppendLine($"        {entry.Identifier} = k_{sanitized}_{entry.Identifier};");
            }
            sb.AppendLine("        return;");
            sb.AppendLine("    }");
        }

        foreach (var entry in group.Entries)
        {
            sb.AppendLine($"    {entry.Identifier} = k_{defaultSanitized}_{entry.Identifier};");
        }

        sb.AppendLine("}");
    }

    private static string ResolveValueWithFallback(ResourceEntry entry, string locale)
    {
        if (entry.Translations.TryGetValue(locale, out var value))
        {
            return value;
        }
        // Fall back to the English key, since the key IS the English text.
        return entry.Translations.TryGetValue(ResxLoader.DefaultLocale, out var defaultValue)
            ? defaultValue
            : entry.Key;
    }

    private static bool HasLegacyIds(ResourceGroup group)
    {
        return group.Entries.Any(e => e.LegacyIds.Count > 0);
    }

    private static void WriteLegacyLookup(StringBuilder sb, ResourceGroup group)
    {
        var charType = group.IsWide ? "wchar_t" : "char";

        // Flatten (legacyId, identifier) pairs and sort by id for binary search.
        var rows = group.Entries
                        .SelectMany(e => e.LegacyIds.Select(id => (id, ident: e.Identifier)))
                        .OrderBy(r => r.id)
                        .ToList();

        sb.AppendLine("namespace {");
        sb.AppendLine($"struct LegacyEntry {{ int id; const {charType}* const* slot; }};");
        sb.AppendLine("constexpr LegacyEntry kLegacyTable[] = {");
        foreach (var (id, ident) in rows)
        {
            sb.AppendLine($"    {{ {id}, &{ident} }},");
        }
        sb.AppendLine("};");
        sb.AppendLine($"constexpr {(group.IsWide ? "wchar_t" : "char")} kLegacyFallback[] = {(group.IsWide ? "L\"\"" : "\"\"")};");
        sb.AppendLine("}  // namespace");
        sb.AppendLine();
        sb.AppendLine($"const {charType}* Lookup(int legacyId) noexcept");
        sb.AppendLine("{");
        sb.AppendLine("    // Binary search the sorted table.");
        sb.AppendLine("    int lo = 0;");
        sb.AppendLine("    int hi = static_cast<int>(sizeof(kLegacyTable) / sizeof(kLegacyTable[0]));");
        sb.AppendLine("    while (lo < hi)");
        sb.AppendLine("    {");
        sb.AppendLine("        const int mid = lo + (hi - lo) / 2;");
        sb.AppendLine("        if (kLegacyTable[mid].id < legacyId) lo = mid + 1;");
        sb.AppendLine("        else hi = mid;");
        sb.AppendLine("    }");
        sb.AppendLine("    if (lo < static_cast<int>(sizeof(kLegacyTable) / sizeof(kLegacyTable[0]))");
        sb.AppendLine("        && kLegacyTable[lo].id == legacyId)");
        sb.AppendLine("    {");
        sb.AppendLine("        return *kLegacyTable[lo].slot;");
        sb.AppendLine("    }");
        sb.AppendLine("    return kLegacyFallback;");
        sb.AppendLine("}");
    }

    private static void AppendBanner(StringBuilder sb)
    {
        sb.AppendLine(GeneratedBanner);
        sb.AppendLine();
    }

    /// Sanitize a key for use in a // comment — strip newlines so the
    /// comment stays on one line.
    private static string EscapeComment(string key)
    {
        return key.Replace('\n', ' ').Replace('\r', ' ');
    }
}
