# -*- coding: utf-8 -*-
"""Vietnamese glossary for the cash shop script files.

Terminology follows src/Localization/Items.vi.resx (Kiem Ngan / Nguc Phuc Lanh style):
descriptive words are translated, proper nouns (Kalima, Varka, Fenrir, W Coin...) stay.
"""

# Core item / package names, longest match wins.
CORE = {
    # --- jewels -------------------------------------------------------
    "Jewel of Bless": "Ngọc Phúc Lành",
    "Jewel of Soul": "Ngọc Linh Hồn",
    "Jewel of Chaos": "Ngọc Hỗn Nguyên",
    "Jewel of Life": "Ngọc Sinh Mệnh",
    "Jewel of Creation": "Ngọc Sáng Tạo",
    "Jewel of Harmony": "Ngọc Hoà Hợp",
    "Jewel of Guardian": "Ngọc Hộ Mệnh",
    "Jewel of Extension": "Ngọc Mở Rộng",
    # --- buff scrolls -------------------------------------------------
    "Scroll of Health": "Cuộn Sinh Lực",
    "Scroll of Mana": "Cuộn Mana",
    "Scroll of Protection": "Cuộn Bảo Vệ",
    "Scroll of Quickness": "Cuộn Nhanh Nhẹn",
    "Scroll of Wizardry": "Cuộn Pháp Thuật",
    "Scroll of Wrath": "Cuộn Phẫn Nộ",
    "Scroll of Battle": "Cuộn Chiến Đấu",
    "Scroll of Strengthener": "Cuộn Tăng Lực",
    # --- skill scrolls / parchments / orbs ----------------------------
    "Scroll of Cometfall": "Cuộn Sao Băng Rơi",
    "Scroll of Evil Spirit": "Cuộn Linh Hồn Ác",
    "Scroll of Expansion of Wizardry": "Cuộn Mở Rộng Pháp Thuật",
    "Scroll of Flame Strike": "Cuộn Đòn Lửa",
    "Scroll of Gigantic Storm": "Cuộn Bão Khổng Lồ",
    "Scroll of Multi Shot": "Cuộn Bắn Liên Hoàn",
    "Scroll of Nova": "Cuộn Nova",
    "Scroll of Soul Barrior": "Cuộn Lá Chắn Linh Hồn",
    "Berserker Parchment": "Trang Sách Cuồng Nộ",
    "Chain Lightning Parchment": "Trang Sách Sét Xích",
    "Damage Reflection Parchment": "Trang Sách Phản Đòn",
    "Dark Side Parchment": "Trang Sách Bóng Tối",
    "Dragon Slasher Parchment": "Trang Sách Rồng Chém",
    "Increase Block Parchment": "Trang Sách Tăng Đỡ Đòn",
    "Increase Health Parchment": "Trang Sách Tăng Sinh Lực",
    "Lightning Shock Parchment": "Trang Sách Sốc Điện",
    "Orb of Death Stab": "Cầu Phép Đâm Tử Thần",
    "Orb of Ice Arrow": "Cầu Phép Mũi Tên Băng",
    "Orb of Penetration": "Cầu Phép Xuyên Phá",
    "Orb of Rageful Blow": "Cầu Phép Đòn Cuồng Nộ",
    "Orb of Recovery": "Cầu Phép Hồi Phục",
    "Orb of Strike of Destruction": "Cầu Phép Đòn Huỷ Diệt",
    "Orb of Swell Life": "Cầu Phép Tăng Sinh Lực",
    # --- potions ------------------------------------------------------
    "Elite Healing Potion": "Bình Máu Tinh Anh",
    "Elite Mana Potion": "Bình Mana Tinh Anh",
    "Elite SD Potion": "Bình SD Tinh Anh",
    "Medium Elite Healing Potion": "Bình Máu Tinh Anh Vừa",
    "AG Boost Aura": "Hào Quang Tăng AG",
    "SD Boost Aura": "Hào Quang Tăng SD",
    # --- seals --------------------------------------------------------
    "Master Seal of Ascension": "Ấn Thăng Hoa Master",
    "Master Seal of Wealth": "Ấn Phú Quý Master",
    "Master Seal of Weath": "Ấn Phú Quý Master",
    "Seal of Ascension": "Ấn Thăng Hoa",
    "Seal of Divinity": "Ấn Thần Thánh",
    "Seal of Healing": "Ấn Hồi Phục",
    "Seal of Sustenance": "Ấn Duy Trì",
    "Seal of Wealth": "Ấn Phú Quý",
    # --- talismans ----------------------------------------------------
    "Talisman of Chaos Assembly": "Bùa Hỗn Nguyên",
    "Talisman of Guardian": "Bùa Hộ Mệnh",
    "Talisman of Item Protection": "Bùa Bảo Vệ Vật Phẩm",
    "Talisman of Luck": "Bùa May Mắn",
    "Talisman of Mobility": "Bùa Di Chuyển",
    "Talisman of Resurrection": "Bùa Hồi Sinh",
    # --- rings & necklaces -------------------------------------------
    "Amethyst Ring": "Nhẫn Thạch Anh Tím",
    "Critical Ring of Wizard": "Nhẫn Chí Mạng Pháp Sư",
    "Emerald Necklace": "Dây Chuyền Lục Ngọc",
    "Panda Ring": "Nhẫn Gấu Trúc",
    "Ruby Necklace": "Dây Chuyền Hồng Ngọc",
    "Ruby Ring": "Nhẫn Hồng Ngọc",
    "Sapphire Necklace": "Dây Chuyền Lam Ngọc",
    "Sapphire Ring": "Nhẫn Lam Ngọc",
    "Skeleton Transformation Ring": "Nhẫn Biến Hình Xương",
    "Snowman Transformation Ring": "Nhẫn Biến Hình Người Tuyết",
    "Topaz Ring": "Nhẫn Hoàng Ngọc",
    "Wizard Ring": "Nhẫn Pháp Sư",
    # --- pets & mounts -----------------------------------------------
    "Pet Demon": "Thú Cưng Ác Quỷ",
    "Pet Panda": "Thú Cưng Gấu Trúc",
    "Pet Rudolph": "Thú Cưng Rudolf",
    "Pet Skeleton": "Thú Cưng Xương",
    "Pet Unicorn": "Thú Cưng Kỳ Lân",
    "Demon": "Ác Quỷ",
    "Spirit of Guardian": "Linh Hồn Vệ Thần",
    "Horn of Fenrir": "Sừng Fenrir",
    "Horn of Hell Miney": "Sừng Hell Maine",
    "Feather of Condor": "Lông Vũ Kền Kền",
    "Condor Feather": "Lông Vũ Kền Kền",
    "Feather of Loch": "Lông Vũ Loch",
    "Feather of Phoenix of Darkness": "Lông Vũ Phượng Hoàng Bóng Tối",
    "Flame of Condor": "Ngọn Lửa Kền Kền",
    "Flame of Death Beam Knight": "Ngọn Lửa Death Beam Knight",
    # --- tickets & keys ----------------------------------------------
    "Blood Castle Ticket": "Vé Blood Castle",
    "Devil Square Ticket": "Vé Devil Square",
    "Illusion Temple Ticket": "Vé Illusion Temple",
    "Kalima Ticket": "Vé Kalima",
    "Gold Channel Ticket": "Vé Kênh Vàng",
    "Gold Channel": "Kênh Vàng",
    "TEST GOLD CHANNEL": "KÊNH VÀNG THỬ NGHIỆM",
    "Invitation Ticket to Santa Village": "Vé Mời Làng Ông Già Noel",
    "Open Access Ticket to Doppelganger": "Vé Vào Doppelganger",
    "Open Access Ticket to Varka": "Vé Vào Varka",
    "Silver Key": "Chìa Khoá Bạc",
    "Gold Key": "Chìa Khoá Vàng",
    # --- boxes --------------------------------------------------------
    "Box of Kundun": "Hộp Kundun",
    "GM Gift Box": "Hộp Quà GM",
    "Blue Chocolate Box": "Hộp Sô Cô La Xanh",
    "Pink Chocolate Box": "Hộp Sô Cô La Hồng",
    "Red Chocolate Box": "Hộp Sô Cô La Đỏ",
    "Cherry Blossom Petal": "Cánh Hoa Anh Đào",
    "Cherry Blossom Rice Cake": "Bánh Gạo Hoa Anh Đào",
    "Cherry Blossom Wine": "Rượu Hoa Anh Đào",
    "Red Ribbon Box": "Hộp Ruy Băng Đỏ",
    "Green Ribbon Box": "Hộp Ruy Băng Xanh Lá",
    "Blue Ribbon Box": "Hộp Ruy Băng Xanh Dương",
    # --- charms / statues --------------------------------------------
    "Golden Oak Charm": "Bùa Sồi Vàng",
    "Oak Charm": "Bùa Sồi",
    "Statue of Hawk": "Tượng Chim Ưng",
    "Statue of Goral": "Tượng Sơn Dương",
    "Worn Horseshoe": "Móng Ngựa Cũ",
    # --- wings & capes ------------------------------------------------
    "Wing of Dimension": "Cánh Không Gian",
    "Wing of Eternal": "Cánh Vĩnh Cửu",
    "Wing of Illusion": "Cánh Ảo Ảnh",
    "Wing of Ruin": "Cánh Diệt Vong",
    "Wing of Storm": "Cánh Bão Tố",
    "Wings of Darkness": "Cánh Bóng Tối",
    "Wings of Despair": "Cánh Tuyệt Vọng",
    "Wings of Dragon": "Cánh Rồng",
    "Wings of Soul": "Cánh Linh Hồn",
    "Wings of Spirits": "Cánh Tinh Linh",
    "Cape of Emperor": "Áo Choàng Hoàng Đế",
    "Cape of Fighter": "Áo Choàng Chiến Binh",
    "Cape of Lord": "Áo Choàng Lãnh Chúa",
    "Cape of Overrule": "Áo Choàng Thống Trị",
    "Small Wings of Disaster": "Cánh Thảm Hoạ Nhỏ",
    "Small Wings of Fairy": "Cánh Tiên Nhỏ",
    "Small Wings of Heaven": "Cánh Thiên Đường Nhỏ",
    "Small Wings of Satan": "Cánh Satan Nhỏ",
    "Rage Fighters Small Wing": "Cánh Nhỏ Rage Fighter",
    "Little Warrior's Cloak": "Áo Choàng Chiến Binh Nhí",
    "Sign of Lord": "Dấu Ấn Lãnh Chúa",
    # --- seeds & spheres ----------------------------------------------
    "Seed (Earth)": "Hạt Giống Đất",
    "Seed (Fire)": "Hạt Giống Lửa",
    "Seed (Ice)": "Hạt Giống Băng",
    "Seed (Ice Mana)": "Hạt Giống Băng (Mana)",
    "Seed (Ice Skill)": "Hạt Giống Băng (Kỹ Năng)",
    "Seed (Lightning)": "Hạt Giống Sét",
    "Seed (Water)": "Hạt Giống Nước",
    "Seed (Water BR)": "Hạt Giống Nước (BR)",
    "Seed (Water DR)": "Hạt Giống Nước (DR)",
    "Seed (Wind)": "Hạt Giống Gió",
    "Seed of Lightning": "Hạt Giống Sét",
    "LV3 Ice Seed Sphere": "Hạt Cầu Băng Cấp 3",
    "LV3 Lightning Seed Sphere": "Hạt Cầu Sét Cấp 3",
    "LV3 Water Seed Sphere": "Hạt Cầu Nước Cấp 3",
    # --- reset fruits / stat leaps -------------------------------------
    "Reset Fruit Control": "Trái Reset Điều Khiển",
    "Reset Fruit Energy": "Trái Reset Năng Lượng",
    "Reset Fruit Health": "Trái Reset Sinh Lực",
    "Reset Fruit Quickness": "Trái Reset Nhanh Nhẹn",
    "Reset Fruit Strength": "Trái Reset Sức Mạnh",
    "Leap of Control": "Bùa Tăng Điều Khiển",
    "Leap of Energy": "Bùa Tăng Năng Lượng",
    "Leap of Health": "Bùa Tăng Sinh Lực",
    "Leap of Quickness": "Bùa Tăng Nhanh Nhẹn",
    "Leap of Strength": "Bùa Tăng Sức Mạnh",
    # --- cards & services ---------------------------------------------
    "Chaos Card Gold": "Thẻ Hỗn Nguyên Vàng",
    "Chaos Card GOLD": "Thẻ Hỗn Nguyên Vàng",
    "Chaos Card Mini": "Thẻ Hỗn Nguyên Mini",
    "Chaos Card Rare": "Thẻ Hỗn Nguyên Hiếm",
    "Rage Fighter Character Card": "Thẻ Nhân Vật Rage Fighter",
    "Summoner Character Card": "Thẻ Nhân Vật Summoner",
    "Character Name Change": "Đổi Tên Nhân Vật",
    "Character Transfer": "Chuyển Nhân Vật",
    "Charater Transfer": "Chuyển Nhân Vật",
    "Charater transfer": "Chuyển Nhân Vật",
    "Server Transfer": "Chuyển Máy Chủ",
    "Master Skill Initialization": "Xoá Cây Kỹ Năng Master",
    "Premium Service": "Dịch Vụ Premium",
    "Party EXP Increase": "Tăng EXP Tổ Đội",
    "Vault Expansion Certificate": "Giấy Mở Rộng Rương Đồ",
    "Magic Backpack": "Túi Phép Thuật",
    "Gladiator Package": "Gói Đấu Sĩ",
    "Scroll Package A": "Gói Cuộn A",
    "Scroll Package B": "Gói Cuộn B",
    "Scroll Package C": "Gói Cuộn C",
    "Scroll Package D": "Gói Cuộn D",
    "Gold Channel Package": "Gói Kênh Vàng",
    "Level up (Master)": "Lên Cấp (Master)",
    "Level up (normal)": "Lên Cấp (Thường)",
    "Goblin Point": "Điểm Goblin",
    "Goblin Points": "Điểm Goblin",
}

# Equipment set names used by the "Event Reward - ..." rows and by the
# Items.vi.resx lookup fallback.
SLOT = {
    "Helm": "Mũ",
    "helm": "Mũ",
    "Mask": "Mặt Nạ",
    "Armor": "Áo Giáp",
    "Pants": "Quần Giáp",
    "Gloves": "Găng Tay",
    "Boots": "Giày",
}

SET = {
    "Black Soul": "Linh Hồn Đen",
    "Dark Master": "Bá Chủ Bóng Tối",
    "Dragon": "Rồng",
    "Great Dragon": "Rồng Vĩ Đại",
    "Guardian": "Vệ Thần",
    "Legendary": "Huyền Thoại",
    "Piercing Groove": "Xuyên Phá",
    "Red Spirit": "Linh Hồn Đỏ",
    "Redwing": "Cánh Đỏ",
    "Sacred Fire": "Lửa Thiêng",
    "Storm Blitz": "Bão Tố Chớp Nhoáng",
    "Thunder Hawk": "Ưng Sấm Sét",
    "Plate": "Thép Tấm",
}

CLASSES = {
    "Dark Knight": "Dark Knight",
    "Dark Wizard": "Dark Wizard",
    "Fairy Elf": "Fairy Elf",
    "Magic Gladiator": "Magic Gladiator",
    "Rage Fighter": "Rage Fighter",
    "Summoner": "Summoner",
}

# Category tab names.
CATEGORIES = {
    "W Coin (C)": "W Coin (C)",
    "W Coin (P)": "W Coin (P)",
    "Goblin Point": "Điểm Goblin",
    "Special": "Đặc Biệt",
    "Accessory": "Trang Sức",
    "Buff": "Tăng Lực",
    "Pet": "Thú Cưng",
    "Equipment": "Trang Bị",
    "Ticket": "Vé",
    "Potion": "Bình Thuốc",
    "Box": "Hộp",
}

# Product unit labels (field 5 of IBSProduct.txt).
UNITS = {
    "EA": "Cái",
    "Day(s)": "Ngày",
    "Sec.": "Giây",
    "%": "%",
    "&nbsp;": "&nbsp;",
    "WReward": "WReward",
}

# Price unit / cash names (fields 15 and 16 of IBSPackage.txt) stay as the
# currency brand, except the goblin point label.
PRICE_UNITS = {
    "W Coin(C)": "W Coin(C)",
    "W Coin(P)": "W Coin(P)",
    "Goblin Point": "Điểm Goblin",
    "Point": "Điểm",
}
