// <copyright file="PacketFunctions.cpp" company="MUnique">
// Licensed under the MIT License. See LICENSE file in the project root for full license information.
// </copyright>

//------------------------------------------------------------------------------
// <auto-generated>
//     This source code was auto-generated by an XSL transformation.
//     Do not change this file. Instead, change the XML data which contains
//     the packet definitions and re-run the transformation (publish/rebuild the
//     managed library project).
// </auto-generated>
//------------------------------------------------------------------------------

#include "stdafx.h"
#include "PacketFunctions_ChatServer.h"
#include "PacketBindings_ChatServer.h"


void PacketFunctions_ChatServer::SendAuthenticate(uint16_t roomId, const wchar_t* token)
{
    dotnet_SendAuthenticate(this->GetHandle(), roomId, token);
}

void PacketFunctions_ChatServer::SendChatRoomClientJoined(BYTE clientIndex, const wchar_t* name)
{
    dotnet_SendChatRoomClientJoined(this->GetHandle(), clientIndex, name);
}

void PacketFunctions_ChatServer::SendChatRoomClientLeft(BYTE clientIndex, const wchar_t* name)
{
    dotnet_SendChatRoomClientLeft(this->GetHandle(), clientIndex, name);
}

void PacketFunctions_ChatServer::SendChatMessage(BYTE senderIndex, BYTE messageLength, const wchar_t* message)
{
    dotnet_SendChatMessage(this->GetHandle(), senderIndex, messageLength, message);
}

void PacketFunctions_ChatServer::SendKeepAlive()
{
    dotnet_SendKeepAlive(this->GetHandle());
}
