// <copyright file="PacketFunctions.cpp" company="MUnique">
// Licensed under the MIT License. See LICENSE file in the project root for full license information.
// </copyright>

//------------------------------------------------------------------------------
// <auto-generated>
//     This source code was auto-generated by an XSL transformation.
//     Do not change this file. Instead, change the XML data which contains
//     the packet definitions and re-run the transformation (publish/rebuild the
//     managed library project).
// </auto-generated>
//------------------------------------------------------------------------------

#include "stdafx.h"
#include "PacketFunctions_ChatServer.h"
#include "PacketBindings_ChatServer.h"


void PacketFunctions_ChatServer::SendAuthenticate(uint16_t roomId, const wchar_t* token, uint32_t tokenByteLength)
{
    dotnet_SendAuthenticate(this->_handle, roomId, token, tokenByteLength);
}

void PacketFunctions_ChatServer::SendChatRoomClientJoined(BYTE clientIndex, const wchar_t* name, uint32_t nameByteLength)
{
    dotnet_SendChatRoomClientJoined(this->_handle, clientIndex, name, nameByteLength);
}

void PacketFunctions_ChatServer::SendChatRoomClientLeft(BYTE clientIndex, const wchar_t* name, uint32_t nameByteLength)
{
    dotnet_SendChatRoomClientLeft(this->_handle, clientIndex, name, nameByteLength);
}

void PacketFunctions_ChatServer::SendChatMessage(BYTE senderIndex, BYTE messageLength, const wchar_t* message, uint32_t messageByteLength)
{
    dotnet_SendChatMessage(this->_handle, senderIndex, messageLength, message, messageByteLength);
}

void PacketFunctions_ChatServer::SendKeepAlive()
{
    dotnet_SendKeepAlive(this->_handle);
}
