// <copyright file="PacketBindings.h" company="MUnique">
// Licensed under the MIT License. See LICENSE file in the project root for full license information.
// </copyright>

//------------------------------------------------------------------------------
// <auto-generated>
//     This source code was auto-generated by an XSL transformation.
//     Do not change this file. Instead, change the XML data which contains
//     the packet definitions and re-run the transformation (publish/rebuild the
//     managed library project).
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once

#include "stdafx.h"
#include "DotNetRuntime.h"
#include "Connection.h"
#include <coreclr_delegates.h>


typedef void(CORECLR_DELEGATE_CALLTYPE* SendPing)(int32_t, uint32_t , uint16_t );
inline SendPing dotnet_SendPing = reinterpret_cast<SendPing>(g_dotnet->get_method(type_name_connection_manager, L"SendPing"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendChecksumResponse)(int32_t, uint32_t );
inline SendChecksumResponse dotnet_SendChecksumResponse = reinterpret_cast<SendChecksumResponse>(g_dotnet->get_method(type_name_connection_manager, L"SendChecksumResponse"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendPublicChatMessage)(int32_t, const wchar_t* , uint32_t, const wchar_t* , uint32_t);
inline SendPublicChatMessage dotnet_SendPublicChatMessage = reinterpret_cast<SendPublicChatMessage>(g_dotnet->get_method(type_name_connection_manager, L"SendPublicChatMessage"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendWhisperMessage)(int32_t, const wchar_t* , uint32_t, const wchar_t* , uint32_t);
inline SendWhisperMessage dotnet_SendWhisperMessage = reinterpret_cast<SendWhisperMessage>(g_dotnet->get_method(type_name_connection_manager, L"SendWhisperMessage"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendLoginLongPassword)(int32_t, const BYTE* , uint32_t, const BYTE* , uint32_t, uint32_t , const BYTE* , uint32_t, const BYTE* , uint32_t);
inline SendLoginLongPassword dotnet_SendLoginLongPassword = reinterpret_cast<SendLoginLongPassword>(g_dotnet->get_method(type_name_connection_manager, L"SendLoginLongPassword"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendLoginShortPassword)(int32_t, const BYTE* , uint32_t, const BYTE* , uint32_t, uint32_t , const BYTE* , uint32_t, const BYTE* , uint32_t);
inline SendLoginShortPassword dotnet_SendLoginShortPassword = reinterpret_cast<SendLoginShortPassword>(g_dotnet->get_method(type_name_connection_manager, L"SendLoginShortPassword"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendLogin075)(int32_t, const BYTE* , uint32_t, const BYTE* , uint32_t, uint32_t , const BYTE* , uint32_t, const BYTE* , uint32_t);
inline SendLogin075 dotnet_SendLogin075 = reinterpret_cast<SendLogin075>(g_dotnet->get_method(type_name_connection_manager, L"SendLogin075"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendLogOut)(int32_t, uint32_t );
inline SendLogOut dotnet_SendLogOut = reinterpret_cast<SendLogOut>(g_dotnet->get_method(type_name_connection_manager, L"SendLogOut"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendLogOutByCheatDetection)(int32_t, BYTE , BYTE );
inline SendLogOutByCheatDetection dotnet_SendLogOutByCheatDetection = reinterpret_cast<SendLogOutByCheatDetection>(g_dotnet->get_method(type_name_connection_manager, L"SendLogOutByCheatDetection"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendResetCharacterPointRequest)(int32_t);
inline SendResetCharacterPointRequest dotnet_SendResetCharacterPointRequest = reinterpret_cast<SendResetCharacterPointRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendResetCharacterPointRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendPlayerShopSetItemPrice)(int32_t, BYTE , uint32_t );
inline SendPlayerShopSetItemPrice dotnet_SendPlayerShopSetItemPrice = reinterpret_cast<SendPlayerShopSetItemPrice>(g_dotnet->get_method(type_name_connection_manager, L"SendPlayerShopSetItemPrice"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendPlayerShopOpen)(int32_t, const wchar_t* , uint32_t);
inline SendPlayerShopOpen dotnet_SendPlayerShopOpen = reinterpret_cast<SendPlayerShopOpen>(g_dotnet->get_method(type_name_connection_manager, L"SendPlayerShopOpen"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendPlayerShopClose)(int32_t);
inline SendPlayerShopClose dotnet_SendPlayerShopClose = reinterpret_cast<SendPlayerShopClose>(g_dotnet->get_method(type_name_connection_manager, L"SendPlayerShopClose"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendPlayerShopItemListRequest)(int32_t, uint16_t , const wchar_t* , uint32_t);
inline SendPlayerShopItemListRequest dotnet_SendPlayerShopItemListRequest = reinterpret_cast<SendPlayerShopItemListRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendPlayerShopItemListRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendPlayerShopItemBuyRequest)(int32_t, uint16_t , const wchar_t* , uint32_t, BYTE );
inline SendPlayerShopItemBuyRequest dotnet_SendPlayerShopItemBuyRequest = reinterpret_cast<SendPlayerShopItemBuyRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendPlayerShopItemBuyRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendPickupItemRequest)(int32_t, uint16_t );
inline SendPickupItemRequest dotnet_SendPickupItemRequest = reinterpret_cast<SendPickupItemRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendPickupItemRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendPickupItemRequest075)(int32_t, uint16_t );
inline SendPickupItemRequest075 dotnet_SendPickupItemRequest075 = reinterpret_cast<SendPickupItemRequest075>(g_dotnet->get_method(type_name_connection_manager, L"SendPickupItemRequest075"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendDropItemRequest)(int32_t, BYTE , BYTE , BYTE );
inline SendDropItemRequest dotnet_SendDropItemRequest = reinterpret_cast<SendDropItemRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendDropItemRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendItemMoveRequest)(int32_t, uint32_t , BYTE , const BYTE* , uint32_t, uint32_t , BYTE );
inline SendItemMoveRequest dotnet_SendItemMoveRequest = reinterpret_cast<SendItemMoveRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendItemMoveRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendConsumeItemRequest)(int32_t, BYTE , BYTE , uint32_t );
inline SendConsumeItemRequest dotnet_SendConsumeItemRequest = reinterpret_cast<SendConsumeItemRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendConsumeItemRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendConsumeItemRequest075)(int32_t, BYTE , BYTE );
inline SendConsumeItemRequest075 dotnet_SendConsumeItemRequest075 = reinterpret_cast<SendConsumeItemRequest075>(g_dotnet->get_method(type_name_connection_manager, L"SendConsumeItemRequest075"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendTalkToNpcRequest)(int32_t, uint16_t );
inline SendTalkToNpcRequest dotnet_SendTalkToNpcRequest = reinterpret_cast<SendTalkToNpcRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendTalkToNpcRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCloseNpcRequest)(int32_t);
inline SendCloseNpcRequest dotnet_SendCloseNpcRequest = reinterpret_cast<SendCloseNpcRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendCloseNpcRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendBuyItemFromNpcRequest)(int32_t, BYTE );
inline SendBuyItemFromNpcRequest dotnet_SendBuyItemFromNpcRequest = reinterpret_cast<SendBuyItemFromNpcRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendBuyItemFromNpcRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendSellItemToNpcRequest)(int32_t, BYTE );
inline SendSellItemToNpcRequest dotnet_SendSellItemToNpcRequest = reinterpret_cast<SendSellItemToNpcRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendSellItemToNpcRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendRepairItemRequest)(int32_t, BYTE , BYTE );
inline SendRepairItemRequest dotnet_SendRepairItemRequest = reinterpret_cast<SendRepairItemRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendRepairItemRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendWarpCommandRequest)(int32_t, uint32_t , uint16_t );
inline SendWarpCommandRequest dotnet_SendWarpCommandRequest = reinterpret_cast<SendWarpCommandRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendWarpCommandRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendEnterGateRequest)(int32_t, uint16_t , BYTE , BYTE );
inline SendEnterGateRequest dotnet_SendEnterGateRequest = reinterpret_cast<SendEnterGateRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendEnterGateRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendEnterGateRequest075)(int32_t, BYTE , BYTE , BYTE );
inline SendEnterGateRequest075 dotnet_SendEnterGateRequest075 = reinterpret_cast<SendEnterGateRequest075>(g_dotnet->get_method(type_name_connection_manager, L"SendEnterGateRequest075"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendTeleportTarget)(int32_t, uint16_t , BYTE , BYTE );
inline SendTeleportTarget dotnet_SendTeleportTarget = reinterpret_cast<SendTeleportTarget>(g_dotnet->get_method(type_name_connection_manager, L"SendTeleportTarget"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendServerChangeAuthentication)(int32_t, const BYTE* , uint32_t, const BYTE* , uint32_t, uint32_t , uint32_t , uint32_t , uint32_t , uint32_t , const BYTE* , uint32_t, const BYTE* , uint32_t);
inline SendServerChangeAuthentication dotnet_SendServerChangeAuthentication = reinterpret_cast<SendServerChangeAuthentication>(g_dotnet->get_method(type_name_connection_manager, L"SendServerChangeAuthentication"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCastleSiegeStatusRequest)(int32_t);
inline SendCastleSiegeStatusRequest dotnet_SendCastleSiegeStatusRequest = reinterpret_cast<SendCastleSiegeStatusRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendCastleSiegeStatusRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCastleSiegeRegistrationRequest)(int32_t);
inline SendCastleSiegeRegistrationRequest dotnet_SendCastleSiegeRegistrationRequest = reinterpret_cast<SendCastleSiegeRegistrationRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendCastleSiegeRegistrationRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCastleSiegeUnregisterRequest)(int32_t);
inline SendCastleSiegeUnregisterRequest dotnet_SendCastleSiegeUnregisterRequest = reinterpret_cast<SendCastleSiegeUnregisterRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendCastleSiegeUnregisterRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCastleSiegeRegistrationStateRequest)(int32_t);
inline SendCastleSiegeRegistrationStateRequest dotnet_SendCastleSiegeRegistrationStateRequest = reinterpret_cast<SendCastleSiegeRegistrationStateRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendCastleSiegeRegistrationStateRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCastleSiegeMarkRegistration)(int32_t, BYTE );
inline SendCastleSiegeMarkRegistration dotnet_SendCastleSiegeMarkRegistration = reinterpret_cast<SendCastleSiegeMarkRegistration>(g_dotnet->get_method(type_name_connection_manager, L"SendCastleSiegeMarkRegistration"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCastleSiegeDefenseBuyRequest)(int32_t, uint32_t , uint32_t );
inline SendCastleSiegeDefenseBuyRequest dotnet_SendCastleSiegeDefenseBuyRequest = reinterpret_cast<SendCastleSiegeDefenseBuyRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendCastleSiegeDefenseBuyRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCastleSiegeDefenseRepairRequest)(int32_t, uint32_t , uint32_t );
inline SendCastleSiegeDefenseRepairRequest dotnet_SendCastleSiegeDefenseRepairRequest = reinterpret_cast<SendCastleSiegeDefenseRepairRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendCastleSiegeDefenseRepairRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCastleSiegeDefenseUpgradeRequest)(int32_t, uint32_t , uint32_t , uint32_t , uint32_t );
inline SendCastleSiegeDefenseUpgradeRequest dotnet_SendCastleSiegeDefenseUpgradeRequest = reinterpret_cast<SendCastleSiegeDefenseUpgradeRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendCastleSiegeDefenseUpgradeRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCastleSiegeTaxInfoRequest)(int32_t);
inline SendCastleSiegeTaxInfoRequest dotnet_SendCastleSiegeTaxInfoRequest = reinterpret_cast<SendCastleSiegeTaxInfoRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendCastleSiegeTaxInfoRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCastleSiegeTaxChangeRequest)(int32_t, BYTE , uint32_t );
inline SendCastleSiegeTaxChangeRequest dotnet_SendCastleSiegeTaxChangeRequest = reinterpret_cast<SendCastleSiegeTaxChangeRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendCastleSiegeTaxChangeRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCastleSiegeTaxMoneyWithdraw)(int32_t, uint32_t );
inline SendCastleSiegeTaxMoneyWithdraw dotnet_SendCastleSiegeTaxMoneyWithdraw = reinterpret_cast<SendCastleSiegeTaxMoneyWithdraw>(g_dotnet->get_method(type_name_connection_manager, L"SendCastleSiegeTaxMoneyWithdraw"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendToggleCastleGateRequest)(int32_t, BYTE , uint16_t );
inline SendToggleCastleGateRequest dotnet_SendToggleCastleGateRequest = reinterpret_cast<SendToggleCastleGateRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendToggleCastleGateRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCastleGuildCommand)(int32_t, BYTE , BYTE , BYTE , BYTE );
inline SendCastleGuildCommand dotnet_SendCastleGuildCommand = reinterpret_cast<SendCastleGuildCommand>(g_dotnet->get_method(type_name_connection_manager, L"SendCastleGuildCommand"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCastleSiegeHuntingZoneEntranceSetting)(int32_t, BYTE );
inline SendCastleSiegeHuntingZoneEntranceSetting dotnet_SendCastleSiegeHuntingZoneEntranceSetting = reinterpret_cast<SendCastleSiegeHuntingZoneEntranceSetting>(g_dotnet->get_method(type_name_connection_manager, L"SendCastleSiegeHuntingZoneEntranceSetting"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCastleSiegeGateListRequest)(int32_t);
inline SendCastleSiegeGateListRequest dotnet_SendCastleSiegeGateListRequest = reinterpret_cast<SendCastleSiegeGateListRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendCastleSiegeGateListRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCastleSiegeStatueListRequest)(int32_t);
inline SendCastleSiegeStatueListRequest dotnet_SendCastleSiegeStatueListRequest = reinterpret_cast<SendCastleSiegeStatueListRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendCastleSiegeStatueListRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCastleSiegeRegisteredGuildsListRequest)(int32_t);
inline SendCastleSiegeRegisteredGuildsListRequest dotnet_SendCastleSiegeRegisteredGuildsListRequest = reinterpret_cast<SendCastleSiegeRegisteredGuildsListRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendCastleSiegeRegisteredGuildsListRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCastleOwnerListRequest)(int32_t);
inline SendCastleOwnerListRequest dotnet_SendCastleOwnerListRequest = reinterpret_cast<SendCastleOwnerListRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendCastleOwnerListRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendFireCatapultRequest)(int32_t, uint16_t , BYTE );
inline SendFireCatapultRequest dotnet_SendFireCatapultRequest = reinterpret_cast<SendFireCatapultRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendFireCatapultRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendWeaponExplosionRequest)(int32_t, uint16_t );
inline SendWeaponExplosionRequest dotnet_SendWeaponExplosionRequest = reinterpret_cast<SendWeaponExplosionRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendWeaponExplosionRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendGuildLogoOfCastleOwnerRequest)(int32_t);
inline SendGuildLogoOfCastleOwnerRequest dotnet_SendGuildLogoOfCastleOwnerRequest = reinterpret_cast<SendGuildLogoOfCastleOwnerRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendGuildLogoOfCastleOwnerRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCastleSiegeHuntingZoneEnterRequest)(int32_t, uint32_t );
inline SendCastleSiegeHuntingZoneEnterRequest dotnet_SendCastleSiegeHuntingZoneEnterRequest = reinterpret_cast<SendCastleSiegeHuntingZoneEnterRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendCastleSiegeHuntingZoneEnterRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCrywolfInfoRequest)(int32_t);
inline SendCrywolfInfoRequest dotnet_SendCrywolfInfoRequest = reinterpret_cast<SendCrywolfInfoRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendCrywolfInfoRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCrywolfContractRequest)(int32_t, uint16_t );
inline SendCrywolfContractRequest dotnet_SendCrywolfContractRequest = reinterpret_cast<SendCrywolfContractRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendCrywolfContractRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCrywolfChaosRateBenefitRequest)(int32_t);
inline SendCrywolfChaosRateBenefitRequest dotnet_SendCrywolfChaosRateBenefitRequest = reinterpret_cast<SendCrywolfChaosRateBenefitRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendCrywolfChaosRateBenefitRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendWhiteAngelItemRequest)(int32_t);
inline SendWhiteAngelItemRequest dotnet_SendWhiteAngelItemRequest = reinterpret_cast<SendWhiteAngelItemRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendWhiteAngelItemRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendEnterOnWerewolfRequest)(int32_t);
inline SendEnterOnWerewolfRequest dotnet_SendEnterOnWerewolfRequest = reinterpret_cast<SendEnterOnWerewolfRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendEnterOnWerewolfRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendEnterOnGatekeeperRequest)(int32_t);
inline SendEnterOnGatekeeperRequest dotnet_SendEnterOnGatekeeperRequest = reinterpret_cast<SendEnterOnGatekeeperRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendEnterOnGatekeeperRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendLeoHelperItemRequest)(int32_t);
inline SendLeoHelperItemRequest dotnet_SendLeoHelperItemRequest = reinterpret_cast<SendLeoHelperItemRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendLeoHelperItemRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendMoveToDeviasBySnowmanRequest)(int32_t);
inline SendMoveToDeviasBySnowmanRequest dotnet_SendMoveToDeviasBySnowmanRequest = reinterpret_cast<SendMoveToDeviasBySnowmanRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendMoveToDeviasBySnowmanRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendSantaClausItemRequest)(int32_t);
inline SendSantaClausItemRequest dotnet_SendSantaClausItemRequest = reinterpret_cast<SendSantaClausItemRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendSantaClausItemRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendKanturuInfoRequest)(int32_t);
inline SendKanturuInfoRequest dotnet_SendKanturuInfoRequest = reinterpret_cast<SendKanturuInfoRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendKanturuInfoRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendKanturuEnterRequest)(int32_t);
inline SendKanturuEnterRequest dotnet_SendKanturuEnterRequest = reinterpret_cast<SendKanturuEnterRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendKanturuEnterRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendRaklionStateInfoRequest)(int32_t);
inline SendRaklionStateInfoRequest dotnet_SendRaklionStateInfoRequest = reinterpret_cast<SendRaklionStateInfoRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendRaklionStateInfoRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCashShopPointInfoRequest)(int32_t);
inline SendCashShopPointInfoRequest dotnet_SendCashShopPointInfoRequest = reinterpret_cast<SendCashShopPointInfoRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendCashShopPointInfoRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCashShopOpenState)(int32_t, BYTE );
inline SendCashShopOpenState dotnet_SendCashShopOpenState = reinterpret_cast<SendCashShopOpenState>(g_dotnet->get_method(type_name_connection_manager, L"SendCashShopOpenState"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCashShopItemBuyRequest)(int32_t, uint32_t , uint32_t , uint32_t , uint16_t , uint32_t , BYTE );
inline SendCashShopItemBuyRequest dotnet_SendCashShopItemBuyRequest = reinterpret_cast<SendCashShopItemBuyRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendCashShopItemBuyRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCashShopItemGiftRequest)(int32_t, uint32_t , uint32_t , uint32_t , uint16_t , uint32_t , BYTE , const wchar_t* , uint32_t, const wchar_t* , uint32_t);
inline SendCashShopItemGiftRequest dotnet_SendCashShopItemGiftRequest = reinterpret_cast<SendCashShopItemGiftRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendCashShopItemGiftRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCashShopStorageListRequest)(int32_t, uint32_t , BYTE );
inline SendCashShopStorageListRequest dotnet_SendCashShopStorageListRequest = reinterpret_cast<SendCashShopStorageListRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendCashShopStorageListRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCashShopDeleteStorageItemRequest)(int32_t, uint32_t , uint32_t , BYTE );
inline SendCashShopDeleteStorageItemRequest dotnet_SendCashShopDeleteStorageItemRequest = reinterpret_cast<SendCashShopDeleteStorageItemRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendCashShopDeleteStorageItemRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCashShopStorageItemConsumeRequest)(int32_t, uint32_t , uint32_t , uint16_t , BYTE );
inline SendCashShopStorageItemConsumeRequest dotnet_SendCashShopStorageItemConsumeRequest = reinterpret_cast<SendCashShopStorageItemConsumeRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendCashShopStorageItemConsumeRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCashShopEventItemListRequest)(int32_t, uint32_t );
inline SendCashShopEventItemListRequest dotnet_SendCashShopEventItemListRequest = reinterpret_cast<SendCashShopEventItemListRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendCashShopEventItemListRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendUnlockVault)(int32_t, uint16_t );
inline SendUnlockVault dotnet_SendUnlockVault = reinterpret_cast<SendUnlockVault>(g_dotnet->get_method(type_name_connection_manager, L"SendUnlockVault"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendSetVaultPin)(int32_t, uint16_t , const wchar_t* , uint32_t);
inline SendSetVaultPin dotnet_SendSetVaultPin = reinterpret_cast<SendSetVaultPin>(g_dotnet->get_method(type_name_connection_manager, L"SendSetVaultPin"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendRemoveVaultPin)(int32_t, const wchar_t* , uint32_t);
inline SendRemoveVaultPin dotnet_SendRemoveVaultPin = reinterpret_cast<SendRemoveVaultPin>(g_dotnet->get_method(type_name_connection_manager, L"SendRemoveVaultPin"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendVaultClosed)(int32_t);
inline SendVaultClosed dotnet_SendVaultClosed = reinterpret_cast<SendVaultClosed>(g_dotnet->get_method(type_name_connection_manager, L"SendVaultClosed"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendVaultMoveMoneyRequest)(int32_t, uint32_t , uint32_t );
inline SendVaultMoveMoneyRequest dotnet_SendVaultMoveMoneyRequest = reinterpret_cast<SendVaultMoveMoneyRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendVaultMoveMoneyRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendLahapJewelMixRequest)(int32_t, uint32_t , uint32_t , uint32_t , BYTE );
inline SendLahapJewelMixRequest dotnet_SendLahapJewelMixRequest = reinterpret_cast<SendLahapJewelMixRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendLahapJewelMixRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendPartyListRequest)(int32_t);
inline SendPartyListRequest dotnet_SendPartyListRequest = reinterpret_cast<SendPartyListRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendPartyListRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendPartyPlayerKickRequest)(int32_t, BYTE );
inline SendPartyPlayerKickRequest dotnet_SendPartyPlayerKickRequest = reinterpret_cast<SendPartyPlayerKickRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendPartyPlayerKickRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendPartyInviteRequest)(int32_t, uint16_t );
inline SendPartyInviteRequest dotnet_SendPartyInviteRequest = reinterpret_cast<SendPartyInviteRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendPartyInviteRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendPartyInviteResponse)(int32_t, BYTE , uint16_t );
inline SendPartyInviteResponse dotnet_SendPartyInviteResponse = reinterpret_cast<SendPartyInviteResponse>(g_dotnet->get_method(type_name_connection_manager, L"SendPartyInviteResponse"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendWalkRequest)(int32_t, BYTE , BYTE , BYTE , BYTE , const BYTE* , uint32_t);
inline SendWalkRequest dotnet_SendWalkRequest = reinterpret_cast<SendWalkRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendWalkRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendWalkRequest075)(int32_t, BYTE , BYTE , BYTE , BYTE , const BYTE* , uint32_t);
inline SendWalkRequest075 dotnet_SendWalkRequest075 = reinterpret_cast<SendWalkRequest075>(g_dotnet->get_method(type_name_connection_manager, L"SendWalkRequest075"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendInstantMoveRequest)(int32_t, BYTE , BYTE );
inline SendInstantMoveRequest dotnet_SendInstantMoveRequest = reinterpret_cast<SendInstantMoveRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendInstantMoveRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendAnimationRequest)(int32_t, BYTE , BYTE );
inline SendAnimationRequest dotnet_SendAnimationRequest = reinterpret_cast<SendAnimationRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendAnimationRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendRequestCharacterList)(int32_t, BYTE );
inline SendRequestCharacterList dotnet_SendRequestCharacterList = reinterpret_cast<SendRequestCharacterList>(g_dotnet->get_method(type_name_connection_manager, L"SendRequestCharacterList"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCreateCharacter)(int32_t, const wchar_t* , uint32_t, uint32_t );
inline SendCreateCharacter dotnet_SendCreateCharacter = reinterpret_cast<SendCreateCharacter>(g_dotnet->get_method(type_name_connection_manager, L"SendCreateCharacter"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendDeleteCharacter)(int32_t, const wchar_t* , uint32_t, const wchar_t* , uint32_t);
inline SendDeleteCharacter dotnet_SendDeleteCharacter = reinterpret_cast<SendDeleteCharacter>(g_dotnet->get_method(type_name_connection_manager, L"SendDeleteCharacter"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendSelectCharacter)(int32_t, const wchar_t* , uint32_t);
inline SendSelectCharacter dotnet_SendSelectCharacter = reinterpret_cast<SendSelectCharacter>(g_dotnet->get_method(type_name_connection_manager, L"SendSelectCharacter"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendFocusCharacter)(int32_t, const wchar_t* , uint32_t);
inline SendFocusCharacter dotnet_SendFocusCharacter = reinterpret_cast<SendFocusCharacter>(g_dotnet->get_method(type_name_connection_manager, L"SendFocusCharacter"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendIncreaseCharacterStatPoint)(int32_t, uint32_t );
inline SendIncreaseCharacterStatPoint dotnet_SendIncreaseCharacterStatPoint = reinterpret_cast<SendIncreaseCharacterStatPoint>(g_dotnet->get_method(type_name_connection_manager, L"SendIncreaseCharacterStatPoint"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendClientReadyAfterMapChange)(int32_t);
inline SendClientReadyAfterMapChange dotnet_SendClientReadyAfterMapChange = reinterpret_cast<SendClientReadyAfterMapChange>(g_dotnet->get_method(type_name_connection_manager, L"SendClientReadyAfterMapChange"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendSaveKeyConfiguration)(int32_t, const BYTE* , uint32_t);
inline SendSaveKeyConfiguration dotnet_SendSaveKeyConfiguration = reinterpret_cast<SendSaveKeyConfiguration>(g_dotnet->get_method(type_name_connection_manager, L"SendSaveKeyConfiguration"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendAddMasterSkillPoint)(int32_t, uint16_t );
inline SendAddMasterSkillPoint dotnet_SendAddMasterSkillPoint = reinterpret_cast<SendAddMasterSkillPoint>(g_dotnet->get_method(type_name_connection_manager, L"SendAddMasterSkillPoint"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendHitRequest)(int32_t, uint16_t , BYTE , BYTE );
inline SendHitRequest dotnet_SendHitRequest = reinterpret_cast<SendHitRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendHitRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendTargetedSkill)(int32_t, uint16_t , uint16_t );
inline SendTargetedSkill dotnet_SendTargetedSkill = reinterpret_cast<SendTargetedSkill>(g_dotnet->get_method(type_name_connection_manager, L"SendTargetedSkill"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendTargetedSkill075)(int32_t, BYTE , uint16_t );
inline SendTargetedSkill075 dotnet_SendTargetedSkill075 = reinterpret_cast<SendTargetedSkill075>(g_dotnet->get_method(type_name_connection_manager, L"SendTargetedSkill075"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendTargetedSkill095)(int32_t, BYTE , uint16_t );
inline SendTargetedSkill095 dotnet_SendTargetedSkill095 = reinterpret_cast<SendTargetedSkill095>(g_dotnet->get_method(type_name_connection_manager, L"SendTargetedSkill095"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendMagicEffectCancelRequest)(int32_t, uint16_t , uint16_t );
inline SendMagicEffectCancelRequest dotnet_SendMagicEffectCancelRequest = reinterpret_cast<SendMagicEffectCancelRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendMagicEffectCancelRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendAreaSkill)(int32_t, uint16_t , BYTE , BYTE , BYTE , uint16_t , BYTE );
inline SendAreaSkill dotnet_SendAreaSkill = reinterpret_cast<SendAreaSkill>(g_dotnet->get_method(type_name_connection_manager, L"SendAreaSkill"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendAreaSkill075)(int32_t, BYTE , BYTE , BYTE , BYTE );
inline SendAreaSkill075 dotnet_SendAreaSkill075 = reinterpret_cast<SendAreaSkill075>(g_dotnet->get_method(type_name_connection_manager, L"SendAreaSkill075"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendAreaSkill095)(int32_t, BYTE , BYTE , BYTE , BYTE );
inline SendAreaSkill095 dotnet_SendAreaSkill095 = reinterpret_cast<SendAreaSkill095>(g_dotnet->get_method(type_name_connection_manager, L"SendAreaSkill095"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendRageAttackRequest)(int32_t, uint16_t , uint16_t );
inline SendRageAttackRequest dotnet_SendRageAttackRequest = reinterpret_cast<SendRageAttackRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendRageAttackRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendRageAttackRangeRequest)(int32_t, uint16_t , uint16_t );
inline SendRageAttackRangeRequest dotnet_SendRageAttackRangeRequest = reinterpret_cast<SendRageAttackRangeRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendRageAttackRangeRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendTradeCancel)(int32_t);
inline SendTradeCancel dotnet_SendTradeCancel = reinterpret_cast<SendTradeCancel>(g_dotnet->get_method(type_name_connection_manager, L"SendTradeCancel"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendTradeButtonStateChange)(int32_t, uint32_t );
inline SendTradeButtonStateChange dotnet_SendTradeButtonStateChange = reinterpret_cast<SendTradeButtonStateChange>(g_dotnet->get_method(type_name_connection_manager, L"SendTradeButtonStateChange"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendTradeRequest)(int32_t, uint16_t );
inline SendTradeRequest dotnet_SendTradeRequest = reinterpret_cast<SendTradeRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendTradeRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendTradeRequestResponse)(int32_t, BYTE );
inline SendTradeRequestResponse dotnet_SendTradeRequestResponse = reinterpret_cast<SendTradeRequestResponse>(g_dotnet->get_method(type_name_connection_manager, L"SendTradeRequestResponse"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendSetTradeMoney)(int32_t, uint32_t );
inline SendSetTradeMoney dotnet_SendSetTradeMoney = reinterpret_cast<SendSetTradeMoney>(g_dotnet->get_method(type_name_connection_manager, L"SendSetTradeMoney"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendLetterDeleteRequest)(int32_t, uint16_t );
inline SendLetterDeleteRequest dotnet_SendLetterDeleteRequest = reinterpret_cast<SendLetterDeleteRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendLetterDeleteRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendLetterListRequest)(int32_t);
inline SendLetterListRequest dotnet_SendLetterListRequest = reinterpret_cast<SendLetterListRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendLetterListRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendLetterSendRequest)(int32_t, uint32_t , const wchar_t* , uint32_t, const wchar_t* , uint32_t, BYTE , BYTE , uint16_t , const wchar_t* , uint32_t);
inline SendLetterSendRequest dotnet_SendLetterSendRequest = reinterpret_cast<SendLetterSendRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendLetterSendRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendLetterReadRequest)(int32_t, uint16_t );
inline SendLetterReadRequest dotnet_SendLetterReadRequest = reinterpret_cast<SendLetterReadRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendLetterReadRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendGuildKickPlayerRequest)(int32_t, const wchar_t* , uint32_t, const wchar_t* , uint32_t);
inline SendGuildKickPlayerRequest dotnet_SendGuildKickPlayerRequest = reinterpret_cast<SendGuildKickPlayerRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendGuildKickPlayerRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendGuildJoinRequest)(int32_t, uint16_t );
inline SendGuildJoinRequest dotnet_SendGuildJoinRequest = reinterpret_cast<SendGuildJoinRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendGuildJoinRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendGuildJoinResponse)(int32_t, BYTE , uint16_t );
inline SendGuildJoinResponse dotnet_SendGuildJoinResponse = reinterpret_cast<SendGuildJoinResponse>(g_dotnet->get_method(type_name_connection_manager, L"SendGuildJoinResponse"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendGuildListRequest)(int32_t);
inline SendGuildListRequest dotnet_SendGuildListRequest = reinterpret_cast<SendGuildListRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendGuildListRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendGuildCreateRequest)(int32_t, const wchar_t* , uint32_t, const BYTE* , uint32_t);
inline SendGuildCreateRequest dotnet_SendGuildCreateRequest = reinterpret_cast<SendGuildCreateRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendGuildCreateRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendGuildCreateRequest075)(int32_t, const wchar_t* , uint32_t, const BYTE* , uint32_t);
inline SendGuildCreateRequest075 dotnet_SendGuildCreateRequest075 = reinterpret_cast<SendGuildCreateRequest075>(g_dotnet->get_method(type_name_connection_manager, L"SendGuildCreateRequest075"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendGuildMasterAnswer)(int32_t, BYTE );
inline SendGuildMasterAnswer dotnet_SendGuildMasterAnswer = reinterpret_cast<SendGuildMasterAnswer>(g_dotnet->get_method(type_name_connection_manager, L"SendGuildMasterAnswer"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCancelGuildCreation)(int32_t);
inline SendCancelGuildCreation dotnet_SendCancelGuildCreation = reinterpret_cast<SendCancelGuildCreation>(g_dotnet->get_method(type_name_connection_manager, L"SendCancelGuildCreation"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendGuildWarResponse)(int32_t, BYTE );
inline SendGuildWarResponse dotnet_SendGuildWarResponse = reinterpret_cast<SendGuildWarResponse>(g_dotnet->get_method(type_name_connection_manager, L"SendGuildWarResponse"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendGuildInfoRequest)(int32_t, uint32_t );
inline SendGuildInfoRequest dotnet_SendGuildInfoRequest = reinterpret_cast<SendGuildInfoRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendGuildInfoRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendGuildRoleAssignRequest)(int32_t, uint32_t , const wchar_t* , uint32_t, BYTE );
inline SendGuildRoleAssignRequest dotnet_SendGuildRoleAssignRequest = reinterpret_cast<SendGuildRoleAssignRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendGuildRoleAssignRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendGuildTypeChangeRequest)(int32_t, BYTE );
inline SendGuildTypeChangeRequest dotnet_SendGuildTypeChangeRequest = reinterpret_cast<SendGuildTypeChangeRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendGuildTypeChangeRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendGuildRelationshipChangeRequest)(int32_t, uint32_t , uint32_t , uint16_t );
inline SendGuildRelationshipChangeRequest dotnet_SendGuildRelationshipChangeRequest = reinterpret_cast<SendGuildRelationshipChangeRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendGuildRelationshipChangeRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendGuildRelationshipChangeResponse)(int32_t, uint32_t , uint32_t , BYTE , uint16_t );
inline SendGuildRelationshipChangeResponse dotnet_SendGuildRelationshipChangeResponse = reinterpret_cast<SendGuildRelationshipChangeResponse>(g_dotnet->get_method(type_name_connection_manager, L"SendGuildRelationshipChangeResponse"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendRequestAllianceList)(int32_t);
inline SendRequestAllianceList dotnet_SendRequestAllianceList = reinterpret_cast<SendRequestAllianceList>(g_dotnet->get_method(type_name_connection_manager, L"SendRequestAllianceList"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendRemoveAllianceGuildRequest)(int32_t, const wchar_t* , uint32_t);
inline SendRemoveAllianceGuildRequest dotnet_SendRemoveAllianceGuildRequest = reinterpret_cast<SendRemoveAllianceGuildRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendRemoveAllianceGuildRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendPingResponse)(int32_t);
inline SendPingResponse dotnet_SendPingResponse = reinterpret_cast<SendPingResponse>(g_dotnet->get_method(type_name_connection_manager, L"SendPingResponse"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendItemRepair)(int32_t, BYTE );
inline SendItemRepair dotnet_SendItemRepair = reinterpret_cast<SendItemRepair>(g_dotnet->get_method(type_name_connection_manager, L"SendItemRepair"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendChaosMachineMixRequest)(int32_t, uint32_t , BYTE );
inline SendChaosMachineMixRequest dotnet_SendChaosMachineMixRequest = reinterpret_cast<SendChaosMachineMixRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendChaosMachineMixRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendCraftingDialogCloseRequest)(int32_t);
inline SendCraftingDialogCloseRequest dotnet_SendCraftingDialogCloseRequest = reinterpret_cast<SendCraftingDialogCloseRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendCraftingDialogCloseRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendFriendListRequest)(int32_t);
inline SendFriendListRequest dotnet_SendFriendListRequest = reinterpret_cast<SendFriendListRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendFriendListRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendFriendAddRequest)(int32_t, const wchar_t* , uint32_t);
inline SendFriendAddRequest dotnet_SendFriendAddRequest = reinterpret_cast<SendFriendAddRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendFriendAddRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendFriendDelete)(int32_t, const wchar_t* , uint32_t);
inline SendFriendDelete dotnet_SendFriendDelete = reinterpret_cast<SendFriendDelete>(g_dotnet->get_method(type_name_connection_manager, L"SendFriendDelete"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendChatRoomCreateRequest)(int32_t, const wchar_t* , uint32_t);
inline SendChatRoomCreateRequest dotnet_SendChatRoomCreateRequest = reinterpret_cast<SendChatRoomCreateRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendChatRoomCreateRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendFriendAddResponse)(int32_t, BYTE , const wchar_t* , uint32_t);
inline SendFriendAddResponse dotnet_SendFriendAddResponse = reinterpret_cast<SendFriendAddResponse>(g_dotnet->get_method(type_name_connection_manager, L"SendFriendAddResponse"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendSetFriendOnlineState)(int32_t, BYTE );
inline SendSetFriendOnlineState dotnet_SendSetFriendOnlineState = reinterpret_cast<SendSetFriendOnlineState>(g_dotnet->get_method(type_name_connection_manager, L"SendSetFriendOnlineState"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendChatRoomInvitationRequest)(int32_t, const wchar_t* , uint32_t, uint16_t , uint32_t );
inline SendChatRoomInvitationRequest dotnet_SendChatRoomInvitationRequest = reinterpret_cast<SendChatRoomInvitationRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendChatRoomInvitationRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendLegacyQuestStateRequest)(int32_t);
inline SendLegacyQuestStateRequest dotnet_SendLegacyQuestStateRequest = reinterpret_cast<SendLegacyQuestStateRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendLegacyQuestStateRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendLegacyQuestStateSetRequest)(int32_t, BYTE , uint32_t );
inline SendLegacyQuestStateSetRequest dotnet_SendLegacyQuestStateSetRequest = reinterpret_cast<SendLegacyQuestStateSetRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendLegacyQuestStateSetRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendPetCommandRequest)(int32_t, uint32_t , uint32_t , uint16_t );
inline SendPetCommandRequest dotnet_SendPetCommandRequest = reinterpret_cast<SendPetCommandRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendPetCommandRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendPetInfoRequest)(int32_t, uint32_t , uint32_t , BYTE );
inline SendPetInfoRequest dotnet_SendPetInfoRequest = reinterpret_cast<SendPetInfoRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendPetInfoRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendIllusionTempleEnterRequest)(int32_t, BYTE , BYTE );
inline SendIllusionTempleEnterRequest dotnet_SendIllusionTempleEnterRequest = reinterpret_cast<SendIllusionTempleEnterRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendIllusionTempleEnterRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendIllusionTempleSkillRequest)(int32_t, uint16_t , BYTE , BYTE );
inline SendIllusionTempleSkillRequest dotnet_SendIllusionTempleSkillRequest = reinterpret_cast<SendIllusionTempleSkillRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendIllusionTempleSkillRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendIllusionTempleRewardRequest)(int32_t);
inline SendIllusionTempleRewardRequest dotnet_SendIllusionTempleRewardRequest = reinterpret_cast<SendIllusionTempleRewardRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendIllusionTempleRewardRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendLuckyCoinCountRequest)(int32_t);
inline SendLuckyCoinCountRequest dotnet_SendLuckyCoinCountRequest = reinterpret_cast<SendLuckyCoinCountRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendLuckyCoinCountRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendLuckyCoinRegistrationRequest)(int32_t);
inline SendLuckyCoinRegistrationRequest dotnet_SendLuckyCoinRegistrationRequest = reinterpret_cast<SendLuckyCoinRegistrationRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendLuckyCoinRegistrationRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendLuckyCoinExchangeRequest)(int32_t, uint32_t );
inline SendLuckyCoinExchangeRequest dotnet_SendLuckyCoinExchangeRequest = reinterpret_cast<SendLuckyCoinExchangeRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendLuckyCoinExchangeRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendDoppelgangerEnterRequest)(int32_t, BYTE );
inline SendDoppelgangerEnterRequest dotnet_SendDoppelgangerEnterRequest = reinterpret_cast<SendDoppelgangerEnterRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendDoppelgangerEnterRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendEnterMarketPlaceRequest)(int32_t);
inline SendEnterMarketPlaceRequest dotnet_SendEnterMarketPlaceRequest = reinterpret_cast<SendEnterMarketPlaceRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendEnterMarketPlaceRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendMuHelperStatusChangeRequest)(int32_t, BYTE );
inline SendMuHelperStatusChangeRequest dotnet_SendMuHelperStatusChangeRequest = reinterpret_cast<SendMuHelperStatusChangeRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendMuHelperStatusChangeRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendMuHelperSaveDataRequest)(int32_t, const BYTE* , uint32_t);
inline SendMuHelperSaveDataRequest dotnet_SendMuHelperSaveDataRequest = reinterpret_cast<SendMuHelperSaveDataRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendMuHelperSaveDataRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendQuestSelectRequest)(int32_t, uint16_t , uint16_t , BYTE );
inline SendQuestSelectRequest dotnet_SendQuestSelectRequest = reinterpret_cast<SendQuestSelectRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendQuestSelectRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendQuestProceedRequest)(int32_t, uint16_t , uint16_t , uint32_t );
inline SendQuestProceedRequest dotnet_SendQuestProceedRequest = reinterpret_cast<SendQuestProceedRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendQuestProceedRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendQuestCompletionRequest)(int32_t, uint16_t , uint16_t );
inline SendQuestCompletionRequest dotnet_SendQuestCompletionRequest = reinterpret_cast<SendQuestCompletionRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendQuestCompletionRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendQuestCancelRequest)(int32_t, uint16_t , uint16_t );
inline SendQuestCancelRequest dotnet_SendQuestCancelRequest = reinterpret_cast<SendQuestCancelRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendQuestCancelRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendQuestClientActionRequest)(int32_t, uint16_t , uint16_t );
inline SendQuestClientActionRequest dotnet_SendQuestClientActionRequest = reinterpret_cast<SendQuestClientActionRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendQuestClientActionRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendActiveQuestListRequest)(int32_t);
inline SendActiveQuestListRequest dotnet_SendActiveQuestListRequest = reinterpret_cast<SendActiveQuestListRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendActiveQuestListRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendQuestStateRequest)(int32_t, uint16_t , uint16_t );
inline SendQuestStateRequest dotnet_SendQuestStateRequest = reinterpret_cast<SendQuestStateRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendQuestStateRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendEventQuestStateListRequest)(int32_t);
inline SendEventQuestStateListRequest dotnet_SendEventQuestStateListRequest = reinterpret_cast<SendEventQuestStateListRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendEventQuestStateListRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendAvailableQuestsRequest)(int32_t);
inline SendAvailableQuestsRequest dotnet_SendAvailableQuestsRequest = reinterpret_cast<SendAvailableQuestsRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendAvailableQuestsRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendNpcBuffRequest)(int32_t);
inline SendNpcBuffRequest dotnet_SendNpcBuffRequest = reinterpret_cast<SendNpcBuffRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendNpcBuffRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendEnterEmpireGuardianEvent)(int32_t, BYTE );
inline SendEnterEmpireGuardianEvent dotnet_SendEnterEmpireGuardianEvent = reinterpret_cast<SendEnterEmpireGuardianEvent>(g_dotnet->get_method(type_name_connection_manager, L"SendEnterEmpireGuardianEvent"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendGensJoinRequest)(int32_t, uint32_t );
inline SendGensJoinRequest dotnet_SendGensJoinRequest = reinterpret_cast<SendGensJoinRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendGensJoinRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendGensLeaveRequest)(int32_t);
inline SendGensLeaveRequest dotnet_SendGensLeaveRequest = reinterpret_cast<SendGensLeaveRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendGensLeaveRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendGensRewardRequest)(int32_t, uint32_t );
inline SendGensRewardRequest dotnet_SendGensRewardRequest = reinterpret_cast<SendGensRewardRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendGensRewardRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendGensRankingRequest)(int32_t);
inline SendGensRankingRequest dotnet_SendGensRankingRequest = reinterpret_cast<SendGensRankingRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendGensRankingRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendDevilSquareEnterRequest)(int32_t, BYTE , BYTE );
inline SendDevilSquareEnterRequest dotnet_SendDevilSquareEnterRequest = reinterpret_cast<SendDevilSquareEnterRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendDevilSquareEnterRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendMiniGameOpeningStateRequest)(int32_t, uint32_t , BYTE );
inline SendMiniGameOpeningStateRequest dotnet_SendMiniGameOpeningStateRequest = reinterpret_cast<SendMiniGameOpeningStateRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendMiniGameOpeningStateRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendEventChipRegistrationRequest)(int32_t, BYTE , BYTE );
inline SendEventChipRegistrationRequest dotnet_SendEventChipRegistrationRequest = reinterpret_cast<SendEventChipRegistrationRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendEventChipRegistrationRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendMutoNumberRequest)(int32_t);
inline SendMutoNumberRequest dotnet_SendMutoNumberRequest = reinterpret_cast<SendMutoNumberRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendMutoNumberRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendEventChipExitDialog)(int32_t);
inline SendEventChipExitDialog dotnet_SendEventChipExitDialog = reinterpret_cast<SendEventChipExitDialog>(g_dotnet->get_method(type_name_connection_manager, L"SendEventChipExitDialog"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendEventChipExchangeRequest)(int32_t, BYTE );
inline SendEventChipExchangeRequest dotnet_SendEventChipExchangeRequest = reinterpret_cast<SendEventChipExchangeRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendEventChipExchangeRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendServerImmigrationRequest)(int32_t, const wchar_t* , uint32_t);
inline SendServerImmigrationRequest dotnet_SendServerImmigrationRequest = reinterpret_cast<SendServerImmigrationRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendServerImmigrationRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendLuckyNumberRequest)(int32_t, const wchar_t* , uint32_t, const wchar_t* , uint32_t, const wchar_t* , uint32_t);
inline SendLuckyNumberRequest dotnet_SendLuckyNumberRequest = reinterpret_cast<SendLuckyNumberRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendLuckyNumberRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendBloodCastleEnterRequest)(int32_t, BYTE , BYTE );
inline SendBloodCastleEnterRequest dotnet_SendBloodCastleEnterRequest = reinterpret_cast<SendBloodCastleEnterRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendBloodCastleEnterRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendMiniGameEventCountRequest)(int32_t, uint32_t );
inline SendMiniGameEventCountRequest dotnet_SendMiniGameEventCountRequest = reinterpret_cast<SendMiniGameEventCountRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendMiniGameEventCountRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendChaosCastleEnterRequest)(int32_t, BYTE , BYTE );
inline SendChaosCastleEnterRequest dotnet_SendChaosCastleEnterRequest = reinterpret_cast<SendChaosCastleEnterRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendChaosCastleEnterRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendChaosCastlePositionSet)(int32_t, BYTE , BYTE );
inline SendChaosCastlePositionSet dotnet_SendChaosCastlePositionSet = reinterpret_cast<SendChaosCastlePositionSet>(g_dotnet->get_method(type_name_connection_manager, L"SendChaosCastlePositionSet"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendDuelStartRequest)(int32_t, uint16_t , const wchar_t* , uint32_t);
inline SendDuelStartRequest dotnet_SendDuelStartRequest = reinterpret_cast<SendDuelStartRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendDuelStartRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendDuelStartResponse)(int32_t, BYTE , uint16_t , const wchar_t* , uint32_t);
inline SendDuelStartResponse dotnet_SendDuelStartResponse = reinterpret_cast<SendDuelStartResponse>(g_dotnet->get_method(type_name_connection_manager, L"SendDuelStartResponse"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendDuelStopRequest)(int32_t);
inline SendDuelStopRequest dotnet_SendDuelStopRequest = reinterpret_cast<SendDuelStopRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendDuelStopRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendDuelChannelJoinRequest)(int32_t, BYTE );
inline SendDuelChannelJoinRequest dotnet_SendDuelChannelJoinRequest = reinterpret_cast<SendDuelChannelJoinRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendDuelChannelJoinRequest"));

typedef void(CORECLR_DELEGATE_CALLTYPE* SendDuelChannelQuitRequest)(int32_t, BYTE );
inline SendDuelChannelQuitRequest dotnet_SendDuelChannelQuitRequest = reinterpret_cast<SendDuelChannelQuitRequest>(g_dotnet->get_method(type_name_connection_manager, L"SendDuelChannelQuitRequest"));
