#ifdef _DEBUG
#define KWAK_FIX_ALT_KEYDOWN_MENU_BLOCK
#endif // _DEBUG

#define ASG_ADD_GENS_SYSTEM
#ifdef ASG_ADD_GENS_SYSTEM
#define ASG_ADD_INFLUENCE_GROUND_EFFECT
#define ASG_ADD_GENS_MARK
#define PBG_MOD_STRIFE_GENSMARKRENDER
#define PBG_ADD_GENSRANKING
#endif	// ASG_ADD_GENS_SYSTEM

#define KJH_PBG_ADD_INGAMESHOP_SYSTEM
#ifdef KJH_PBG_ADD_INGAMESHOP_SYSTEM
#define PBG_ADD_INGAMESHOP_UI_MAINFRAME
#define PBG_ADD_INGAMESHOP_UI_ITEMSHOP
#define PBG_ADD_NAMETOPMSGBOX
#define KJH_ADD_INGAMESHOP_UI_SYSTEM
#define KJH_ADD_PERIOD_ITEM_SYSTEM
#define PBG_ADD_INGAMESHOPMSGBOX
#define PBG_ADD_ITEMRESIZE
#define KJH_MOD_SHOP_SCRIPT_DOWNLOAD
//^#define PBG_ADD_CHARACTERSLOT
#define PBG_ADD_CHARACTERCARD
//^#define LDK_ADD_INGAMESHOP_LIMIT_MOVE_WINDOW
#endif //KJH_PBG_ADD_INGAMESHOP_SYSTEM

#define PJH_ADD_PANDA_PET
#define PJH_ADD_PANDA_CHANGERING

#define SEND_POSITION_TO_SERVER

#define ASG_ADD_MAP_KARUTAN
#define ASG_ADD_KARUTAN_MONSTERS