#pragma once

// Window identifiers, apart from _enum.h so code that only names a window needn't include every
// game enum.

namespace mu::ui::window
{
enum INTERFACE_LIST
{
    INTERFACE_BEGIN = 0x00,
    INTERFACE_FRIEND,
    INTERFACE_MOVEMAP,
    INTERFACE_PARTY,
    INTERFACE_MYQUEST,
    INTERFACE_NPCQUEST,
    INTERFACE_GUILDINFO,
    INTERFACE_TRADE,
    INTERFACE_STORAGE,
    INTERFACE_STORAGE_EXT,
    INTERFACE_MIXINVENTORY,
    INTERFACE_COMMAND,
    INTERFACE_PET,
    INTERFACE_NPCSHOP,
    INTERFACE_INVENTORY,
    INTERFACE_INVENTORY_EXT,
    INTERFACE_MYSHOP_INVENTORY,
    INTERFACE_PURCHASESHOP_INVENTORY,
    INTERFACE_CHARACTER,
    INTERFACE_NPCBREEDER,
    INTERFACE_SERVERDIVISION,
    INTERFACE_DEVILSQUARE,
    INTERFACE_BLOODCASTLE,
    INTERFACE_NPCGUILDMASTER,
    INTERFACE_GUARDSMAN,
    INTERFACE_SENATUS,
    INTERFACE_GATEKEEPER,
    INTERFACE_GATESWITCH,
    INTERFACE_CATAPULT,
    INTERFACE_REFINERY,
    INTERFACE_REFINERYINFO,
    INTERFACE_KANTURU2ND_ENTERNPC,
    INTERFACE_CURSEDTEMPLE_NPC,
    INTERFACE_CURSEDTEMPLE_GAMESYSTEM,
    INTERFACE_CURSEDTEMPLE_RESULT,
    INTERFACE_CHATINPUTBOX,
    INTERFACE_WINDOW_MENU,
    INTERFACE_OPTION,
    INTERFACE_HELP,
    INTERFACE_ITEM_EXPLANATION,
    INTERFACE_SETITEM_EXPLANATION,
    INTERFACE_QUICK_COMMAND,
    INTERFACE_KANTURU_INFO,
    INTERFACE_CHATLOGWINDOW,
    INTERFACE_PARTY_INFO_WINDOW,
    INTERFACE_BLOODCASTLE_TIME,
    INTERFACE_CHAOSCASTLE_TIME,
    INTERFACE_BATTLE_SOCCER_SCORE,
    INTERFACE_SLIDEWINDOW,
    INTERFACE_MU_HELPER_BAR, // renamed from INTERFACE_HERO_POSITION_INFO -- see
                             // CMuHelperBar (UI/HUD/MuHelperBar.h)'s own header comment
    INTERFACE_MESSAGEBOX,
    INTERFACE_DUEL_WINDOW,
    INTERFACE_CRYWOLF,
    INTERFACE_NAME_WINDOW,
    INTERFACE_SIEGEWARFARE,
    INTERFACE_MAINFRAME,
    INTERFACE_SKILL_LIST,
    INTERFACE_ITEM_ENDURANCE_INFO,
    INTERFACE_BUFF_WINDOW,
    INTERFACE_MASTER_LEVEL,
    INTERFACE_GOLD_BOWMAN,
    INTERFACE_GOLD_BOWMAN_LENA,
    INTERFACE_LUCKYCOIN_REGISTRATION,
    INTERFACE_EXCHANGE_LUCKYCOIN,
    INTERFACE_DUELWATCH,
    INTERFACE_DUELWATCH_MAINFRAME,
    INTERFACE_DUELWATCH_USERLIST,
    INTERFACE_INGAMESHOP,
    INTERFACE_DOPPELGANGER_NPC,
    INTERFACE_DOPPELGANGER_FRAME,
    INTERFACE_QUEST_PROGRESS,
    INTERFACE_QUEST_PROGRESS_ETC,
    INTERFACE_EMPIREGUARDIAN_NPC,
    INTERFACE_EMPIREGUARDIAN_TIMER,
    INTERFACE_MINI_MAP,
    INTERFACE_NPC_DIALOGUE,
    INTERFACE_GENSRANKING,
    INTERFACE_UNITEDMARKETPLACE_NPC_JULIA,
    INTERFACE_LUCKYITEMWND,
    INTERFACE_HOTKEY,
    INTERFACE_3DRENDERING_CAMERA_BEGIN,
    INTERFACE_3DRENDERING_CAMERA_END = INTERFACE_3DRENDERING_CAMERA_BEGIN + 24,
    INTERFACE_ITEM_TOOLTIP,
    INTERFACE_MUHELPER,
    INTERFACE_MUHELPER_EXT,
    INTERFACE_MUHELPER_SKILL_LIST,
    INTERFACE_SYSTEMLOGWINDOW,
    INTERFACE_COMMAND_LIST,
    // CCreditWin is the pilot for migrating CUIMng's CWin-derived windows onto CManager's
    // registry. Inserted just before INTERFACE_END so every other entry's numeric value is
    // unaffected.
    INTERFACE_CREDITS,
    // CServerMsgWin, same reasoning as INTERFACE_CREDITS above.
    INTERFACE_SERVER_MESSAGE,
    // CServerSelWin, same reasoning as INTERFACE_CREDITS above.
    INTERFACE_SERVER_SELECT,
    // CMsgWin (distinct from INTERFACE_MESSAGEBOX, the unrelated MAIN_SCENE-tier
    // CMessageBoxBase key) -- same reasoning as INTERFACE_CREDITS above.
    INTERFACE_MSG_WINDOW,
    // CSysMenuWin, same reasoning as INTERFACE_CREDITS above.
    INTERFACE_SYS_MENU,
    // CCharSelMainWin, same reasoning as INTERFACE_CREDITS above.
    INTERFACE_CHAR_SEL_MAIN,
    // CCharMakeWin, same reasoning as INTERFACE_CREDITS above.
    INTERFACE_CHAR_MAKE,
    // CLoginMainWin, same reasoning as INTERFACE_CREDITS above.
    INTERFACE_LOGIN_MAIN,
    // CLoginWin (distinct from INTERFACE_LOGIN_MAIN, CLoginMainWin's own key), same
    // reasoning as INTERFACE_CREDITS above.
    INTERFACE_LOGIN,
    // CCharInfoBalloonMng's thin adapter -- never a CWin, previously driven by direct
    // CUIMng calls rather than through any list at all; same reasoning as INTERFACE_CREDITS above.
    INTERFACE_CHAR_INFO_BALLOON,
    // CGenericConfirmDialog (UI/Dialogs/GenericConfirmDialog.h) -- the reusable RmlUi confirm-
    // dialog primitive, distinct from INTERFACE_MESSAGEBOX (the native CMessageBoxBase/
    // CMessageBoxMng system it's meant to eventually replace). Inserted just before INTERFACE_END,
    // same reasoning as INTERFACE_CREDITS above.
    INTERFACE_GENERIC_CONFIRM_DIALOG,
    // CGenericMenuDialog (UI/Dialogs/GenericMenuDialog.h) -- sibling primitive to
    // CGenericConfirmDialog for native "N-button menu" dialogs (CSystemMenuMsgBox and similar),
    // a different button model (arbitrary labeled list vs two fixed OK/Cancel slots). Same
    // reasoning as INTERFACE_CREDITS above.
    INTERFACE_GENERIC_MENU_DIALOG,
    INTERFACE_END,
    INTERFACE_COUNT = INTERFACE_END - 2,
};
}
