#ifndef _CkHttp_H
#define _CkHttp_H
#include "Chilkat_C.h"

HCkHttp CkHttp_Create(void);
void CkHttp_Dispose(HCkHttp handle);
void CkHttp_getAccept(HCkHttp cHandle, HCkString retval);
void CkHttp_putAccept(HCkHttp cHandle, const char *newVal);
void CkHttp_getAcceptCharset(HCkHttp cHandle, HCkString retval);
void CkHttp_putAcceptCharset(HCkHttp cHandle, const char *newVal);
void CkHttp_getAcceptLanguage(HCkHttp cHandle, HCkString retval);
void CkHttp_putAcceptLanguage(HCkHttp cHandle, const char *newVal);
BOOL CkHttp_getAutoAddHostHeader(HCkHttp cHandle);
void CkHttp_putAutoAddHostHeader(HCkHttp cHandle, BOOL newVal);
void CkHttp_getBgLastErrorText(HCkHttp cHandle, HCkString retval);
void CkHttp_getBgResultData(HCkHttp cHandle, HCkByteData retval);
int CkHttp_getBgResultInt(HCkHttp cHandle);
void CkHttp_getBgResultString(HCkHttp cHandle, HCkString retval);
BOOL CkHttp_getBgTaskFinished(HCkHttp cHandle);
BOOL CkHttp_getBgTaskRunning(HCkHttp cHandle);
BOOL CkHttp_getBgTaskSuccess(HCkHttp cHandle);
long CkHttp_getConnectTimeout(HCkHttp cHandle);
void CkHttp_putConnectTimeout(HCkHttp cHandle, long newVal);
void CkHttp_getConnection(HCkHttp cHandle, HCkString retval);
void CkHttp_putConnection(HCkHttp cHandle, const char *newVal);
void CkHttp_getCookieDir(HCkHttp cHandle, HCkString retval);
void CkHttp_putCookieDir(HCkHttp cHandle, const char *newVal);
long CkHttp_getDefaultFreshPeriod(HCkHttp cHandle);
void CkHttp_putDefaultFreshPeriod(HCkHttp cHandle, long newVal);
BOOL CkHttp_getDigestAuth(HCkHttp cHandle);
void CkHttp_putDigestAuth(HCkHttp cHandle, BOOL newVal);
int CkHttp_getEventLogCount(HCkHttp cHandle);
BOOL CkHttp_getFetchFromCache(HCkHttp cHandle);
void CkHttp_putFetchFromCache(HCkHttp cHandle, BOOL newVal);
void CkHttp_getFinalRedirectUrl(HCkHttp cHandle, HCkString retval);
BOOL CkHttp_getFollowRedirects(HCkHttp cHandle);
void CkHttp_putFollowRedirects(HCkHttp cHandle, BOOL newVal);
long CkHttp_getFreshnessAlgorithm(HCkHttp cHandle);
void CkHttp_putFreshnessAlgorithm(HCkHttp cHandle, long newVal);
long CkHttp_getHeartbeatMs(HCkHttp cHandle);
void CkHttp_putHeartbeatMs(HCkHttp cHandle, long newVal);
BOOL CkHttp_getIgnoreMustRevalidate(HCkHttp cHandle);
void CkHttp_putIgnoreMustRevalidate(HCkHttp cHandle, BOOL newVal);
BOOL CkHttp_getIgnoreNoCache(HCkHttp cHandle);
void CkHttp_putIgnoreNoCache(HCkHttp cHandle, BOOL newVal);
BOOL CkHttp_getKeepEventLog(HCkHttp cHandle);
void CkHttp_putKeepEventLog(HCkHttp cHandle, BOOL newVal);
long CkHttp_getLMFactor(HCkHttp cHandle);
void CkHttp_putLMFactor(HCkHttp cHandle, long newVal);
void CkHttp_getLastContentType(HCkHttp cHandle, HCkString retval);
void CkHttp_getLastErrorHtml(HCkHttp cHandle, HCkString retval);
void CkHttp_getLastErrorText(HCkHttp cHandle, HCkString retval);
void CkHttp_getLastErrorXml(HCkHttp cHandle, HCkString retval);
void CkHttp_getLastHeader(HCkHttp cHandle, HCkString retval);
void CkHttp_getLastModDate(HCkHttp cHandle, HCkString retval);
void CkHttp_getLastResponseHeader(HCkHttp cHandle, HCkString retval);
long CkHttp_getLastStatus(HCkHttp cHandle);
void CkHttp_getLogin(HCkHttp cHandle, HCkString retval);
void CkHttp_putLogin(HCkHttp cHandle, const char *newVal);
void CkHttp_getLoginDomain(HCkHttp cHandle, HCkString retval);
void CkHttp_putLoginDomain(HCkHttp cHandle, const char *newVal);
long CkHttp_getMaxConnections(HCkHttp cHandle);
void CkHttp_putMaxConnections(HCkHttp cHandle, long newVal);
long CkHttp_getMaxFreshPeriod(HCkHttp cHandle);
void CkHttp_putMaxFreshPeriod(HCkHttp cHandle, long newVal);
unsigned long CkHttp_getMaxResponseSize(HCkHttp cHandle);
void CkHttp_putMaxResponseSize(HCkHttp cHandle, unsigned long newVal);
long CkHttp_getMaxUrlLen(HCkHttp cHandle);
void CkHttp_putMaxUrlLen(HCkHttp cHandle, long newVal);
BOOL CkHttp_getMimicFireFox(HCkHttp cHandle);
void CkHttp_putMimicFireFox(HCkHttp cHandle, BOOL newVal);
BOOL CkHttp_getMimicIE(HCkHttp cHandle);
void CkHttp_putMimicIE(HCkHttp cHandle, BOOL newVal);
long CkHttp_getMinFreshPeriod(HCkHttp cHandle);
void CkHttp_putMinFreshPeriod(HCkHttp cHandle, long newVal);
BOOL CkHttp_getNegotiateAuth(HCkHttp cHandle);
void CkHttp_putNegotiateAuth(HCkHttp cHandle, BOOL newVal);
BOOL CkHttp_getNtlmAuth(HCkHttp cHandle);
void CkHttp_putNtlmAuth(HCkHttp cHandle, BOOL newVal);
long CkHttp_getNumCacheLevels(HCkHttp cHandle);
void CkHttp_putNumCacheLevels(HCkHttp cHandle, long newVal);
long CkHttp_getNumCacheRoots(HCkHttp cHandle);
void CkHttp_getPassword(HCkHttp cHandle, HCkString retval);
void CkHttp_putPassword(HCkHttp cHandle, const char *newVal);
void CkHttp_getProxyDomain(HCkHttp cHandle, HCkString retval);
void CkHttp_putProxyDomain(HCkHttp cHandle, const char *newVal);
void CkHttp_getProxyLogin(HCkHttp cHandle, HCkString retval);
void CkHttp_putProxyLogin(HCkHttp cHandle, const char *newVal);
BOOL CkHttp_getProxyPartialUrl(HCkHttp cHandle);
void CkHttp_putProxyPartialUrl(HCkHttp cHandle, BOOL newVal);
void CkHttp_getProxyPassword(HCkHttp cHandle, HCkString retval);
void CkHttp_putProxyPassword(HCkHttp cHandle, const char *newVal);
long CkHttp_getProxyPort(HCkHttp cHandle);
void CkHttp_putProxyPort(HCkHttp cHandle, long newVal);
long CkHttp_getReadTimeout(HCkHttp cHandle);
void CkHttp_putReadTimeout(HCkHttp cHandle, long newVal);
void CkHttp_getReferer(HCkHttp cHandle, HCkString retval);
void CkHttp_putReferer(HCkHttp cHandle, const char *newVal);
void CkHttp_getRequiredContentType(HCkHttp cHandle, HCkString retval);
void CkHttp_putRequiredContentType(HCkHttp cHandle, const char *newVal);
BOOL CkHttp_getSaveCookies(HCkHttp cHandle);
void CkHttp_putSaveCookies(HCkHttp cHandle, BOOL newVal);
int CkHttp_getSendBufferSize(HCkHttp cHandle);
void CkHttp_putSendBufferSize(HCkHttp cHandle, int newVal);
BOOL CkHttp_getSendCookies(HCkHttp cHandle);
void CkHttp_putSendCookies(HCkHttp cHandle, BOOL newVal);
void CkHttp_getSessionLogFilename(HCkHttp cHandle, HCkString retval);
void CkHttp_putSessionLogFilename(HCkHttp cHandle, const char *newVal);
void CkHttp_getSocksHostname(HCkHttp cHandle, HCkString retval);
void CkHttp_putSocksHostname(HCkHttp cHandle, const char *newVal);
void CkHttp_getSocksPassword(HCkHttp cHandle, HCkString retval);
void CkHttp_putSocksPassword(HCkHttp cHandle, const char *newVal);
int CkHttp_getSocksPort(HCkHttp cHandle);
void CkHttp_putSocksPort(HCkHttp cHandle, int newVal);
void CkHttp_getSocksUsername(HCkHttp cHandle, HCkString retval);
void CkHttp_putSocksUsername(HCkHttp cHandle, const char *newVal);
int CkHttp_getSocksVersion(HCkHttp cHandle);
void CkHttp_putSocksVersion(HCkHttp cHandle, int newVal);
void CkHttp_getSslProtocol(HCkHttp cHandle, HCkString retval);
void CkHttp_putSslProtocol(HCkHttp cHandle, const char *newVal);
BOOL CkHttp_getUpdateCache(HCkHttp cHandle);
void CkHttp_putUpdateCache(HCkHttp cHandle, BOOL newVal);
BOOL CkHttp_getUseBgThread(HCkHttp cHandle);
void CkHttp_putUseBgThread(HCkHttp cHandle, BOOL newVal);
BOOL CkHttp_getUseIEProxy(HCkHttp cHandle);
void CkHttp_putUseIEProxy(HCkHttp cHandle, BOOL newVal);
void CkHttp_getUserAgent(HCkHttp cHandle, HCkString retval);
void CkHttp_putUserAgent(HCkHttp cHandle, const char *newVal);
BOOL CkHttp_getUtf8(HCkHttp cHandle);
void CkHttp_putUtf8(HCkHttp cHandle, BOOL newVal);
BOOL CkHttp_getVerboseLogging(HCkHttp cHandle);
void CkHttp_putVerboseLogging(HCkHttp cHandle, BOOL newVal);
void CkHttp_getVersion(HCkHttp cHandle, HCkString retval);
BOOL CkHttp_getWasRedirected(HCkHttp cHandle);
void CkHttp_AddCacheRoot(HCkHttp cHandle, const char *dir);
HCkHttpResponse CkHttp_BgResponseObject(HCkHttp cHandle);
void CkHttp_BgTaskAbort(HCkHttp cHandle);
void CkHttp_ClearEventLog(HCkHttp cHandle);
void CkHttp_ClearInMemoryCookies(HCkHttp cHandle);
BOOL CkHttp_Download(HCkHttp cHandle, const char *url, const char *filename);
BOOL CkHttp_DownloadAppend(HCkHttp cHandle, const char *url, const char *filename);
BOOL CkHttp_EventLogName(HCkHttp cHandle, int index, HCkString outStr);
BOOL CkHttp_EventLogValue(HCkHttp cHandle, int index, HCkString outStr);
void CkHttp_GenTimeStamp(HCkHttp cHandle, HCkString outStr);
BOOL CkHttp_GetCacheRoot(HCkHttp cHandle, int index, HCkString str);
BOOL CkHttp_GetCookieXml(HCkHttp cHandle, const char *domain, HCkString outStr);
void CkHttp_GetDomain(HCkHttp cHandle, const char *url, HCkString str);
HCkHttpResponse CkHttp_GetHead(HCkHttp cHandle, const char *url);
BOOL CkHttp_GetRequestHeader(HCkHttp cHandle, const char *name, HCkString str);
HCkCert CkHttp_GetServerSslCert(HCkHttp cHandle, const char *domain, int port);
void CkHttp_GetUrlPath(HCkHttp cHandle, const char *url, HCkString str);
BOOL CkHttp_HasRequestHeader(HCkHttp cHandle, const char *name);
BOOL CkHttp_IsUnlocked(HCkHttp cHandle);
BOOL CkHttp_PostBinary(HCkHttp cHandle, const char *url, HCkByteData byteData, const char *contentType, BOOL md5, BOOL gzip, HCkString outStr);
HCkHttpResponse CkHttp_PostMime(HCkHttp cHandle, const char *url, const char *mime);
HCkHttpResponse CkHttp_PostUrlEncoded(HCkHttp cHandle, const char *url, HCkHttpRequest req);
HCkHttpResponse CkHttp_PostXml(HCkHttp cHandle, const char *url, const char *xmlDoc, const char *charset);
BOOL CkHttp_PutBinary(HCkHttp cHandle, const char *url, HCkByteData byteData, const char *contentType, BOOL md5, BOOL gzip, HCkString outStr);
BOOL CkHttp_PutText(HCkHttp cHandle, const char *url, const char *textData, const char *charset, const char *contentType, BOOL md5, BOOL gzip, HCkString outStr);
BOOL CkHttp_QuickDeleteStr(HCkHttp cHandle, const char *url, HCkString outStr);
BOOL CkHttp_QuickGet(HCkHttp cHandle, const char *url, HCkByteData data);
HCkHttpResponse CkHttp_QuickGetObj(HCkHttp cHandle, const char *url);
BOOL CkHttp_QuickGetStr(HCkHttp cHandle, const char *url, HCkString str);
BOOL CkHttp_QuickPutStr(HCkHttp cHandle, const char *url, HCkString outStr);
void CkHttp_RemoveRequestHeader(HCkHttp cHandle, const char *name);
BOOL CkHttp_RenderGet(HCkHttp cHandle, const char *url, HCkString outStr);
BOOL CkHttp_ResumeDownload(HCkHttp cHandle, const char *url, const char *filename);
BOOL CkHttp_SaveLastError(HCkHttp cHandle, const char *filename);
BOOL CkHttp_SetCookieXml(HCkHttp cHandle, const char *domain, const char *cookieXml);
void CkHttp_SetRequestHeader(HCkHttp cHandle, const char *name, const char *value);
void CkHttp_SetSslClientCert(HCkHttp cHandle, HCkCert cert);
BOOL CkHttp_SetSslClientCertPfx(HCkHttp cHandle, const char *pfxFilename, const char *pfxPassword, const char *certSubjectCN);
void CkHttp_SleepMs(HCkHttp cHandle, int millisec);
HCkHttpResponse CkHttp_SynchronousRequest(HCkHttp cHandle, const char *domain, long port, BOOL ssl, HCkHttpRequest req);
BOOL CkHttp_UnlockComponent(HCkHttp cHandle, const char *unlockCode);
BOOL CkHttp_UrlDecode(HCkHttp cHandle, const char *str, HCkString outStr);
BOOL CkHttp_UrlEncode(HCkHttp cHandle, const char *str, HCkString outStr);
BOOL CkHttp_XmlRpc(HCkHttp cHandle, const char *urlEndpoint, const char *xmlIn, HCkString outStr);
BOOL CkHttp_XmlRpcPut(HCkHttp cHandle, const char *urlEndpoint, const char *xmlIn, HCkString outStr);
const char *CkHttp_acceptCharset(HCkHttp cHandle);
const char *CkHttp_acceptLanguage(HCkHttp cHandle);
const char *CkHttp_bgLastErrorText(HCkHttp cHandle);
const char *CkHttp_bgResultString(HCkHttp cHandle);
const char *CkHttp_ck_accept(HCkHttp cHandle);
const char *CkHttp_connection(HCkHttp cHandle);
const char *CkHttp_cookieDir(HCkHttp cHandle);
const char *CkHttp_eventLogName(HCkHttp cHandle, int index);
const char *CkHttp_eventLogValue(HCkHttp cHandle, int index);
const char *CkHttp_finalRedirectUrl(HCkHttp cHandle);
const char *CkHttp_genTimeStamp(HCkHttp cHandle);
const char *CkHttp_getCacheRoot(HCkHttp cHandle, int index);
const char *CkHttp_getCookieXml(HCkHttp cHandle, const char *domain);
const char *CkHttp_getDomain(HCkHttp cHandle, const char *url);
const char *CkHttp_getRequestHeader(HCkHttp cHandle, const char *name);
const char *CkHttp_getUrlPath(HCkHttp cHandle, const char *url);
const char *CkHttp_lastContentType(HCkHttp cHandle);
const char *CkHttp_lastErrorHtml(HCkHttp cHandle);
const char *CkHttp_lastErrorText(HCkHttp cHandle);
const char *CkHttp_lastErrorXml(HCkHttp cHandle);
const char *CkHttp_lastHeader(HCkHttp cHandle);
const char *CkHttp_lastModDate(HCkHttp cHandle);
const char *CkHttp_lastResponseHeader(HCkHttp cHandle);
const char *CkHttp_login(HCkHttp cHandle);
const char *CkHttp_loginDomain(HCkHttp cHandle);
const char *CkHttp_password(HCkHttp cHandle);
const char *CkHttp_postBinary(HCkHttp cHandle, const char *url, HCkByteData byteData, const char *contentType, BOOL md5, BOOL gzip);
const char *CkHttp_proxyDomain(HCkHttp cHandle);
const char *CkHttp_proxyLogin(HCkHttp cHandle);
const char *CkHttp_proxyPassword(HCkHttp cHandle);
const char *CkHttp_putBinary(HCkHttp cHandle, const char *url, HCkByteData byteData, const char *contentType, BOOL md5, BOOL gzip);
const char *CkHttp_putText(HCkHttp cHandle, const char *url, const char *textData, const char *charset, const char *contentType, BOOL md5, BOOL gzip);
const char *CkHttp_quickDeleteStr(HCkHttp cHandle, const char *url);
const char *CkHttp_quickGetStr(HCkHttp cHandle, const char *url);
const char *CkHttp_quickPutStr(HCkHttp cHandle, const char *url);
const char *CkHttp_referer(HCkHttp cHandle);
const char *CkHttp_renderGet(HCkHttp cHandle, const char *url);
const char *CkHttp_requiredContentType(HCkHttp cHandle);
const char *CkHttp_sessionLogFilename(HCkHttp cHandle);
const char *CkHttp_socksHostname(HCkHttp cHandle);
const char *CkHttp_socksPassword(HCkHttp cHandle);
const char *CkHttp_socksUsername(HCkHttp cHandle);
const char *CkHttp_sslProtocol(HCkHttp cHandle);
const char *CkHttp_urlDecode(HCkHttp cHandle, const char *str);
const char *CkHttp_urlEncode(HCkHttp cHandle, const char *str);
const char *CkHttp_userAgent(HCkHttp cHandle);
const char *CkHttp_version(HCkHttp cHandle);
const char *CkHttp_xmlRpc(HCkHttp cHandle, const char *urlEndpoint, const char *xmlIn);
const char *CkHttp_xmlRpcPut(HCkHttp cHandle, const char *urlEndpoint, const char *xmlIn);
#endif
