#pragma once

enum CASTLESIEGE_STATE
{
    CASTLESIEGE_STATE_NONE = -1,
    CASTLESIEGE_STATE_IDLE_1 = 0,
    CASTLESIEGE_STATE_REGSIEGE = 1,
    CASTLESIEGE_STATE_IDLE_2 = 2,
    CASTLESIEGE_STATE_REGMARK = 3,
    CASTLESIEGE_STATE_IDLE_3 = 4,
    CASTLESIEGE_STATE_NOTIFY = 5,
    CASTLESIEGE_STATE_READYSIEGE = 6,
    CASTLESIEGE_STATE_STARTSIEGE = 7,
    CASTLESIEGE_STATE_ENDSIEGE = 8,
    CASTLESIEGE_STATE_ENDCYCLE = 9,
};
