foreach(required_file IN ITEMS RENDERER_HEADER RENDERER_SOURCE BMD_SOURCE SHADER_SOURCE)
    if(NOT EXISTS "${${required_file}}")
        message(FATAL_ERROR "GPU skinning path missing ${required_file}: ${${required_file}}")
    endif()
endforeach()

file(READ "${RENDERER_HEADER}" renderer_header)
file(READ "${RENDERER_SOURCE}" renderer_source)
file(READ "${BMD_SOURCE}" bmd_source)
file(READ "${SHADER_SOURCE}" shader_source)

if(NOT renderer_header MATCHES "RenderSkinnedTriangles")
    message(FATAL_ERROR "Renderer contract must expose GPU-skinned triangle submission")
endif()
if(NOT renderer_source MATCHES "SDL_BindGPUVertexStorageBuffers")
    message(FATAL_ERROR "SDL GPU backend must bind the bone palette as vertex storage")
endif()
if(NOT renderer_source MATCHES "DrawSkinnedTriangles")
    message(FATAL_ERROR "SDL GPU backend must replay a dedicated skinned draw command")
endif()
if(NOT bmd_source MATCHES "RenderSkinnedTriangles")
    message(FATAL_ERROR "BMD meshes must submit rest-pose geometry to the GPU skinning path")
endif()
if(NOT bmd_source MATCHES "EnsureCpuVertices\\(meshIndex\\)")
    message(FATAL_ERROR "BMD must retain CPU-skinned fallback vertices")
endif()
if(NOT bmd_source MATCHES "EnsureCpuNormals\\(meshIndex\\)")
    message(FATAL_ERROR "BMD must retain CPU-skinned fallback normals")
endif()
if(NOT shader_source MATCHES "boneRows")
    message(FATAL_ERROR "Skinned shader must read the bone palette")
endif()
if(NOT shader_source MATCHES "boneScale")
    message(FATAL_ERROR "Skinned shader must preserve BoneScale behavior")
endif()
if(NOT renderer_header MATCHES "SkinningTextureCoordinates")
    message(FATAL_ERROR "GPU skinning contract must carry generated chrome texture coordinates")
endif()
if(NOT bmd_source MATCHES "SkinningTextureCoordinates::Chrome")
    message(FATAL_ERROR "Chrome meshes must remain eligible for GPU skinning")
endif()
if(NOT bmd_source MATCHES "const float colorScale = useBlendMeshColor \\? blendMeshAlpha : 1\\.0f")
    message(FATAL_ERROR "Blend-mesh fades must modulate downstream renderer vertex colors")
endif()
if(NOT bmd_source MATCHES "PackABGR\\(BodyLight\\[0\\] \\* colorScale")
    message(FATAL_ERROR "GPU-skinned vertices must carry the blend-mesh fade in their packed color")
endif()
if(NOT shader_source MATCHES "textureCoordinateMode")
    message(FATAL_ERROR "Skinned shader must select legacy texture-coordinate formulas")
endif()
if(NOT shader_source MATCHES "chromeWave")
    message(FATAL_ERROR "Skinned shader must preserve animated chrome texture coordinates")
endif()
