

CREATE TABLE [dbo].[CustomGift](
	[AccountID] [varchar](10) NOT NULL,
	[Quantity] [int] NOT NULL DEFAULT ((0)),
 CONSTRAINT [PK_CustomGift] PRIMARY KEY CLUSTERED 
(
	[AccountID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


