#pragma once

#ifdef _EDITOR

#include <Windows.h>
#include <string>
#include "ItemStructs.h"
#include "ItemFieldDefs.h"
#include "GameData/Common/FieldMetadataHelper.h"

// ============================================================================
// ITEM-SPECIFIC METADATA
// ============================================================================

// Type alias for backward compatibility
using EItemFieldType = EFieldType;

// Item field descriptor (specialized from generic FieldDescriptor)
using ItemFieldDescriptor = FieldDescriptor<ITEM_ATTRIBUTE>;

// Macro to generate item field descriptors
#define MAKE_SIMPLE_FIELD_DESCRIPTOR(name, type, arraySize, width) \
    { #name, EFieldType::type, offsetof(ITEM_ATTRIBUTE, name), width },

#define MAKE_ARRAY_FIELD_DESCRIPTOR(nameWithIndex, baseName, index, type, width) \
    { #nameWithIndex, EFieldType::type, offsetof(ITEM_ATTRIBUTE, baseName[index]), width },

// Internal: Single static array for all field descriptors (generated by X-macros)
namespace ItemFieldMetadataInternal
{
    static const ItemFieldDescriptor s_descriptors[] = {
        { "Name", EFieldType::WCharArray, offsetof(ITEM_ATTRIBUTE, Name), 150.0f },
        ITEM_FIELDS_SIMPLE(MAKE_SIMPLE_FIELD_DESCRIPTOR)
        ITEM_FIELDS_ARRAYS(MAKE_ARRAY_FIELD_DESCRIPTOR)
    };
}

// Get pointer to field descriptor array
inline const ItemFieldDescriptor* GetFieldDescriptors()
{
    return ItemFieldMetadataInternal::s_descriptors;
}

// Get count of fields (auto-computed from array size)
inline constexpr int GetFieldCount()
{
    return sizeof(ItemFieldMetadataInternal::s_descriptors) / sizeof(ItemFieldDescriptor);
}

// Helper to render an item field by descriptor (uses generic helper)
template<typename TColumns>
inline void RenderFieldByDescriptor(const ItemFieldDescriptor& desc, TColumns* cols, ITEM_ATTRIBUTE& item,
                                     int& colIdx, int itemIndex, bool& rowInteracted, bool isVisible)
{
    ::RenderFieldByDescriptor(desc, cols, item, colIdx, itemIndex, rowInteracted, isVisible, MAX_ITEM_NAME);
}

#endif // _EDITOR
