#pragma once
#define PSW_ONLY_EVENT
#ifdef	PSW_ONLY_EVENT 


// (2007.08.24)
#define PRUARIN_EVENT07_3COLORHARVEST			

// (2008.03.12)
#define CSK_EVENT_CHERRYBLOSSOM							    
#ifdef CSK_EVENT_CHERRYBLOSSOM
	#define ADD_GLOBAL_MIX_MAR08
	#define PSW_EVENT_CHERRYBLOSSOMTREE
	#define PBG_FIX_GOLD_CHERRYBLOSSOMTREE
#endif CSK_EVENT_CHERRYBLOSSOM

	#define PSW_GOLDBOWMAN
	#define PSW_EVENT_LENA
	#define YDG_ADD_GOLDBOWMAN_INVENTORY_SPACE_CHECK

#endif //PSW_ONLY_EVENT