file(READ "${BINDINGS}" bindings)
file(READ "${CONNECTION}" connection)

string(REGEX MATCHALL "inline [^\r\n]+ dotnet_[A-Za-z0-9_]+ =" binding_lines "${bindings}")
foreach(binding IN LISTS binding_lines)
    string(REGEX REPLACE ".* (dotnet_[A-Za-z0-9_]+) =$" "\\1" symbol "${binding}")
    string(FIND "${connection}" "ReResolve(${symbol}," resolver_pos)
    if(resolver_pos EQUAL -1)
        list(APPEND missing "${symbol}")
    endif()
endforeach()

if(missing)
    list(JOIN missing ", " missing_list)
    message(FATAL_ERROR "Packet bindings missing post-load resolution: ${missing_list}")
endif()
