// =============================================================
// Auto-generated by the one-shot DialogImporter tool (removed; see git history).
// Source: Data/Local/Eng/Dialog_eng.bmd (structural fields only)
// =============================================================

#pragma once

namespace GameLogic::Quests::Dialog {

inline constexpr int MaxAnswer = 10;
inline constexpr int MaxDialog = 200;

// I18N::Dialog legacy-id encoding (mirrored the removed DialogImporter tool):
//   text:           legacy_id = dialogIndex                   (0..199)
//   answer (i, n):  legacy_id = 1000 + dialogIndex*10 + slot  (1000..2999)
inline constexpr int AnswerLegacyIdBase = 1000;
inline constexpr int AnswerLegacyIdStride = 10;
inline constexpr int DialogAnswerLegacyId(int dialogIndex, int answerSlot) noexcept
{
    return AnswerLegacyIdBase + dialogIndex * AnswerLegacyIdStride + answerSlot;
}

// One reply branch in a dialog entry. `link` is the dialog index
// the client jumps to when the player picks this reply; `returnCode`
// is the answer code the client sends back to the server.
struct Branch {
    int link;
    int returnCode;
};

// The non-localized half of a dialog entry. The localized NPC line
// and reply labels live in I18N::Dialog (resolved by index via
// I18N::Dialog::Lookup / LookupSlot).
struct Entry {
    int numAnswer;
    Branch answers[MaxAnswer];
};

// Returns the entry for `dialogIndex` (0-based). Out-of-range
// indices return a zero-answer sentinel entry so callers can
// render an empty dialog rather than dereferencing past the table.
const Entry& GetEntry(int dialogIndex) noexcept;

}  // namespace GameLogic::Quests::Dialog
