# Writes the git commit of the source tree into OUTPUT, for the control
# socket's `ping`: which client a test run tested. Runs on every build, but
# writes only when the content changed, so an unchanged commit rebuilds nothing.
#
#   cmake -DSOURCE_DIR=<repo> -DOUTPUT=<header> -P WriteGitCommit.cmake

set(commit "unknown")
set(changed 0)
find_program(GIT_EXECUTABLE git)
if(GIT_EXECUTABLE)
  execute_process(
    COMMAND "${GIT_EXECUTABLE}" rev-parse HEAD
    WORKING_DIRECTORY "${SOURCE_DIR}"
    OUTPUT_VARIABLE head
    OUTPUT_STRIP_TRAILING_WHITESPACE
    RESULT_VARIABLE head_result
    ERROR_QUIET)
  if(head_result EQUAL 0 AND head)
    set(commit "${head}")
    # Tracked files that differ from the commit: the client is not exactly it.
    execute_process(
      COMMAND "${GIT_EXECUTABLE}" status --porcelain --untracked-files=no
      WORKING_DIRECTORY "${SOURCE_DIR}"
      OUTPUT_VARIABLE status
      RESULT_VARIABLE status_result
      ERROR_QUIET)
    if(status_result EQUAL 0 AND NOT status STREQUAL "")
      set(changed 1)
    endif()
  endif()
endif()

set(content "#pragma once\n// Generated by cmake/WriteGitCommit.cmake on every build.\n#define MU_GIT_COMMIT \"${commit}\"\n#define MU_GIT_COMMIT_CHANGED ${changed}\n")
set(old "")
if(EXISTS "${OUTPUT}")
  file(READ "${OUTPUT}" old)
endif()
if(NOT old STREQUAL content)
  file(WRITE "${OUTPUT}" "${content}")
endif()
