#pragma once

namespace SEASON3A
{
	enum eCursedTempleState
	{
		eCursedTempleState_None = 0,
		eCursedTempleState_Wait,
		eCursedTempleState_Ready,
		eCursedTempleState_Play,
		eCursedTempleState_End,
	};
	
	enum eCursedTempleTeam
	{
		eTeam_Allied = 0,
		eTeam_Illusion,
		eTeam_Count,
	};
};

namespace SEASON3B
{
	enum INTERFACE_LIST
	{
		INTERFACE_BEGIN = 0x00,
		INTERFACE_FRIEND,
		INTERFACE_MOVEMAP,
		INTERFACE_PARTY,
		INTERFACE_MYQUEST,
		INTERFACE_NPCQUEST,
		INTERFACE_GUILDINFO,
		INTERFACE_TRADE,
		INTERFACE_STORAGE,
		INTERFACE_MIXINVENTORY,	
		INTERFACE_COMMAND,
		INTERFACE_PET,	
		INTERFACE_NPCSHOP,	
		INTERFACE_INVENTORY,
		INTERFACE_MYSHOP_INVENTORY,
		INTERFACE_PURCHASESHOP_INVENTORY,	
		INTERFACE_CHARACTER,
		INTERFACE_NPCBREEDER,	
		INTERFACE_SERVERDIVISION,
		INTERFACE_DEVILSQUARE,			
		INTERFACE_BLOODCASTLE,
		INTERFACE_NPCGUILDMASTER,
		INTERFACE_GUARDSMAN,
		INTERFACE_SENATUS,
		INTERFACE_GATEKEEPER,
		INTERFACE_GATESWITCH,
		INTERFACE_CATAPULT,
		INTERFACE_REFINERY,
		INTERFACE_REFINERYINFO,
		INTERFACE_KANTURU2ND_ENTERNPC,
		INTERFACE_CURSEDTEMPLE_NPC,
		INTERFACE_CURSEDTEMPLE_GAMESYSTEM,
		INTERFACE_CURSEDTEMPLE_RESULT,
		INTERFACE_CHATINPUTBOX,
		INTERFACE_WINDOW_MENU,
		INTERFACE_OPTION,
		INTERFACE_HELP,
		INTERFACE_ITEM_EXPLANATION,
		INTERFACE_SETITEM_EXPLANATION,
		INTERFACE_QUICK_COMMAND,
		INTERFACE_KANTURU_INFO,
		INTERFACE_CHATLOGWINDOW,
		INTERFACE_PARTY_INFO_WINDOW,
		INTERFACE_BLOODCASTLE_TIME,
		INTERFACE_CHAOSCASTLE_TIME,
		INTERFACE_BATTLE_SOCCER_SCORE,		
		INTERFACE_SLIDEWINDOW,
		INTERFACE_HERO_POSITION_INFO,
		INTERFACE_MESSAGEBOX,
		INTERFACE_DUEL_WINDOW,
		INTERFACE_CRYWOLF,
		INTERFACE_NAME_WINDOW,
		INTERFACE_SIEGEWARFARE,
		INTERFACE_MAINFRAME,
		INTERFACE_SKILL_LIST,
		INTERFACE_ITEM_ENDURANCE_INFO,
		INTERFACE_BUFF_WINDOW,
		INTERFACE_MASTER_LEVEL,
		INTERFACE_GOLD_BOWMAN,
		INTERFACE_GOLD_BOWMAN_LENA,
		INTERFACE_LUCKYCOIN_REGISTRATION,
		INTERFACE_EXCHANGE_LUCKYCOIN,
		INTERFACE_DUELWATCH,
		INTERFACE_DUELWATCH_MAINFRAME,
		INTERFACE_DUELWATCH_USERLIST,
		INTERFACE_INGAMESHOP,
		INTERFACE_DOPPELGANGER_NPC,
		INTERFACE_DOPPELGANGER_FRAME,
		INTERFACE_QUEST_PROGRESS,
		INTERFACE_QUEST_PROGRESS_ETC,
		INTERFACE_EMPIREGUARDIAN_NPC,
		INTERFACE_EMPIREGUARDIAN_TIMER,
		INTERFACE_MINI_MAP,
		INTERFACE_NPC_DIALOGUE,
		INTERFACE_GENSRANKING,
		INTERFACE_UNITEDMARKETPLACE_NPC_JULIA,
		INTERFACE_LUCKYITEMWND,
		INTERFACE_HOTKEY,
		INTERFACE_3DRENDERING_CAMERA_BEGIN,
		INTERFACE_3DRENDERING_CAMERA_END = INTERFACE_3DRENDERING_CAMERA_BEGIN + 24, 
		INTERFACE_ITEM_TOOLTIP,	
		INTERFACE_END,
		INTERFACE_COUNT = INTERFACE_END-2,
	};
}

namespace info
{
	enum InfoTextType
	{
		eInfo_Text_File = 0,
		eInfo_Item_File,
		eInfo_Skill_File,
		eInfo_Slide_File,
		eInfo_Dialog_File,
		eInfo_Credit_File,
		eInfo_Filter_File,
		eInfo_FilterName_File,
		eInfo_MonsterSkill_File,
		eInfo_Movereq_File,
		eInfo_Quest_File,
		eInfo_ItemSetType_File,
		eInfo_ItemSetOption_File,
		eInfo_NpcName_File,
		eInfo_JewelOfHarmonyOption_File,
		eInfo_JewelOfHarmonySmelt_File,
		eInfo_ItemAddOption_File,
		eInfo_File_Count,
	};
};

//scene start
enum ENUM_MUSIC
{
	MUSIC_PUB = 0,
	MUSIC_MUTHEME,
	MUSIC_CHURCH,
	MUSIC_DEVIAS,
	MUSIC_NORIA,
	MUSIC_DUNGEON,
	MUSIC_ATLANS,
	MUSIC_ICARUS,
	MUSIC_TARKAN,
	MUSIC_LOSTTOWER_A,
	MUSIC_LOSTTOWER_B,
	MUSIC_KALIMA,
	MUSIC_CASTLE_PEACE,
	MUSIC_CASTLE_BATTLE_START,
	MUSIC_CASTLE_BATTLE_ING,
	MUSIC_BC_HUNTINGGROUND,
	MUSIC_BC_ADIA,
	MUSIC_BC_CRYWOLF_1ST,
	MUSIC_CRYWOLF_READY,
	MUSIC_CRYWOLF_BEFORE,
	MUSIC_CRYWOLF_BACK,	
	MUSIC_MAIN_THEME,
	MUSIC_KANTURU_1ST,
	MUSIC_KANTURU_2ND,
	MUSIC_KANTURU_MAYA_BATTLE,
	MUSIC_KANTURU_NIGHTMARE_BATTLE,
	MUSIC_KANTURU_TOWER,
	MUSIC_BALGAS_BARRACK,
	MUSIC_BALGAS_REFUGE,
	MUSIC_CURSEDTEMPLE_WAIT,
	MUSIC_CURSEDTEMPLE_GAME,
	MUSIC_ELBELAND,	
	MUSIC_LOGIN_THEME,
	MUSIC_SWAMP_OF_QUIET,
	MUSIC_RAKLION,
	MUSIC_RAKLION_BOSS,
	MUSIC_SANTA_TOWN,
	MUSIC_DUEL_ARENA,
	MUSIC_PKFIELD,
	MUSIC_EMPIREGUARDIAN1,
	MUSIC_EMPIREGUARDIAN2,
	MUSIC_EMPIREGUARDIAN3,
	MUSIC_EMPIREGUARDIAN4,
	MUSIC_DOPPELGANGER,
	MUSIC_UNITEDMARKETPLACE,
	MUSIC_KARUTAN1,
	MUSIC_KARUTAN2,
	NUM_MUSIC
};

enum
{
	MESSAGE_FREE_MSG_NOT_BTN	= 91,
	MESSAGE_GAME_END_COUNTDOWN		,
	MESSAGE_WAIT				= 93,
	MESSAGE_DELETE_CHARACTER_CONFIRM,
	MESSAGE_DELETE_CHARACTER_RESIDENT,
	MESSAGE_DELETE_CHARACTER_SUCCESS,
	MESSAGE_DELETE_CHARACTER_ID_BLOCK,
	MESSAGE_DELETE_CHARACTER_ITEM_BLOCK,
	MESSAGE_SERVER_BUSY,
	MESSAGE_INPUT_ID              = 100,
	MESSAGE_INPUT_PASSWORD        ,
	MESSAGE_INPUT_CONFIRM         ,
	MESSAGE_INPUT_QUIZ            ,
	MESSAGE_INPUT_ANSWER          ,
	MESSAGE_INPUT_NAME            ,
	MESSAGE_INPUT_RESIDENT_NUMBER ,
	MESSAGE_INPUT_PHONE           ,
	MESSAGE_INPUT_EMAIL           ,
	MESSAGE_PASSWORD              ,
	MESSAGE_LOG_OUT               ,	//(110)		// Custom
	MESSAGE_VERSION               ,				// 상규형 
	MESSAGE_SERVER_LOST		      ,				// 상규형
	MESSAGE_DELETE_CHARACTER      ,				// 현재 사용 안함.
	MESSAGE_ID_SPACE_ERROR        ,
	MESSAGE_INPUT_GOLD            ,
	MESSAGE_NOT_ENOUGH_GOLD       ,
	MESSAGE_OVERFLOW_GOLD         ,
	MESSAGE_GUILD                 ,
	MESSAGE_PARTY                 ,
	MESSAGE_TRADE                 ,	//(120)
	MESSAGE_MIN_LENGTH            ,
	MESSAGE_SPECIAL_NAME          ,
	MESSAGE_RESIDENT_NUMBER_ERROR ,		// 현재 사용 안함.
	MESSAGE_INPUT_GUILD           ,
	MESSAGE_DELETE_GUILD          ,
	MESSAGE_NO_GUILD_MARK         ,
	MESSAGE_GUILD_WAR             ,
	MESSAGE_HOMEPAGE1             ,
	MESSAGE_HOMEPAGE2             ,
	MESSAGE_HOMEPAGE3             ,	//(130)
	MESSAGE_DELETE_CHARACTER_WARNING ,
	MESSAGE_BLOCKED_CHARACTER	  ,
	MESSAGE_STORAGE_PASSWORDWRONG ,
	MESSAGE_STORAGE_ALREADYLOCKED ,
	MESSAGE_STORAGE_PASSWORDTOOSIMPLE ,
	MESSAGE_STORAGE_PASSWORDNOTMATCH  ,
	MESSAGE_STORAGE_RESIDENTWRONG ,
	MESSAGE_CUSTOM				  ,
	MESSAGE_DEVILSQUARERANK		  ,
	MESSAGE_SEMI_QUEST            ,	//(140)
	MESSAGE_DIALOG				  ,
	MESSAGE_SELECT_CHAOS		  ,
	MESSAGE_SERVER_IMMIGR_ERROR_RESIDENT,
	MESSAGE_SERVER_IMMIGR_ERROR_DB	    ,

	MESSAGE_PERSONALSHOP		  ,     //. Type 1 : 상점명 입력, Type 2 : 판매가격 입력
	MESSAGE_DELETE_CHARACTER_GUILDWARNING,

	MESSAGE_OPTIONS               ,
	MESSAGE_TRADE_CHECK           ,
	MESSAGE_LOCK_STORAGE          ,
	MESSAGE_USE_STATE             ,	//(150)
	MESSAGE_BLOODCASTLE_RESULT    ,
	MESSAGE_CHECK                 ,
	MESSAGE_PERSONALSHOP_WARNING  ,

	MESSAGE_CHAOS_CASTLE_CHECK    ,     //  카오스 캐슬 입장 체크.
	MESSAGE_CHAOS_CASTLE_RESULT   ,     //  카오스 캐슬 결과.
	MESSAGE_CUSTOM_MESSAGEBOX     ,
	MESSAGE_GEM_INTEGRATION		  ,		//	축석 조합-해체를 위한 인터페이스
	MESSAGE_GEM_INTEGRATION2	  ,
	MESSAGE_GEM_INTEGRATION3	  ,
	MESSAGE_GEM_INTEGRATION4	  ,	//(160)
	MESSAGE_GEM_INTEGRATION5	  ,
	MESSAGE_GEM_INTEGRATION6	  ,
	MESSAGE_WT_MATCH_RESULT       ,		// 경기 결과를 표시하는 다이얼로그
	MESSAGE_USE_STATE2			  ,		//: 열매사용 생성할것인가? 감소할것인가?
	MESSAGE_FENRIR_REPAIR		  ,		// 펜릴의 뿔피리를 수리하시겠습니까?
	MESSAGE_CANCEL_SKILL		  ,		// 스킬을 취소하는 메세지창!
#ifdef PCROOM_EVENT
	MESSAGE_PCROOM_EVENT		  ,
#endif	// PCROOM_EVENT
	MESSAGE_WHITEANGEL_EVENT	  ,	    // 화이트앤젤 이벤트	(이벤트라 아직 미확인)
#ifdef ADD_EXPERIENCE_SERVER
	MESSAGE_PCROOM_POSSIBLE		  ,		// PC방에서만 접속이 가능합니다.	(로그인시)
#endif	// ADD_EXPERIENCE_SERVER
#ifdef PRUARIN_EVENT07_3COLORHARVEST
	MESSAGE_3COLORHARVEST_EVENT		,	// 07년도 3Color & 추석 이벤트
#endif // PRUARIN_EVENT07_3COLORHARVEST
};

/*
#define MESSAGE_GEM_INTEGRATION		  161	//	초기 팝업
#define MESSAGE_GEM_INTEGRATION2	  162	//	조합 상세 질문창
#define MESSAGE_GEM_INTEGRATION3	  163	//	Yes/No
#define MESSAGE_GEM_INTEGRATION4	  164	//	해체 상세 질문창
#define MESSAGE_GEM_INTEGRATION5	  165	//	대기창
#define MESSAGE_GEM_INTEGRATION6	  166	//  성공 출력
#define	MESSAGE_WT_MATCH_RESULT       167	// 경기 결과를 표시하는 다이얼로그
#define MESSAGE_USE_STATE2			  168	//: 열매 생성/감소
#define MESSAGE_FENRIR_REPAIR		  169	// 펜릴 수리
*/

//scene end

//infomation start
/*
enum
{
	STAMINA_WHEEL = 0,
	STAMINA_MULTI_USE,	// 여러 스킬에 공통으로 쓰임
	STAMINA_FURY_STRIKE,
	STAMINA_SWORDFORCE,
	STAMINA_VITALITY,
	STAMINA_COMBINATION,
	MAX_SKILL_STAMINAS
};
*/
enum
{
	SKILL_ABILITY_NONE = 0,
	SKILL_ABILITY_FIRE,
	SKILL_ABILITY_THUNDER,
	SKILL_ABILITY_ICE,
	SKILL_ABILITY_POSION,
	SKILL_ABILITY_EARTH,
	SKILL_ABILITY_WIND,
	SKILL_ABILITY_WATER
};

enum
{
	SKILL_USE_TYPE_NONE = 0,
	SKILL_USE_TYPE_MASTER,			// 1
	SKILL_USE_TYPE_BRAND,			// 2
	SKILL_USE_TYPE_MASTERLEVEL,		// 3
	SKILL_USE_TYPE_MASTERACTIVE,	// 4
};
//infomation end

//character start
enum
{
	CHARACTER_NONE = 0,
	CHARACTER_RENDER_OBJ,
	CHARACTER_ANIMATION
};

enum
{
	RENDER_TYPE_NONE = 0,
	RENDER_TYPE_ALPHA_BLEND,
	RENDER_TYPE_ALPHA_TEST,
	RENDER_TYPE_ALPHA_BLEND_MINUS,
	RENDER_TYPE_ALPHA_BLEND_OTHER,
};
//character end

//object start
enum
{
	//nature
	MODEL_WORLD_OBJECT       = 0,
	MODEL_TREE01             = 0,
	MODEL_GRASS01            = 20,
	MODEL_STONE01            = 30,
	//outside
	MODEL_STONE_STATUE01	 = 40,
	MODEL_STONE_STATUE02	 ,
	MODEL_STONE_STATUE03     ,
	MODEL_STEEL_STATUE       ,
	MODEL_TOMB01             ,
	MODEL_TOMB02             ,
	MODEL_TOMB03             ,
	MODEL_FIRE_LIGHT01  	 = 50,
	MODEL_FIRE_LIGHT02  	 ,
	MODEL_BONFIRE            ,
	MODEL_DUNGEON_GATE  	 = 55,
	MODEL_MERCHANT_ANIMAL01  ,
	MODEL_MERCHANT_ANIMAL02  ,
	MODEL_TREASURE_DRUM  	 ,
	MODEL_TREASURE_CHEST     ,
	MODEL_SHIP               ,
	//wall
	MODEL_STEEL_WALL01       = 65,
	MODEL_STEEL_WALL02       ,
	MODEL_STEEL_WALL03       ,
	MODEL_STEEL_DOOR         ,
	MODEL_STONE_WALL01       ,
	MODEL_STONE_WALL02       ,
	MODEL_STONE_WALL03       ,
	MODEL_STONE_WALL04       ,
	MODEL_STONE_WALL05       ,
	MODEL_STONE_WALL06       ,
	MODEL_MU_WALL01          ,
	MODEL_MU_WALL02          ,
	MODEL_MU_WALL03          ,
	MODEL_MU_WALL04          ,
	MODEL_BRIDGE    	     = 80,
	MODEL_FENCE01     	     ,
	MODEL_FENCE02     	     ,
	MODEL_FENCE03     	     ,
	MODEL_FENCE04     	     ,
	MODEL_BRIDGE_STONE	     ,
	//town
	MODEL_STREET_LIGHT   	 = 90,
	MODEL_CANNON01    	     ,
	MODEL_CANNON02    	     ,
	MODEL_CANNON03    	     ,
	MODEL_CURTAIN    	     = 95,
	MODEL_SIGN01             ,
	MODEL_SIGN02             ,
	MODEL_CARRIAGE01  	     ,
	MODEL_CARRIAGE02  	     ,
	MODEL_CARRIAGE03  	     ,
	MODEL_CARRIAGE04  	     ,
	MODEL_STRAW01 	         ,
	MODEL_STRAW02 	         ,
	MODEL_WATERSPOUT	     = 105,
	MODEL_WELL01 	         ,
	MODEL_WELL02 	         ,
	MODEL_WELL03 	         ,
	MODEL_WELL04 	         ,
	MODEL_HANGING            ,
	MODEL_STAIR              ,
	//house
	MODEL_HOUSE01            = 115,
	MODEL_HOUSE02            ,
	MODEL_HOUSE03            ,
	MODEL_HOUSE04            ,
	MODEL_HOUSE05            ,
	MODEL_TENT               ,
	MODEL_HOUSE_WALL01       ,
	MODEL_HOUSE_WALL02       ,
	MODEL_HOUSE_WALL03       ,
	MODEL_HOUSE_WALL04       ,
	MODEL_HOUSE_WALL05       ,
	MODEL_HOUSE_WALL06       ,
	MODEL_HOUSE_ETC01        ,
	MODEL_HOUSE_ETC02        ,
	MODEL_HOUSE_ETC03        ,
	MODEL_LIGHT01            = 130,
	MODEL_LIGHT02            ,
	MODEL_LIGHT03            ,
	MODEL_POSE_BOX           ,
	//bar
	MODEL_FURNITURE01	     = 140,
	MODEL_FURNITURE02	     ,
	MODEL_FURNITURE03	     ,
	MODEL_FURNITURE04	     ,
	MODEL_FURNITURE05	     ,
	MODEL_FURNITURE06	     ,
	MODEL_FURNITURE07	     ,
	MODEL_CANDLE        	 = 150,
	MODEL_BEER01        	 ,
	MODEL_BEER02        	 ,
	MODEL_BEER03        	 ,
	MODEL_HERO_CHAIR		 ,
	MODEL_HERO_GUARD		 ,
	MODEL_MURDERER_DOG		 ,
	MAX_WORLD_OBJECTS        = 160,
	//logo
	MODEL_LOGO   	         = MAX_WORLD_OBJECTS,
	MODEL_WAVEBYSHIP		 ,
	MODEL_MUGAME			 ,
	MODEL_LOGOSUN		     ,
	MODEL_CARD   	         ,
	MODEL_FACE   	         = MODEL_CARD   	         + 4,
	//animal
	MODEL_BIRD01			 = MODEL_FACE   	         + MAX_CLASS,

	MODEL_BUTTERFLY01		 ,
	MODEL_BAT01			     ,
	MODEL_RAT01		       	 ,
	MODEL_BUG01		         ,
	MODEL_FISH01			 ,
	MODEL_GHOST				 ,
	MODEL_DRAGON			 ,
	MODEL_LOGIN_WARP		 ,
	MODEL_CLOUD              = MODEL_FISH01			     + 9,
#ifdef TAMAJJANG
	MODEL_TAMAJJANG          ,
#endif //TAMAJJANG
	MODEL_CROW               ,
	MODEL_SHINE              ,
	MODEL_EAGLE				 ,
	MODEL_MAP_TORNADO		 ,
	MODEL_GM_CHARACTER,
	MODEL_XMAS_EVENT_CHA_SSANTA,
	MODEL_XMAS_EVENT_CHA_SNOWMAN,
	MODEL_XMAS_EVENT_CHA_DEER,
	MODEL_XMAS_EVENT_CHANGE_GIRL,
	MODEL_XMAS_EVENT_EARRING,
	MODEL_XMAS_EVENT_ICEHEART,
	MODEL_XMAS_EVENT_BOX,
	MODEL_XMAS_EVENT_CANDY,
	MODEL_XMAS_EVENT_TREE,
	MODEL_XMAS_EVENT_SOCKS,
	MODEL_NEWYEARSDAY_EVENT_BEKSULKI,
	MODEL_NEWYEARSDAY_EVENT_CANDY,
	MODEL_NEWYEARSDAY_EVENT_HOTPEPPER_GREEN,
	MODEL_NEWYEARSDAY_EVENT_HOTPEPPER_RED,
	MODEL_NEWYEARSDAY_EVENT_PIG,
	MODEL_NEWYEARSDAY_EVENT_YUT,
	MODEL_NEWYEARSDAY_EVENT_MONEY,
	
#ifdef PRUARIN_EVENT07_3COLORHARVEST
	MODEL_MOONHARVEST_GAM,			// 감
	MODEL_MOONHARVEST_SONGPUEN1,	// 송편1 (흰색)
	MODEL_MOONHARVEST_SONGPUEN2,	// 송편2 (녹색)
	MODEL_MOONHARVEST_MOON,			// 달
#endif // PRUARIN_EVENT07_3COLORHARVEST
	
	MODEL_LIGHTNING_ORB,			// 라이트닝오브 스킬에 쓰이는 구형태의 이펙트를 발생시키기 위해 만든 모델타입(모델데이타는 없음)
	MODEL_CHAIN_LIGHTNING,			// 체인라이트닝 스킬 (모델데이타 없음)
	MODEL_ALICE_BUFFSKILL_EFFECT,	// 버프관련 스킬 쓸 때 나타나는 모델 이펙트
	MODEL_ALICE_BUFFSKILL_EFFECT2,
	MODEL_ALICE_DRAIN_LIFE,			// 드레인 라이프 (모델데이타 없음)
#ifdef CSK_RAKLION_BOSS
	MODEL_RAKLION_BOSS_CRACKEFFECT,	// 라클리온 보스 이펙트중 땅 가라지는 이펙트
	MODEL_RAKLION_BOSS_MAGIC,		// 라클리온 보스 이펙트중 마법진 이펙트
#endif // CSK_RAKLION_BOSS
#ifdef YDG_ADD_SKILL_LIGHTNING_SHOCK
	MODEL_LIGHTNING_SHOCK,			// 라이트닝쇼크 스킬에 쓰이는 구형태의 이펙트를 발생시키기 위해 만든 모델타입(모델데이타는 없음)
#endif	// YDG_ADD_SKILL_LIGHTNING_SHOCK
	MODEL_MOVE_TARGETPOSITION_EFFECT,

	//skill
	MODEL_SKILL_BEGIN  		 ,	
	MODEL_DARK_HORSE         ,
	MODEL_DARK_SPIRIT        ,
	MODEL_ICE		         ,
	MODEL_FIRE               ,
	MODEL_POISON             ,
	MODEL_WOLF               ,
	MODEL_WARCRAFT           ,
	MODEL_UNICON             ,
	MODEL_BLOOD              ,
	MODEL_STONE1             ,
	MODEL_STONE2             ,
	MODEL_ICE_SMALL          ,
	MODEL_CIRCLE             ,
	MODEL_CIRCLE_LIGHT       ,
	MODEL_MAGIC1             ,
	MODEL_MAGIC2             ,
	MODEL_STORM              ,
	MODEL_LASER              ,
	MODEL_SKELETON1          ,
	MODEL_SKELETON2          ,
	MODEL_SKELETON3          ,
	MODEL_SKELETON_PCBANG	 ,		// PC방 이벤트 해골전사 변신반지 모델
	MODEL_HALLOWEEN			 ,		// 할로윈 이벤트 잭 오랜턴 변신반지 모델
	MODEL_HALLOWEEN_EX		 ,
	MODEL_HALLOWEEN_CANDY_BLUE,
	MODEL_HALLOWEEN_CANDY_ORANGE,
	MODEL_HALLOWEEN_CANDY_RED,
	MODEL_HALLOWEEN_CANDY_YELLOW,
	MODEL_HALLOWEEN_CANDY_HOBAK,
	MODEL_HALLOWEEN_CANDY_STAR,
	MODEL_CURSEDTEMPLE_ALLIED_PLAYER,
	MODEL_CURSEDTEMPLE_ILLUSION_PLAYER,
	MODEL_WOOSISTONE		 ,
	MODEL_SAW                ,
	MODEL_BONE1              ,
	MODEL_BONE2              ,
	MODEL_SNOW1              ,
	MODEL_SNOW2              ,
	MODEL_SNOW3              ,
	MODEL_DUNGEON_STONE01    ,
	MODEL_ARROW              ,
	MODEL_ARROW_STEEL        ,
	MODEL_ARROW_THUNDER      ,
	MODEL_ARROW_LASER        ,
	MODEL_ARROW_V            ,
	MODEL_ARROW_SAW          ,
	MODEL_ARROW_NATURE       ,
	MODEL_ARROW_BOMB         ,
	MODEL_ARROW_WING         ,
	MODEL_PROTECT            ,
	MODEL_BIG_STONE1         ,
	MODEL_BIG_STONE2         ,
	MODEL_BIG_METEO1         ,
	MODEL_BIG_METEO2         ,
	MODEL_BIG_METEO3         ,
	MODEL_METEO1             ,
	MODEL_METEO2             ,
	MODEL_MAGIC_CIRCLE1      ,
	MODEL_ARROW_TANKER       ,	// 탱커 공격
	MODEL_ARROW_TANKER_HIT	 ,	// 탱커 땅에 맞을때
	MODEL_BOSS_HEAD          ,
	MODEL_PRINCESS           ,
	MODEL_BALL               ,
	MODEL_BOSS_ATTACK        ,
	MODEL_SKILL_WHEEL1       ,
	MODEL_SKILL_WHEEL2       ,
	MODEL_SKILL_BLAST        ,
	MODEL_SKILL_INFERNO      ,
	MODEL_ARROW_DOUBLE       ,
	MODEL_ARROW_HOLY         ,
	MODEL_ARROW_SPARK        ,
	MODEL_ARROW_RING		 ,
#ifdef ADD_SOCKET_ITEM
	MODEL_ARROW_DARKSTINGER		,		// 다크스팅거 화살 모델
	MODEL_FEATHER,						// 다크 스팅거 깃털 모델
#endif // ADD_SOCKET_ITEM
#ifdef LDK_ADD_PC4_GUARDIAN_EFFECT_IMAGE
	MODEL_FEATHER_FOREIGN,						// 다크 스팅거 깃털 모델
#endif //LDK_ADD_PC4_GUARDIAN_EFFECT_IMAGE
	MODEL_SKILL_FURY_STRIKE  ,
	MODEL_WAVE              = MODEL_SKILL_FURY_STRIKE  +9,
	MODEL_TAIL               ,
	MODEL_PIERCING           ,
	MODEL_WAVE_FORCE        = MODEL_PIERCING           +2,
	MODEL_BLIZZARD	         ,//	내려오는 얼음조각.
	MODEL_MAGIC_CAPSULE2     ,// 법사용 방어막 맞을때
	MODEL_STONE_COFFIN       ,//  석관 파편1. 2.
	MODEL_GATE              = MODEL_STONE_COFFIN       +2,//  성문 파편1. 2.
	MODEL_ARROW_BEST_CROSSBOW= MODEL_GATE              +2,//	절대 석궁 화살.
	MODEL_SPEARSKILL         ,// 기사 창술
	MODEL_PEGASUS            ,//  페가수스.
	MODEL_ARROW_DRILL		 ,//    초절대 석궁 화살.
	MODEL_COMBO				 ,//	콤보 스킬 효과.
	MODEL_AIR_FORCE          ,//    공기 저항 효과.
	MODEL_WAVES              ,//    스트롱 피어의 파장.
	MODEL_PIERCING2          ,//    스트롱 피어 부품.
	MODEL_PIER_PART          ,//    피어싱 부품.
	MODEL_DARKLORD_SKILL     ,//    다크로드 이것저것스킬에 쓰이는것.
	MODEL_GROUND_STONE       ,//    바위.
	MODEL_GROUND_STONE2      ,//    바위2.
	MODEL_WATER_WAVE         ,  //  워터 웨이브 공격
	MODEL_SKULL              ,  //  해골.
	MODEL_LACEARROW			 ,  //	레이스 에로우
	MODEL_CUNDUN_PART1		 ,  //  쿤둔 조각1
	MODEL_CUNDUN_PART2		 ,  //  쿤둔 조각2
	MODEL_CUNDUN_PART3		 ,  //  쿤둔 조각3
	MODEL_CUNDUN_PART4		 ,  //  쿤둔 조각4
	MODEL_CUNDUN_PART5		 ,  //  쿤둔 조각5
	MODEL_CUNDUN_PART6		 ,  //  쿤둔 조각6
	MODEL_CUNDUN_PART7		 ,  //  쿤둔 조각7
	MODEL_CUNDUN_PART8		 ,  //  쿤둔 조각8
	MODEL_CUNDUN_DRAGON_HEAD ,  //  쿤둔 용머리
	MODEL_CUNDUN_PHOENIX	 ,  //  쿤둔 불새
	MODEL_CUNDUN_GHOST		 ,  //  쿤둔 도망가는 혼
	MODEL_CUNDUN_SKILL		 ,  //  쿤둔 스킬용 (데이터 없음)
	MODEL_MANY_FLAG          ,  //  중국 경극에서 사용되는 깃발.
	MODEL_WEBZEN_MARK        ,  //  웹젠마크.
	MODEL_FLY_BIG_STONE1     ,  //  투석기의 무기 ( 공성측 ).
	MODEL_FLY_BIG_STONE2     ,  //  투석기의 무기 ( 수성측 ).
	MODEL_BIG_STONE_PART1    ,  //  투석기 무기 파편1.
	MODEL_BIG_STONE_PART2    ,  //  투석기 무기 판편2.
	MODEL_WALL_PART1         ,  //  성벽 파편1.
	MODEL_WALL_PART2         ,  //  성벽 파편2.
	MODEL_GATE_PART1         ,  //  성문 파편1.
	MODEL_GATE_PART2         ,  //  성문 파편2.
	MODEL_GATE_PART3         ,  //  성문 파편3.
	MODEL_AURORA             ,  //  회복 영역 표시.
	MODEL_TOWER_GATE_PLANE   ,  //  이동 공간.
	MODEL_STUN_STONE         ,  //  스턴을 위한 돌1.
	MODEL_SKIN_SHELL         ,  //  스킨 파편 조각.
	MODEL_MANA_RUNE          ,  //  마나 증가 룬.
	MODEL_SKILL_JAVELIN      ,  //  표창.
	MODEL_ARROW_IMPACT       ,  //  강력한 한방.
	MODEL_SWORD_FORCE        ,  //  
	MODEL_GOLEM_STONE		 ,	// 골렘 파편
	MODEL_FISSURE			 ,	// 지면 균열
	MODEL_FISSURE_LIGHT		 ,  // 지면 균열 빛
	MODEL_SKILL_FISSURE		 ,	// 사냥터 보스 전체마법
	MODEL_PROTECTGUILD       ,  // 수호길드
	MODEL_TREE_ATTACK		 ,  //  아이다 데쓰트리 공격
	MODEL_WARP				 ,	//  노리아 -> 아이다, 라클리온 -> 영웅탑 
	MODEL_WARP2				 ,	//  노리아 -> 아이다, 라클리온 -> 영웅탑
	MODEL_WARP3				 ,	//  노리아 -> 아이다, 라클리온 -> 영웅탑
#ifdef CSK_ADD_MAP_ICECITY
	MODEL_WARP4				 ,	//  라클리온 -> 라클리온 보스맵
	MODEL_WARP5				 ,	//  라클리온 -> 라클리온 보스맵
	MODEL_WARP6				 ,	//  라클리온 -> 라클리온 보스맵
#endif // CSK_ADD_MAP_ICECITY
	MODEL_DARK_ELF_SKILL	,
	MODEL_BALGAS_SKILL		,
	MODEL_DEATH_SPI_SKILL	,
	MODEL_SCOLPION			,
	MODEL_BUG_CRY1ST		,
	MODEL_FENRIR_BLACK		,	// 펜릴 검정
	MODEL_FENRIR_RED		,	// 펜릴 빨강
	MODEL_FENRIR_BLUE		,	// 펜릴 파랑
	MODEL_FENRIR_GOLD		,	// 펜릴 골드
	MODEL_FENRIR_THUNDER	,	// 펜릴 몸 주위에 번개줄기, 엘리스 체인라이트닝 손 번개효과
	MODEL_FENRIR_FOOT_THUNDER	,	// 펜릴 발바닥 번개
	MODEL_FENRIR_SKILL_THUNDER	,	// 펜릴 스킬 쓰면 번개줄기
	MODEL_FENRIR_SKILL_DAMAGE	,	// 펜릴 스킬 맞으면 타격 이펙트
	MODEL_ARROW_AUTOLOAD		,	// 화살 무한사용 (AT_INFINITY_ARROW) 이펙트 사용
	MODEL_SHIELD_CRASH			,	// 실드 파괴 이펙트
	MODEL_SHIELD_CRASH2			,	// 실드 파괴 이펙트2
	MODEL_INFINITY_ARROW		,	// 무한사용 새 이펙트
	MODEL_INFINITY_ARROW1		,
	MODEL_INFINITY_ARROW2		,
	MODEL_INFINITY_ARROW3		,
	MODEL_INFINITY_ARROW4		,
	MODEL_IRON_RIDER_ARROW		,
	MODEL_KENTAUROS_ARROW		,
	MODEL_BLADE_SKILL			,
	MODEL_TWINTAIL_EFFECT		,	// 칸투르 2차 몬스터 트윈테일 머리발바닥 효과
	MODEL_STORM2				,   //  칸투르 3차 보스몹 나이트메어 스톰 스킬
	MODEL_SUMMON				,   //  칸투르 3차 보스몹 나이트메어 소환 스킬
	MODEL_STORM3				,	//  칸투르 3차 마야 회오리 스킬
	MODEL_MAYASTAR				,	//  칸투르 3차 마야 죽을때 빛
	MODEL_MAYASTONE1			,	//  칸투르 3차 마야 크리스탈 스킬중 떨어지는 크리스탈1
	MODEL_MAYASTONE2			,	//  칸투르 3차 마야 크리스탈 스킬중 떨어지는 크리스탈2
	MODEL_MAYASTONE3			,	//  칸투르 3차 마야 크리스탈 스킬중 떨어지는 크리스탈3
	MODEL_MAYASTONE4			,	//  칸투르 3차 마야 크리스탈 스킬중 크리스탈 작은 조각1
	MODEL_MAYASTONE5			,	//  칸투르 3차 마야 크리스탈 스킬중 크리스탈 작은 조각2
	MODEL_MAYASTONEFIRE			,	//  칸투르 3차 마야 크리스탈 스킬중 떨어지는 크리스탈의 불 효과
	MODEL_MAYAHANDSKILL			,	//  칸투르 3차 마야손 스킬
	MODEL_DARK_SCREAM			,	// 다크로드 파이어스크림
	MODEL_DARK_SCREAM_FIRE		,	// 다크로드 파이어스크림
	MODEL_CURSEDTEMPLE_HOLYITEM ,
	MODEL_CURSEDTEMPLE_PRODECTION_SKILL ,
	MODEL_CURSEDTEMPLE_RESTRAINT_SKILL ,
	MODEL_FALL_STONE_EFFECT,
	MODEL_CURSEDTEMPLE_STATUE_PART1,
	MODEL_CURSEDTEMPLE_STATUE_PART2,
	MODEL_CHANGE_UP_EFF,
	MODEL_CHANGE_UP_NASA,
	MODEL_CHANGE_UP_CYLINDER,	
	MODEL_TOTEMGOLEM_PART1,
	MODEL_TOTEMGOLEM_PART2,
	MODEL_TOTEMGOLEM_PART3,
	MODEL_TOTEMGOLEM_PART4,
	MODEL_TOTEMGOLEM_PART5,
	MODEL_TOTEMGOLEM_PART6,
	MODEL_SUMMONER_WRISTRING_EFFECT,	// 손목 링 이펙트 모델
	MODEL_SUMMONER_EQUIP_HEAD_SAHAMUTT,	// 사하무트 머리 회전
	MODEL_SUMMONER_EQUIP_HEAD_NEIL,		// 닐 머리 회전
#ifdef ASG_ADD_SUMMON_RARGLE
	MODEL_SUMMONER_EQUIP_HEAD_LAGUL,	// 라글 머리 회전
#endif	// ASG_ADD_SUMMON_RARGLE
	MODEL_SUMMONER_CASTING_EFFECT1,		// 소환 시전 이펙트
	MODEL_SUMMONER_CASTING_EFFECT11,	// 소환 시전 이펙트
	MODEL_SUMMONER_CASTING_EFFECT111,	// 소환 시전 이펙트
	MODEL_SUMMONER_CASTING_EFFECT2,		// 소환 시전 이펙트
	MODEL_SUMMONER_CASTING_EFFECT22,	// 소환 시전 이펙트
	MODEL_SUMMONER_CASTING_EFFECT222,	// 소환 시전 이펙트
	MODEL_SUMMONER_CASTING_EFFECT4,		// 소환 시전 이펙트
	MODEL_SUMMONER_SUMMON_SAHAMUTT,		// 사하무트
	MODEL_SUMMONER_SUMMON_NEIL,			// 닐
#ifdef ASG_ADD_SUMMON_RARGLE
	MODEL_SUMMONER_SUMMON_LAGUL,		// 라글
#endif	// ASG_ADD_SUMMON_RARGLE
	MODEL_SUMMONER_SUMMON_NEIL_NIFE1,	// 닐 스킬 이펙트 칼
	MODEL_SUMMONER_SUMMON_NEIL_NIFE2,	// 닐 스킬 이펙트 칼
	MODEL_SUMMONER_SUMMON_NEIL_NIFE3,	// 닐 스킬 이펙트 칼
	MODEL_SUMMONER_SUMMON_NEIL_GROUND1,	// 닐 스킬 이펙트 바닥
	MODEL_SUMMONER_SUMMON_NEIL_GROUND2,	// 닐 스킬 이펙트 바닥
	MODEL_SUMMONER_SUMMON_NEIL_GROUND3,	// 닐 스킬 이펙트 바닥
	MODEL_SHADOW_PAWN_ANKLE_LEFT,	// 새도우 폰
	MODEL_SHADOW_PAWN_ANKLE_RIGHT,
	MODEL_SHADOW_PAWN_BELT,
	MODEL_SHADOW_PAWN_CHEST,
	MODEL_SHADOW_PAWN_HELMET,
	MODEL_SHADOW_PAWN_KNEE_LEFT,
	MODEL_SHADOW_PAWN_KNEE_RIGHT,
	MODEL_SHADOW_PAWN_WRIST_LEFT,
	MODEL_SHADOW_PAWN_WRIST_RIGHT,

	MODEL_SHADOW_KNIGHT_ANKLE_LEFT,	// 새도우 나이트 사망 몸뚱이
	MODEL_SHADOW_KNIGHT_ANKLE_RIGHT,
	MODEL_SHADOW_KNIGHT_BELT,
	MODEL_SHADOW_KNIGHT_CHEST,
	MODEL_SHADOW_KNIGHT_HELMET,
	MODEL_SHADOW_KNIGHT_KNEE_LEFT,
	MODEL_SHADOW_KNIGHT_KNEE_RIGHT,
	MODEL_SHADOW_KNIGHT_WRIST_LEFT,
	MODEL_SHADOW_KNIGHT_WRIST_RIGHT,

	MODEL_SHADOW_ROOK_ANKLE_LEFT,	// 새도우 룩 사망 몸뚱이
	MODEL_SHADOW_ROOK_ANKLE_RIGHT,
	MODEL_SHADOW_ROOK_BELT,
	MODEL_SHADOW_ROOK_CHEST,
	MODEL_SHADOW_ROOK_HELMET,
	MODEL_SHADOW_ROOK_KNEE_LEFT,
	MODEL_SHADOW_ROOK_KNEE_RIGHT,
	MODEL_SHADOW_ROOK_WRIST_LEFT,
	MODEL_SHADOW_ROOK_WRIST_RIGHT,
	
#ifdef ADD_RAKLION_MOB_ICEGIANT
	MODEL_ICE_GIANT_PART1,			// 아이스 자이언트 사망시 몸 조각.
	MODEL_ICE_GIANT_PART2,
	MODEL_ICE_GIANT_PART3,
	MODEL_ICE_GIANT_PART4,
	MODEL_ICE_GIANT_PART5,
	MODEL_ICE_GIANT_PART6,
#endif	// ADD_RAKLION_MOB_ICEGIANT

	MODEL_EFFECT_SAPITRES_ATTACK,		// 사피트레스 공격 이팩트(BMD없음)
	MODEL_EFFECT_SAPITRES_ATTACK_1,		// 사피트레스 가시 공격 모델
	MODEL_EFFECT_SAPITRES_ATTACK_2,		// 사피트레스 가시 사방으로 날리기 모델
	MODEL_EFFECT_THUNDER_NAPIN_ATTACK_1,	// 썬더네이핀 썬더 에너지볼(BMD없음)
#ifdef CSK_EVENT_CHERRYBLOSSOM
	MODEL_EFFECT_SKURA_ITEM,      // 벚꽃 이벤트 이펙트
#endif //CSK_EVENT_CHERRYBLOSSOM	
#ifdef ADD_RAKLION_IRON_KNIGHT
	MODEL_EFFECT_BROKEN_ICE0,
	MODEL_EFFECT_BROKEN_ICE1,
	MODEL_EFFECT_BROKEN_ICE2,
	MODEL_EFFECT_BROKEN_ICE3,
#endif	// ADD_RAKLION_IRON_KNIGHT
#ifdef KJH_ADD_09SUMMER_EVENT
	MODEL_EFFECT_UMBRELLA_LIGHT,
#endif // KJH_ADD_09SUMMER_EVENT
#ifdef PJH_SEASON4_DARK_NEW_SKILL_CAOTIC
	MODEL_DESAIR,
#endif //SKILL_DEBUG
#ifdef ADD_SOCKET_ITEM	
	// [잔상이팩트] (BMD없음)
	//* 무기종류의 잔상을 사용할때(BITMAP_JOINT_ENERGY) zzzCharacter::RenderCharacer()에서 CreateJoint()를 호출하는데,
	//* CreateJoint()의 인자인 OBJECT는 캐릭터의 Object를 넘긴다.
	//* 이는 같은 잔상이펙트 서브타입 을 사용하는 무기가 두가지 동시에 겹쳤을시에, 서로 꼬이게 된다.
	//* ex) BITMAP_JOINT_ENERGY Subtype 17번,
	//* 따라서 CreateEffect()를 호출하여, 이 안에서 CreateJoint()를 호출하여 OBJECT의 인자로 Effect의 Object를 넘기면 된다.
	MODEL_EFFECT_TRACE,
	MODEL_STAR_SHINE,			// 별 모양 반짝이기 (반짝반짝 작은별!!)
#endif // ADD_SOCKET_ITEM
#ifdef CSK_ADD_SKILL_BLOWOFDESTRUCTION
	MODEL_BLOW_OF_DESTRUCTION,			// 흑기사 파괴의 일격 이펙트(BMD없음)
	MODEL_NIGHTWATER_01,				// 흑기사 파괴의 일격 이펙트
	MODEL_KNIGHT_PLANCRACK_A,			// 흑기사 파괴의 일격 이펙트
	MODEL_KNIGHT_PLANCRACK_B,			// 흑기사 파괴의 일격 이펙트
#endif // CSK_ADD_SKILL_BLOWOFDESTRUCTION
#ifdef KJH_ADD_SKILL_SWELL_OF_MAGICPOWER
	MODEL_SWELL_OF_MAGICPOWER,			// 흑마법사(소울마스터) "마력증대"
	MODEL_SWELL_OF_MAGICPOWER_GUIDE,	// 흑마법사(소울마스터) "마력증대" (에니메이션위치 저장)
	MODEL_ARROWSRE06,					// 흑마법사(소울마스터) "마력증대" 팔에 붙는 이팩트모델
	MODEL_SWELL_OF_MAGICPOWER_BUFF_EFF,	// 흑마법사(소울마스터) "마력증대" 버프중 이팩트
#endif // KJH_ADD_SKILL_SWELL_OF_MAGICPOWER
#ifdef YDG_ADD_SKILL_FLAME_STRIKE
	MODEL_EFFECT_FLAME_STRIKE,			// 마검사 플레임스트라이크 이펙트
#endif	// YDG_ADD_SKILL_FLAME_STRIKE
#ifdef LDS_RAKLION_ADDMONSTER_ICEWALKER
	MODEL_STREAMOFICEBREATH,			// 라클리온 아이스워커 Attack2 이펙트 입김(별반짝)
#endif // LDS_RAKLION_ADDMONSTER_ICEWALKER
#ifdef LDS_RAKLION_ADDMONSTER_COOLERTIN
	MODEL_1_STREAMBREATHFIRE,			// 라클리온 쿨러틴 입김 파이어 한개 발사
#endif // LDS_RAKLION_ADDMONSTER_COOLERTIN
#ifdef LDK_ADD_GAMBLERS_WEAPONS
	MODEL_ARROW_GAMBLE,					// 겜블 보우 화살
#endif //LDK_ADD_GAMBLERS_WEAPONS
#ifdef PBG_ADD_PKFIELD
	MODEL_PKFIELD_ASSASSIN_EFFECT_GREEN_HEAD,		// PK필드 암살자 이펙트
	MODEL_PKFIELD_ASSASSIN_EFFECT_RED_HEAD,
	MODEL_PKFIELD_ASSASSIN_EFFECT_GREEN_BODY,
	MODEL_PKFIELD_ASSASSIN_EFFECT_RED_BODY,
	MODEL_LAVAGIANT_FOOTPRINT_R,
	MODEL_LAVAGIANT_FOOTPRINT_V,
#endif //PBG_ADD_PKFIELD
#ifdef LDS_ADD_GOLDCORPS_EVENT_MOD_GREATDRAGON
	MODEL_EFFECT_FIRE_HIK3_MONO,					// 황금 군단의 황금 그레이트 드래곤 비주얼 이펙트. 
#endif // LDS_ADD_GOLDCORPS_EVENT_MOD_GREATDRAGON
#ifdef LDS_ADD_EMPIRE_GUARDIAN
	MODEL_PROJECTILE,		//제국 수호군 이펙트 - 투석기 발사체
	MODEL_DOOR_CRUSH_EFFECT,			//성문 파괴 이펙트
	MODEL_DOOR_CRUSH_EFFECT_PIECE01,	//성문 파괴 이펙트 조각 1
	MODEL_DOOR_CRUSH_EFFECT_PIECE02,	//성문 파괴 이펙트 조각 2
	MODEL_DOOR_CRUSH_EFFECT_PIECE03,	//성문 파괴 이펙트 조각 3
	MODEL_DOOR_CRUSH_EFFECT_PIECE04,	//성문 파괴 이펙트 조각 4
	MODEL_DOOR_CRUSH_EFFECT_PIECE05,	//성문 파괴 이펙트 조각 5
	MODEL_DOOR_CRUSH_EFFECT_PIECE06,	//성문 파괴 이펙트 조각 6
	MODEL_DOOR_CRUSH_EFFECT_PIECE07,	//성문 파괴 이펙트 조각 7
	MODEL_DOOR_CRUSH_EFFECT_PIECE08,	//성문 파괴 이펙트 조각 8
	MODEL_DOOR_CRUSH_EFFECT_PIECE09,	//성문 파괴 이펙트 조각 9
	MODEL_DOOR_CRUSH_EFFECT_PIECE10,	// 주말 성문 파괴 이펙트 조각1 잔해
	MODEL_DOOR_CRUSH_EFFECT_PIECE11,	// 주말 성문 파괴 이펙트 조각2
	MODEL_DOOR_CRUSH_EFFECT_PIECE12,	// 주말 성문 파괴 이펙트 조각3
	MODEL_DOOR_CRUSH_EFFECT_PIECE13,	// 주말 성문 파괴 이펙트 조각4
	MODEL_STATUE_CRUSH_EFFECT,			//석상 파괴 이펙트
	MODEL_STATUE_CRUSH_EFFECT_PIECE01,	//석상 파괴 이펙트 조각 1
	MODEL_STATUE_CRUSH_EFFECT_PIECE02,	//석상 파괴 이펙트 조각 2
	MODEL_STATUE_CRUSH_EFFECT_PIECE03,	//석상 파괴 이펙트 조각 3
	MODEL_STATUE_CRUSH_EFFECT_PIECE04,	//석상 파괴 이펙트 조각 4 잔해
#endif //LDS_ADD_EMPIRE_GUARDIAN
#ifdef PJH_ADD_PANDA_CHANGERING
	MODEL_PANDA,			//
#endif //PJH_ADD_PANDA_CHANGERING
#ifdef LDS_ADD_EG_4_MONSTER_WORLDBOSS_GAIONKALEIN		// 제국 수호군 막보가이온 이펙트
	MODEL_EMPIREGUARDIANBOSS_SKILLEFF01_GENERALATTACK,	// 제국 수호군 막보가이온 1 스킬 (일반 공격)
	MODEL_EMPIREGUARDIANBOSS_SKILLEFF02_BLOODATTACK,	// 제국 수호군 막보가이온 2 스킬 (블러드 어택)
	MODEL_EMPIREGUARDIANBOSS_SKILLEFF03_GIGANTIC,		// 제국 수호군 막보가이온 3 스킬 (기간틱)
	MODEL_EMPIREGUARDIANBOSS_SKILLEFF04_FRAMESTRIKE,	// 제국 수호군 막보가이온 4 스킬 (프레임스트라이크)
	MODEL_SWORDLEFT01_EMPIREGUARDIAN_BOSS_GAION_,		// 제국 수호군 막보가이온 ONE OF 5SWORDS
	MODEL_SWORDLEFT02_EMPIREGUARDIAN_BOSS_GAION_,		// 제국 수호군 막보가이온 ONE OF 5SWORDS
	MODEL_SWORDRIGHT01_EMPIREGUARDIAN_BOSS_GAION_,		// 제국 수호군 막보가이온 ONE OF 5SWORDS
	MODEL_SWORDRIGHT02_EMPIREGUARDIAN_BOSS_GAION_,		// 제국 수호군 막보가이온 ONE OF 5SWORDS
	MODEL_SWORDMAIN01_EMPIREGUARDIAN_BOSS_GAION_,		// 제국 수호군 막보가이온 ONE OF 5SWORDS
#endif // LDS_ADD_EG_4_MONSTER_WORLDBOSS_GAIONKALEIN
#ifdef LDS_ADD_EG_4_MONSTER_JELINT	
	MODEL_EMPIREGUARDIAN_BLOW_OF_DESTRUCTION,			// 제국 수호군 "파괴의 일격" 리뉴얼 이펙트
#endif // LDS_ADD_EG_4_MONSTER_JELINT
#ifdef KJH_ADD_09SUMMER_EVENT
	MODEL_EFFECT_UMBRELLA_DIE,							// 우산몬스터 죽을때 이팩트(BMD없음)
	MODEL_EFFECT_UMBRELLA_GOLD,							// 우산몬스터 금덩어리 이팩트
#endif // KJH_ADD_09SUMMER_EVENT
#ifdef PBG_ADD_CHARACTERSLOT
	MODEL_SLOT_LOCK,									// 캐릭터 선택창의 자물쇠
#endif //PBG_ADD_CHARACTERSLOT
#ifdef YDG_ADD_DOPPELGANGER_MONSTER
	MODEL_DOPPELGANGER_SLIME_CHIP,		// 도플갱어 슬라임 폭발할때 젤리 덩어리
#endif	// YDG_ADD_DOPPELGANGER_MONSTER
#ifdef LDS_ADD_EG_4_MONSTER_WORLDBOSS_GAIONKALEIN
	MODEL_EMPIREGUARDIANBOSS_FRAMESTRIKE,
#endif // LDS_ADD_EG_4_MONSTER_WORLDBOSS_GAIONKALEIN
#ifdef LDK_ADD_EG_MONSTER_DEASULER
	MODEL_DEASULER,
#endif //LDK_ADD_EG_MONSTER_DEASULER
#ifdef KJH_ADD_EG_MONSTER_GUARDIANDEFENDER_EFFECT		
	MODEL_EFFECT_EG_GUARDIANDEFENDER_ATTACK2,			// 제국수호군 방패병 공격2 이팩트
#endif // KJH_ADD_EG_MONSTER_GUARDIANDEFENDER_EFFECT
#ifdef PBG_ADD_AURA_EFFECT
	MODEL_EFFECT_SD_AURA,									// SD증가 이펙트
#endif //PBG_ADD_AURA_EFFECT
#ifdef YDG_ADD_SKELETON_CHANGE_RING
	MODEL_SKELETON_CHANGED,								// 스켈레톤 변신
#endif	// YDG_ADD_SKELETON_CHANGE_RING
#ifdef LDK_ADD_14_15_GRADE_ITEM_MODEL
	MODEL_15GRADE_ARMOR_OBJ_ARMLEFT,					// 14, 15등급 방어구용 모델 왼팔
	MODEL_15GRADE_ARMOR_OBJ_ARMRIGHT,					// 14, 15등급 방어구용 모델 오른팔
	MODEL_15GRADE_ARMOR_OBJ_BODYLEFT,					// 14, 15등급 방어구용 모델 갑옷왼쪽
	MODEL_15GRADE_ARMOR_OBJ_BODYRIGHT,					// 14, 15등급 방어구용 모델 갑옷오른쪽
	MODEL_15GRADE_ARMOR_OBJ_BOOTLEFT,					// 14, 15등급 방어구용 모델 왼발
	MODEL_15GRADE_ARMOR_OBJ_BOOTRIGHT,					// 14, 15등급 방어구용 모델 오른발
	MODEL_15GRADE_ARMOR_OBJ_HEAD,						// 14, 15등급 방어구용 모델 머리
	MODEL_15GRADE_ARMOR_OBJ_PANTLEFT,					// 14, 15등급 방어구용 모델 바지왼쪽
	MODEL_15GRADE_ARMOR_OBJ_PANTRIGHT,					// 14, 15등급 방어구용 모델 바지오른쪽
#endif //LDK_ADD_14_15_GRADE_ITEM_MODEL
#ifdef LDS_EXTENSIONMAP_MONSTERS_SWAMPOFQUIET		
	MODEL_EX01_SHADOW_MASTER_ANKLE_LEFT,				// 확장맵 : 평온의 늪 쉐도우 마스터 (쉐도우 룩 동일) DIE EFFECT
	MODEL_EX01_SHADOW_MASTER_ANKLE_RIGHT,
	MODEL_EX01_SHADOW_MASTER_BELT,
	MODEL_EX01_SHADOW_MASTER_CHEST,
	MODEL_EX01_SHADOW_MASTER_HELMET,
	MODEL_EX01_SHADOW_MASTER_KNEE_LEFT,
	MODEL_EX01_SHADOW_MASTER_KNEE_RIGHT,
	MODEL_EX01_SHADOW_MASTER_WRIST_LEFT,
	MODEL_EX01_SHADOW_MASTER_WRIST_RIGHT,
#endif // LDS_EXTENSIONMAP_MONSTERS_SWAMPOFQUIET

#ifdef ASG_ADD_KARUTAN_MONSTERS
	MODEL_CONDRA_ARM_L,		// 콘드라 죽는 이펙트 몸 조각
	MODEL_CONDRA_ARM_L2,	// 콘드라 죽는 이펙트 몸 조각
	MODEL_CONDRA_SHOULDER,	// 콘드라 죽는 이펙트 몸 조각
	MODEL_CONDRA_ARM_R,		// 콘드라 죽는 이펙트 몸 조각
	MODEL_CONDRA_ARM_R2,	// 콘드라 죽는 이펙트 몸 조각
	MODEL_CONDRA_CONE_L,	// 콘드라 죽는 이펙트 몸 조각
	MODEL_CONDRA_CONE_R,	// 콘드라 죽는 이펙트 몸 조각
	MODEL_CONDRA_PELVIS,	// 콘드라 죽는 이펙트 몸 조각
	MODEL_CONDRA_STOMACH,	// 콘드라 죽는 이펙트 몸 조각
	MODEL_CONDRA_NECK,		// 콘드라 죽는 이펙트 몸 조각
	MODEL_CONDRA_STONE,		// 콘드라 죽는 이펙트 돌 조각
	MODEL_CONDRA_STONE1,	// 콘드라 죽는 이펙트 돌 조각
	MODEL_CONDRA_STONE2,	// 콘드라 죽는 이펙트 돌 조각
	MODEL_CONDRA_STONE3,	// 콘드라 죽는 이펙트 돌 조각
	MODEL_CONDRA_STONE4,	// 콘드라 죽는 이펙트 돌 조각
	MODEL_CONDRA_STONE5,	// 콘드라 죽는 이펙트 돌 조각

	MODEL_NARCONDRA_ARM_L,		// 나르콘드라 죽는 이펙트 몸 조각
	MODEL_NARCONDRA_ARM_L2,		// 나르콘드라 죽는 이펙트 몸 조각
	MODEL_NARCONDRA_SHOULDER_L,	// 나르콘드라 죽는 이펙트 몸 조각
	MODEL_NARCONDRA_SHOULDER_R,	// 나르콘드라 죽는 이펙트 몸 조각
	MODEL_NARCONDRA_ARM_R,		// 나르콘드라 죽는 이펙트 몸 조각
	MODEL_NARCONDRA_ARM_R2,		// 나르콘드라 죽는 이펙트 몸 조각
	MODEL_NARCONDRA_ARM_R3,		// 나르콘드라 죽는 이펙트 몸 조각
	MODEL_NARCONDRA_CONE_1,		// 나르콘드라 죽는 이펙트 몸 조각
	MODEL_NARCONDRA_CONE_2,		// 나르콘드라 죽는 이펙트 몸 조각
	MODEL_NARCONDRA_CONE_3,		// 나르콘드라 죽는 이펙트 몸 조각
	MODEL_NARCONDRA_CONE_4,		// 나르콘드라 죽는 이펙트 몸 조각
	MODEL_NARCONDRA_CONE_5,		// 나르콘드라 죽는 이펙트 몸 조각
	MODEL_NARCONDRA_CONE_6,		// 나르콘드라 죽는 이펙트 몸 조각
	MODEL_NARCONDRA_PELVIS,		// 나르콘드라 죽는 이펙트 몸 조각
	MODEL_NARCONDRA_STOMACH,	// 나르콘드라 죽는 이펙트 몸 조각
	MODEL_NARCONDRA_NECK,		// 나르콘드라 죽는 이펙트 몸 조각
	MODEL_NARCONDRA_STONE,		// 나르콘드라 죽는 이펙트 돌 조각
	MODEL_NARCONDRA_STONE1,		// 나르콘드라 죽는 이펙트 돌 조각
	MODEL_NARCONDRA_STONE2,		// 나르콘드라 죽는 이펙트 돌 조각
	MODEL_NARCONDRA_STONE3,		// 나르콘드라 죽는 이펙트 돌 조각
#endif	// ASG_ADD_KARUTAN_MONSTERS

#ifdef PBG_ADD_NEWCHAR_MONK_ITEM
	MODEL_SWORD_32_LEFT,
	MODEL_SWORD_32_RIGHT,
	MODEL_SWORD_33_LEFT,
	MODEL_SWORD_33_RIGHT,
	MODEL_SWORD_34_LEFT,
	MODEL_SWORD_34_RIGHT,
	MODEL_WOLF_HEAD_EFFECT,
	MODEL_ARMORINVEN_60,
	MODEL_ARMORINVEN_61,
	MODEL_ARMORINVEN_62,
	MODEL_DOWN_ATTACK_DUMMY_L,
	MODEL_DOWN_ATTACK_DUMMY_R,
	MODEL_SHOCKWAVE01,
	MODEL_SHOCKWAVE02,
	MODEL_SHOCKWAVE_SPIN01,
	MODEL_WINDFOCE,
	MODEL_WINDFOCE_MIRROR,
	MODEL_WOLF_HEAD_EFFECT2,
	MODEL_SHOCKWAVE_GROUND01,
	MODEL_DRAGON_KICK_DUMMY,
	MODEL_DRAGON_LOWER_DUMMY,
	MODEL_TARGETMON_EFFECT,
	MODEL_SHOCKWAVE03,
	MODEL_VOLCANO_OF_MONK,
	MODEL_VOLCANO_STONE,
#endif //PBG_ADD_NEWCHAR_MONK_ITEM

	MODEL_SKILL_END
};

enum 
{
	//npc
	MODEL_NPC_BEGIN = MODEL_MONSTER_END,
	MODEL_MERCHANT_FEMALE,
	MODEL_MERCHANT_MAN   ,
	MODEL_MERCHANT_GIRL  ,
	MODEL_SMITH          ,
	MODEL_SCIENTIST      ,
	MODEL_SNOW_MERCHANT  ,
	MODEL_SNOW_SMITH     ,
	MODEL_SNOW_WIZARD    ,
	MODEL_ELF_WIZARD     ,
	MODEL_ELF_MERCHANT   ,
	MODEL_MASTER         ,
	MODEL_STORAGE        ,
	MODEL_TOURNAMENT     ,
	MODEL_MIX_NPC        ,
	MODEL_NPC_DEVILSQUARE,
	MODEL_MERCHANT_FEMALE_HEAD  ,
	MODEL_MERCHANT_FEMALE_UPPER = MODEL_MERCHANT_FEMALE_HEAD  +2,
	MODEL_MERCHANT_FEMALE_LOWER = MODEL_MERCHANT_FEMALE_UPPER +2,
	MODEL_MERCHANT_FEMALE_GLOVES= MODEL_MERCHANT_FEMALE_LOWER +2,
	MODEL_MERCHANT_FEMALE_BOOTS = MODEL_MERCHANT_FEMALE_GLOVES+2,
	MODEL_MERCHANT_MAN_HEAD     = MODEL_MERCHANT_FEMALE_BOOTS +2,
	MODEL_MERCHANT_MAN_UPPER    = MODEL_MERCHANT_MAN_HEAD     +2,
	MODEL_MERCHANT_MAN_GLOVES   = MODEL_MERCHANT_MAN_UPPER    +2,
	MODEL_MERCHANT_MAN_BOOTS    = MODEL_MERCHANT_MAN_GLOVES   +2,
	MODEL_MERCHANT_GIRL_HEAD    = MODEL_MERCHANT_MAN_BOOTS    +2,
	MODEL_MERCHANT_GIRL_UPPER   = MODEL_MERCHANT_GIRL_HEAD    +2,
	MODEL_MERCHANT_GIRL_LOWER   = MODEL_MERCHANT_GIRL_UPPER   +2,
	MODEL_NPC_SEVINA            = MODEL_MERCHANT_GIRL_LOWER   +2,
	MODEL_NPC_ARCHANGEL			 ,
	MODEL_NPC_ARCHANGEL_MESSENGER,
	MODEL_DEVIAS_TRADER          ,  //  데비아스, 로랜시아 추가 상점 NPC
	MODEL_NPC_BREEDER            ,  //  조련사 NPC
	MODEL_ANGEL					 ,
#ifdef _PVP_MURDERER_HERO_ITEM
	MODEL_HERO_SHOP				 ,
#endif	// _PVP_MURDERER_HERO_ITEM
	MODEL_KALIMA_SHOP			 ,
	MODEL_BC_NPC1,					// 공성 물약 NPC 수정 캐릭
	MODEL_BC_NPC2,					// 공성 물약 NPC 수정 캐릭
	MODEL_BC_BOX,					// 공성 물약 NPC 박스
	MODEL_NPC_CAPATULT_ATT       ,  //  공성측 투석기.
	MODEL_NPC_CAPATULT_DEF       ,  //  수성측 투석기.
	MODEL_NPC_SENATUS            ,  //  원로원.
	MODEL_NPC_GATE_SWITCH        ,  //  성문 스위치.
	MODEL_NPC_CROWN              ,  //  왕관 NPC.
	MODEL_NPC_CHECK_FLOOR        ,  //  왕관 체크 발판
	MODEL_NPC_CLERK              ,  //  신청 서기.
	MODEL_NPC_BARRIER            ,  //  보호막.
	MODEL_NPC_SERBIS			 ,	//  석조합 NPC
	MODEL_NPC_SERBIS_DONKEY		 ,	//	당나귀
	MODEL_NPC_SERBIS_FLAG		 ,  //  깃발
	MODEL_CRYWOLF_STATUE		 ,  //  늑대 신상
	MODEL_CRYWOLF_ALTAR1		 ,  //  제단 1
	MODEL_CRYWOLF_ALTAR2		 ,  //  제단 2
	MODEL_CRYWOLF_ALTAR3		 ,  //  제단 3
	MODEL_CRYWOLF_ALTAR4		 ,  //  제단 4
	MODEL_CRYWOLF_ALTAR5		 ,  //  제단 5
	MODEL_KANTURU2ND_ENTER_NPC	 ,	//	칸투르 2차에서 3차로 가는 입구 NPC
	MODEL_TRAP_CANON			,	// 칸투르 2차에 트랩형 캐넌
	MODEL_SMELTING_NPC			 ,  //  정재의 탑 NPC
	MODEL_REFINERY_NPC  ,           //   제련 NPC
	MODEL_RECOVERY_NPC  ,           //   환원 NPC
	MODEL_WEDDING_NPC	,			// 웨딩 NPC
#ifdef ADD_NPC_DEVIN
	MODEL_NPC_DEVIN				,	// 사제 데빈 NPC
#endif	// ADD_NPC_DEVIN
	MODEL_NPC_QUARREL			,	// 웨어울프쿼렐 NPC
	MODEL_NPC_CASTEL_GATE		,	// 성문 NPC
	MODEL_CURSEDTEMPLE_ENTER_NPC,       // 이벤트 맵 입장 NPC
	MODEL_CURSEDTEMPLE_ALLIED_NPC,      // 이벤트 맵 연합군 NPC
	MODEL_CURSEDTEMPLE_ILLUSION_NPC,    // 이벤트 맵 환영교 NPC
	MODEL_CURSEDTEMPLE_STATUE,       // 석상 NPC
	MODEL_CURSEDTEMPLE_ALLIED_BASKET,      // 연합군 성물보관함 NPC
	MODEL_CURSEDTEMPLE_ILLUSION__BASKET,    // 환영교단 성물보관함 NPC
	MODEL_ELBELAND_SILVIA,			// 6번째 캐릭터 시작맵 물약파는 NPC 실비아
	MODEL_ELBELAND_RHEA,			// 6번째 캐릭터 시작맵 무기파는 NPC 레아
	MODEL_ELBELAND_MARCE,			// 6번째 캐릭터 시작맵 스킬북파는 NPC 마르세
#ifdef CSK_EVENT_CHERRYBLOSSOM
	MODEL_NPC_CHERRYBLOSSOM,        // 벚꽃의 정령
#endif // CSK_EVENT_CHERRYBLOSSOM
#ifdef PSW_EVENT_CHERRYBLOSSOMTREE
	MODEL_NPC_CHERRYBLOSSOMTREE,        // 벚꽃의 나무
#endif //PSW_EVENT_CHERRYBLOSSOMTREE
#ifdef ADD_SOCKET_MIX
	MODEL_SEED_MASTER,			// 시드 마스터 (소켓아이템)
	MODEL_SEED_INVESTIGATOR,	// 시드 연구가 (소켓아이템)
#endif	// ADD_SOCKET_MIX
#ifdef PBG_ADD_LITTLESANTA_NPC
	MODEL_LITTLESANTA,			// 리틀산타(1~8)
	MODEL_LITTLESANTA_END = MODEL_LITTLESANTA + 7,
#endif //PBG_ADD_LITTLESANTA_NPC
#ifdef LDK_ADD_SNOWMAN_CHANGERING
	MODEL_XMAS2008_SNOWMAN,		//2008크리스마스(해외) 눈사람 변신 모델
	MODEL_XMAS2008_SNOWMAN_HEAD,
	MODEL_XMAS2008_SNOWMAN_BODY,
#endif //LDK_ADD_SNOWMAN_CHANGERING
#ifdef LDK_ADD_SNOWMAN_NPC
	MODEL_XMAS2008_SNOWMAN_NPC,	//2008눈사람 npc
#endif //LDK_ADD_SNOWMAN_NPC
#ifdef LDK_ADD_SANTA_NPC
	MODEL_XMAS2008_SANTA_NPC,	//2008산타 NPC
#endif //LDK_ADD_SANTA_NPC
#ifdef YDG_ADD_NEW_DUEL_NPC
	MODEL_DUEL_NPC_TITUS,		// 결투장 문지기 타이투스
#endif	// YDG_ADD_NEW_DUEL_NPC
#ifdef LDK_ADD_GAMBLE_NPC_MOSS
	MODEL_GAMBLE_NPC_MOSS,			// 겜블 무기 상인 모스
#endif //LDK_ADD_GAMBLE_NPC_MOSS
#ifdef YDG_ADD_DOPPELGANGER_NPC
	MODEL_DOPPELGANGER_NPC_LUGARD,		// 도플갱어 NPC 루가드
	MODEL_DOPPELGANGER_NPC_BOX,			// 도플갱어 보상 상자
	MODEL_DOPPELGANGER_NPC_GOLDENBOX,	// 도플갱어 최종보상 상자
#endif	// YDG_ADD_DOPPELGANGER_NPC
#ifdef ASG_ADD_GENS_NPC
	MODAL_GENS_NPC_DUPRIAN,			// 겐스 NPC 듀프리언 집사
	MODAL_GENS_NPC_BARNERT,			// 겐스 NPC 바네르트 집사
#endif	// ASG_ADD_GENS_NPC
#ifdef LDS_ADD_NPC_UNITEDMARKETPLACE
	MODEL_UNITEDMARKETPLACE_CHRISTIN,	// 통합 시장 크리스틴
	MODEL_UNITEDMARKETPLACE_RAUL,		// 통합 시장 라울
	MODEL_UNITEDMARKETPLACE_JULIA,		// 통합 시장 줄리아
#endif // LDS_ADD_NPC_UNITEDMARKETPLACE
#ifdef ASG_ADD_TIME_LIMIT_QUEST_NPC
	MODEL_TIME_LIMIT_QUEST_NPC_TERSIA,	// 길드관리인 테르시아
	MODEL_TIME_LIMIT_QUEST_NPC_BENA,	// 신녀 베이나
	MODEL_TIME_LIMIT_QUEST_NPC_ZAIRO,	// 떠돌이상인 자이로
#endif	// ASG_ADD_TIME_LIMIT_QUEST_NPC
#ifdef ASG_ADD_KARUTAN_NPC
	MODEL_KARUTAN_NPC_REINA,			// 잡화상인 레이나
	MODEL_KARUTAN_NPC_VOLVO,			// 무기상인 볼로
#endif	// ASG_ADD_KARUTAN_NPC
#ifdef LEM_ADD_LUCKYITEM				// 럭키아이템 NPC
	MODEL_LUCKYITEM_NPC,			
#endif // LEM_ADD_LUCKYITEM
	MODEL_NPC_END                ,
	//player
	MODEL_PLAYER         		 ,	// (507)
	MODEL_SHADOW_BODY     		 ,
	MODEL_SHADOW_SWORD	    	 ,
	MODEL_SHADOW_AXE	    	 ,
	MODEL_SHADOW_MACE   		 ,
	MODEL_SHADOW_SPEAR	    	 ,
	MODEL_SHADOW_BOW		     ,
	MODEL_SHADOW_STAFF		     ,

	//item
	MODEL_ITEM					 ,	// (515)
	
	MODEL_SWORD					= MODEL_ITEM,
	MODEL_AXE					= (MODEL_ITEM+ITEM_AXE),
	MODEL_MACE					= (MODEL_ITEM+ITEM_MACE),
	MODEL_SPEAR					= (MODEL_ITEM+ITEM_SPEAR),
	MODEL_BOW					= (MODEL_ITEM+ITEM_BOW),
	MODEL_STAFF					= (MODEL_ITEM+ITEM_STAFF),
	MODEL_SHIELD				= (MODEL_ITEM+ITEM_SHIELD),
	MODEL_HELM 					= (MODEL_ITEM+ITEM_HELM),	//헬멧
	MODEL_ARMOR					= (MODEL_ITEM+ITEM_ARMOR),	//갑옷
	MODEL_PANTS					= (MODEL_ITEM+ITEM_PANTS),	//바지
	MODEL_GLOVES				= (MODEL_ITEM+ITEM_GLOVES),	//장갑
	MODEL_BOOTS					= (MODEL_ITEM+ITEM_BOOTS),	//부츠
	MODEL_WING 					= (MODEL_ITEM+ITEM_WING),	//날개
	MODEL_HELPER				= (MODEL_ITEM+ITEM_HELPER),
	MODEL_POTION				= (MODEL_ITEM+ITEM_POTION),
	MODEL_ETC					= (MODEL_ITEM+ITEM_ETC),

	// 소환술사와 요정이 같이 쓰는 넝쿨, 실크 시리즈 아이템.
	MODEL_HELM2 				= (MODEL_ITEM+MAX_ITEM),
	MODEL_ARMOR2				= (MODEL_HELM2+MODEL_ITEM_COMMON_NUM),
	MODEL_PANTS2				= (MODEL_ARMOR2+MODEL_ITEM_COMMON_NUM),
	MODEL_GLOVES2				= (MODEL_PANTS2+MODEL_ITEM_COMMON_NUM),
	MODEL_BOOTS2				= (MODEL_GLOVES2+MODEL_ITEM_COMMON_NUM),
#ifdef PBG_ADD_NEWCHAR_MONK_ITEM
	// 레이지파이터의 기존 모델과 동일 속성의 모델만 다른 아이템추가
	MODEL_HELM_MONK				= (MODEL_BOOTS2+MODEL_ITEM_COMMON_NUM),
	MODEL_ARMOR_MONK			= (MODEL_HELM_MONK+MODEL_ITEM_COMMONCNT_RAGEFIGHTER),
	MODEL_PANTS_MONK			= (MODEL_ARMOR_MONK+MODEL_ITEM_COMMONCNT_RAGEFIGHTER),
	MODEL_BOOTS_MONK			= (MODEL_PANTS_MONK+MODEL_ITEM_COMMONCNT_RAGEFIGHTER),

	MODEL_BODY_HELM 			= (MODEL_BOOTS_MONK+MODEL_ITEM_COMMONCNT_RAGEFIGHTER),
#else //PBG_ADD_NEWCHAR_MONK_ITEM
	MODEL_BODY_HELM 			= (MODEL_BOOTS2+MODEL_ITEM_COMMON_NUM),
#endif //PBG_ADD_NEWCHAR_MONK_ITEM
	MODEL_BODY_ARMOR			= (MODEL_BODY_HELM+MODEL_BODY_NUM),
	MODEL_BODY_PANTS			= (MODEL_BODY_ARMOR+MODEL_BODY_NUM),
	MODEL_BODY_GLOVES			= (MODEL_BODY_PANTS+MODEL_BODY_NUM),
	MODEL_BODY_BOOTS			= (MODEL_BODY_GLOVES+MODEL_BODY_NUM),

	MODEL_EVENT					= (MODEL_BODY_BOOTS+MODEL_BODY_NUM),
	MODEL_QUEST                 = (MODEL_EVENT+MAX_EVENT_ITEM),		 //  퀘스트 아이템.
#ifdef PJH_SEASON4_SPRITE_NEW_SKILL_MULTI_SHOT
	MODEL_MULTI_SHOT1			,
	MODEL_MULTI_SHOT2			,
	MODEL_MULTI_SHOT3			,
	MODEL_MASK_HELM             = (MODEL_MULTI_SHOT3+MAX_QUEST_ITEM),		 //  다크로드에 추가되는 마스크.
#else
	MODEL_MASK_HELM             = (MODEL_QUEST+MAX_QUEST_ITEM),		 //  다크로드에 추가되는 마스크.
#endif //PJH_SEASON4_SPRITE_NEW_SKILL_MULTI_SHOT
	MAX_MODELS					= (MODEL_MASK_HELM+MAX_ITEM_INDEX),
};
//object end

//inventory start
enum 
{ 
	PSHOPWNDTYPE_NONE = -1,
	PSHOPWNDTYPE_SALE = 1,
	PSHOPWNDTYPE_PURCHASE 
};
enum ITEM_EX_SRC_TYPE
{
	ITEM_EX_SRC_EQUIPMENT = 1,		//. 인벤토리 장비창
};

enum ENUM_KEYPADMODE
{
	// 참고 잠금
	KPM_MOVE = 1,
	KPM_LOCK3 = 2,
	KPM_UNLOCK = 3,
	KPM_LOCK1 = 4,
	KPM_LOCK2 = 5,

	// 서버 분할 관련 주민번호 확인
	KPM_SERVER_IMMIGRATION_CHECK = 6,
};

enum
{
	EVENT_NONE = 0,
	EVENT_LENA,             //  레나.
	EVENT_STONE,            //  스톤.
	EVENT_SCRATCH_TICKET,   //  복권.
	EVENT_STONE_EXCHANGE,   //  스톤 환전.
	EVENT_FRIEND,           //  친구 이벤트.
};

//inventory end

//ai start

enum
{
	PLAYER_SET,	
	PLAYER_STOP_MALE,
	PLAYER_STOP_FEMALE,
	PLAYER_STOP_SUMMONER,				// 소환술사 제자리
	PLAYER_STOP_SWORD,
	PLAYER_STOP_TWO_HAND_SWORD,
	PLAYER_STOP_SPEAR,
	PLAYER_STOP_SCYTHE,
	PLAYER_STOP_BOW,
	PLAYER_STOP_CROSSBOW,
	PLAYER_STOP_WAND,					// 완드 들고 제자리
	PLAYER_STOP_FLY,
	PLAYER_STOP_FLY_CROSSBOW,
	PLAYER_STOP_RIDE,
	PLAYER_STOP_RIDE_WEAPON,

	PLAYER_WALK_MALE,
	PLAYER_WALK_FEMALE,
	PLAYER_WALK_SWORD,
	PLAYER_WALK_TWO_HAND_SWORD,
	PLAYER_WALK_SPEAR,
	PLAYER_WALK_SCYTHE,
	PLAYER_WALK_BOW,
	PLAYER_WALK_CROSSBOW,
	PLAYER_WALK_WAND,					// 완드 들고 걷기
	PLAYER_WALK_SWIM,
	PLAYER_RUN,
	PLAYER_RUN_SWORD,
	PLAYER_RUN_TWO_SWORD,
	PLAYER_RUN_TWO_HAND_SWORD,
	PLAYER_RUN_SPEAR,
	PLAYER_RUN_BOW,
	PLAYER_RUN_CROSSBOW,
	PLAYER_RUN_WAND,					// 완드 들고 뛰기
	PLAYER_RUN_SWIM,
	PLAYER_FLY,
	PLAYER_FLY_CROSSBOW,
	PLAYER_RUN_RIDE,
	PLAYER_RUN_RIDE_WEAPON,

	PLAYER_ATTACK_FIST,					// 주먹 에니메이션
	PLAYER_ATTACK_SWORD_RIGHT1,
	PLAYER_ATTACK_SWORD_RIGHT2,
	PLAYER_ATTACK_SWORD_LEFT1,
	PLAYER_ATTACK_SWORD_LEFT2,
	PLAYER_ATTACK_TWO_HAND_SWORD1,
	PLAYER_ATTACK_TWO_HAND_SWORD2,
	PLAYER_ATTACK_TWO_HAND_SWORD3,
	PLAYER_ATTACK_SPEAR1,
	PLAYER_ATTACK_SCYTHE1,
	PLAYER_ATTACK_SCYTHE2,
	PLAYER_ATTACK_SCYTHE3,
	PLAYER_ATTACK_BOW,
	PLAYER_ATTACK_CROSSBOW,
	PLAYER_ATTACK_FLY_BOW,
	PLAYER_ATTACK_FLY_CROSSBOW,
	PLAYER_ATTACK_RIDE_SWORD,
	PLAYER_ATTACK_RIDE_TWO_HAND_SWORD,
	PLAYER_ATTACK_RIDE_SPEAR,
	PLAYER_ATTACK_RIDE_SCYTHE,
	PLAYER_ATTACK_RIDE_BOW,
	PLAYER_ATTACK_RIDE_CROSSBOW,

	PLAYER_ATTACK_SKILL_SWORD1,
	PLAYER_ATTACK_SKILL_SWORD2,
	PLAYER_ATTACK_SKILL_SWORD3,
	PLAYER_ATTACK_SKILL_SWORD4,
	PLAYER_ATTACK_SKILL_SWORD5,

	PLAYER_ATTACK_SKILL_WHEEL,
	PLAYER_ATTACK_SKILL_FURY_STRIKE,
	PLAYER_SKILL_VITALITY,
	PLAYER_SKILL_RIDER,
	PLAYER_SKILL_RIDER_FLY,
	PLAYER_ATTACK_SKILL_SPEAR,
	PLAYER_ATTACK_ONETOONE,
	PLAYER_SKILL_HELL_BEGIN,
	PLAYER_SKILL_HELL_START,

	PLAYER_ATTACK_END,

	PLAYER_FLY_RIDE                 = PLAYER_ATTACK_END,
	PLAYER_FLY_RIDE_WEAPON          ,
	PLAYER_DARKLORD_STAND           ,   //  다크로드 다크스피릿들고 서기.
	PLAYER_DARKLORD_WALK            ,   //  다크로드 다크스피릿들고 걷기.
	PLAYER_STOP_RIDE_HORSE          ,   //  다크로드 공격 ( 찌르는 것 ).        (●) 
	PLAYER_RUN_RIDE_HORSE           ,   //  다크로드 파티 소환.                 (●) 
	PLAYER_ATTACK_STRIKE            ,   //  다크홀스 타고 정지.                 (●)
	PLAYER_ATTACK_TELEPORT          ,   //  다크홀스 달리기.                        
	PLAYER_ATTACK_RIDE_STRIKE       ,   //  다크홀스 타고 공격 ( 찌르는 것 ).
	PLAYER_ATTACK_RIDE_TELEPORT     ,   //  다크홀스 타고  파티 소환.
	PLAYER_ATTACK_RIDE_HORSE_SWORD  ,   //  다크홀스 타고 한손 공격.
	PLAYER_ATTACK_RIDE_ATTACK_FLASH ,   //  다크홀스 타고 선터슽트라이크.
	PLAYER_ATTACK_RIDE_ATTACK_MAGIC ,   //  다크홀스 타고 마법 공격.
	PLAYER_ATTACK_DARKHORSE         ,   //  다크홀스 스킬.
	PLAYER_IDLE1_DARKHORSE			,   //  (로그인씬용)다크홀스 타고 셉터 휘두르기
	PLAYER_IDLE2_DARKHORSE			,   //  (로그인씬용)다크홀스 위로 다리 들기
	PLAYER_FENRIR_ATTACK			,		//	일반공격 - 아무것도 안든 상태
	PLAYER_FENRIR_ATTACK_DARKLORD_AQUA,		//	일반공격 - 사용안함
	PLAYER_FENRIR_ATTACK_DARKLORD_STRIKE,	//	일반공격 - 다크로드 찌르기
	PLAYER_FENRIR_ATTACK_DARKLORD_SWORD,	//	일반공격 - 다크로드 타격(한손 공격)
	PLAYER_FENRIR_ATTACK_DARKLORD_TELEPORT,	//	일반공격 - 다크로드 파티 소환
	PLAYER_FENRIR_ATTACK_DARKLORD_FLASH,	//	일반공격 - 다크로드 아쿠아플래쉬
	PLAYER_FENRIR_ATTACK_TWO_SWORD,			//	일반공격 - 두손칼 공격(기사)
	PLAYER_FENRIR_ATTACK_MAGIC,				//	일반공격 - 마법 공격(마법사)
	PLAYER_FENRIR_ATTACK_CROSSBOW,			//	일반공격 - 석궁 공격(요정)
	PLAYER_FENRIR_ATTACK_SPEAR,				//	일반공격 - 창 공격(기사)
	PLAYER_FENRIR_ATTACK_ONE_SWORD,			//	일반공격 - 한손칼 공격(기사)
	PLAYER_FENRIR_ATTACK_BOW,				//  일반공격 - 활 공격(요정)
	PLAYER_FENRIR_SKILL,					//	스킬공격 - 맨손
	PLAYER_FENRIR_SKILL_TWO_SWORD,			//	스킬공격 - 양손칼
	PLAYER_FENRIR_SKILL_ONE_RIGHT,			//	스킬공격 - 한손 오른쪽(100)
	PLAYER_FENRIR_SKILL_ONE_LEFT,			//	스킬공격 - 한손 왼쪽
	PLAYER_FENRIR_DAMAGE,					//	데미지 - 맨손
	PLAYER_FENRIR_DAMAGE_TWO_SWORD,			//	데미지 - 양손칼
	PLAYER_FENRIR_DAMAGE_ONE_RIGHT,			//	데미지 - 한손 오른쪽
	PLAYER_FENRIR_DAMAGE_ONE_LEFT,			//	데미지 - 한손 왼쪽
	PLAYER_FENRIR_RUN,						//	달리기 - 맨손(110)
	PLAYER_FENRIR_RUN_TWO_SWORD,			//	달리기 - 양손칼
	PLAYER_FENRIR_RUN_ONE_RIGHT,			//	달리기 - 한손 오른쪽
	PLAYER_FENRIR_RUN_ONE_LEFT,				//	달리기 - 한손 왼쪽
	PLAYER_FENRIR_RUN_MAGOM,				//	달리기 - 맨손_마검(114)
	PLAYER_FENRIR_RUN_TWO_SWORD_MAGOM,		//	달리기 - 양손_마검
	PLAYER_FENRIR_RUN_ONE_RIGHT_MAGOM,		//	달리기 - 오른손_마검
	PLAYER_FENRIR_RUN_ONE_LEFT_MAGOM,		//	달리기 - 왼손_마검
	PLAYER_FENRIR_RUN_ELF,					//	달리기 - 맨손_엘프
	PLAYER_FENRIR_RUN_TWO_SWORD_ELF,		//	달리기 - 양손_엘프
	PLAYER_FENRIR_RUN_ONE_RIGHT_ELF,		//	달리기 - 오른손_엘프
	PLAYER_FENRIR_RUN_ONE_LEFT_ELF,			//	달리기 - 왼손_엘프
	PLAYER_FENRIR_STAND,					//  정지 - 맨손
	PLAYER_FENRIR_STAND_TWO_SWORD,			//	정지 - 양손칼
	PLAYER_FENRIR_STAND_ONE_RIGHT,			//	정지 - 한손 오른쪽
	PLAYER_FENRIR_STAND_ONE_LEFT,			//  정지 - 한손 왼쪽
	PLAYER_FENRIR_WALK,						//	걷기 - 맨손
	PLAYER_FENRIR_WALK_TWO_SWORD,			//	걷기 - 양손칼
	PLAYER_FENRIR_WALK_ONE_RIGHT,			//	걷기 - 한손 오른쪽
	PLAYER_FENRIR_WALK_ONE_LEFT,			//	걷기 - 한손 왼쪽(129)

	PLAYER_ATTACK_BOW_UP			,   //  활로 하늘로 향해서 공격
	PLAYER_ATTACK_CROSSBOW_UP       ,   //  석궁으로 하늘로 향해서 공격
	PLAYER_ATTACK_FLY_BOW_UP		,   //  날개 달고 활로 하늘로 향해서 공격
	PLAYER_ATTACK_FLY_CROSSBOW_UP   ,   //  날개 달고 석궁으로 하늘로 향해서 공격
	PLAYER_ATTACK_RIDE_BOW_UP       ,   //  말타고 활로 하늘로 향해서 공격
	PLAYER_ATTACK_RIDE_CROSSBOW_UP  ,   //  말타고 석궁으로 하늘로 향해서 공격
	PLAYER_ATTACK_ONE_FLASH         ,   //  기마검 일섬공격.
	PLAYER_ATTACK_RUSH              ,   //  기사 돌격 공격.
	PLAYER_ATTACK_DEATH_CANNON      ,   //  법마검 마섬광.
	PLAYER_ATTACK_REMOVAL           ,   //  마스터 스킬 제거 마법.
	PLAYER_ATTACK_STUN              ,   //  스텐 해제
	PLAYER_HIGH_SHOCK               ,   //  심각한 충격 효과.(142)

	//	추가되는 두손 무기 애니메이션.
	PLAYER_STOP_TWO_HAND_SWORD_TWO	,
	PLAYER_WALK_TWO_HAND_SWORD_TWO	,
	PLAYER_RUN_TWO_HAND_SWORD_TWO	,
	PLAYER_ATTACK_TWO_HAND_SWORD_TWO,

	PLAYER_SKILL_HAND1              ,
	PLAYER_SKILL_HAND2				,
	PLAYER_SKILL_WEAPON1    		,
	PLAYER_SKILL_WEAPON2		    , //(150)
	PLAYER_SKILL_ELF1				,	// 엘프 : 공격력업/발어력업/힐링
	PLAYER_SKILL_TELEPORT  		    ,
	PLAYER_SKILL_FLASH     		    ,
	PLAYER_SKILL_INFERNO            ,
	PLAYER_SKILL_HELL     		    ,
	PLAYER_RIDE_SKILL               ,
// 소환술사 전용 스킬.
	PLAYER_SKILL_SLEEP				,
	PLAYER_SKILL_SLEEP_UNI			,
	PLAYER_SKILL_SLEEP_DINO			,
	PLAYER_SKILL_SLEEP_FENRIR		,
	PLAYER_SKILL_CHAIN_LIGHTNING	,
	PLAYER_SKILL_CHAIN_LIGHTNING_UNI,
	PLAYER_SKILL_CHAIN_LIGHTNING_DINO,
	PLAYER_SKILL_CHAIN_LIGHTNING_FENRIR,
	PLAYER_SKILL_LIGHTNING_ORB		,
	PLAYER_SKILL_LIGHTNING_ORB_UNI	,
	PLAYER_SKILL_LIGHTNING_ORB_DINO	,
	PLAYER_SKILL_LIGHTNING_ORB_FENRIR,
	PLAYER_SKILL_DRAIN_LIFE			,	// 소환술사 : 드레인라이프
	PLAYER_SKILL_DRAIN_LIFE_UNI		,
	PLAYER_SKILL_DRAIN_LIFE_DINO	,
	PLAYER_SKILL_DRAIN_LIFE_FENRIR	,
// 소환술사 소환 동작.
	PLAYER_SKILL_SUMMON				,
	PLAYER_SKILL_SUMMON_UNI			,
	PLAYER_SKILL_SUMMON_DINO		,
	PLAYER_SKILL_SUMMON_FENRIR		,

#ifdef ADD_NEW_SKILL_SEASON4
	PLAYER_SKILL_BLOW_OF_DESTRUCTION,	// 파괴의 일격
	PLAYER_SKILL_SWELL_OF_MP		,	// 마력 증대
	PLAYER_SKILL_MULTISHOT_BOW_STAND,	// 멀티샷
	PLAYER_SKILL_MULTISHOT_BOW_FLYING,
	PLAYER_SKILL_MULTISHOT_CROSSBOW_STAND,
	PLAYER_SKILL_MULTISHOT_CROSSBOW_FLYING,
	PLAYER_SKILL_RECOVERY			,	// 실드 회복 증대
	PLAYER_SKILL_GIGANTICSTORM		,	// 기간틱스톰
	PLAYER_SKILL_FLAMESTRIKE		,	// 플래임스트라이크
	PLAYER_SKILL_LIGHTNING_SHOCK	,	// 라이트닝쇼크
#endif	// ADD_NEW_SKILL_SEASON4
#ifdef YDG_ADD_SKILL_RIDING_ANIMATIONS
	PLAYER_SKILL_GIGANTICSTORM_UNI	,	// 기간틱스톰 탑승추가
	PLAYER_SKILL_GIGANTICSTORM_DINO	,
	PLAYER_SKILL_GIGANTICSTORM_FENRIR	,
	PLAYER_ATTACK_SKILL_WHEEL_UNI	,	// 회오리베기 블러드어택 탑승추가
	PLAYER_ATTACK_SKILL_WHEEL_DINO	,
	PLAYER_ATTACK_SKILL_WHEEL_FENRIR	,
#endif	// YDG_ADD_SKILL_RIDING_ANIMATIONS
	PLAYER_DEFENSE1                 ,
	PLAYER_GREETING1                ,
	PLAYER_GREETING_FEMALE1       	,
	PLAYER_GOODBYE1               	, //(160)
	PLAYER_GOODBYE_FEMALE1          ,
	PLAYER_CLAP1                  	,//박수
	PLAYER_CLAP_FEMALE1             ,
	PLAYER_CHEER1                   ,//환호
	PLAYER_CHEER_FEMALE1            ,
	PLAYER_DIRECTION1               ,
	PLAYER_DIRECTION_FEMALE1        ,
	PLAYER_GESTURE1                 ,
	PLAYER_GESTURE_FEMALE1        	,
	PLAYER_UNKNOWN1               	, //(170)
	PLAYER_UNKNOWN_FEMALE1          ,
	PLAYER_CRY1                   	,//
	PLAYER_CRY_FEMALE1              ,
	PLAYER_AWKWARD1                 ,//어색
	PLAYER_AWKWARD_FEMALE1          ,
	PLAYER_SEE1                     ,
	PLAYER_SEE_FEMALE1              ,
	PLAYER_WIN1                     ,
	PLAYER_WIN_FEMALE1            	,
	PLAYER_SMILE1                 	, //(180)
	PLAYER_SMILE_FEMALE1            ,
	PLAYER_SLEEP1                 	,
	PLAYER_SLEEP_FEMALE1            ,
	PLAYER_COLD1                    ,
	PLAYER_COLD_FEMALE1             ,
	PLAYER_AGAIN1                   ,
	PLAYER_AGAIN_FEMALE1            ,
	PLAYER_RESPECT1                 ,//경의
	PLAYER_SALUTE1                	,//경례
	PLAYER_SCISSORS				  	,	// 가위 (동작 순서 안맞으면 SetActionClass() 참고) (190)
	PLAYER_ROCK					    ,	// 바위 (계속 루프 안되게 하려면 PLAYER_SHOCK위에 추가)
	PLAYER_PAPER				  	,	// 보
	PLAYER_HUSTLE					,	// 일본 레슬러 동작 -_-
	PLAYER_PROVOCATION				,
	PLAYER_LOOK_AROUND				,
	PLAYER_CHEERS					,
	PLAYER_RUSH1                    ,
	PLAYER_COME_UP                  ,
	PLAYER_SHOCK                    ,
	PLAYER_DIE1                     ,
	PLAYER_DIE2                     ,
	PLAYER_SIT1                   	,
	PLAYER_SIT2                   	,
	PLAYER_SIT_FEMALE1              ,
	PLAYER_SIT_FEMALE2            	,
	PLAYER_HEALING1                 ,
	PLAYER_HEALING_FEMALE1          ,
	PLAYER_POSE1                    ,
	PLAYER_POSE_FEMALE1             ,
	PLAYER_JACK_1					,	// 마빡이 동작1
	PLAYER_JACK_2					,	// 마빡이 동작2
	PLAYER_SANTA_1					,	// 점프 동작
	PLAYER_SANTA_2					,	// 턴 동작
	PLAYER_CHANGE_UP				,
	PLAYER_RECOVER_SKILL			,

#ifdef PBG_ADD_NEWCHAR_MONK_SKILL
	PLAYER_SKILL_THRUST				,
	PLAYER_SKILL_STAMP				,
	PLAYER_SKILL_GIANTSWING			,
	PLAYER_SKILL_DARKSIDE_READY		,
	PLAYER_SKILL_DARKSIDE_ATTACK	,
	PLAYER_SKILL_DRAGONKICK			,
	PLAYER_SKILL_DRAGONLORE			,
	PLAYER_SKILL_ATT_UP_OURFORCES	,
	PLAYER_SKILL_HP_UP_OURFORCES	,
// 레이지 파이터 관련 애니
	PLAYER_RAGE_UNI_ATTACK			,
	PLAYER_RAGE_UNI_ATTACK_ONE_RIGHT,
	PLAYER_RAGE_UNI_RUN				,
	PLAYER_RAGE_UNI_RUN_ONE_RIGHT	,
	PLAYER_RAGE_UNI_STOP_ONE_RIGHT	,
	PLAYER_RAGE_FENRIR				,
	PLAYER_RAGE_FENRIR_TWO_SWORD	,
	PLAYER_RAGE_FENRIR_ONE_RIGHT	,
	PLAYER_RAGE_FENRIR_ONE_LEFT		,
	PLAYER_RAGE_FENRIR_WALK			,
	PLAYER_RAGE_FENRIR_WALK_ONE_RIGHT,
	PLAYER_RAGE_FENRIR_WALK_ONE_LEFT,
	PLAYER_RAGE_FENRIR_WALK_TWO_SWORD,
	PLAYER_RAGE_FENRIR_RUN			,
	PLAYER_RAGE_FENRIR_RUN_TWO_SWORD,
	PLAYER_RAGE_FENRIR_RUN_ONE_RIGHT,
	PLAYER_RAGE_FENRIR_RUN_ONE_LEFT	,
	PLAYER_RAGE_FENRIR_STAND		,
	PLAYER_RAGE_FENRIR_STAND_TWO_SWORD,
	PLAYER_RAGE_FENRIR_STAND_ONE_RIGHT,
	PLAYER_RAGE_FENRIR_STAND_ONE_LEFT,
	PLAYER_RAGE_FENRIR_DAMAGE		,
	PLAYER_RAGE_FENRIR_DAMAGE_TWO_SWORD,
	PLAYER_RAGE_FENRIR_DAMAGE_ONE_RIGHT,
	PLAYER_RAGE_FENRIR_DAMAGE_ONE_LEFT,
	PLAYER_RAGE_FENRIR_ATTACK_RIGHT	,
	PLAYER_STOP_RAGEFIGHTER			,
#endif //PBG_ADD_NEWCHAR_MONK_SKILL
	MAX_PLAYER_ACTION               ,
};
//ai end

//publicfile start
// 캐릭터 번호


enum CLASS_TYPE
{
// 1차 직업
	CLASS_WIZARD = 0,		// 흑마법사
	CLASS_KNIGHT,			// 흑기사
	CLASS_ELF,				// 요정
	CLASS_DARK,				// 마검사
	CLASS_DARK_LORD,		// 다크로드
	CLASS_SUMMONER,			// 소환술사
#ifdef PBG_ADD_NEWCHAR_MONK
	CLASS_RAGEFIGHTER,		// 레이지파이터
#endif //PBG_ADD_NEWCHAR_MONK

// 2차 직업
	CLASS_SOULMASTER,		// 흑마법사 - 소울마스터
	CLASS_BLADEKNIGHT,		// 흑기사 - 블레이드나이트
	CLASS_MUSEELF,			// 요정 - 뮤즈엘프
	CLASS_BLOODYSUMMONER,	// 소환술사 - 블러디서머너

// 3차 직업
	CLASS_GRANDMASTER,		// 흑마법사 - 소울마스터 - 그랜드마스터
	CLASS_BLADEMASTER,		// 흑기사 - 블레이드나이트 - 블레이드마스터
	CLASS_HIGHELF,			// 요정 - 뮤즈엘프 - 하이엘프
	CLASS_DUELMASTER,		// 마검사 - X - 듀얼마스터
	CLASS_LORDEMPEROR,		// 다크로드 - X - 로드엠퍼러
	CLASS_DIMENSIONMASTER,	// 소환술사 - 블러디서머너 - 디멘션마스터
#ifdef PBG_ADD_NEWCHAR_MONK
	CLASS_TEMPLENIGHT,		// 레이지파이터 - 템플 나이트
#endif //PBG_ADD_NEWCHAR_MONK
};

enum MonsterSkillType
{
	ATMON_SKILL_BIGIN		= 0,
	ATMON_SKILL_THUNDER		= 1,   //선더브레이크
	ATMON_SKILL_WIND		= 2,   //블러디윈드
	ATMON_SKILL_FIRELAY		= 3,   //파이어레이
	ATMON_SKILL_CHARM		= 4,   //참
	ATMON_SKILL_TOUCH		= 5,   //뱀파이어릭터치
	ATMON_SKILL_NUM1		= 6,	// 다크엘프-그룹소환술
	ATMON_SKILL_NUM2		= 7,	// 다크엘프-그룹치료
	ATMON_SKILL_NUM3		= 8,	// 다크엘프-검기
	ATMON_SKILL_NUM4		= 9,	// 발람-방향해제
	ATMON_SKILL_NUM5		= 10,	// 데쓰스피릿-마나AG감소
	ATMON_SKILL_NUM6		= 11,	// 소람-밀어내기
	ATMON_SKILL_NUM7		= 12,	// 발가스-대지직격
	ATMON_SKILL_NUM8		= 13,	// 발가스-10자베기
	ATMON_SKILL_NUM9		= 14,	// 켄타우로스-다발스킬
	ATMON_SKILL_NUM10		= 15,
	ATMON_SKILL_NUM11		= 16,	// 트윈테일 - 독공격
	ATMON_SKILL_NUM12		= 17,	// 드래드피어 - 2단공격
	ATMON_SKILL_NORMAL		= 18,	// 노멀 스킬
	ATMON_SKILL_STORM		= 19,	// 회오리 스킬
	ATMON_SKILL_SUMMON		= 20,	// 소환 스킬
	ATMON_SKILL_HELL		= 21,	// 헬버스터 스킬
	ATMON_SKILL_TELEPORT	= 22,	// 순간이동 스킬
	ATMON_SKILL_SHOCK		= 23,	// 충격파 스킬
	ATMON_SKILL_CRYSTAL		= 24,	// 크리스탈 스킬
	ATMON_SKILL_MAYASTORM	= 25,	// 회오리 스킬
	ATMON_SKILL_MAYACRYSTAL = 26,	// 크리스탈 메테오
	ATMON_SKILL_COURSED_STUN   = 27,
	ATMON_SKILL_COURSED_POISON = 28,
#ifdef CSK_RAKLION_BOSS
	// 라클리온 보스몬스터 스킬
	ATMON_SKILL_SERUFAN_POISONGEM = 34,		// 독구슬(세루판)
	ATMON_SKILL_SERUFAN_COOLSTORM = 35,		// 냉기폭풍(세루판)
	ATMON_SKILL_SERUFAN_COOLSHOCK = 36,		// 냉기충격(세루판)
	ATMON_SKILL_SERUFAN_FALLING = 37,		// 낙하(세루판)
	ATMON_SKILL_SERUFAN_SUMMON = 38,		// 소환(세루판)
	ATMON_SKILL_SERUFAN_HEAL = 39,			// 치료(세루판)
	ATMON_SKILL_SERUFAN_FREEZE = 40,		// 얼리기(세루판)
	ATMON_SKILL_SERUFAN_TELEPORT = 41,		// 순간이동(세루판)
	ATMON_SKILL_SERUFAN_SUPERMAN = 42,		// 무적(세루판)
#endif // CSK_RAKLION_BOSS
#ifdef LDS_ADD_EG_4_MONSTER_WORLDBOSS_GAIONKALEIN
	ATMON_SKILL_EMPIREGUARDIAN_BERSERKER = 59,				// 제국수호군 모든 보스 - 광폭화
	ATMON_SKILL_EMPIREGUARDIAN_GAION_02_BLOODATTACK = 64,	// 제국수호군 보스 가이온 - SKILL02 - 블러드어택
	ATMON_SKILL_EMPIREGUARDIAN_GAION_03_GIGANTIKSTORM = 65,	// 제국수호군 보스 가이온 - SKILL03 - 기간틱스톰
	ATMON_SKILL_EMPIREGUARDIAN_GAION_04_FLAMEATTACK = 66,	// 제국수호군 보스 가이온 - SKILL04 - 플레임
	ATMON_SKILL_EMPIREGUARDIAN_GAION_01_GENERALATTACK = 67,	// 제국수호군 보스 가이온 - SKILL01 - 기본공격	// 작업도중 추가
#endif // LDS_ADD_EG_4_MONSTER_WORLDBOSS_GAIONKALEIN
#ifdef LDS_EXTENSIONMAP_MONSTERS_AIDA
	ATMON_SKILL_EX_BLOODYGOLUEM_ATTACKSKILL = 68,		// 확장맵 몬스터 추가 스킬 (블러디 골렘)
	ATMON_SKILL_EX_BLOODYWITCHQUEEN_ATTACKSKILL = 69,	// 확장맵 몬스터 추가 스킬 (블러디 위치퀸)
#endif // LDS_EXTENSIONMAP_MONSTERS_AIDA
#ifdef LDS_EXTENSIONMAP_MONSTERS_KANTUR
	ATMON_SKILL_EX_BERSERKERWARRIOR_ATTACKSKILL = 70,	// 확장맵 몬스터 추가 스킬 (버서커 워리어)
	ATMON_SKILL_EX_KENTAURUSWARRIOR_ATTACKSKILL = 14,	// 확장맵 몬스터 추가 스킬 (켄타우루스 워리어)
	ATMON_SKILL_EX_GENOSIDEWARRIOR_ATTACKSKILL = 71,	// 확장맵 몬스터 추가 스킬 (제노사이드 워리어)
#endif // LDS_EXTENSIONMAP_MONSTERS_KANTUR
#ifdef LDS_EXTENSIONMAP_MONSTERS_SWAMPOFQUIET
	ATMON_SKILL_EX_SAPIQUEEN_ATTACKSKILL = 72,			// 확장맵 몬스터 추가 스킬 (사피퀸)
	ATMON_SKILL_EX_ICENAPIN_ATTACKSKILL = 73,			// 확장맵 몬스터 추가 스킬 (아이스 네이핀)
	ATMON_SKILL_EX_SHADOWMASTER_ATTACKSKILL = 74,		// 확장맵 몬스터 추가 스킬 (쉐도우 마스터)
#endif // LDS_EXTENSIONMAP_MONSTERS_SWAMPOFQUIET
#ifdef LDS_EXTENSIONMAP_MONSTERS_RAKLION
	ATMON_SKILL_EX_DARKMEMUD_ATTACKSKILL = 75,			// 확장맵 몬스터 추가 스킬 (다크 메머드)
	ATMON_SKILL_EX_DARKGIANT_ATTACKSKILL = 76,			// 확장맵 몬스터 추가 스킬 (다크 자이언트)
	ATMON_SKILL_EX_DARKAIONNIGHT_ATTACKSKILL = 32,		// 확장맵 몬스터 추가 스킬 (다크 아이언 나이트)
	ATMON_SKILL_EX_DARKCOOLERTIN_ATTACKSKILL = 77,		// 확장맵 몬스터 추가 스킬 (다크 쿨러틴)
#endif // LDS_EXTENSIONMAP_MONSTERS_RAKLION
	ATMON_SKILL_END,
};

//----------------------------------------------------------------------------
// 캐릭터의 행동 번호
enum ActionSkillType
{
	//////////////////////////////////////////////////////////////////////////
	//  스킬.
	//////////////////////////////////////////////////////////////////////////

	//마법사
	AT_SKILL_POISON			= 1,	//	포이즌			// 이곳부터 16개는 마법책과 대응한다.(수정할수 없다)
	AT_SKILL_METEO			= 2,	//	운석
	AT_SKILL_THUNDER		= 3,	//	번개
	AT_SKILL_FIREBALL		= 4,	//	파이어볼
	AT_SKILL_FLAME			= 5,	//	불기둥
	AT_SKILL_TELEPORT		= 6,	//	순간이동
	AT_SKILL_SLOW			= 7,	//	얼음
	AT_SKILL_STORM			= 8,	//	회오리
	AT_SKILL_EVIL			= 9,	//	악령
	AT_SKILL_HELL			= 10,	//	헬파이어
	AT_SKILL_POWERWAVE		= 11,	//	파워웨이브
	AT_SKILL_FLASH			= 12,	//	아쿠아플래쉬
	AT_SKILL_BLAST			= 13,	//	블래스트
	AT_SKILL_INFERNO		= 14,	//	인페르노
	AT_SKILL_TELEPORT_B		= 15,   //	텔레키네시스	// 순간이동 B. ( 파티원을 이동시킨다. )
	AT_SKILL_WIZARDDEFENSE	= 16,	//	소울바리어		// 물리공격방어 ***
	AT_SKILL_ENERGYBALL		= 17,	//	에너지볼
	
	AT_SKILL_BLAST_POISON		= 38,	//	데스포이즌
	AT_SKILL_BLAST_FREEZE		= 39,	//	서든아이스
	AT_SKILL_BLAST_HELL			= 40,	//	헬버스트
	AT_SKILL_BLAST_HELL_BEGIN	= 58,	//	헬버스트 시작.
	
	//기사
	AT_SKILL_BLOCKING   = 18,	//	방어
	AT_SKILL_SWORD1     = 19,	//	내려찍기
	AT_SKILL_SWORD2     = 20,	//	찌르기
	AT_SKILL_SWORD3     = 21,	//	올려치기
	AT_SKILL_SWORD4     = 22,	//	돌려치기
	AT_SKILL_SWORD5     = 23,	//	베기
	AT_SKILL_SPEAR		= 47,	//	창찌르기	(기마병 창 스킬 ***)
	AT_SKILL_VITALITY	= 48,	//	스웰라이프	(기사 생명력 증가	**)
	AT_SKILL_RIDER      = 49,	//	레이드슛	(기사 디노란트 공격. ***)


	//요정
	AT_SKILL_CROSSBOW   = 24,	//	다발 (활스킬)
	AT_SKILL_BOW        = 25,	//	활스킬
	AT_SKILL_HEALING    = 26,	//	치료       (에너지/5+(아이템레벨+1)*5)            //이곳부터는 마법구술과 대응한다.
	AT_SKILL_DEFENSE    = 27,	//	방어력증가 (약30초간 에너지/8+(아아템레벨+1)*2만큼 증가)
	AT_SKILL_ATTACK     = 28,	//	공격력증가 (약30초간 에너지/7+(아아템레벨+1)*3만큼 증가)
	AT_SKILL_SUMMON     = 30,	//	소환       (아아템레벨에 따라 몹소환)
	AT_SKILL_PARALYZE	= 51,	//	몬스터석화시키기			***
	AT_SKILL_PIERCING	= 52,	//	아이스애로우	(요정관통					***)
	AT_SKILL_IMPROVE_AG = 53,	//	민요정 ( AG증가 속도 증가. )
	AT_SKILL_BLAST_CROSSBOW4 = 54,	//	활스킬 ( 4 다발 ).
	

	//마검사
	AT_SKILL_REDUCEDEFENSE	= 55,	//	블러드어택	(몬스터 방어력 감소		***)
	AT_SKILL_ICE_BLADE      = 56,	//	파워슬래쉬	(데스블레이드 무기스킬)(순차적인 연쇄공격.)

	//다중공격
	AT_SKILL_WHEEL      = 41,		//  회오리베기
	AT_SKILL_FURY_STRIKE= 42,		//  분노의일격 (일정범위내에 있는 몬스터 공격속도/이동속도 30%느려짐.)
	AT_SKILL_ONETOONE	= 43,		//  블로우 (기사 1대1 공격		***)
	AT_SKILL_RUSH       = 44,   //  기사 돌격 스킬.
	AT_SKILL_JAVELIN    = 45,   //  법사 마법 표창 공격.
	AT_SKILL_DEEPIMPACT = 46,   //  요정 강력한 충격 공격.
	AT_SKILL_ONEFLASH   = 57,   //  기마검 일섬 공격.

	//몬스터
	AT_SKILL_BOSS       = 50,	

	//콤보스킬.
	AT_SKILL_COMBO		= 59,//콤보스킬.

	//. 다크로드
	AT_SKILL_STRONG_PIER        = 60,   //  스트롱 피어
	AT_SKILL_LONGPIER_ATTACK,           //  롱피어 어택.(파이어 버스트)
	AT_SKILL_DARK_HORSE,                //  다크홀스 어택.(어스퀘이크)
	AT_SKILL_PARTY_TELEPORT,            //  파티원 소환.
	AT_SKILL_ADD_CRITICAL,              //  크리티컬데미지증가
	AT_SKILL_THUNDER_STRIKE,            //  일렉트릭 스파이크.
	AT_SKILL_LONG_SPEAR,                //  서버에서만 사용하는 롱스피어. 
	AT_SKILL_STUN               ,       //  스턴.
	AT_SKILL_REMOVAL_STUN       ,       //  스턴 제거.
	AT_SKILL_MANA               ,       //  마나증가.
	AT_SKILL_INVISIBLE          ,       //  투명.(70)
	AT_SKILL_REMOVAL_INVISIBLE  ,       //  투명 해제.
	AT_SKILL_REMOVAL_BUFF       ,       //  보조마법 일시 제거.
	AT_SKILL_DEATH_CANNON       ,       //  법마검 마살포 공격.
	AT_SKILL_SPACE_SPLIT        ,       //  다크로드 공격스킬 ( 공간 가르기 ).
	AT_SKILL_BRAND_OF_SKILL     ,       //  다크로드 스킬의 낙인 ( 확장된 스킬을 사용할수 있게 하는 스킬 )
	AT_SKILL_PLASMA_STORM_FENRIR	= 76	,	// 펜릴 플라즈마 스톰(76)
	AT_SKILL_INFINITY_ARROW		,		//	지속시간동안 화살의 내구도가 닳지 않는다.
	AT_SKILL_DARK_SCREAM,				// 파이어 스크림
	AT_SKILL_EXPLODE,

//////////////////////////////////////////////////////////////////////////
//  옵션.
//////////////////////////////////////////////////////////////////////////
	AT_IMPROVE_DAMAGE           ,//추가 공격력           (Level*4)
	AT_IMPROVE_MAGIC            ,//추가 마력             (Level*4)
	AT_IMPROVE_CURSE            ,//추가 저주력
	AT_IMPROVE_BLOCKING         ,//추가 방어율           (Level*5)
	AT_IMPROVE_DEFENSE          ,//추가 방어력           (Level*4)
	AT_LUCK                     ,//영혼의 보석 성공 확율 +25%
	AT_LIFE_REGENERATION        ,//생명 자동 회복        (Level*1%)

	AT_IMPROVE_LIFE             ,//생명력 증가
	AT_IMPROVE_MANA             ,//마나 증가
	AT_DECREASE_DAMAGE          ,//데미지 감소
	AT_REFLECTION_DAMAGE        ,//데미지 반사
	AT_IMPROVE_BLOCKING_PERCENT ,//방어성공율
	AT_IMPROVE_GAIN_GOLD        ,//획득 젠 증가
	AT_EXCELLENT_DAMAGE         ,//액설런트 데미지 증가
	AT_IMPROVE_DAMAGE_LEVEL     ,//공격력 증가(레벨)
	AT_IMPROVE_DAMAGE_PERCENT   ,//공격력 증가(2퍼센트)
	AT_IMPROVE_MAGIC_LEVEL      ,//마력 증가(레벨)
	AT_IMPROVE_MAGIC_PERCENT    ,//마력 증가(퍼센트)
	AT_IMPROVE_ATTACK_SPEED     ,//공격 속도
	AT_IMPROVE_GAIN_LIFE        ,//획득 생명력
	AT_IMPROVE_GAIN_MANA        ,//획득 마나

	//  날개 추가 옵션.
	AT_IMPROVE_HP_MAX           ,   //  최대 HP +50 증가.
	AT_IMPROVE_MP_MAX           ,   //  최대 MP +50 증가.
	AT_ONE_PERCENT_DAMAGE       ,   //  3% 확률로 적에 방어력 무시 공격.
	AT_IMPROVE_AG_MAX           ,   //  최대 AG +50 증가.
	AT_DAMAGE_ABSORB            ,   //  추가 데미지 흡수.

	//  날개 3차 추가 옵션
	AT_DAMAGE_REFLECTION     ,	// [대상의 공격이 유저에게 명중한 경우] 5% 확률로 적 공격력 50% 돌려줌
	AT_RECOVER_FULL_LIFE     ,	// [대상의 공격이 유저에게 명중한 경우] 5% 확률로 유저 생명 100% 순간 회복
	AT_RECOVER_FULL_MANA     ,	// [대상의 공격이 유저에게 명중한 경우] 5% 확률로 유저 마나 100% 순간 회복

	//  망토 추가 옵션.
	AT_IMPROVE_CHARISMA         ,   //  통솔 증가.

	//  디노란트.
	AT_IMPROVE_EVADE            = 110,   //  캐릭터 회피율 10% 증가.

	//  몬스터 스킬.
	AT_SKILL_MONSTER_SUMMON     = 200,  //  몬스터 소환.
	AT_SKILL_MONSTER_MAGIC_DEF  ,       //  마법 방어력 최고.
	AT_SKILL_MONSTER_PHY_DEF    ,       //  물리 방어력 최고.
	AT_SKILL_HELLOWIN_EVENT_1	= 205,
	AT_SKILL_HELLOWIN_EVENT_2	= 206,
	AT_SKILL_HELLOWIN_EVENT_3	= 207,
	AT_SKILL_HELLOWIN_EVENT_4	= 208,
	AT_SKILL_HELLOWIN_EVENT_5	= 209,
	AT_SKILL_CURSED_TEMPLE_PRODECTION  = 210,        //보호의 주문
	AT_SKILL_CURSED_TEMPLE_RESTRAINT   = 211,        //속박의 주문
	AT_SKILL_CURSED_TEMPLE_TELEPORT    = 212,        //소환의 주문
//	AT_SKILL_CURSED_TEMPLE_QUICKNESS   = 213,        //신속의 주문
	AT_SKILL_CURSED_TEMPLE_SUBLIMATION = 213,        //쉴듭번
	AT_SKILL_ALICE_DRAINLIFE = 214,				// 214	"드레인 라이프"
	AT_SKILL_ALICE_CHAINLIGHTNING = 215,		// 215	"체인 라이트닝"
	AT_SKILL_ALICE_LIGHTNINGORB = 216,			// 216	"라이트닝 오브"
	AT_SKILL_ALICE_THORNS = 217,				// 217	"쏜즈"
	AT_SKILL_ALICE_BERSERKER = 218,				// 218	"버서커"
	AT_SKILL_ALICE_SLEEP = 219,					// 219	"슬립"
	AT_SKILL_ALICE_BLIND = 220,					// 220	"블라인드"
	AT_SKILL_ALICE_WEAKNESS = 221,				// 221	"위크니스"
	AT_SKILL_ALICE_ENERVATION = 222,			// 222	"이너베이션"

	// 소환술사
	AT_SKILL_SUMMON_EXPLOSION = 223,			// 익스플로전
	AT_SKILL_SUMMON_REQUIEM,					// 레퀴엠
#ifdef ASG_ADD_SUMMON_RARGLE
	AT_SKILL_SUMMON_POLLUTION = 225,			// 펄루션.
#endif	// ASG_ADD_SUMMON_RARGLE
	
	// Season4 신규 스킬
#ifdef YDG_ADD_SKILL_LIGHTNING_SHOCK
	AT_SKILL_LIGHTNING_SHOCK = 230,			// 230 소환술사 라이트닝 쇼크
#endif	// YDG_ADD_SKILL_LIGHTNING_SHOCK
#ifdef CSK_ADD_SKILL_BLOWOFDESTRUCTION
	AT_SKILL_BLOW_OF_DESTRUCTION = 232,		// 232	"파괴의일격"
#endif // CSK_ADD_SKILL_BLOWOFDESTRUCTION
	
#ifdef KJH_ADD_SKILL_SWELL_OF_MAGICPOWER
	AT_SKILL_SWELL_OF_MAGICPOWER = 233,			// 233	흑마법사(소울마스터) "마력증대"
#endif // KJH_ADD_SKILL_SWELL_OF_MAGICPOWER

#ifdef YDG_ADD_SKILL_FLAME_STRIKE
	AT_SKILL_FLAME_STRIKE = 236,		// 236 마검사 플레임 스크라이크
#endif	// YDG_ADD_SKILL_FLAME_STRIKE
#ifdef YDG_ADD_SKILL_GIGANTIC_STORM
	AT_SKILL_GIGANTIC_STORM = 237,		// 237 마검사 기간틱 스톰
#endif	// YDG_ADD_SKILL_GIGANTIC_STORM
#ifdef PJH_SEASON4_SPRITE_NEW_SKILL_RECOVER
	AT_SKILL_RECOVER = 234,             // 234 회복
#endif //PJH_SEASON4_SPRITE_NEW_SKILL_RECOVER
#ifdef PJH_SEASON4_SPRITE_NEW_SKILL_MULTI_SHOT
	AT_SKILL_MULTI_SHOT = 235,
#endif //PJH_SEASON4_SPRITE_NEW_SKILL_MULTI_SHOT
#ifdef PJH_SEASON4_DARK_NEW_SKILL_CAOTIC
	AT_SKILL_GAOTIC = 238,
#endif //PJH_SEASON4_DARK_NEW_SKILL_CAOTIC
#ifdef YDG_ADD_DOPPELGANGER_MONSTER
	AT_SKILL_DOPPELGANGER_SELFDESTRUCTION = 239,	// 239 도플갱어 자폭
#endif	// YDG_ADD_DOPPELGANGER_MONSTER
#ifdef PBG_ADD_NEWCHAR_MONK_SKILL		// 레이지파이터 스킬
	AT_SKILL_THRUST = 260,				// 찌르기
	AT_SKILL_STAMP = 261,				// 내려찍기
	AT_SKILL_GIANTSWING = 262,			// 자이언트 스윙
	AT_SKILL_DARKSIDE = 263,			// 다크사이드
	AT_SKILL_DRAGON_LOWER = 264,		// 드레곤로어
	AT_SKILL_DRAGON_KICK = 265,			// 드레곤킥
	AT_SKILL_ATT_UP_OURFORCES = 266,	// 공격성공율향상
	AT_SKILL_HP_UP_OURFORCES = 267,		// 체력향상
	AT_SKILL_DEF_UP_OURFORCES = 268,	// 방어성공율향상
	AT_SKILL_OCCUPY = 269,				// 차지
#endif //PBG_ADD_NEWCHAR_MONK_SKILL

	AT_SKILL_ATTACK_RATEUP		= 300,								//공격 성공율 상승.
	AT_SKILL_TOMAN_ATTACKUP		= AT_SKILL_ATTACK_RATEUP + 5,		//대인 공격율 상승.
	AT_SKILL_TOMAN_DEFENCEUP	= AT_SKILL_TOMAN_ATTACKUP + 5,		//대인 방어율 증가.
	AT_SKILL_DURABLE_MINUS1		= AT_SKILL_TOMAN_DEFENCEUP + 5,		//내구 감소 1
	AT_SKILL_DURABLE_MINUS2		= AT_SKILL_DURABLE_MINUS1 + 5,		//내구 감소 2
	AT_SKILL_RESIST_UP_POISON	= AT_SKILL_DURABLE_MINUS2 + 5,		//저항력 상승(독)
	AT_SKILL_RESIST_UP_LIGHT	= AT_SKILL_RESIST_UP_POISON + 5,	//저항력 상승(번개)
	AT_SKILL_RESIST_UP_ICE		= AT_SKILL_RESIST_UP_LIGHT + 5,		//저항력 상승(얼음)
	AT_SKILL_AUTO_RECOVER_LIFE	= AT_SKILL_RESIST_UP_ICE + 5,		//생명력 자동 회복 강화
	AT_SKILL_GET_MONEY_UP		= AT_SKILL_AUTO_RECOVER_LIFE + 5,	//젠 증가
	AT_SKILL_DEF_UP				= AT_SKILL_GET_MONEY_UP + 5,		//방어력 증가(350)
	AT_SKILL_MAX_HP_UP			= AT_SKILL_DEF_UP + 5,				//최대HP증가
	AT_SKILL_MAX_AG_UP			= AT_SKILL_MAX_HP_UP + 5,			//최대AG증가
	AT_SKILL_MANA_RECOVER		= AT_SKILL_MAX_AG_UP + 5,			//몬스터킬시마나회복
	AT_SKILL_HP_RECOVER			= AT_SKILL_MANA_RECOVER + 5,		//몬스터킬시생명력회복
	AT_SKILL_SD_RECOVER			= AT_SKILL_HP_RECOVER + 5,			//몬스터킬시SD증가
	AT_SKILL_EXP_UP				= AT_SKILL_SD_RECOVER + 5,			//경험치상승
	AT_SKILL_MAX_SD_UP			= AT_SKILL_EXP_UP + 5,				//최대SD증가
	AT_SKILL_SD_RECOVER_SPD_UP	= AT_SKILL_MAX_SD_UP + 5,			//SD회복속도상승
	AT_SKILL_MAX_ATTACKRATE_UP  = AT_SKILL_SD_RECOVER_SPD_UP + 5,	//최대공격력상승
	AT_SKILL_MIN_ATTACKRATE_UP  = AT_SKILL_MAX_ATTACKRATE_UP + 5,	//최소공격력상승(400)
	AT_SKILL_MANA_MINUS_ADD     = AT_SKILL_MIN_ATTACKRATE_UP + 5,	//마나감소강화
	AT_SKILL_MAX_MANA_UP		= AT_SKILL_MANA_MINUS_ADD + 5,		//최대마력상승
	AT_SKILL_MIN_MANA_UP		= AT_SKILL_MAX_MANA_UP + 5,			//최소마력상승
	AT_SKILL_PET_DURABLE_SPD_DN = AT_SKILL_MIN_MANA_UP + 5,			//펫내구소모속도감소
	AT_SKILL_MAX_ATT_MAGIC_UP	= AT_SKILL_PET_DURABLE_SPD_DN + 5,	//최대공격력/마력상승
	AT_SKILL_MIN_ATT_MAGIC_UP   = AT_SKILL_MAX_ATT_MAGIC_UP	+ 5,	//최소공격력/마력상승

	AT_SKILL_SOUL_UP			= AT_SKILL_MIN_ATT_MAGIC_UP	+ 5,	//소울바리어강화
	AT_SKILL_HELL_FIRE_UP		= AT_SKILL_SOUL_UP + 5,				//헬파이어강화
	AT_SKILL_EVIL_SPIRIT_UP		= AT_SKILL_HELL_FIRE_UP + 5,		//악령강화(흑마법사)
	AT_SKILL_ICE_UP				= AT_SKILL_EVIL_SPIRIT_UP + 5,		//서든아이스강화(450)
	AT_SKILL_TORNADO_SWORDA_UP	= AT_SKILL_ICE_UP + 5,				//회오리베기강화A(흑기사)
	AT_SKILL_BLOW_UP			= AT_SKILL_TORNADO_SWORDA_UP + 5,	//블로우강화
	AT_SKILL_ANGER_SWORD_UP		= AT_SKILL_BLOW_UP + 5,				//분노의일격강화
	AT_SKILL_LIFE_UP			= AT_SKILL_ANGER_SWORD_UP + 5,		//스웰라이프강화

	AT_SKILL_HEAL_UP			= AT_SKILL_LIFE_UP + 5,				//치료강화
	AT_SKILL_DEF_POWER_UP		= AT_SKILL_HEAL_UP + 5,				//방어력향상강화
	AT_SKILL_ATT_POWER_UP		= AT_SKILL_DEF_POWER_UP + 5,		//공격력향상강화
	AT_SKILL_MANY_ARROW_UP		= AT_SKILL_ATT_POWER_UP + 5,		//다발강화

	AT_SKILL_TORNADO_SWORDB_UP	= AT_SKILL_MANY_ARROW_UP + 5,		//회오리베기강화B
	AT_SKILL_BLOOD_ATT_UP		= AT_SKILL_TORNADO_SWORDB_UP + 5,   //블러드어택강화(500)
	AT_SKILL_POWER_SLASH_UP		= AT_SKILL_BLOOD_ATT_UP + 5,		//파워슬래쉬강화
	AT_SKILL_BLAST_UP			= AT_SKILL_POWER_SLASH_UP + 5,		//블래스트강화

	AT_SKILL_ASHAKE_UP			= AT_SKILL_BLAST_UP + 5,			//어스쉐이크강화
	AT_SKILL_FIRE_BUST_UP		= AT_SKILL_ASHAKE_UP + 5,			//파이어버스트강화
	AT_SKILL_FIRE_SCREAM_UP		= AT_SKILL_FIRE_BUST_UP + 5,		//파이어스크림강화

	AT_SKILL_EVIL_SPIRIT_UP_M	= AT_SKILL_FIRE_SCREAM_UP + 5,		//악령강화(마검사)
#ifdef PJH_ADD_MASTERSKILL
	AT_SKILL_ALICE_SLEEP_UP				= AT_SKILL_EVIL_SPIRIT_UP_M + 5,		//슬립 강화
	AT_SKILL_ALICE_CHAINLIGHTNING_UP	= AT_SKILL_ALICE_SLEEP_UP + 5,	//체인라이트닝 강화
	AT_SKILL_LIGHTNING_SHOCK_UP			= AT_SKILL_ALICE_CHAINLIGHTNING_UP + 5,	//라이트닝쇼크(오브) 강화
	AT_SKILL_ALICE_DRAINLIFE_UP			= AT_SKILL_LIGHTNING_SHOCK_UP + 5,		//드레인라이프 강화
#endif
};


enum    PetCommandType
{
	//  커맨드 스킬.
	AT_PET_COMMAND_DEFAULT      = 120,  //  일반 행동.
	AT_PET_COMMAND_RANDOM       ,       //  랜덤 공격.
	AT_PET_COMMAND_OWNER        ,       //  주인과 같이 공격.
	AT_PET_COMMAND_TARGET       ,       //  타켓 공격.
	AT_PET_COMMAND_END          ,   
};

enum    OptionType
{

	//////////////////////////////////////////////////////////////////////////
	//  행동.
	//////////////////////////////////////////////////////////////////////////

	AT_ATTACK1          = 120,
	AT_ATTACK2,

	AT_STAND1,
	AT_STAND2,
	AT_MOVE1,
	AT_MOVE2,

	AT_DAMAGE1,
	AT_DIE1,
	AT_SIT1,
	AT_POSE1,
	AT_HEALING1,
	AT_GREETING1,
	AT_GOODBYE1,
	AT_CLAP1,
	AT_GESTURE1,
	AT_DIRECTION1,
	AT_UNKNOWN1,
	AT_CRY1,
	AT_CHEER1,
	AT_AWKWARD1,
	AT_SEE1,
	AT_WIN1,
	AT_SMILE1,
	AT_SLEEP1,
	AT_COLD1,
	AT_AGAIN1,
	AT_RESPECT1,
	AT_SALUTE1,
	AT_RUSH1,
	AT_SCISSORS,	// 가위
	AT_ROCK,		// 바위
	AT_PAPER,		// 보
	AT_HUSTLE,		// 일본 레슬러 동작
	AT_PROVOCATION,
	AT_LOOK_AROUND,
	AT_CHEERS,
	AT_JACK1,		// 잭 행동1
	AT_JACK2,		// 잭 행동2
	AT_SANTA1_1,		// 산타 행동1
	AT_SANTA1_2,
	AT_SANTA1_3,
	AT_SANTA2_1,		// 산타 행동2
	AT_SANTA2_2,
	AT_SANTA2_3,
#ifdef PBG_ADD_NEWCHAR_MONK_SKILL
	AT_RAGEBUFF_1,
	AT_RAGEBUFF_2,
#endif //PBG_ADD_NEWCHAR_MONK_SKILL

	//////////////////////////////////////////////////////////////////////////
	//  세트 옵션.
	//////////////////////////////////////////////////////////////////////////
#ifdef PBG_ADD_NEWCHAR_MONK_SKILL
	AT_SET_OPTION_IMPROVE_STRENGTH              = AT_RAGEBUFF_2+1,  //	힘 증가                         (●)	                
#else //PBG_ADD_NEWCHAR_MONK_SKILL
	AT_SET_OPTION_IMPROVE_STRENGTH              = 140,  //	힘 증가                         (●)	                
#endif //PBG_ADD_NEWCHAR_MONK_SKILL
	AT_SET_OPTION_IMPROVE_DEXTERITY,					//	민첩성 증가                     (●)		            
	AT_SET_OPTION_IMPROVE_ENERGY,						//	에너지 증가	                    (●)	                
	AT_SET_OPTION_IMPROVE_VITALITY,					    //	체력 증가	                    (●)	                
	AT_SET_OPTION_IMPROVE_CHARISMA,					    //	통솔력 증가	                    (●)	                
	AT_SET_OPTION_IMPROVE_ATTACK_MIN,                   //  최소 공격력 증가    
	AT_SET_OPTION_IMPROVE_ATTACK_MAX,                   //  최대 공격력 증가
	AT_SET_OPTION_IMPROVE_MAGIC_POWER,                  //  마력 증가
	AT_SET_OPTION_IMPROVE_DAMAGE,		                //	데미지 증가
	AT_SET_OPTION_IMPROVE_ATTACKING_PERCENT,			//	공격 성공률 증가                (●)
	AT_SET_OPTION_IMPROVE_DEFENCE,				        //	방어력 증가                     (●)
	AT_SET_OPTION_IMPROVE_MAX_LIFE,					    //	최대 생명력 증가
	AT_SET_OPTION_IMPROVE_MAX_MANA,					    //	최대 마나 증가
	AT_SET_OPTION_IMPROVE_MAX_AG,						//	최대 AG 증가
	AT_SET_OPTION_IMPROVE_ADD_AG,					    //	AG 증가양 증가	                (●)
	AT_SET_OPTION_IMPROVE_CRITICAL_DAMAGE_PERCENT,      //  크리티컬 데미지 확률 증가
	AT_SET_OPTION_IMPROVE_CRITICAL_DAMAGE,              //  크리티컬 데미지 증가
	AT_SET_OPTION_IMPROVE_EXCELLENT_DAMAGE_PERCENT,     //  액설런트 데미지 확률 증가
	AT_SET_OPTION_IMPROVE_EXCELLENT_DAMAGE,             //  액설런트 데미지 증가
	AT_SET_OPTION_IMPROVE_SKILL_ATTACK,                 //  스킬 공격력 증가
	AT_SET_OPTION_DOUBLE_DAMAGE,                        //	더블 데미지 확률
	AT_SET_OPTION_DISABLE_DEFENCE,                      //  적 방어력 무시
	AT_SET_OPTION_IMPROVE_SHIELD_DEFENCE,               //  방패 장비시 방어력 증가.
	AT_SET_OPTION_TWO_HAND_SWORD_IMPROVE_DAMAGE,        //  양손검 장비시 데미지 증가.
	
	AT_SET_OPTION_IMPROVE_ATTACK_2,						//	특정 캐릭터 공격력 증가 힘/50   	(●)
	AT_SET_OPTION_IMPROVE_ATTACK_1,						//	특정 캐릭터 공격력 증가 민첩성/60	(●)
	AT_SET_OPTION_IMPROVE_DEFENCE_3,					//	특정 캐릭터 방어력 증가 민첩성/50	(●)
	AT_SET_OPTION_IMPROVE_DEFENCE_4,					//	특정 캐릭터 방어력 증가 체력/40	    (●)
	AT_SET_OPTION_IMPROVE_MAGIC,						//	특정 캐릭터 마력 증가 에너지/70	    (●)
	AT_SET_OPTION_ICE_MASTERY,							//	특정 캐릭터 얼음속성 추가			    
	AT_SET_OPTION_POSION_MASTERY,						//	특정 캐릭터 독속성 추가			        
	AT_SET_OPTION_THUNDER_MASTERY,						//	특정 캐릭터 번개속성 추가			    
	AT_SET_OPTION_FIRE_MASTERY,							//	특정 캐릭터 불속성 추가			        
	AT_SET_OPTION_EARTH_MASTERY,						//	특정 캐릭터 땅속성 추가			        
	AT_SET_OPTION_WIND_MASTERY,							//	특정 캐릭터 바람속성 추가			    
	AT_SET_OPTION_WATER_MASTERY,						//	특정 캐릭터 물속성 추가			        

	AT_IMPROVE_MAX_MANA,                                //  최대 마나 증가 옵션. ( 1%, 2%, 3%, 4% )
	AT_IMPROVE_MAX_AG,                                  //  최대 AG증가 옵션. ( 1%, 2%, 3%, 4% )
};
//publicfile end

//npcbreederfile start
enum
{
	BREEDER_NONE    = 0 ,
	BREEDER_START       ,   //  원하는 명령 선택창을 띄운다.
	BREEDER_RECOVERY    ,   //  생명 회복창 띄운다.
	BREEDER_REVIVAL     ,   //  영혼 환생창 띄운다.
//  BREEDER_UPGRADE     ,   //  업그레이드창 띄운다.
	BREEDER_END
};

enum
{
	REVIVAL_NONE    = 0 ,   //  조합 조건 no.
	REVIVAL_DARKHORSE   ,   //  다크홀스 환생.
	REVIVAL_DARKSPIRIT  ,   //  다크스피릿 환생.
#ifdef DARK_WOLF
	REVIVAL_DARKWOLF    ,   //  다크울프 환생.
#endif// DARK_WOLF
	REVIVAL_END
};

enum
{
	REVIVAL_SUCCESS = 0 ,   //  환생 성공 조건.
	REVIVAL_ERROR_ZEN   ,   //  젠부족.
	REVIVAL_ERROR_LEVEL ,   //  레벨부족.
	REVIVAL_ERROR_END   
};

enum
{
	ITEM_ETC_TYPE   = 0 ,
	ITEM_DARKHORSE      ,                    
	ITEM_DARKSPIRIT     ,
#ifdef DARK_WOLF
	ITEM_DARKWOLF       ,   
#endif// DARK_WOLF
	ITEM_BLESS_GEM      ,
	ITEM_SPIRIT_GEM     ,
	ITEM_CHAOS_GEM      ,
	ITEM_CREATING_GEM   ,
	ITEM_LIFE_GEM       ,
	ITEM_END
};
//npcbreederfile end

//gm_kanturu_2nd start
enum POPUP_MESSAGE
{
	POPUP_NONE = 0,
	POPUP_USER_OVER,	// 입장 가능한 인원 수 초과
	POPUP_NOT_MUNSTONE,	// 문스톤 펜던트 착용하고 있는 않다.
	POPUP_FAILED,		// 입장 가능한 상태가 아님
	POPUP_FAILED2,		// 이상한 오류로 실패
	POPUP_UNIRIA = 5,	// 유니리아를 탑승하고 이동 불과
	POPUP_CHANGERING,	// 변신반지 착용하면 이동 불과
	POPUP_NOT_HELPER,	// 날개, 망토, 디노란트, 펜릴, 다크호스를 가지고 있지 않을 경우
};
//gm_kanturu_2nd end

//csquest start
enum    //  퀘스트 타입.
{
	TYPE_QUEST = 0,         //  기본 퀘스트.
	TYPE_DEVIL_SQUARE,      //  악마의 광장.
	TYPE_BLOOD_CASTLE,      //  블러드캐슬.
	TYPE_CURSEDTEMPLE,      //  환영사원
	TYPE_QUEST_END
};

enum    //  퀘스트를 보여주는 대상.
{
	QUEST_VIEW_NONE = 0,
	QUEST_VIEW_NPC,
	QUEST_VIEW_PREVIEW,
	QUEST_VIEW_END
};

enum    //
{
	QUEST_ITEM = 1,
	QUEST_MONSTER,
};

enum    //  퀘스트 상태.
{
	QUEST_NONE = 0, //
	QUEST_ING = 1,  //  퀘스트 진행 상태.
	QUEST_END,      //  퀘스트 완료 상태.
	QUEST_NO,       //  퀘스트를 받지 않은 상태.
	QUEST_READY,    //  퀘스트 대기 상태.
	QUEST_ERROR,    //  에러 상태.
};

enum	//	퀘스트 리스트.
{
	QUEST_CHANGE_UP_1 = 0,	//	1차 전직 퀘스트.
	QUEST_CHANGE_UP_2,		//	2차 전직 퀘스트.
	QUEST_CHANGE_UP_3,		//	3차 전직 퀘스트.
	QUEST_COMBO,			//	콤보 퀘스트.
	QUEST_3RD_CHANGE_UP_1,	//	3차 전직 퀘스트.
	QUEST_3RD_CHANGE_UP_2,	//	3차 전직 퀘스트.
	QUEST_3RD_CHANGE_UP_3,	//	3차 전직 퀘스트.
	QUEST_LIST_END
};
//csquest end

//cspetsystem start
enum
{
	PET_FLYING    = 0,
	PET_FLY          ,      //  하늘을 난다.
	PET_ESCAPE       ,      //  회피.
	PET_STAND        ,      //  손에 서있는다.
	PET_STAND_START  ,      //  손의 위치로 강제로 이동을 한다.
	PET_ATTACK       ,      //  맨 몸 공격한다.
	PET_ATTACK_MAGIC ,      //  특수 공격1.
	PET_END
};


enum    PET_TYPE
{
#ifdef KJH_FIX_DARKLOAD_PET_SYSTEM
	PET_TYPE_NONE		 = -1,	// 펫이 없을때,
#endif // KJH_FIX_DARKLOAD_PET_SYSTEM
	PET_TYPE_DARK_SPIRIT = 0,   //  다크 스피릿.
	PET_TYPE_DARK_HORSE,        //  다크 호스.
//	PET_TYPE_DARK_WOLF,         //  다크 울프. (사용안함)
	PET_TYPE_END
};


enum    PET_COMMAND
{
	PET_CMD_DEFAULT = 0 ,   //  기본 상태.
	PET_CMD_RANDOM      ,   //  랜덤 공격.
	PET_CMD_OWNER       ,   //  주인과 같이 공격.
	PET_CMD_TARGET      ,   //  타켓공격.
	PET_CMD_END
};
//cspetsystem end

//csparts start
enum    
{
#ifdef LJW_FIX_PARTS_ENUM
	PARTS_NONE = 0,
	PARTS_START,
	PARTS_STAFF = PARTS_START,
	PARTS_SWORD,
	PARTS_BOW,
#endif // LJW_FIX_PARTS_ENUM
	PARTS_LION = 4,
	PARTS_WEBZEN,
	PARTS_ATTACK_TEAM_MARK,
	PARTS_ATTACK_TEAM_MARK2,
	PARTS_ATTACK_TEAM_MARK3,
	PARTS_ATTACK_KING_TEAM_MARK,
	PARTS_ATTACK_KING_TEAM_MARK2,
	PARTS_ATTACK_KING_TEAM_MARK3,
	PARTS_DEFENSE_TEAM_MARK,
	PARTS_DEFENSE_KING_TEAM_MARK,
	PARTS_END
};
//csparts end

//csmapinterface start
enum
{
	TYPE_OBSERVER = 0,
	TYPE_GUILD_SOLDIER,
	TYPE_GUILD_COMMANDER
};
//csmapinterface end

//csitemsetoption start
enum
{
	SET_OPTION_NONE = 0,        //  옵션이 없음.
	SET_OPTION_STRENGTH,        //  힘 옵션 증가.
	SET_OPTION_DEXTERITY,       //  민첩 옵션 증가.
	SET_OPTION_ENERGY,          //  에너지 옵션 증가.
	SET_OPTION_VITALITY,        //  체력 옵션 증가.
	SET_OPTION_END
};
//csitemsetoption start


//cseventmatch start
enum  MATCH_TYPE
{
	TYPE_MATCH_NONE = 0,
	TYPE_MATCH_DEVIL_ENTER_START,   //  악마의광장 입장시작
	TYPE_MATCH_DEVIL_ENTER_CLOSE,   //  악마의광장 입장마감
	TYPE_MATCH_DEVIL_CLOSE,         //  악마의광장 패쇄
	TYPE_MATCH_CASTLE_ENTER_CLOSE,  //  블러드캐슬 입장마감
	TYPE_MATCH_CASTLE_INFILTRATION, //  블러드캐슬 잠입
	TYPE_MATCH_CASTLE_CLOSE,        //  블러드캐슬 경기 종료
	TYPE_MATCH_CASTLE_END,          //  블러드캐슬 경기 패쇄
	TYPE_MATCH_CHAOS_ENTER_START = 11,  //  카오스 캐슬 입장시작
	TYPE_MATCH_CHAOS_EINFILTRATION,     //  카오스 캐슬 잠입
	TYPE_MATCH_CHAOS_CLOSE,             //  카오스 캐슬 종료
	TYPE_MATCH_CHAOS_END,               //  카오스 캐슬 패쇄
	TYPE_MATCH_CURSEDTEMPLE_ENTER_CLOSE, 
	TYPE_MATCH_CURSEDTEMPLE_GAME_START, 
#ifdef YDG_ADD_DOPPELGANGER_UI
	TYPE_MATCH_DOPPELGANGER_ENTER_CLOSE,
	TYPE_MATCH_DOPPELGANGER_GAME_START,
	TYPE_MATCH_DOPPELGANGER_ICEWALKER,
	TYPE_MATCH_DOPPELGANGER_CLOSE,
#endif	// YDG_ADD_DOPPELGANGER_UI
	TYPE_MATCH_END
};

enum
{
	MATCH_TYPE_NONE_EVENT = 0,
	MATCH_TYPE_DEVIL_SQUARE,
	MATCH_TYPE_BLOOD_CASTLE,
	MATCH_TYPE_END
};
//cseventmatch end

// 명령창
enum COMMAND_TYPE
{
	COMMAND_NONE  = -1, //  초기값.
	COMMAND_TRADE = 0,  //  거래.
	COMMAND_PURCHASE,	//  구매.
	COMMAND_PARTY,      //  파티.
	COMMAND_WHISPER,    //  귓속말.
	COMMAND_GUILD,      //  길드.
	COMMAND_GUILDUNION,	//  길드연합.
	COMMAND_RIVAL,		//  적대길드.
	COMMAND_RIVALOFF,	//  적대길드해제.
	COMMAND_ADD_FRIEND, //  친구추가.
	COMMAND_FOLLOW,     //  따라가기.
	COMMAND_BATTLE,     //  결투.
#ifndef KJH_DEL_PC_ROOM_SYSTEM				// #ifndef
#ifdef ADD_PCROOM_POINT_SYSTEM
	COMMAND_PCBANG,		// PC방 포인트 상점.
#endif	// ADD_PCROOM_POINT_SYSTEM
#endif // KJH_DEL_PC_ROOM_SYSTEM
	COMMAND_END
};


//cmvp1stdirection start

enum CRYWOLF_OCCUPATION_STATE_TYPE			  // 크라이 울프 맵 상태
{
	CRYWOLF_OCCUPATION_STATE_PEACE		= 0,  // 평화상태
	CRYWOLF_OCCUPATION_STATE_OCCUPIED	= 1,  // 점령상태
	CRYWOLF_OCCUPATION_STATE_WAR		= 2,  // 전쟁상태
};

enum CRYWOLF_STATE_TYPE						  // 크라이 울프 진행 상태
{
	CRYWOLF_STATE_NONE					= 0,  // NONE
	CRYWOLF_STATE_NOTIFY_1				= 1,  // 공지 1
	CRYWOLF_STATE_NOTIFY_2				= 2,  // 공지 2
	CRYWOLF_STATE_READY					= 3,  // 준비
	CRYWOLF_STATE_START					= 4,  // 시작
	CRYWOLF_STATE_END					= 5,  // 종료
	CRYWOLF_STATE_ENDCYCLE				= 6,  // 종료 후 주기 재시작 준비
};

enum CRYWOLF_ALTAR_STATE					  // 늑대의 제단 상태
{
	CRYWOLF_ALTAR_STATE_NONE					= 0,  // 계약 상태 아님
	CRYWOLF_ALTAR_STATE_CONTRACTED				= 1,  // 계약 상채 중임
	CRYWOLF_ALTAR_STATE_APPLYING_CONTRACT		= 2,  // 계약을 시도 중임
	CRYWOLF_ALTAR_STATE_EXCEEDING_CONTRACT_COUNT= 3,  // 계약 횟수를 초과했음
	CRYWOLF_ALTAR_STATE_OCCUPYING				= 4,  // 제단 점령을 시도 중이다
	CRYWOLF_ALTAR_STATE_OCCUPIED				= 5,  // 제단이 점령 되었음
};

//cmvp1stdirection end

//ckanturudirection start
enum KANTURU_STATE_TYPE				  // 칸투르 진행 상태
{
	KANTURU_STATE_NONE				= 0,  // NONE
	KANTURU_STATE_STANDBY			= 1,  // 칸투르 준비
	KANTURU_STATE_MAYA_BATTLE		= 2,  // 마야 전투
	KANTURU_STATE_NIGHTMARE_BATTLE	= 3,  // 나이트메어 전투
	KANTURU_STATE_TOWER				= 4,  // 정재의 탑
	KANTURU_STATE_END				= 5,  // 끝

};

enum KANTURU_MAYA_DIRECTION_TYPE
{
	KANTURU_MAYA_DIRECTION_NONE				= 0,
	KANTURU_MAYA_DIRECTION_STANBY1			= 1,
	KANTURU_MAYA_DIRECTION_NOTIFY			= 2,
	KANTURU_MAYA_DIRECTION_MONSTER1			= 3,
	KANTURU_MAYA_DIRECTION_MAYA1			= 4,
	KANTURU_MAYA_DIRECTION_END_MAYA1		= 5,
	KANTURU_MAYA_DIRECTION_ENDCYCLE_MAYA1	= 6,
	KANTURU_MAYA_DIRECTION_STANBY2			= 7,
	KANTURU_MAYA_DIRECTION_MONSTER2			= 8,
	KANTURU_MAYA_DIRECTION_MAYA2			= 9,
	KANTURU_MAYA_DIRECTION_END_MAYA2		= 10,
	KANTURU_MAYA_DIRECTION_ENDCYCLE_MAYA2	= 11,
	KANTURU_MAYA_DIRECTION_STANBY3			= 12,
	KANTURU_MAYA_DIRECTION_MONSTER3			= 13,
	KANTURU_MAYA_DIRECTION_MAYA3			= 14,
	KANTURU_MAYA_DIRECTION_END_MAYA3		= 15,
	KANTURU_MAYA_DIRECTION_ENDCYCLE_MAYA3	= 16,
	KANTURU_MAYA_DIRECTION_END				= 17,
	KANTURU_MAYA_DIRECTION_ENDCYCLE			= 18,
};

enum KANTURU_NIGHTMARE_DIRECTION_TYPE
{
	KANTURU_NIGHTMARE_DIRECTION_NONE		= 0,
	KANTURU_NIGHTMARE_DIRECTION_IDLE		= 1,
	KANTURU_NIGHTMARE_DIRECTION_NIGHTMARE	= 2,
	KANTURU_NIGHTMARE_DIRECTION_BATTLE		= 3,
	KANTURU_NIGHTMARE_DIRECTION_END			= 4,
	KANTURU_NIGHTMARE_DIRECTION_ENDCYCLE	= 5,
};

enum KANTURU_TOWER_STATE_TYPE
{
	KANTURU_TOWER_NONE						= 0,
	KANTURU_TOWER_REVITALIXATION			= 1,
	KANTURU_TOWER_NOTIFY					= 2,
	KANTURU_TOWER_CLOSE						= 3,
	KANTURU_TOWER_NOTIFY2					= 4,
	KANTURU_TOWER_END						= 5,
	KANTURU_TOWER_ENDCYCLE					= 6,
};
//ckanturudirection end

//ccomgem start
namespace COMGEM
{
	enum	_METHOD			//창의 기능분류 - 조합/해체
	{
		ATTACH	= 0,
		DETACH
	};

#ifdef LEM_ADD_SEASON5_PART5_MINIUPDATE_JEWELMIX
	enum	eGEMTYPE		//조합할 보석
	{
		eNOGEM = -1,
		eBLESS = 0,		
		eBLESS_C,

		eSOUL, 
		eSOUL_C, 

		eLIFE,		
		eLIFE_C,

		eCREATE, 
		eCREATE_C, 

		ePROTECT,	
		ePROTECT_C,	

		eGEMSTONE, 
		eGEMSTONE_C, 

		eHARMONY,	
		eHARMONY_C,	

		eCHAOS, 
		eCHAOS_C, 

		eLOW,		
		eLOW_C,		

		eUPPER, 		
		eUPPER_C, 

		eGEMTYPE_END = 10,
		eGEMTYPE_END_ALL = 20,
	};
	enum eGEMINDEXTYPE
	{
		eGEM_NAME, eGEM_INDEX, eGEM_END
	};
#endif // LEM_ADD_SEASON5_PART5_MINIUPDATE_JEWELMIX

	enum	_GEMTYPE		//조합할 보석
	{
		NOGEM = -1,
		CELE = 0,			//축복의 보석
		SOUL = 1,			//영혼의 보석
		COMCELE = 2,		//조합된 축복의 보석
		COMSOUL= 3			//조합된 영혼의 보석
	};

	enum	_COMTYPE		//조합의 지정된 갯수
	{
		NOCOM = -1,
		FIRST	= 10,
		SECOND	= 20,
		THIRD	= 30
#ifdef LEM_ADD_SEASON5_PART5_MINIUPDATE_JEWELMIX
		,eCOMTYPE_END = 3
#endif // LEM_ADD_SEASON5_PART5_MINIUPDATE_JEWELMIX
	};

	enum	_STATE			//현재 창의 상태
	{
		STATE_READY,		//조합 전
		STATE_HOLD,			//서버의 응답 대기중
		STATE_END			//조합 끝
	};

	enum	_ERRORTYPE
	{
		NOERR = 0,
		POPERROR_NOTALLOWED,		//부적절한 아이템 창에 등록 시도
		COMERROR_NOTALLOWED,		//부적절한 아이템 조합 시도
		DEERROR_SOMANY,			//너무 많아서 해체 불가능
		DEERROR_NOTALLOWED,		//부적절한 아이템 해체 시도
		ERROR_UNKNOWN,
		ERROR_ALL
	};

};
//ccomgem end

#ifdef FIX_MIX_NOT_PICKING_BUG
enum eMixState
{
	eMixState_MixFunctionPossibility = 0,     //조합 기능을 다 할 수 있다..
	eMixState_MixFunctionImpossibility,       //서버쪽으로 조합 메세지를 보냈을 경우 조합의 기능을 제한 할 수 있다
	eMixState_MixEnd,
};
#endif //FIX_MIX_NOT_PICKING_BUG

enum ITEM_COLORSTATE
{
	ITEM_COLOR_NORMAL = 0,
	ITEM_COLOR_DURABILITY_50,
	ITEM_COLOR_DURABILITY_70,
	ITEM_COLOR_DURABILITY_80,
	ITEM_COLOR_DURABILITY_100,
	ITEM_COLOR_TRADE_WARNING,
};

enum eCursorType
{
	CURSOR_NORMAL = 0,
	CURSOR_PUSH,
	CURSOR_ATTACK,
	CURSOR_GET,
	CURSOR_TALK,
	CURSOR_REPAIR,
	CURSOR_LEANAGAINST,
	CURSOR_SITDOWN,
	CURSOR_DONTMOVE,
	CURSOR_IDSELECT,
};

// Skill.txt (Skill.Bmd)파일에 "스킬 타입" Column 값과 상통.
#ifdef LDS_FIX_APPLYSKILLTYPE_AND_CURSEDTEMPLEWRONGPARTYMEMBER
enum eTypeSkill
{
	eTypeSkill_None = -1,
		eTypeSkill_CommonAttack,	// 0 일반 공격	
		eTypeSkill_Buff,			// 1 버프
		eTypeSkill_DeBuff,			// 2 디버프
		eTypeSkill_FrendlySkill,	// 3 기타 아군 친화적 스킬 (힐 같은 스킬)
		eTypeSkill_End,
};
#endif // LDS_FIX_APPLYSKILLTYPE_AND_CURSEDTEMPLEWRONGPARTYMEMBER

enum eBuffClass
{
	eBuffClass_Buff = 0,
	eBuffClass_DeBuff,

	eBuffClass_Count,
};

enum eBuffState
{
	eBuffNone        = 0,           // 보통인 상태 안씀                                            STATE_NONE
	// Buff
	eBuff_Attack,				    // 공격력 상승                                                 STATE_ATTACK
	eBuff_Defense,					// 방어력 상승                                                 STATE_DEFENSE
	eBuff_HelpNpc,                  // 쉐도우 팬텀                                                 STATE_HELPER_DEFENSE

	//eBuff_HpRecovery == eBuff_Life 같은 인덱스
	//eBuff_Life,						// 생명력 상승                                                 STATE_ADD_VITALITY
	eBuff_PhysDefense,				// 물리 공격 방어막( 법사 )                                    STATE_PHYS_DEF
	eBuff_AddCriticalDamage,		// 크리티컬 데미지 상승                                        STATE_ADD_CRITICAL_DMG
	eBuff_InfinityArrow,            // 인피니티 에로우									           STATE_INFINITY_ARROW      xxxxxx
	eBuff_AddAG,					// AG 증가속도 상승                                            STATE_ADD_AG
	eBuff_HpRecovery,               // 체력 증가                                                   STATE_HP_RECOVERY
	eBuff_AddMana     ,             // 마나 상승                                                   STATE_ADD_MANA
	eBuff_BlessPotion,              // 축복의 물약 복용 상태                                       STATE_BLESS_POTION
	eBuff_SoulPotion,               // 영혼의 물약 복용 상태                                       STATE_SPIRIT_POTION
	eBuff_RemovalMagic,             // 마법 해제 ( 서버팀에 문의 디버프? 혹은 버프 )               STATE_REMOVAL_MAGIC
	eBuff_CastleGateIsOpen,         // 공성 성문 여닫힌 상태                                       STATE_GATE_OPEN
	eBuff_CastleRegimentDefense,    // 공성 수비측                                                 STATE_REGIMENT_DEFENSE
	eBuff_CastleRegimentAttack1,    // 공성 공격측 1                                               STATE_REGIMENT_ATTACK
	eBuff_CastleRegimentAttack2,    // 공성 공격측 2                                               STATE_REGIMENT_ATTACK2
	eBuff_CastleRegimentAttack3,    // 공성 공격측 3                                               STATE_REGIMENT_ATTACK3
	eBuff_Cloaking,                 // 투명                                                        STATE_INVISIBLE
	eBuff_AddSkill		,		    // 추가 스킬을 쓰게 하는 상태( 다크 로드 공성 스킬 )           STATE_SKILL_BUFF
	eBuff_CastleCrown,              // 공성 왕관 등록 중 상태 ( STATE_GATE_OPEN와 Index가 같음 ) ================  X
	eBuff_CrywolfAltarEnable,       // 크라이울프 늑대의 제단 ONLY - 계약 가능 상태                STATE_CRYWOLF_ALTAR_ENABLE
	eBuff_CrywolfAltarDisable,      // 크라이울프 늑대의 제단 ONLY - 계약 불능 상태                STATE_CRYWOLF_ALTAR_DISABLE
	eBuff_CrywolfAltarContracted,   // 크라이울프 늑대의 제단 ONLY - 계약 되어 있는 상태           STATE_CRYWOLF_ALTAR_CONTRACTED
	eBuff_CrywolfAltarAttempt,      // 크라이울프 늑대의 제단 ONLY - 계약 시도 상태                STATE_CRYWOLF_ALTAR_ATTEMPT
	eBuff_CrywolfAltarOccufied,     // 크라이울프 늑대의 제단 ONLY - 점령 당한 상태                STATE_CRYWOLF_ALTAR_OCCUFIED 
	eBuff_CrywolfHeroContracted,    // 크라이울프 히어로 계약 중인 상태                            HERO_ALTAR_CONTRACTED
	eBuff_CrywolfNPCHide,           // 크라이울프 ONLY - NPC HIDE 상태                             STATE_CRYWOLF_NPC_HIDE
	eBuff_GMEffect,                 // GM 효과                                                     STATE_GM_EFFECT
	eBuff_PcRoomSeal1,				// Pc방 인장 1                                                 STATE_SEAL1
	eBuff_PcRoomSeal2,              // Pc방 인장 2                                                 STATE_SEAL2
	eBuff_PcRoomSeal3,              // Pc방 인장 3                                                 STATE_SEAL3
	eBuff_CursedTempleQuickness,    // 신속의 스킬 	                                               STATE_CURSED_TEMPLE_QUICKNESS
	eBuff_CursedTempleSublimation,	// 승화의 주문												   STATE_CURSED_TEMPLE_SUBLIMATION
	eBuff_CursedTempleProdection,   // 보호막 스킬								                   STATE_CURSED_TEMPLE_PRODECTION
	eBuff_Hellowin1,                // 잭오랜턴의 축복											   STATE_HELLOWIN_1
	eBuff_Hellowin2,                // 잭오랜턴의 분노                                             STATE_HELLOWIN_2
	eBuff_Hellowin3,                // 잭오랜턴의 외침                                             STATE_HELLOWIN_3
	eBuff_Hellowin4,                // 잭오랜턴의 음식                                             STATE_HELLOWIN_4
	eBuff_Hellowin5,				// 잭오랜턴의 음료                                             STATE_HELLOWIN_5
//	eBuff_LuckSeal,                 // 인장( 히어로를 제외한 뷰포터 상의 캐릭터)                   STATE_LUCK_SEAL
	eBuff_Seal1,                    // 인장 1                                                      STATE_SEAL1
	eBuff_Seal2,                    // 인장 2                                                      STATE_SEAL2
	eBuff_Seal3,                    // 인장 3                                                      STATE_SEAL3
	eBuff_Seal4,                    // 인장 4                                                      STATE_SEAL4
	eBuff_EliteScroll1,				// 신속                                                        STATE_ELITE_SCROLL1
	eBuff_EliteScroll2,				// 방어                                                        STATE_ELITE_SCROLL2
	eBuff_EliteScroll3,				// 분노                                                        STATE_ELITE_SCROLL3
	eBuff_EliteScroll4,				// 마력                                                        STATE_ELITE_SCROLL4
	eBuff_EliteScroll5,				// 체력                                                        STATE_ELITE_SCROLL5
	eBuff_EliteScroll6,				// 마나                                                        STATE_ELITE_SCROLL6
	eBuff_SecretPotion1,            // 힘                                                          STATE_ELITE_SECRET1
	eBuff_SecretPotion2,            // 민첩                                                        STATE_ELITE_SECRET2
	eBuff_SecretPotion3,            // 체력                                                        STATE_ELITE_SECRET3
	eBuff_SecretPotion4,            // 에너지                                                      STATE_ELITE_SECRET4
	eBuff_SecretPotion5,            // 통솔                                                        STATE_ELITE_SECRET5
	
	// DeBuff
	eDeBuff_Poison,						// 독 걸린 상태                                                STATE_POISON
	eDeBuff_Freeze,						// 얼음 걸린 상태                                              STATE_FREEZE
	eDeBuff_Harden,						// 석화된 상태                                                 STATE_PARALYZE
	eDeBuff_Defense,					// 방어력 감소( 마검사 )                                       STATE_REDUCE_DEF
	eDeBuff_Attack,						// 공격력 감소( 법사 ) ( 클라에서 쓰지 않음 )
	eDeBuff_MagicPower,					// 마력 감소 ( 클라에서 쓰지 않음 )
	eDeBuff_Stun,						// 스턴에 걸린 상태                                            STATE_STUN
	eDeBuff_InvincibleMagic,			// 마법 방어 무적( 몹 한테만 )                                 STATE_ABSOLUTE_DEF
	eDeBuff_InvincibleMagicAttack,		// 마법 마법 공격 몬스터 저항 효과
	eDeBuff_InvinciblePhysAttack,       // 마법 물리 공격 몬스터 저항 효과 
	eDeBuff_CursedTempleRestraint,      // 속박 스킬								                   STATE_CURSED_TEMPLE_RESTRAINT
	// 버프는 eBuff 붙이고, 디버프는 eDeBuff 붙여주세용 ^^

	eBuff_CrywolfProdection1, 
	eBuff_CrywolfProdection2, 
	eBuff_CrywolfProdection3, 
	eBuff_CrywolfProdection4, 
	eBuff_CrywolfProdection5, 

	// 소환술사 버프 관련 스킬
	eBuff_Thorns		= 71,	// 쏜즈(버프)
	eDeBuff_Sleep		= 72,	// 슬립(디버프)
	eDeBuff_Blind		= 73,	// 블라인드(디버프)
	eDeBuff_NeilDOT		= 74,	// 소환수 닐 DOT (출혈)
	eDeBuff_SahamuttDOT = 75,	// 소환수 사하무트 DOT (출혈)
	eDeBuff_AttackDown	= 76,	// 위크니스
	eDeBuff_DefenseDown = 77,	// 이너베이션
#ifdef CSK_EVENT_CHERRYBLOSSOM
	eBuff_CherryBlossom_Liguor,	// 벚꽃술
	eBuff_CherryBlossom_RiceCake,// 벚꽃경단
	eBuff_CherryBlossom_Petal,	// 벚꽃꽃잎
#endif //CSK_EVENT_CHERRYBLOSSOM
#ifdef ASG_ADD_SKILL_BERSERKER
	eBuff_Berserker		= 81,	// 버서커
#endif	// ASG_ADD_SKILL_BERSERKER
#ifdef KJH_ADD_SKILL_SWELL_OF_MAGICPOWER
	eBuff_SwellOfMagicPower	= 82,	// 마력증대 (버프)
#endif // KJH_ADD_SKILL_SWELL_OF_MAGICPOWER
#ifdef YDG_ADD_SKILL_FLAME_STRIKE
	eDeBuff_FlameStrikeDamage	= 83,	// 플레임스트라이크 데미지
#endif	// YDG_ADD_SKILL_FLAME_STRIKE
#ifdef YDG_ADD_SKILL_GIGANTIC_STORM
	eDeBuff_GiganticStormDamage	= 84,	// 기간틱스톰 데미지
#endif	// YDG_ADD_SKILL_GIGANTIC_STORM
#ifdef YDG_ADD_SKILL_LIGHTNING_SHOCK
	eDeBuff_LightningShockDamage = 85,	// 라이트닝쇼크 데미지
#endif	// YDG_ADD_SKILL_LIGHTNING_SHOCK
#ifdef CSK_ADD_SKILL_BLOWOFDESTRUCTION
	eDeBuff_BlowOfDestruction = 86,		// 파괴의일격 데미지
#endif // CSK_ADD_SKILL_BLOWOFDESTRUCTION
#ifdef PSW_ADD_PC4_SEALITEM
	eBuff_Seal_HpRecovery = 87,         // 체력젠 인장( 부분4차 ), eBuffTime_Seal 으로 쓰면 된다
	eBuff_Seal_MpRecovery = 88,         // 마나젠 인장( 부분4차 ), eBuffTime_Seal 으로 쓰면 된다
#endif //PSW_ADD_PC4_SEALITEM
#ifdef PSW_ADD_PC4_SCROLLITEM
	eBuff_Scroll_Battle = 89,           // 전투 스크롤( 부분4차 ), eBuffTime_Scroll 으로 쓰면 된다
	eBuff_Scroll_Strengthen = 90,       // 강화 스크롤( 부분4차 ), eBuffTime_Scroll 으로 쓰면 된다
#endif //PSW_ADD_PC4_SCROLLITEM
#ifdef PBG_ADD_SANTABUFF
	eBuff_BlessingOfXmax = 91,		//크리스마스의축복	index 91
	eBuff_CureOfSanta,				//산타의치유		index 92
	eBuff_SafeGuardOfSanta,			//산타의보호		index 93
	eBuff_StrengthOfSanta,			//산타의강화		index 94
	eBuff_DefenseOfSanta,			//산타의방어		index 95
	eBuff_QuickOfSanta,				//산타의신속		index 96
	eBuff_LuckOfSanta,				//산타의행운		index 97
#endif //PBG_ADD_SANTABUFF
#ifdef YDG_ADD_NEW_DUEL_WATCH_BUFF
	eBuff_DuelWatch = 98,			// 결투 관전모드
#endif	// YDG_ADD_NEW_DUEL_WATCH_BUFF
#ifdef ASG_ADD_CS6_GUARD_CHARM
	eBuff_GuardCharm = 99,				// 수호의부적
#endif	// ASG_ADD_CS6_GUARD_CHARM
#ifdef ASG_ADD_CS6_ITEM_GUARD_CHARM
	eBuff_ItemGuardCharm = 100,			// 아이템보호부적
#endif	// ASG_ADD_CS6_ITEM_GUARD_CHARM
#ifdef ASG_ADD_CS6_ASCENSION_SEAL_MASTER
	eBuff_AscensionSealMaster = 101,	// 상승의인장마스터
#endif	// ASG_ADD_CS6_ASCENSION_SEAL_MASTER
#ifdef ASG_ADD_CS6_WEALTH_SEAL_MASTER
	eBuff_WealthSealMaster = 102,		// 풍요의인장마스터
#endif	// ASG_ADD_CS6_WEALTH_SEAL_MASTER
#ifdef YDG_ADD_NEW_DUEL_SYSTEM
	eBuff_HonorOfGladiator = 103,		// 검투사의 명예
#endif	// YDG_ADD_NEW_DUEL_SYSTEM
#ifdef LDS_ADD_PCROOM_ITEM_JPN_6TH
	eBuff_StrongCharm = 104,			// 강함의 인장
#endif // LDS_ADD_PCROOM_ITEM_JPN_6TH
#ifdef YDG_ADD_DOPPELGANGER_MONSTER
	eBuff_Doppelganger_Ascension = 105,	// 도플갱어 승천
#endif	// YDG_ADD_DOPPELGANGER_MONSTER
#ifdef PBG_ADD_PKSYSTEM_INGAMESHOP
	eDeBuff_MoveCommandWin = 106,		// PK패널티
#endif //PBG_ADD_PKSYSTEM_INGAMESHOP
#ifdef PBG_ADD_SECRETBUFF
	eDeBuff_Fatigue_FirstPenalty = 107,	// 피로함1
	eDeBuff_Fatigue_SecondPenalty = 108,// 피로함2
#endif //PBG_ADD_SECRETBUFF
#ifdef YDG_ADD_CS7_PARTY_EXP_BONUS_ITEM
	eBuff_PartyExpBonus = 112,			// 파티 경험치 증가
#endif	// YDG_ADD_CS7_PARTY_EXP_BONUS_ITEM
#ifdef PBG_ADD_AURA_EFFECT
	eBuff_AG_Addition = 113,			// AG증가 버프
	eBuff_SD_Addition = 114,			// SD증가 버프
#endif //PBG_ADD_AURA_EFFECT
#ifdef PBG_ADD_SECRETBUFF
	eBuff_Vitality_Lowest = 115,		// 최하급활력
	eBuff_Vitality_Low = 116,			// 하급활력
	eBuff_Vitality_Middle = 117,		// 중급활력
	eBuff_Vitality_High = 118,			// 상급활력
#endif //PBG_ADD_SECRETBUFF
#ifdef LDK_ADD_INGAMESHOP_NEW_WEALTH_SEAL
	eBuff_NewWealthSeal = 119,
#endif //LDK_ADD_INGAMESHOP_NEW_WEALTH_SEAL
#ifdef YDG_ADD_GM_DISCHARGE_STAMINA_DEBUFF
	eDeBuff_Discharge_Stamina = 120,	// GM이 거는 스태미너 방전 디버프
#endif	// YDG_ADD_GM_DISCHARGE_STAMINA_DEBUFF
#ifdef YDG_ADD_HEALING_SCROLL
	eBuff_Scroll_Healing = 121,			// 치유의 스크롤
#endif	// YDG_ADD_HEALING_SCROLL
#ifdef PBG_ADD_NEWCHAR_MONK_SKILL
	eBuff_Att_up_Ourforces = 129,		// 공격성공율 상승
	eBuff_Hp_up_Ourforces = 130,		// 체력상승
	eBuff_Def_up_Ourforces = 131,		// 방어성공율 상승
#endif //PBG_ADD_NEWCHAR_MONK_SKILL
	eBuff_Count,
};

// 버프에 시간이 들어 가면 여기에 추가를 하면 된다.
// BuffTimeControl 여기에 추가를 해줘야 한다. <------- 이 부분도 스크립트로 빠져야 하느데....-=-
enum eBuffTimeType 
{ 
	eBuffTime_None = 0, 
	eBuffTime_Hellowin = 1006, 
	eBuffTime_PcRoomSeal, 
	eBuffTime_Seal, 
	eBuffTime_Scroll, 
	eBuffTime_Secret,
#ifdef CSK_EVENT_CHERRYBLOSSOM
	eBuffTime_CherryBlossom,
#endif //CSK_EVENT_CHERRYBLOSSOM
#ifdef KJH_ADD_SKILL_SWELL_OF_MAGICPOWER
	eBuffTime_SwellOfMP,
#endif // KJH_ADD_SKILL_SWELL_OF_MAGICPOWER
#ifdef PBG_ADD_SANTABUFF
	eBuffTime_Christmax,
#endif //PBG_ADD_SANTABUFF
#ifdef PBG_ADD_HONOROFGLADIATORBUFFTIME
	eBuffTime_HonorOfGladiator,
#endif //PBG_ADD_HONOROFGLADIATORBUFFTIME
#ifdef ASG_ADD_CS6_GUARD_CHARM
	eBuffTime_GuardCharm,
#endif	// ASG_ADD_CS6_GUARD_CHARM
#ifdef ASG_ADD_CS6_ITEM_GUARD_CHARM
	eBuffTime_ItemGuardCharm,
#endif	// ASG_ADD_CS6_ITEM_GUARD_CHARM
#ifdef LDS_ADD_PCROOM_ITEM_JPN_6TH
	eBuffTime_ItemStrongCharm,				// 강함의 인장 (PC방 아이템)
#endif // LDS_ADD_PCROOM_ITEM_JPN_6TH
#ifdef PBG_ADD_SECRETBUFF
	eBuffTime_Vitality,
#endif //PBG_ADD_SECRETBUFF
#ifdef YDG_ADD_CS7_MAX_AG_AURA
	eBuffTime_AG_Addition,
#endif	// YDG_ADD_CS7_MAX_AG_AURA
#ifdef YDG_ADD_CS7_MAX_SD_AURA
	eBuffTime_SD_Addition,
#endif	// YDG_ADD_CS7_MAX_SD_AURA
#ifdef YDG_ADD_CS7_PARTY_EXP_BONUS_ITEM
	eBuffTime_PartyExpBonus,
#endif	// YDG_ADD_CS7_PARTY_EXP_BONUS_ITEM
	eBuffTime_Count,
};

// value부분을 셋팅 할때 어떤 파일에서 가져 올지를 결정한다.
enum eBuffValueLoadType
{
	eBuffValueLoad_None = 0,
	eBuffValueLoad_Skill,
	eBuffValueLoad_Item,
	eBuffValueLoad_Text,
	eBuffValueLoad_ItemAddOption,

	eBuffValueLoad_Count,
};

#define BUFFINDEX( buff )				static_cast<eBuffState>(buff)
#define BUFFTIMEINDEX( timetype )		static_cast<eBuffTimeType>(timetype)
#define ITEMINDEX( type, index )        static_cast<DWORD>((type*MAX_ITEM_INDEX)+index)

#ifdef NEW_COMMANDS

//client enums
enum eShopType
{
	eShop_NoCharge,                 //무료상점
	eShop_PartCharge,				//부분유료상점
	eShop_Count,
};

enum eHighCategoryType
{
	eHighCategory_None = 0,         //0 = 카테고리가 없는것을 말함
	eHighCategory_NewItem,		    //아이템
	eHighCategory_OldItem,			//임시
	eHighCategory_MyItem,			//내 아이템
	eHighCategory_Count,
};

enum eLowCategoryType
{
	eLowCategory_None = 0,			//0 = 카테고리가 없는것을 말함
	eLowCategory_All,				//아이템전체
	eLowCategory_NewItem,			//뉴아이템
	eLowCategory_BestItem,			//베스트아이템
	eLowCategory_DiscountItem,		//디스카운트아이템
	eLowCategory_Count,
};

enum eSortType
{
	eSort_ClassAll = 0,
	eSort_Class_Wizard,				//흑마법사		  1
	eSort_ClassKnight,				//흑기사		  2
	eSort_ClassElf,					//엘프            3
	eSort_ClassDark,				//마검사          4
	eSort_ClassDarkLord,			//다크로드        5

	eSort_ClassSoulMaster = 9,		//소울마스터	  6   1-1
	eSort_ClassBladeKnight,			//블레이드나이트  7   2-1
	eSort_ClassMuzElf,				//뮤즈엘프        8   3-1

	eSort_ClassCount,
};



enum eCashShopResult
{
	//서버 클라 같음.
	eCashShop_Success = 0,									// 구매, 상점 오픈 등등 성공
	eCashShop_Fail_NotEnoughCash,							// 구매 실패 (캐쉬 잔액 부족)
	eCashShop_Fail_NotEmptySpace,							// 구매 실패 (인벤토리 공간 없음)
	eCashShop_Fail_NotFoundItem,							// 구매 실패 (일치하는 아이템 정보가 없음)
	eCashShop_Fail_AlreadyHaveItem,							// 구매 실패 (중복 구매 불가능한 아이템을 소지)
	eCashShop_Fail_DbError,									// 구매 실패 (DB 오류)
	eCashShop_Fail_ShopserverDisconnect,					// 구매 실패 (샵 서버와의 연결이 끊어졌음)
	eCashShop_Fail_ShopErrror,								// 구매 실패 (샵 서버로부터 이상한 에러 확인)
	eCashShop_Fail_OpenCashShop,							// 상점 열고 닫기 실패
	eCashShop_Fail_ETC,										// 구매 실패 (기타)

	//fail Message가 아님( 클라이언트 전용 )
	eCashShop_ItemEqual,
	eCashShop_NotItem,
	eCashShop_Count,
};

enum eMessageBoxType
{
    eMB_OK,
    eMB_YESNO,
    eMB_OKCANCEL,
};

/*
enum eBottomCategoryType
{
	//0 = 카테고리가 없는것을 말함
	eBottomCategory_Weapon = 1,		//무기
	eBottomCategory_Armor,			//방어구
	eBottomCategory_Supplies,		//소모성
	eBottomCategory_Pet,			//펫
	eBottomCategory_Ability,		//기능성
	eBottomCategory_Count,
};
*/

#endif //NEW_COMMANDS

#ifdef CSK_FREE_TICKET
enum
{
	FREETICKET_TYPE_DEVILSQUARE = 0,
	FREETICKET_TYPE_BLOODCASTLE,
	FREETICKET_TYPE_KALIMA,
#ifdef PSW_CURSEDTEMPLE_FREE_TICKET
	FREETICKET_TYPE_CURSEDTEMPLE,
#endif //PSW_CURSEDTEMPLE_FREE_TICKET
#ifdef LDS_ADD_INGAMESHOP_ITEM_PASSCHAOSCASTLE
	FREETICKED_TYPE_CHAOSCASTLE,
#endif // LDS_ADD_INGAMESHOP_ITEM_PASSCHAOSCASTLE
#ifdef LJH_ADD_FREE_TICKET_FOR_DOPPELGANGGER_BARCA_BARCA_7TH
	FREETICKED_TYPE_DOPPLEGANGGER,
	FREETICKED_TYPE_BARCA,
	FREETICKED_TYPE_BARCA7TH,
#endif //LJH_ADD_FREE_TICKET_FOR_DOPPELGANGGER_BARCA_BARCA_7TH
};
#endif // CSK_FREE_TICKET

#ifdef ADD_SOCKET_ITEM
// 활의 타입을 지정
// zzzCharacter::GetEquipedBowType() 에서 사용
enum eTYPEBOW
{
	BOWTYPE_NONE = 0,
	BOWTYPE_BOW,
	BOWTYPE_CROSSBOW,	
};
#endif // ADD_SOCKET_ITEM


#ifdef LDS_ADD_CS6_CHARM_MIX_ITEM_WING

// 소스 작업중에 스크립트 변동으로 인해 중간 변수 선언. 
#define ITEM_TYPE_CHARM_MIXWING		ITEM_HELPER
#define MODEL_TYPE_CHARM_MIXWING	MODEL_HELPER

enum E_WINGMIXCHAR_SEQUENCE
{
	EWS_KNIGHT_1_CHARM	= 83,
	EWS_MAGICIAN_1_CHARM,
	EWS_ELF_1_CHARM,
	EWS_SUMMONER_1_CHARM,
	EWS_DARKLORD_1_CHARM,
	EWS_KNIGHT_2_CHARM,
	EWS_MAGICIAN_2_CHARM,
	EWS_ELF_2_CHARM,
	EWS_SUMMONER_2_CHARM,
	EWS_DARKKNIGHT_2_CHARM,
	EWS_BEGIN = 83,
	EWS_END = EWS_BEGIN + 10,
};
#endif // LDS_ADD_CS6_CHARM_MIX_ITEM_WING
